### ISSUE TITLE
What regex syntax does the llpp support?

### ISSUE THREAD

**Issue by acgtyrant** [moosotc/llpp#101]
I would like to know what regex syntax does it support.

**Comment by moosotc** [comment]
Isaac Ge <notifications@github.com> writes:

> I would like to know what regex syntax does it support.

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/regex.h.html
http://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html

Are used, first one for the whole document searches and the second in
the UI (outline etc)

-- 
mailto:moosotc@gmail.com

**Comment by acgtyrant** [comment]
Do you open the `REG_EXTENDED` flag at default?
