### ISSUE TITLE
Invert color customization

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#102]
Hi moosotc,

I was wondering if we could tweak how `llpp` inverts colors to make the inversion "softer"? For example, can we make background dark grey instead of black, and text light grey instead of white? 

I tried poking around the code but I have no idea how opengl (I guess?) inverts the colors. I thought there should be a function that maps the original color (r, g, b) to a new color (r', g', b')? If it works like that, I can just tweak the mapping function. 

Could you enlighten me on this issue?

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Hi moosotc,
>
> I was wondering if we could tweak how `llpp` inverts colors to make
> the inversion "softer"? For example, can we make background dark grey
> instead of black, and text light grey instead of white?
>

You can do almost anything (doesn't mean that it would be easy though).

> I tried poking around the code but I have no idea how opengl (I
> guess?) inverts the colors. I thought there should be a function that
> maps the original color (r, g, b) to a new color (r', g', b')? If it
> works like that, I can just tweak the mapping function.
>
> Could you enlighten me on this issue?

llpp "abuses" blending to do the inversion..

       if conf.invert
       then GlTex.env (`mode `blend);
       drawtile params opaque;
       if conf.invert
       then GlTex.env (`mode `modulate);

So, basically, the only difference is that when inverting textures, that
comprise the rendered page, are drawn in blend mode... The OpenGL mapping
machinery llpp uses is described in the glTexEnv documentation [1]

[1] https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glTexEnv.xml

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
Thanks for the reply. According to the documentation, I think I just need to change the value of C_p and C_c to something like C_p=(0.9, 0.9, 0.9) and C_c=(0.1, 0.1, 0.1). However, I know nothing about OCaml and I couldn't figure out where in the code you specified these two colors. Would you mind showing me how to achieve this?

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Thanks for the reply. According to the documentation, I think I just
> need to change the value of C_p and C_c to something like C_p=(0.9,
> 0.9, 0.9) and C_c=(0.1, 0.1, 0.1). However, I know nothing about OCaml
> and I couldn't figure out where in the code you specified these two
> colors. Would you mind showing me how to achieve this?

To quote the manual:
            The subscript p refers to the color computed from the
            previous texture stage (or the incoming fragment if
            processing texture stage 0), the subscript s to the texture
            source color, the subscript c to the texture environment
            color, and the subscript v indicates a value produced by the
            texture function.

[...]
            GL_TEXTURE_ENV_MODE defaults to GL_MODULATE and
            GL_TEXTURE_ENV_COLOR defaults to (0, 0, 0, 0).
        
IOW you can set C_c. C_p is the color of the page so to speak.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Thanks for the reply. According to the documentation, I think I just
> need to change the value of C_p and C_c to something like C_p=(0.9,
> 0.9, 0.9) and C_c=(0.1, 0.1, 0.1). However, I know nothing about OCaml
> and I couldn't figure out where in the code you specified these two
> colors. Would you mind showing me how to achieve this?

Here's a contrived example that changes the way inversion behaves:

diff --git a/main.ml b/main.ml
index 0445b50..6e2c80b 100644
--- a/main.ml
+++ b/main.ml
@@ -5006,6 +5006,7 @@ let () =
               ; "GL_NV_texture_rectangle" ]
   then (dolog "OpenGL does not suppport rectangular textures"; exit 1);
 
+  GlTex.env (`color (0.2, 0.2, 0.2, 0.0));
   let cs, ss =
     match Unix.socketpair Unix.PF_UNIX Unix.SOCK_STREAM 0 with
     | exception exn ->

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> This is fantastic! Thank you! It's certainly good enough for me.

Heh n/p.

>
> Since C_p is (1, 1, 1) I assume, the black text is still gonna be pure
> white, but dark grey background is much better than pure black! So
> there is no way to change C_p?

C_p is the color of the page, that's what mupdf gives you so to speak,
you cannot change it unless you want to go through every pixel on the
CPU or want to play games with register combiners/fragment shaders on
the GPU.

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
I see. I just realized that I can fine-tune the contrast using `[` and `]`. Now it's perfect!

Thanks again!
