### ISSUE TITLE
Provide -- to signify end of arguments

### ISSUE THREAD

**Issue by Earnestly** [moosotc/llpp#107]
Currently if a document starts with a hyphen then llpp has no way of opening the file without thinking the leading `-` is an option.

POSIX.1 requires the use of `--` to indicate the end of arguments in order to shield operands from arbitrary inputs. With this `llpp` could be called as `llpp -- -file.pdf`

**Comment by moosotc** [comment]
Earnestly <notifications@github.com> writes:

> Currently if a document starts with a hyphen then llpp has no way of
> opening the file without thinking the leading `-` is an option.
>
> POSIX.1 requires the use of `--` to indicate the end of arguments in
> order to shield operands from arbitrary inputs. With this `llpp` could
> be called as `llpp -- -file.pdf`

OCaml's Arg module, responsible for command line parsing, doesn't claim
to adhere to POSIX though there are mentions in the documentation
alluding to double dash [1]

Following patch seems to work, but no idea if it's the right thing to
do, @nojb what say you?

[1] http://caml.inria.fr/pub/docs/manual-ocaml/libref/Arg.html

'''
diff --git a/main.ml b/main.ml
index 0b053ac..4853614 100644
--- a/main.ml
+++ b/main.ml
@@ -4884,6 +4884,8 @@ let () =
         ("-no-title", Arg.Set ignoredoctitlte, " ignore document title");
         ("-layout-height", Arg.Set_int layouth,
          "<height> layout height html/epub/etc (-1, 0, N)");
+
+        ("--", Arg.Rest (fun s -> state.path <- s), "");
        ]
     )
     (fun s -> state.path <- s)
'''

-- 
mailto:moosotc@gmail.com

**Comment by nojb** [comment]
Yes, that should do it.

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Earnestly <notifications@github.com> writes:
>
>> Currently if a document starts with a hyphen then llpp has no way of
>> opening the file without thinking the leading `-` is an option.
>>
>> POSIX.1 requires the use of `--` to indicate the end of arguments in
>> order to shield operands from arbitrary inputs. With this `llpp` could
>> be called as `llpp -- -file.pdf`
>
> OCaml's Arg module, responsible for command line parsing, doesn't claim
> to adhere to POSIX though there are mentions in the documentation
> alluding to double dash [1]
>
> Following patch seems to work, but no idea if it's the right thing to
> do, @nojb what say you?
>

[..snip..]

After some reflection I'm not sure if this deserves complicating the
code given that `llpp ./-file.pdf` or `llpp $PWD/-file.pdf` work too.

-- 
mailto:moosotc@gmail.com
