### ISSUE TITLE
Searching forward/backward inconsistent behaviors

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#108]
Searching forward returns the next matched word and the search starts from the top of the current screen. Now, if I press `n` it will return the next match. This is the normal behavior. 

However, searching backward seems to return the *last* matched word on the current *page*. Now, if I press `p` again it will skip all other matches on the current page and return a match before this page. 

Is this the desired behavior?

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> However, searching backward seems to return the last matched word on the
> current page. Now, if I press p again it will skip all other matches on the
> current page and return a match before this page.
>
> Is this the desired behavior?
>

It always just seraches from the top of the visible page, so to
speak. So, yes, it behaves as coded (not necessarily as desired)

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
I don't think it searches from the top of the visible page. Say I'm at the the top of page 2 and the second half of this page is invisible (below the screen). If I search backward, it will actually search up from the bottom of page 2 and return the first result. So if there is a matched word in the second half of page 2, it will jump *forward* to the bottom of page 2.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> I don't think it searches from the top of the visible page. Say I'm at
> the the top of page 2 and the second half of this page is invisible
> (below the screen). If I search backward, it will actually search up
> from the bottom of page 2 and return the first result. So if there is
> a matched word in the second half of page 2, it will jump *forward* to
> the bottom of page 2.

I've just looked at the code, and it's inconsistent on the subject,
first iteration it searches on page N at vertical position 0 but on
subsequent ones it decrements N and searches from vertical INT_MAX plus
there's an obvious attempt to do something about things in the OCamk
parts of the code initial positions for backward searches was, at some
point, set to vertical height, but then that was nullified (literally
multiplied by zero)

At least the documentation is upfront about things (caveat emptor part
of the 'h/f1' screen.

-- 
mailto:moccosotc@gmail.com

**Comment by JunnanZ** [comment]
Lol, that doesn't sound naive at all. Anyway, I've noticed this for a while but didn't open an issue, having read the caveat, until today I learned that it can search in regex.
