### ISSUE TITLE
Custom keymap don't work.

### ISSUE THREAD

**Issue by pqnhan** [moosotc/llpp#110]
I build llpp by my self. After it, I configured the keymap based on the instructions from [https://wiki.archlinux.org/index.php/Llpp#Configuration](url) but I got "Fatal error: exception Failure("parse error: unexpected subelement in llppconfig".
Anyone can suggest me how to fix it?
I just want custom key to vi-like emulation.

**Comment by moosotc** [comment]
PQNhan <notifications@github.com> writes:

> I build llpp by my self. After it, I configured the keymap based on
> the instructions from
> [https://wiki.archlinux.org/index.php/Llpp#Configuration](url) but I
> got "Fatal error: exception Failure("parse error: unexpected
> subelement in llppconfig".
> Anyone can suggest me how to fix it?

Can you share your llppconfig?

-- 
mailto:moosotc@gmail.com

**Comment by pqnhan** [comment]
`<llppconfig>
<ui-font size='20'/>
<defaults
    width='980'
    height='1080'
    scroll-bar-width='7'
    scroll-handle-height='12'
    horizontal-scrollbar-visible='true'
    vertical-scrollbar-visible='true'
    case-insensitive-search='true'
    preload='true'
    page-bias='0'
    scroll-step='52'
    auto-scroll-step='2'
    max-height-fit='true'
    highlight-links='true'
    under-cursor-info='false'
    vertical-margin='2'
    zoom='100'
    presentation='false'
    rotation-angle='0'
    fit-model='proportional'
    pixmap-cache-size='32M'
    tex-count='256'
    slice-height='24'
    thumbnail-width='76'
    background-color='127/127/127'
    scrollbar-color='163/163/163/178'
    scrollbar-handle-color='0/0/0/178'
    texture-color='0/0/0/0'
    tile-width='2048'
    tile-height='2048'
    mupdf-store-size='256M'
    checkers='true'
    aalevel='8'
    trim-margins='false'
    trim-fuzz='0/0/0/0'
    uri-launcher='echo &quot;%s&quot;'
    path-launcher='lp &quot;%s&quot;'
    color-space='rgb'
    invert-colors='false'
    brightness='1.000000'
    selection-command='LC_CTYPE=UTF-8 xclip -i'
    paste-command='LC_CTYPE=UTF-8 xclip -o'
    synctex-command='echo SyncTex'
    pax-command='cat'
    askpass-command=''
    savepath-command=''
    update-cursor='true'
    hint-font-size='12'
    horizontal-scroll-step='24'
    page-scroll-scale='1.000000'
    use-pbo='false'
    wheel-scrolls-pages='true'
    remote-in-a-new-instance='false'
    point-and-x='false'
    point-and-x-mark='word'
    scroll-bar-on-the-left='false'
    last-visit='-9223372036854775808'
    edit-annotations-inline='true'
    coarse-presentation-positioning='false'
    use-document-css='true'/>

<keymap mode='view'>
	 <map in='menu' out='F'/>
</keymap>
</llppconfig>
`

I just added 3 lines as above, but it doesn't work
'<keymap mode='view'>
	 <map in='menu' out='F'/>
</keymap>'

**Comment by pqnhan** [comment]
<llppconfig>
<ui-font size='20'/>
<defaults
    width='980'
    height='1080'
    scroll-bar-width='7'
    scroll-handle-height='12'
    horizontal-scrollbar-visible='true'
    vertical-scrollbar-visible='true'
    case-insensitive-search='true'
    preload='true'
    page-bias='0'
    scroll-step='52'
    auto-scroll-step='2'
    max-height-fit='true'
    highlight-links='true'
    under-cursor-info='false'
    vertical-margin='2'
    zoom='100'
    presentation='false'
    rotation-angle='0'
    fit-model='proportional'
    pixmap-cache-size='32M'
    tex-count='256'
    slice-height='24'
    thumbnail-width='76'
    background-color='127/127/127'
    scrollbar-color='163/163/163/178'
    scrollbar-handle-color='0/0/0/178'
    texture-color='0/0/0/0'
    tile-width='2048'
    tile-height='2048'
    mupdf-store-size='256M'
    checkers='true'
    aalevel='8'
    trim-margins='false'
    trim-fuzz='0/0/0/0'
    uri-launcher='echo &quot;%s&quot;'
    path-launcher='lp &quot;%s&quot;'
    color-space='rgb'
    invert-colors='false'
    brightness='1.000000'
    selection-command='LC_CTYPE=UTF-8 xclip -i'
    paste-command='LC_CTYPE=UTF-8 xclip -o'
    synctex-command='echo SyncTex'
    pax-command='cat'
    askpass-command=''
    savepath-command=''
    update-cursor='true'
    hint-font-size='12'
    horizontal-scroll-step='24'
    page-scroll-scale='1.000000'
    use-pbo='false'
    wheel-scrolls-pages='true'
    remote-in-a-new-instance='false'
    point-and-x='false'
    point-and-x-mark='word'
    scroll-bar-on-the-left='false'
    last-visit='-9223372036854775808'
    edit-annotations-inline='true'
    coarse-presentation-positioning='false'
    use-document-css='true'/>         
<keymap mode='view'>
	 <map in='menu' out='F'/>
</keymap>
</llppconfig>

I just add 3 lines as above, but it doesn't work, I don't understand why or this configured is obsoleted.
<keymap mode='view'>
	 <map in='menu' out='F'/>
</keymap>

**Comment by moosotc** [comment]
PQNhan <notifications@github.com> writes:

> `<llppconfig>
> <ui-font size='20'/>
> <defaults
>     width='980'

[..snip..]

>     use-document-css='true'/>
>
> <keymap mode='view'>
> 	 <map in='menu' out='F'/>
> </keymap>
> </llppconfig>
> `
>
> I just added 3 lines as above, but it doesn't work
> '<keymap mode='view'>
> 	 <map in='menu' out='F'/>
> </keymap>'

keyap should be inside the defaults - not llppconfig, i.e.

`<llppconfig>
 <ui-font size='20'/>
 <defaults
    ...
 >
    <keymap mode='view'>
      <map in='menu' out='F'/>
    </keymap>
 </defaults>
</llppconfig>'
 
-- 
mailto:moosotc@gmail.com

**Comment by pqnhan** [comment]
This llpp.conf file auto generator by llpp don't have \</defaults> tag.
I try to add \</defaults> before </llppconfig> but not succeed.

**Comment by moosotc** [comment]
PQNhan <notifications@github.com> writes:

> This llpp.conf file auto generator by llpp don't have \</defaults> tag.
> I try to add \</defaults> before </llppconfig> but not succeed.

If your current config looks like:

<defaults...
.../>

I.e. defaults is closed you have to replace "/>" with ">" (and add a
closing "</defautls>" tag) if you want are going to add keymap section.

https://wiki.archlinux.org/index.php/Llpp has a working example. More
infromation can be had here - https://repo.or.cz/w/llpp.git/blob/HEAD:/misc/keys.txt.

-- 
mailto:moosotc@gmail.com

**Comment by pqnhan** [comment]
Thank you very much, I did it.
