### ISSUE TITLE
Ctrl-g doesn't work

### ISSUE THREAD

**Issue by Fandekasp** [moosotc/llpp#113]
```
$ llpp -v
llpp v30-dirty, fitz 1.14.0, ocaml 4.07.0/64 bit
configuration file: /home/dori/.config/llpp.conf
```

How to reproduce:
* search something with /
* navigate through matches with n and p
* try to leave search with Ctrl-g ⇒ Nothing happens

Thought: The Escape character feels more natural than Ctrl-g for this purpose (interrupting search)

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> ```
> $ llpp -v
> llpp v30-dirty, fitz 1.14.0, ocaml 4.07.0/64 bit
> configuration file: /home/dori/.config/llpp.conf
> ```
>
> How to reproduce:
> * search something with /
> * navigate through matches with n and p
> * try to leave search with Ctrl-g ⇒ Nothing happens
>
> Thought: The Escape character feels more natural than Ctrl-g for this
> purpose (interrupting search)

Say one has some humongous document [1] and initiates a search with '/',
searching for, say, "abracadabra", on this, addmittedly slow machine, it
takes ~31 seconds to arrive at "no matches" state. To interrupt this
search midway (while progress bar at the bottom is active) 'ctrl-g' can
be used.

ctrl-g does nothing when the search has been completed (i.e. a page with
a match has been found)

As for natural, it is natural for me as a Emacs user.

[1] ECMA-376, Second Edition, Part 1 - Fundamentals And Markup Language Reference.pdf (5568) pages

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> Oh I see, I misunderstood the doc, thanks for the details. And what I was
> looking for what "u" to dehighlight the text, perfect !
>

And while refreshing my memory on how this code works I've hit a bug
that is hopefully fixed in:
https://github.com/moosotc/llpp/commit/1f3ae0843d5877a0e599d8411d433bd9b0078157

So thanks :)

[..snip..]
