### ISSUE TITLE
RFC: Suggestion to make spacebar behave like it does in `less`

### ISSUE THREAD

**Issue by gnull** [moosotc/llpp#114]
It seems like all other programs treat spacebar key in a different way than llpp and the original mupdf do. When spacebar is pressed, they usually scroll text one screen forward. Examples of such programs are firefox, evince, zathura, w3m and plenty of others. Еven less does it as said in its manpage:

> Scroll forward N lines, default one window (see option -z below).  If N is more than the screen size, only the final screenful is displayed.

The keys PgUp/Down and Ctrl+Up/Down which currently do this in llpp are a bit less comfortable to use. On some keyboards PgUp/Down are small and located inconveniently, and Ctrl+Arrow requires you to find two keys with your fingers both of which are usually small. These actions require some attention from user — you can't just hit these keys blindly like you can with spacebar, which is a lot more comfortable to press, large and located at the very center of the keyboard.

I suggest canging the behaviour of llpp so that it scrolls one screen forward when spacebar is pressed and, similarly, one screen backward when Shift+spacebar is pressed. At the same time we could bind current action of Spacebar to PgUp/Down. This should make llpp's keybinding more silimar to less and more confortable to use.

**Comment by moosotc** [comment]
Ivan Oleynikov <notifications@github.com> writes:

> It seems like all other programs treat spacebar key in a different way
> than llpp and the original mupdf do. When spacebar is pressed, they
> usually scroll text one screen forward. Examples of such programs are
> firefox, evince, zathura, w3m and plenty of others. Еven less does it
> as said in its manpage:
>
>> Scroll forward N lines, default one window (see option -z below).
> If N is more than the screen size, only the final screenful is
> displayed.
>
> The keys PgUp/Down and Ctrl+Up/Down which currently do this in llpp
> are a bit less comfortable to use. On some keyboards PgUp/Down are
> small and located inconveniently, and Ctrl+Arrow requires you to find
> two keys with your fingers both of which are usually small. These
> actions require some attention from user — you can't just hit these
> keys blindly like you can with spacebar, which is a lot more
> comfortable to press, large and located at the very center of the
> keyboard.
>
> I suggest to change the behaviour of llpp so that it scrolls one
> screen forward when spacebar is pressed and, similarly, one screen
> backward when Shift+spacebar is pressed. At the same time we could
> bind current action of Spacebar to PgUp/Down. This should make llpp's
> keybinding more silimar to less and more confortable to use.

<map in='space' out='pgdown'/>

Does what you want for space, shift space does not work out-of-the-box,
trying to figure out why.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Ivan Oleynikov <notifications@github.com> writes:
>
[..snip..]

>
> <map in='space' out='pgdown'/>
>
> Does what you want for space, shift space does not work out-of-the-box,
> trying to figure out why.

Enabling vebose mode (i.e. pressing '-' followed by 'v') and monitoring
console output revealed that here pressing shift-spacebar yields 0xfe08.
I have no idea why or whether it is universal behavior.

<map in='shift-0xfe08' out='pgup'/>

-- 
mailto:moosotc@gmail.com

**Comment by gnull** [comment]
> > <map in='space' out='pgdown'/>

This one worked for me.

> <map in='shift-0xfe08' out='pgup'/>

This one didn't work. But I tried 'shift-space' and it worked
out-of-the box.

Right now it works as I desired with this config:

  <map in='shift-space' out='pgup'/>
  <map in='space' out='pgdown'/>

Just in case, I'm running this version of llpp on Arch Linux:

  $ llpp -v
  llpp v30-dirty, fitz 1.14.0, ocaml 4.07.0/64 bit
  configuration file: /home/io/.config/llpp.conf

Thanks for your helpful suggestions, moosotc!

Is there any chance to make space behave like this by default for
everyone?

**Comment by moosotc** [comment]
Ivan Oleynikov <notifications@github.com> writes:

>> > <map in='space' out='pgdown'/>
>
> This one worked for me.
>
>> <map in='shift-0xfe08' out='pgup'/>
>
> This one didn't work. But I tried 'shift-space' and it worked
> out-of-the box.
>

Great. That was the first thing I've tried but here it didn't work.

> Right now it works as I desired with this config:
>
>   <map in='shift-space' out='pgup'/>
>   <map in='space' out='pgdown'/>
>
> Just in case, I'm running this version of llpp on Arch Linux:
>
>   $ llpp -v
>   llpp v30-dirty, fitz 1.14.0, ocaml 4.07.0/64 bit
>   configuration file: /home/io/.config/llpp.conf
>
> Thanks for your helpful suggestions, moosotc!
>
> Is there any chance to make space behave like this by default for
> everyone?

No, sorry.

-- 
mailto:moosotc@gmail.com
