### ISSUE TITLE
provide --synctex-forward feature similar to zathura

### ISSUE THREAD

**Issue by amosbird** [moosotc/llpp#115]
hi, synctex-inverse in llpp works as expected. However I don't find any feature of synctex-forward in llpp. Is there someway to achieve this?

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> hi, synctex-inverse in llpp works as expected. However I don't find
> any feature of synctex-forward in llpp. Is there someway to achieve
> this?

I don't know. In case of synctex-inverse someone just wanted it and
explained to me what should be done, so I was able to implement it. If
you can do that too (ie explain what should be done and also test it)
then I can try implementing it.

**Comment by amosbird** [comment]
basically it's the opposite of synctex-inverse,  demo video   https://la.wentropy.com/xdbr.webm

when executing `zathura demo.pdf --synctex-forward 41:0:demo.tex`, zathura opens demo.pdf and scrolls to the right page and position. If demo.pdf is already opened, zathura scrolls the cursor in the existing instance.

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> basically it's the opposite of synctex-inverse, demo video
> https://la.wentropy.com/xdbr.webm
>
> when executing `zathura demo.pdf --synctex-forward 41:0:demo.tex`,
> zathura opens demo.pdf and scrolls to the right page and position. If
> demo.pdf is already opened, zathura scrolls the cursor in the existing
> instance.

On the surface it looks as if the thing you want is achievable with
remote interface, some information is avaiable at:
https://wiki.archlinux.org/index.php/Llpp

Then again maybe it is indeed only on the surface...

**Comment by amosbird** [comment]
using named fifo would be too fragile. zathura uses dbus. It first iterates over all instances and try to find a related one https://github.com/pwmt/zathura/blob/develop/zathura/synctex.c#L351

then it does a dbus call to this method https://github.com/pwmt/zathura/blob/develop/zathura/synctex.c#L351

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> using named fifo would be too fragile. zathura uses dbus. It first
> iterates over all instances and try to find a related one
> https://github.com/pwmt/zathura/blob/develop/zathura/synctex.c#L351
>
> then it does a dbus call to this method
> https://github.com/pwmt/zathura/blob/develop/zathura/synctex.c#L351

FWIW both links you've posted point to same line 351 and nowhere on thet
line or bellow (or, for that matter, above) is dbus mentioned.

In any case DBUS is a no got, given that llpp has a native macOS
version.

Also, I guess, one can make named fifos less fragile, but one has to
invent a policy to make it so, I don't feel competent enough to invent
this policy therefore only (portable (fifos)) mechanism is available.

**Comment by amosbird** [comment]
Heh, github really need some delay when pushing notifications. I've had edited that link in less than 3 seconds after it was posted.

> I don't feel competent enough to invent this policy therefore only (portable (fifos)) mechanism is available.

Does that mean it's a "help wanted" issue then?

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> Heh, github really need some delay when pushing notifications. I've
> had edited that link in less than 3 seconds after it was posted.
>
>> I don't feel competent enough to invent this policy therefore only
> (portable (fifos)) mechanism is available.
>
> Does that mean it's a "help wanted" issue then?

I don't really know what that means (not a heavy github user).

The creation of policy/documentation/scripts would certainly require
outside help.

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Amos Bird <notifications@github.com> writes:
>
>> Heh, github really need some delay when pushing notifications. I've
>> had edited that link in less than 3 seconds after it was posted.
>>

I just reply to e-mail I receive (hardly ever visit the website), so, I
guess, lesson here is - github is really _git_ hub and "forced pushes"
do not really work for issues.

>>> I don't feel competent enough to invent this policy therefore only
>> (portable (fifos)) mechanism is available.
>>
>> Does that mean it's a "help wanted" issue then?
>
> I don't really know what that means (not a heavy github user).
>

> The creation of policy/documentation/scripts would certainly require
> outside help.

**Comment by amosbird** [comment]
tbh, policy is not enough. zathura calculates the right rectangles to select when receiving line:col parameters. I guess this feature can be implemented easily in llpp due to ocaml magic :) ?

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> tbh, policy is not enough. zathura calculates the right rectangles to
> select when receiving line:col parameters. I guess this feature can be
> implemented easily in llpp due to ocaml magic :) ?

By policy I meant the name/path of the fifo. As for rectangles - you've
lost me here, rectangles covering what?

-- 
mailto:moosotc@gmail.com

**Comment by amosbird** [comment]
`zathura demo.pdf --synctex-forward 41:16:demo.tex`  means scrolling to the position of the pdf file corresponding to the tex file's line 41 and column 16. In order to scroll to the right pos of the pdf file, we actually need <x-coordinate> and <y-coordinate>. Zathura calculates the coordinates by computing the rectangle area that covers the related tex content. https://github.com/pwmt/zathura/blob/develop/zathura/synctex.c#L267   .  I think a similar feature is deserved in llpp?

**Comment by amosbird** [comment]
So I have this workflow setup.
```bash
#!/usr/bin/env bash

args=()
sync=
pdf=
while (( $# ))
do
    case $1 in
        --synctex-forward)
            sync=$2
            shift
            shift
            ;;
        *.pdf)
            pdf=$(realpath $1)
            shift
            ;;
        *)
            args+=$1
            shift
            ;;
    esac
done

fifoname=$(zathura_getfifo.pl $pdf)
if [ -n "$fifoname" ]
then
    echo 'reload' > $fifoname
    if [ -z "$sync" ]
    then
        echo 'activatewin' > $fifoname
    fi
else
    fifoname=$(mktemp -u /tmp/llpp/XXXXXX)
    mkfifo $fifoname
    trap "rm -rf $fifoname" 0
    export EDITOR=eee
    /home/amos/git/llpp/build/llpp -remote $fifoname -- $pdf &
fi

if [ -n "$sync" ]
then
    synctex view -i $sync -o $pdf -x "echo rect %{page} 999999 %{h} %{v} \$(echo '%{h} + %{width}' | bc -l) \$(echo '%{v} + %{height}' | bc -l) > $fifoname; echo goto %{page} %{x} %{y} > $fifoname"
fi
wait
```

```perl
#!/usr/bin/env perl

use feature qw(say switch);
use IPC::Run3;

sub fuser {
    my $line;
    run3 [ 'fuser', $_[0] ], \undef, \$line, \$line;
    return split( " ", substr( $line, rindex( $line, ": " ) + 2 ) );
}

$file  = $ARGV[0];
@pids  = fuser $file;
@fifos = glob "/tmp/llpp/*";
for my $pid (@pids) {
    for my $fifo (@fifos) {
        if ( grep { $_ eq $pid } fuser($fifo) ) {
            print $fifo;
            exit 0;
        }
    }
}
```

It works fine, instance gets reused, auto-scrolling, etc. However the `synctex view` command only generates one rectangle and is way off from the correct position. Here is a demo https://la.wentropy.com/nzdd.webm

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> So I have this workflow setup.

[..snip..]

>
> It works fine, instance gets reused, auto-scrolling, etc. However the
> `synctex view` command only generates one rectangle and is way off
> from the correct position. Here is a demo
> https://la.wentropy.com/nzdd.webm

Neat. As for `synctex view`, sorry, but I have no idea what it is or how
it's supposed to operate.

The development of synctex/remote features is mostly:

Someone wants something
This desire is somehow articulated
I try to implement it based on the description (if it's looks easy)
Someone finds flaws in the implementation
Rinse and repeat

For instance there's no TeX installed on this machine... This puts more
limits on what's "easy"

**Comment by amosbird** [comment]
>  As for `synctex view`, sorry, but I have no idea what it is or how it's supposed to operate.

Yeah, I don't understand that either. I'll try building something when I get time based on what zathura does.

**Comment by amosbird** [comment]
heh, actually it works just right. I got that `rect` command wrong. I should use `prect` instead :)

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> heh, actually it works just right. I got that `rect` command wrong. I
> should use `prect` instead :)

:)
