### ISSUE TITLE
llpp annotation doesn't show CJK characters

### ISSUE THREAD

**Issue by amosbird** [moosotc/llpp#116]
I have 
```
export LC_CTYPE=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
```
before launching llpp, however the inline annotation displayer still doesn't show any Chinese character, leaving blanks. Opening external annotation editor do reveal those chars.

**Comment by amosbird** [comment]
Also there is a suspicous warning  `warning: freetype getting character advance: invalid argument`

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> I have 
> ```
> export LC_CTYPE=zh_CN.UTF-8
> export LANG=zh_CN.UTF-8
> ```
> before launching llpp, however the inline annotation displayer still
> doesn't show any Chinese character, leaving blanks. Opening external
> annotation editor do reveal those chars.

Can you provide a document with hanzi annotations?

**Comment by amosbird** [comment]
https://la.wentropy.com/uHhu.pdf

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> https://la.wentropy.com/uHhu.pdf

Default font use to draw UI elements does not cover Han characters, one
can use something like:

<ui-font size='20'><![CDATA[/home/malc/xsrc/llpp/build/mupdf/resources/fonts/han/SourceHanSerif-Regular.ttc]]></ui-font>

in llpp.conf.

Caveat emptor: there's no support for complex scripts/shaping in llpp.

-- 
mailto:moosotc@gmail.com

**Comment by amosbird** [comment]
Cool. Does it somehow support two fonts? Primary one for ascii and latin characters and the fallback of hanzi font?

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> Cool. Does it somehow support two fonts? Primary one for ascii and
> latin characters and the fallback of hanzi font?

No.

-- 
mailto:moosotc@gmail.com

**Comment by amosbird** [comment]
Ok, I'll build a combined font for llpp then. Thanks.
