### ISSUE TITLE
brightness color

### ISSUE THREAD

**Issue by Fandekasp** [moosotc/llpp#117]
Hi @moosotc 
It is nice that we have some color options in `$XDG_CONFIG_HOME/llpp.conf`, but most of my documents are pdfs and my solarized background color is ignored for the pdf white background.
```
    background-color='253/246/227'
    scrollbar-color='238/232/213/178'
    scrollbar-handle-color='0/43/54/178'
    texture-color='0/43/54/0'
```

Since I always use the brightness `[` and `]` shortcuts to make the document more eye-friendly, I was wondering if you could add tinting or something like that, so the document color looks more similar to the color I want to see rather than black?

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> Hi @moosotc 
> It is nice that we have some color options in
> `$XDG_CONFIG_HOME/llpp.conf`, but most of my documents are pdfs and my
> solarized background color is ignored for the pdf white background.
> ``
>     background-color='253/246/227'
>     scrollbar-color='238/232/213/178'
>     scrollbar-handle-color='0/43/54/178'
>     texture-color='0/43/54/0'
> ```
>
> Since I always use the brightness `[` and `]` shortcuts to make the
> document more eye-friendly, I was wondering if you could add tinting
> or something like that, so the document color looks more similar to
> the color I want to see rather than black?

Not sure I'm getting the question... What prevents you from setting the
brightness globally so that you don't have to use brackets every time?
(i.e. setting brightness value to something acceptable in the defaults
section inside $XDG_CONFIG_HOME/llpp.conf)

**Comment by Fandekasp** [comment]
@moosotc sorry for the confusing request.

The pdf documents I'm reading have white background, and I woud prefer reading them on a yellowish solarized background color instead. Since the llpp background-color doesn't work on pdfs, I am wondering if adding a new option "tinting" to colorize the page could do the trick.

Brightness is a float value from 0 to 1, and as I understand, it only changes the color of the page from its original color to black.  Setting a color for value doesn't work
```
error processing attribute (`"brightness"' = `"253/246/227"'): Failure("float_of_string")
```

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> @moosotc sorry for the confusing request.
>
> The pdf documents I'm reading have white background, and I woud prefer
> reading them on a yellowish solarized background color instead. Since
> the llpp background-color doesn't work on pdfs, I am wondering if
> adding a new option "tinting" to colorize the page could do the trick.
>
> Brightness is a float value from 0 to 1, and as I understand, it only
> changes the color of the page from its original color to black.
> Setting a color for value doesn't work

Yes it "only" modifies everything that will be drawn.

> ```
> error processing attribute (`"brightness"' = `"253/246/227"'):
> Failure("float_of_string")
> ``` 

If I understood you correctly, what you want is the ability to modify
"paper color". link.c:rendertile does this "whitening" of the page to be
rendered via fz_clear_pixmap_with_value call, this function has
scary/amusing comment inside mupdf's sources. fz_fill_pixmap_with_color
should probabsy be used instead, but it's a function of 5 arguments
I'm a bit uneasy with.

**Comment by Fandekasp** [comment]
Yes, paper color is what I wish I could use, didn't know mupdf had this property available :)

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> Yes, paper color is what I wish I could use, didn't know mupdf had
> this property available :)

diff --git a/link.c b/link.c
index 76b0464..ea6b88e 100644
--- a/link.c
+++ b/link.c
@@ -165,6 +165,7 @@ static struct {
     GLenum texty;
 
     fz_colorspace *colorspace;
+    float papercolor[4];
 
     struct {
         int w, h;
@@ -614,7 +615,10 @@ static struct tile *rendertile (struct page *page, int x, int y, int w, int h,
 
     tile->w = w;
     tile->h = h;
-    fz_clear_pixmap_with_value (state.ctx, tile->pixmap, 0xff);
+    fz_fill_pixmap_with_color (state.ctx, tile->pixmap,
+                               fz_device_rgb (state.ctx),
+                               state.papercolor,
+                               fz_default_color_params);
 
     dev = fz_new_draw_device (state.ctx, fz_identity, tile->pixmap);
     ctm = pagectm (page);
@@ -3790,6 +3794,10 @@ void ml_init (value csock_v, value params_v)
     state.trimfuzz.y1 = Int_val (Field (fuzz_v, 3));
 
     set_tex_params (colorspace);
+    state.papercolor[0] = 1.f;
+    state.papercolor[1] = 1.f;
+    state.papercolor[2] = 1.f;
+    state.papercolor[3] = 0.f;
 
     if (*fontpath) {
         state.face = load_font (fontpath);

**Comment by tuncer** [comment]
Great to see I'm not the only one to miss this feature. In fact, I had a similar patch cooking in my fork, where @moosotc and I were discussing implementation details. I'll rework it accordingly, now that there's consensus on the approach. Stay tuned...

**Comment by tuncer** [comment]
See #118.

**Comment by tuncer** [comment]
@Fandekasp, `paper-color` option is in `master` now, so this should be resolved.

**Comment by Fandekasp** [comment]
@tuncer it looks like the git version of llpp on AUR is more outdated than the stable version ^^
```console
$ yay -Ss llpp
aur/llpp-git 30.r22.g6905dbc-1 (+60 0.00%) 
    A graphical PDF viewer which aims to superficially resemble less(1).
community/llpp 30.r63.gcf119d0-1 (19.9 MiB 36.7 MiB) (Installed)
    opengl accelerated pdf viewer based on mupdf
```
I'll just wait for the official update. Anyways, you guys are really fast, thanks a lot for that :cupid:

**Comment by Fandekasp** [comment]
@moosotc when can we expect an update on the arch linux packages?

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> @moosotc when can we expect an update on the arch linux packages?

i don't know, not affiliated with the people who make those.

**Comment by eli-schwartz** [comment]
> @moosotc when can we expect an update on the arch linux packages?

I do not see a stable update, why do you think it should be updated?

**Comment by Fandekasp** [comment]
@eli-schwartz thanks for the follow-up.

* the current version of llpp is not built from the "stable" v30 (Oct 3, 2018), but from [some commit](https://github.com/moosotc/llpp/commit/cf119d072f56f8a1371190c2f61e4de9ada05a6d) pushed to master on May 9.
* [llpp-git](https://aur.archlinux.org/packages/llpp-git/) is built from a version more recent than v30 but older than llpp (v30.r22), and their source is fishy (git://repo.or.cz/llpp.git, I don't know what repo.or.cz is).

You'll understand why I'm at a loss here. I would assume llpp to be at v30, and llpp-git to be at the latest master commit from github.

@moosotc I'm not seeing a ROADMAP for this project. Can you give more details about the estimated date for releasing v31? Thanks a bunch :grinning:

**Comment by eli-schwartz** [comment]
@Fandekasp I updated the Arch Linux community package for llpp via the following change: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/llpp&id=db3af9991dae6ffb1354154fd6128b51505c4d24

Note the commit message details my reason for updating to a non-stable release -- the stable release no longer builds correctly using the stable libmupdf (due to changes in libmupdf itself), therefore I tested and updated to a new llpp snapshot as that was the fastest way to resolve the FTBFS (Fails To Build From Source). I am not, however, in the habit of regularly building the latest snapshot.

This, then, explains my above statement.
- The only reason to *expect* an update in the Arch Linux repository, is when there is a stable release tagged by @moosotc.
- There may, from time to time, be unstable packages that should not be "expected", which will be uploaded at my discretion, but usually "when it is needed to fix an FTBFS in conjunction with libmupdf".

I hope this clarifies things for you.

**Comment by Fandekasp** [comment]
Thanks for taking the time to explain things, I appreciate. It makes complete sense :+1:

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> @eli-schwartz thanks for the follow-up.
>
> * the current version of llpp is not built from the "stable" v30 (Oct
> 3, 2018), but from [some
> commit](https://github.com/moosotc/llpp/commit/cf119d072f56f8a1371190c2f61e4de9ada05a6d)
> pushed to master on May 9.
> * [llpp-git](https://aur.archlinux.org/packages/llpp-git/) is built
> from a version more recent than v30 but older than llpp (v30.r22), and
> their source is fishy (git://repo.or.cz/llpp.git, I don't know what
> repo.or.cz is).
>
repo.or.cz is an original llpp repository (github mirror came much later)
http://caml.inria.fr/pub/ml-archives/caml-list/2010/06/3e7d20f6578df4051235574d47caf1db.en.html

> You'll understand why I'm at a loss here. I would assume llpp to be at
> v30, and llpp-git to be at the latest master commit from github.
>
> @moosotc I'm not seeing a ROADMAP for this project. Can you give more
> details about the estimated date for releasing v31? Thanks a bunch
> :grinning:

there is no ROADMAP. i'm plannig to add a tag when ocaml 4.08 is
officially released

**Comment by Fandekasp** [comment]
@moosotc thanks for the details.
I'm not acquainted with Ocaml, but isn't [4.08 already released](https://opam.ocaml.org/packages/ocaml/ocaml.4.08.0/)? Looking at [Github](https://github.com/ocaml/ocaml), their working version is now at 4.09 :)

Anyways, this discussion isn't related to this issue anymore, so closing, thanks everybody!

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> @moosotc thanks for the details.
> I'm not acquainted with Ocaml, but isn't [4.08 already
> released](https://opam.ocaml.org/packages/ocaml/ocaml.4.08.0/)?
> Looking at [Github](https://github.com/ocaml/ocaml), their working
> version is now at 4.09 :)

hmmm, it looks as if my old ways of doing things aren't good anymore.
i was monitoring https://caml.inria.fr/pub/distrib/ocaml-4.08/ for a
tarball, but 4.08 never landed there (nor at http://ocaml.org/releases/)

thanks for heads up.

>
> Anyways, this discussion isn't related to this issue anymore, so
> closing, thanks everybody!

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Adrien Lemaire <notifications@github.com> writes:
>
>> @moosotc thanks for the details.
>> I'm not acquainted with Ocaml, but isn't [4.08 already
>> released](https://opam.ocaml.org/packages/ocaml/ocaml.4.08.0/)?
>> Looking at [Github](https://github.com/ocaml/ocaml), their working
>> version is now at 4.09 :)
>
> hmmm, it looks as if my old ways of doing things aren't good anymore.
> i was monitoring https://caml.inria.fr/pub/distrib/ocaml-4.08/ for a
> tarball, but 4.08 never landed there (nor at http://ocaml.org/releases/)
>

the official ocaml repository does't have 4.08 tag, coupled with lack of
tarballs and mention of 4.08 in http://ocaml.org/releases/index.html,
makes me think that - no 4.08 wasn't released yet and llpp release will
have to wait some...

**Comment by eli-schwartz** [comment]
Github doesn't have a 4.08 tag either, and the *release candidate 2* for 4.08 was tagged a week ago.

On trunk, they incremented to 4.10 after branching 4.09 -- that's not a release version either, it is simply a development model in which many parallel versions of something are developed, with a stable track, a development track, an experimental track, etc.
