### ISSUE TITLE
Same-level bookmark navigation in outline

### ISSUE THREAD

**Issue by rknop** [moosotc/llpp#119]
This is related to issue #89 (which is now closed).

I find that the left and right cursor buttons are cluky for navigating a long document with a large number of bookmarks of different levels.

The problem: consider a book whose outline has

Chapter 1
 ..Section 1
 ....Subsection 1.1
 ....Subsection 1.2
 ..Section 2
 ....Subsection 2.1
 ....Subsection 2.2
 ....(etc).
Chapter 2
(etc)

In the outline, I'm currently on Chapter 1, and I want to jump to Chapter 2 (then 3, 4, etc.).  If I press the right arrow button, I go to Section 1, then Subsection 1.1, then Section 1.2, then Subsection 1.2, and finally when I get through all the sections, I get to Chapter 2.  In practice, this is not very usable for a long document with many subsections.  It requires too many presses; in practice, I start to speed up, and by the time I get where I want, I'm trying to move too fast and am liable to jump right past what I was looking for.

Issue #89 suggested fixing this with the ability to collapse outlines.

Another way to fix this would be a button combination (CTRL-Shift and arrow, or some such) that jumps to the next bookmark of the same or a higher level.  That would allow me to jump straight from Chapter 1 to Chapter 2.  This together with the left and right arrows would make navigating a large nested outline MUCH easier;.

**Comment by moosotc** [comment]
Rob Knop <notifications@github.com> writes:

> This is related to issue #89 (which is now closed).
>
> I find that the left and right cursor buttons are cluky for navigating a long document with a large number of bookmarks of different levels.
>
> The problem: consider a book whose outline has
>
> Chapter 1
>    Section 1
>       Subsection 1.1
>       Subsection 1.2
>   Section 2
>       Subsection 2.1
>       Subsection 2.2
>       .....
> Chapter 2
> ....
>
> In the outline, I'm currently on Chapter 1, and I want to jump to Chapter 2 (the 3, 4, etc.).  If I press the right arrow button, I go to Section 1, then Subsection 1.1, then Section 1.2, then Subsection 1.2, and finally when I get through all the sections, I get to Chapter 2.  In practice, this is not very usable for a long document with many subsections.  It requires too many presses; in practice, I start to speed up, and by the time I get where I want, I'm trying to move too fast and am liable to jump right past what I was looking for.
>
> Issue #89 suggested fixing this with the ability to collapse outlines.
>
> Another way to fix this would be a button combination (CTRL-Shift and arrow, or some such) that jumps to the next bookmark of the same or a higher level.  That would allow me to jump straight from Chapter 1 to Chapter 2.  This together with the left and right arrows would make navigating a large nested outline MUCH easier;.

Not saying that what you want is unreasonable, but have you considered
just typing (for exapmle) "ter 2", this shuld land you where you want, no?

**Comment by rknop** [comment]
That would work in exactly the example I gave you.  It does not work in general where the chapters aren't named things like "Chapter n", but have general names.

I've attached a patch that does what I want.  I don't really know OCAML (started learning it about an hour ago), so I'm cargo-culting a bit off of your current code.  However, a quick test seems to indicate it works the way I want:


[outlinepatch.txt](https://github.com/moosotc/llpp/files/3414612/outlinepatch.txt)

**Comment by moosotc** [comment]
Rob Knop <notifications@github.com> writes:

> That would work in exactly the example I gave you.  It does not work
> in general where the chapters aren't named things like "Chapter n",
> but have general names.
>

my bad, i've missed the "should work in general" requirement.

> I've attached a patch that does what I want.  I don't really know
> OCAML (started learning it about an hour ago), so I'm cargo-culting a
> bit off of your current code.  However, a quick test seems to indicate
> it works the way I want:
>

caml used to be an acronym for categorical abstroct machine language,
but it so not the case any more

>
> [outlinepatch.txt](https://github.com/moosotc/llpp/files/3414612/outlinepatch.txt)

there is one thing in this patch i find objectionable, namely nested if
then else with misleading indentation.

diff --git a/main.ml b/main.ml
index d6896a8..60ff83e 100644
--- a/main.ml
+++ b/main.ml
@@ -1942,6 +1942,7 @@ class outlinelistview ~zebra ~source =
              postRedisplay "outline ctrl right";
              {< m_pan = m_pan + 1 >}
            )
+           else if Wsi.withshift mask then self#nextcurlevel 1
            else self#updownlevel 1

i would have added explitit braces/begin-end, otherwise looks good and
if it even works for you - even better. apart from the indentation nag i
have no objections to this, good job - thank you.

**Comment by rknop** [comment]
Yeah, I meant that the problem in the general case is that searching for the next heading only works if you already know what the next heading is.  If you want to jump to the next chapter but haven't memorized what it's called, a search doesn't work.

Re: indentation, that's fine; I'm not up on good OCAML indentation style.  (Python is probably my primary language, so I am very aware of indentation in general....)

Are you going to apply this patch to the main code base?

**Comment by moosotc** [comment]
Rob Knop <notifications@github.com> writes:

> Yeah, I meant that the problem in the general case is that searching
> for the next heading only works if you already know what the next
> heading is.  If you want to jump to the next chapter but haven't
> memorized what it's called, a search doesn't work.
>
> Re: indentation, that's fine; I'm not up on good OCAML indentation
> style.  (Python is probably my primary language, so I am very aware of
> indentation in general....)
>
> Are you going to apply this patch to the main code base?

if the indentaition issue is resolved and there is a 
git-am-able patch - yes

**Comment by rknop** [comment]
Does the indentation look better her?  Also, I made this with "git format-patch" rather than "git diff".


[outline_nextcurlevel_patch.txt](https://github.com/moosotc/llpp/files/3418925/outline_nextcurlevel_patch.txt)

**Comment by moosotc** [comment]
Rob Knop <notifications@github.com> writes:

> Does the indentation look better her?  Also, I made this with "git
> format-patch" rather than "git diff".
>

Nope :) For one thing it only tries to fix main.ml leaving listview
broken. And I have just noticed that flow in listview is broken wrt
ifthenelse indentaiton, so i will commit this one and fix the
indantaiton issues myself (should be a bit easier than triying to
explain exactly what I don't like)

>
> [outline_nextcurlevel_patch.txt](https://github.com/moosotc/llpp/files/3418925/outline_nextcurlevel_patch.txt)

**Comment by rknop** [comment]
Oh!  Huh.  The indentation I put in listview is *exactly the same* as in your function "updownlevel" right below it, so I figured you wouldn't object to it.

**Comment by moosotc** [comment]
Rob Knop <notifications@github.com> writes:

> Oh!  Huh.  The indentation I put in listview is *exactly the same* as
> in your function "updownlevel" right below it, so I figured you
> wouldn't object to it.

what can i say... https://www.youtube.com/watch?v=35K6vQRt67g
anyhow things are now committed, hypocrisy reduced and smoe gratitude is
in order, so - thank you.

**Comment by rknop** [comment]
Heh.  I know what it's like.  Sometimes I look at code I wrote just a couple of months ago, and wonder "who wrote this?"
