### ISSUE TITLE
Eliminate flicker upon refresh (feature request)

### ISSUE THREAD

**Issue by ghennequin** [moosotc/llpp#12]
Would it be possible to implement some sort of double-buffering that prevents the page transiently going black (or filled with checkerboards) upon refresh?

**Comment by ghennequin** [comment]
sorry, should've read the code more carefully; I see you do use glXSwapBuffers; would you have a suggestion then for why I see pronounced flicker?

**Comment by moosotc** [comment]
ghennequin <notifications@github.com> writes:

> Would it be possible to implement some sort of double-buffering that
> prevents the page transiently going black (or filled with
> checkerboards) upon refresh?
>

Can you, please, describe the steps needed to perform to reproduce
flicker?

-- 
mailto:moosotc@gmail.com

**Comment by ghennequin** [comment]
open a PDF document, and press 'r' to refresh. Note that it never flickers when I scroll down the page, nor when I do PageUp or PageDown.

**Comment by moosotc** [comment]
ghennequin <notifications@github.com> writes:

> open a PDF document, and press 'r' to refresh. Note that it never
> flickers when I scroll down the page, nor when I do PageUp or
> PageDown.

Does following work for you? (llpp must be invoked with -wtmode command
line argument)

P.S. What's the use case btw?

diff --git a/link.c b/link.c
index 855f333..c7cb1e6 100644
--- a/link.c
+++ b/link.c
@@ -824,7 +824,7 @@ pdf_load_page_objs (pdf_document *doc)
 }
 #endif
 
-static void initpdims (void)
+static void initpdims (int wthack)
 {
     double start, end;
     FILE *trimf = NULL;
@@ -1091,9 +1091,11 @@ static void initpdims (void)
         }
     }
     end = now ();
-    printd ("progress 1 %s %d pages in %f seconds",
-            state.trimmargins ? "Trimmed" : "Processed",
-            state.pagecount, end - start);
+    if (!wthack) {
+        printd ("progress 1 %s %d pages in %f seconds",
+                state.trimmargins ? "Trimmed" : "Processed",
+                state.pagecount, end - start);
+    }
     state.trimanew = 0;
     if (trimf) {
         if (fclose (trimf)) {
@@ -1697,7 +1699,7 @@ static void * mainloop (void UNUSED_ATTR *unused)
             }
             if (ok) {
                 pdfinfo ();
-                initpdims ();
+                initpdims (wthack);
             }
             unlock ("open");
 
@@ -1934,7 +1936,7 @@ static void * mainloop (void UNUSED_ATTR *unused)
             state.pagedimcount = 0;
             free (state.pagedims);
             state.pagedims = NULL;
-            initpdims ();
+            initpdims (0);
             layout ();
             process_outline ();
             unlock ("settrim");

-- 
mailto:moosotc@gmail.com

**Comment by ghennequin** [comment]
yes, it works perfectly with this patch. What does -wtmode mean btw? Use case: i'm using llpp with synctex and vim to edit latex/pdf files and I refresh the pdf output quite frequently. Thanks!

**Comment by ghennequin** [comment]
actually: I noticed that I also get the flicker when I resize the window. Is there also a fix for that?

**Comment by moosotc** [comment]
ghennequin <notifications@github.com> writes:

> yes, it works perfectly with this patch. What does -wtmode mean btw?

It was meant for WhizzyTex (http://cristal.inria.fr/whizzytex/)

> Use case: i'm using llpp with synctex and vim to edit latex/pdf files
> and I refresh the pdf output quite frequently. Thanks!
>

I expected it to be something of this sort, thanks for confirming.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
ghennequin <notifications@github.com> writes:

> actually: I noticed that I also get the flicker when I resize the
> window. Is there also a fix for that?

Nope. The only thing I can think of to somewhat alleviate the problem is
to keep old rendered pages and show them (while those matching resized
window are being pepared), but resizing will invariably lead to the
situation where no old pages are available for the new view area and
this will again lead to flicker. IOW that'd be quite a bit of work and
will not solve the problem completely.

-- 
mailto:moosotc@gmail.com

**Comment by ghennequin** [comment]
> but resizing will invariably lead to the situation where no old pages are 
> available for the new view area and this will again lead to flicker.

OK, makes sense. Thanks!

**Comment by frabjous** [comment]
I'm not exactly sure why this was closed, as the feature does not exist in the main branch as far as I can tell. I'm not confident in my ability to apply the patch, especially with the way github seems to have bulleted part of the diff, if even the patch would still work years later. 
Anyway, I was hoping to use llpp in a similar manner, with a live-updating PDF preview for LaTeX. The flashing back to the checkerboard, however, is far too distracting to make this viable.  Even flashing a plain white background would be preferable. The plain MuPDF viewer does not have his problem, though its lack of synctex features makes llpp otherwise much more attractive.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> I'm not exactly sure why this was closed, as the feature does not
> exist in the main branch as far as I can tell. I'm not confident in my
> ability to apply the patch, especially with the way github seems to
> have bulleted part of the diff, if even the patch would still work
> years later.
> Anyway, I was hoping to use llpp in a similar manner, with a
> live-updating PDF preview for LaTeX. The flashing back to the
> checkerboard, however, is far too distracting to make this viable.
> Even flashing a plain white background would be preferable. The plain
> MuPDF viewer does not have his problem, though its lack of synctex
> features makes llpp otherwise much more attractive.

Doubt that the patch still makes any sense, given that I've removed
wtmode along the way. mupdf-[gl|x11] works better, in the resize case at
least, for two main reasons (I guess):
 1) it only has to deal with one page (no "continous scroll")
 2) the page has the same dimensions when the window is resized

As for flickering when "live editing" - I am not a writer, but a reader,
it's hard for me to come up with heuristics to alleviate the problem
that I, myself, am not experiencing, I've tried (with wtmode for
instance) but wasn't successful apparently.

When you have edited the document and want your edits to be presented in
llpp - you tell it, one way or the other, to reload the wole document,
and then the querstion arises what should it display while the
loading/rendering is being performed?

wtmode(originally meant to work with whizzytex, hence the name) IIRC
delayed the redisplay if certain conditons were met, thus reducing the
flickering. Nobody complained when I've removed it (as this feature had
some indirect costs and complicated the code) so here we are...

-- 
mailto:moosotc@gmail.com

**Comment by frabjous** [comment]
I'm not using whizzytex, which is an emacs plugin, but rather an equivalent plugin for the micro text editor (which I wrote myself). Basically, every time I take even the slightest break in typing, under the hood, the document is saved, and a new pdf is created, and then llpp is refreshed via the reload command sent to the FIFO remote. (I've also tried it with the HUP signal.)

I'll try the patch when I get a chance, but when I was trying to come up with a method of showing you the problem, I think I discovered what it is that is bothering me, which is that it is actually displaying some text during the refresh period, something like "Loading [0.0]". It disappears so fast that before I couldn't even tell what I was seeing. But it is definitely noticeable.

I made two animated gifs of my desktop, with the windows shrunk down to make the gifs appropriately sized. The first is llpp, and the second is the same thing on mupdf:

LLPP (It only happens near the end of the loop in the recording)

![](https://the21stcenturymonads.net/misc/llpp-out.gif)

MUPDF

![](https://the21stcenturymonads.net/misc/mupdf.gif)

Of course, llpp has much better features than mupdf: as a non-author, you went to the trouble to do a really nice and flexible implementation for synctex, which I more than appreciate as an author!

But I'll get back to you after trying the patch.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> I'm not using whizzytex, which is an emacs plugin, but rather an
> equivalent plugin for the micro text editor (which I wrote
> myself). Basically, every time I take even the slightest break in
> typing, under the hood, the document is saved, and a new pdf is
> created, and then llpp is refreshed via the reload command sent to the
> FIFO remote. (I've also tried it with the HUP signal.)
>

Only mentioned whizzytex to explain the origin of the (removed) wtmode.

> I'll try the patch when I get a chance, but when I was trying to come
> up with a method of showing you the problem, I think I discovered what
> it is that is bothering me, which is that it is actually displaying
> some text during the refresh period, something like "Loading
> [0.0]". It disappears so fast that before I couldn't even tell what I
> was seeing. But it is definitely noticeable.
>
> I made two animated gifs of my desktop, with the windows shrunk down
> to make the gifs appropriately sized. The first is llpp, and the
> second is the same thing on mupdf:
>

Thanks, much appreciated. What basically happens is this:

llpp receives a message that it must reload the document

it instructs mupdf to do the loading/rendering

while the processing takes place the UI part is being notified that
things have changed

it tries to redisplay, but rendering/loading hasn't finnished yet and so
it draws a "Loading..." message

Once there was a throttling mode so that one can delay the redisplaying
part for a bit, but I've removed that too, as things that I, personally,
do not use tend to bitrott quite rapidly

> LLPP (It only happens near the end of the loop in the recording)
>
> ![](https://the21stcenturymonads.net/misc/llpp-out.gif)
>
> MUPDF
>
> ![](https://the21stcenturymonads.net/misc/mupdf.gif)
>
> Of course, llpp has much better features than mupdf: as a non-author,
> you went to the trouble to do a really nice and flexible
> implementation for synctex, which I more than appreciate as an author!
>
> But I'll get back to you after trying the patch.

-- 
mailto:moosotc@gmail.com

**Comment by frabjous** [comment]
The patch seems to work wonders! Thanks so much for your help.

![](https://the21stcenturymonads.net/misc/llpp-good.gif)

I made a PKGBUILD for ArchLinux that applies the patch. If you're planning on incorporating this into the main line and/or make it a command line option or similar, I'll just keep it privately until then. If not, then I'll probably upload the PKGBUILD to the AUR (Arch User Repository). Either way, you rock! This puts llpp way ahead of everything else on my document viewer list.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> The patch seems to work wonders! Thanks so much for your help.
>

Thanks for trying.

> ![](https://the21stcenturymonads.net/misc/llpp-good.gif)
>
> I made a PKGBUILD for ArchLinux that applies the patch. If you're
> planning on incorporating this into the main line and/or make it a
> command line option or similar, I'll just keep it privately until
> then. If not, then I'll probably upload the PKGBUILD to the AUR (Arch
> User Repository). Either way, you rock! This puts llpp way ahead of
> everything else on my document viewer list.

The patch basically is a much trimmed down version of the removed
throttle feature. It has consequences. I will give the whole situation
another thought but wouldn't hold the breath that the outcome this time
would be any different than before :(


-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> The patch seems to work wonders! Thanks so much for your help.
>
> ![](https://the21stcenturymonads.net/misc/llpp-good.gif)
>
> I made a PKGBUILD for ArchLinux that applies the patch. If you're
> planning on incorporating this into the main line and/or make it a
> command line option or similar, I'll just keep it privately until
> then. If not, then I'll probably upload the PKGBUILD to the AUR (Arch
> User Repository). Either way, you rock! This puts llpp way ahead of
> everything else on my document viewer list.

Following is a less blunt way to achieve the same effect (a conjecture
given that I have no latex and consequetly no way to test) If it works
for you I will commit it.

diff --git a/config.ml b/config.ml
index ff0eae1..b7c9553 100644
--- a/config.ml
+++ b/config.ml
@@ -298,6 +298,7 @@ type state =
   ; mutable bzoom         : bool
   ; mutable lnava         : (pageno * linkno) option
   ; mutable slideshow     : int
+  ; mutable reload        : (x * y * float) option
   }
 and hists =
   { pat : string circbuf
@@ -446,6 +447,7 @@ let state =
   ; bzoom         = false
   ; lnava         = None
   ; slideshow     = 0
+  ; reload        = None
   }
 ;;
 
diff --git a/main.ml b/main.ml
index c5ebfc7..07b4cd9 100644
--- a/main.ml
+++ b/main.ml
@@ -799,6 +799,7 @@ let opendoc path password =
 
 let reload () =
   state.anchor <- getanchor ();
+  state.reload <- Some (state.x, state.y, now ());
   opendoc state.path state.password;
 ;;
 
@@ -4202,6 +4203,21 @@ let display () =
   Wsi.swapb ();
 ;;
 
+let display () =
+  match state.reload with
+  | None -> display ()
+  | Some (x, y, t) ->
+     let doredisplay =
+       x != state.x || y != state.y || abs_float @@ now () -. t > 0.5
+       || layoutready state.layout
+     in
+     if doredisplay
+     then (
+       state.reload <- None;
+       display ()
+     )
+;;
+
 let zoomrect x y x1 y1 =
   let x0 = min x x1
   and x1 = max x x1

-- 
mailto:moosotc@gmail.com

**Comment by frabjous** [comment]
I'd be happy to give it a try, but could you put the patch in a code block, or make it available somehow as a separate file? If I just copy and paste it, it messes up the leading whitespace inside the patch, and then `git apply` or `patch` (whichever I use) tells me it's mangled or corrupted. The previous one was short enough that I was able to figure out for myself how to restore the whitespace, but my experience with patching is limited enough that this one has so far eluded me.
Thanks again!

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> I'd be happy to give it a try, but could you put the patch in a code
> block, or make it available somehow as a separate file? If I just copy
> and paste it, it messes up the leading whitespace inside the patch,
> and then `git apply` or `patch` (whichever I use) tells me it's
> mangled or corrupted. The previous one was short enough that I was
> able to figure out for myself how to restore the whitespace, but my
> experience with patching is limited enough that this one has so far
> eluded me.
> Thanks again!

I'm answering via my usual mail client (i.e. not using githubs web
interface) so... Let's try attaching the patch, see how it goes...



-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Didn't go to well apparently...  http://ix.io/1z7g

**Comment by frabjous** [comment]
Thanks, I was able to get and apply the new version of patch. Unfortunately, with this version of the patch the "Loading [0,0]" and flickering is back.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> Thanks, I was able to get and apply the new version of
> patch. Unfortunately, with this version of the patch the "Loading
> [0,0]" and flickering is back.

My bad, please try this one http://ix.io/1z7L

-- 
mailto:moosotc@gmail.com

**Comment by frabjous** [comment]
Thanks again.
Interesting results for this one. No flicker at all. Indeed, if I use the HUP command to reload the page, everything seems to work perfectly. However, if I use "echo reload > " to the FIFO remote pipe as the command to refresh, then sometimes it doesn't reload the pdf at all. I suspect it has to do with some kind of bottleneck in receiving and processing the reload commands if they come in too close together.
But I'd need to do some more experimentation to see if I can isolate exactly under what conditions that happens; for me, using the HUP is probably suitable for my needs, but still, it might be worth trying to isolate.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> Thanks again.
> Interesting results for this one. No flicker at all. Indeed, if I use
> the HUP command to reload the page, everything seems to work
> perfectly. However, if I use "echo reload > " to the FIFO remote pipe
> as the command to refresh, then sometimes it doesn't reload the pdf at
> all. I suspect it has to do with some kind of bottleneck in receiving
> and processing the reload commands if they come in too close together.
> But I'd need to do some more experimentation to see if I can isolate
> exactly under what conditions that happens; for me, using the HUP is
> probably suitable for my needs, but still, it might be worth trying to
> isolate.

"reload" and sighup commands do _exactly_ the same thing (i.e. call the
reload function), so it's a bit suprising :(

-- 
mailto:moosotc@gmail.com

**Comment by frabjous** [comment]
I tried today to see if I could isolate the problem, and couldn't replicate the problems I was having yesterday. Everything seems to be working perfectly today, whether I use the reload method or the sighup method. It may have been a fluke, or some error in the script I was using to send the commands. 
I'm happy with how things are now, thanks every so much for your help. Most appreciated.

**Comment by moosotc** [comment]
Kevin Klement <notifications@github.com> writes:

> I tried today to see if I could isolate the problem, and couldn't
> replicate the problems I was having yesterday. Everything seems to be
> working perfectly today, whether I use the reload method or the sighup
> method. It may have been a fluke, or some error in the script I was
> using to send the commands.
> I'm happy with how things are now, thanks every so much for your
> help. Most appreciated.

Great. If you will hit it again, please, try to memorize the conditons.

-- 
mailto:moosotc@gmail.com
