### ISSUE TITLE
How to automatically update pdf file?

### ISSUE THREAD

**Issue by fu123456** [moosotc/llpp#120]
Hi, how to automatically update pdf file, similar to Evince, Okular, Mupdf?
I have done some things according to Archwiki, but it does not work well. So how to handle this issue? Very thanks.

**Comment by moosotc** [comment]
FuGang <notifications@github.com> writes:

> Hi, how to automatically update pdf file, similar to Evince, Okular, Mupdf?
> I have done some things according to Archwiki, but it does not work
> well. So how to handle this issue? Very thanks.

I don't know what you mean by "automatically update pdf" file. You might
mean reload if changed, but arh wiki covers that.

So, what it is you want to do exactly?

**Comment by fu123456** [comment]
It means reload if changed. No any one works for me according to archwiki. Why not like Evince, Okular that can automatically reload pdf file if they are changed? I feel that this is convenient since people are lazy.

**Comment by fu123456** [comment]
My system is Manjaro with i3wm desktop manager.

**Comment by moosotc** [comment]
FuGang <notifications@github.com> writes:

> It means reload if changed. No any one works for me according to
> archwiki. Why not like Evince, Okular that can automatically reload
> pdf file if they are changed? I feel that this is convenient since
> people are lazy.

https://stackoverflow.com/questions/15451114/auto-reload-pdf-viewer-while-editing-latex-files

https://repo.or.cz/llpp.git/blob/HEAD:/misc/llpp.inotify

**Comment by fu123456** [comment]
Thanks. It works for me.
