### ISSUE TITLE
Error: invalid glyph index

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#122]
In some files, llpp gives errors in certain pages that seem to be related to OCR.

The error looks like
`[w] FT_Get_Advance(HiddenHorzOCR, 126): invalid glyph index`

To be clear, it didn't give any error in the same file a couple of versions before.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> In some files, llpp gives errors in certain pages that seem to be
> related to OCR.
>
> The error looks like
> `[w] FT_Get_Advance(HiddenHorzOCR, 126): invalid glyph index`
>
> To be clear, it didn't give any error in the same file a couple of
> versions before.

Does this happen with b1cc2167d698404014d79b9f3794af03312c7ec6 mupdf?
Are any of the problematic files publicly availale?

**Comment by JunnanZ** [comment]
Do you mean I rebuild llpp with mupdf desired version in getmupdf.sh changed to 61cc? 

I got `cannot create context: incompatible header (1.16.1) and library (1.15.0) versions` after running the newly built `llpp`.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Do you mean I rebuild llpp with mupdf desired version in getmupdf.sh
> changed to 61cc?
>
> I got `cannot create context: incompatible header (1.16.1) and library
> (1.15.0) versions` after running the newly built `llpp`.

I just did:

$ git diff
diff --git a/misc/getmupdf.sh b/misc/getmupdf.sh
index 04efbab..e3c395d 100644
--- a/misc/getmupdf.sh
+++ b/misc/getmupdf.sh
@@ -3,7 +3,8 @@ set -eu
 
 MUPDF_OUTPUT_DIR="$1"
 MUPDF_URL="https://github.com/ArtifexSoftware/mupdf"
-MUPDF_DESIRED_VERSION="5354bd4ddf1990dc52e8330353ce319756300379"
+#MUPDF_DESIRED_VERSION="5354bd4ddf1990dc52e8330353ce319756300379"
+MUPDF_DESIRED_VERSION="b1cc2167d698404014d79b9f3794af03312c7ec6"
 
 if [ ! -d ${MUPDF_OUTPUT_DIR} ]; then
     echo "mupdf does not exist, fetching it from ${MUPDF_URL}"

$ sh misc/getmupdf.sh build2
$ bash build.bash build2

And I'm not seeing the incompatible error you cite...

**Comment by JunnanZ** [comment]
Thanks. Now the build was successful. The issue is still there though and I don't have a public file to show you.

Could it be related to my ocaml version? I have 4.08 on my machine.

**Comment by sebras** [comment]
@moosotc asked me, one of the MuPDF developers, to chime in on this one.

Can you share the .PDF-file exhibiting the issue?

**Comment by JunnanZ** [comment]
[Recursive Methods in Economic Dynamics - Stokey, Lucas, and Prescott.pdf](https://github.com/moosotc/llpp/files/3653275/Recursive.Methods.in.Economic.Dynamics.-.Stokey.Lucas.and.Prescott.pdf)

Thank you. Could you try this file?

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> [Recursive Methods in Economic Dynamics - Stokey, Lucas, and
> Prescott.pdf](https://github.com/moosotc/llpp/files/3653275/Recursive.Methods.in.Economic.Dynamics.-.Stokey.Lucas.and.Prescott.pdf)
>
> Thank you. Could you try this file?

I did, no warnings on the first few pages.

**Comment by sebras** [comment]
I do see the warning on page three using mupdf git HEAD. The warning probably comes from freetype, the question being: is something really wrong?

**Comment by sebras** [comment]
Let me focus on the warnings MuPDF prints for page four of the file:

> warning: FT_Get_Advance(HiddenHorzOCR,73): invalid glyph index
> warning: FT_Get_Advance(HiddenHorzOCR,126): invalid glyph index
> warning: FT_Get_Advance(HiddenHorzOCR,71): invalid glyph index
> warning: FT_Get_Advance(HiddenHorzOCR,32): invalid glyph index

Ok, so `FT_Get_Advance(HiddenHorzOCR, 126): invalid glyph index` is what MuPDF prints and then llpp prefixes this warning with `[w]`. `HiddenHorzOCR` is the name of the font being referenced, and MuPDF is trying to determine the width of character with id `126` in that font. Unfortunately the font does not contain any character with that id, so when MuPDF asks FreeType for the width it fails with the error message at the end.

On page four the PDF contains a black/white JBIG2 image of all the visible text. To make that text searchable in a PDF viewer some OCRing software has tried to convert the characters on the page to text and added invisible text strings to the page in the PDF at the locations of the characters in the image. 

Towards the bottom of the page there is a slanted stamp say `"Univerzita Karlova V Praze"`. Here the text appears to be OCRed to `Univerwa Karlova V p c E Eraze`, which is obviously not correct. Before the string `Eraze` the OCRing software decided to add invisible characters using the font `HiddenHorzOCR`, refering to character ids `73`, `126`, `71` and `32`. I think the software was struggling to make sense of what's in the image, and attempted to capture the marks on the page into a newly created font, but failed to actually include the glyphs in the font! I extracted the font file from the PDF and it doesn't seem to contain any characters at all! Yet the PDF at page four refers to characters in this font with ids `73`, `126`, `71` and `32`. I see the same type of errors on many other pages of the book.

My conclusion is that the OCRing software wrote a broken PDF file which causes MuPDF to write warnings when FreeType balks at the broken font, and then llpp dutifully prints the warnings. I'm not sure FreeType, MuPDF or llpp can do any better with this type of file.

**Comment by JunnanZ** [comment]
Thanks!

The question is why I didn't have this error with a previous version and can I somehow suppress this error?
