### ISSUE TITLE
How to avoid openting a same pdf file twice or more times?

### ISSUE THREAD

**Issue by fu123456** [moosotc/llpp#124]
If I have opened a file, "temp.pdf", and then again opened it, at this time, there exist two buffers for a same pdf file. So I want to know the reason, and how to avoid this.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> If I have opened a file, "temp.pdf", and then again opened it, at this
> time, there exist two buffers for a same pdf file. So I want to know
> the reason, and how to avoid this.

Sorry, but i don't understand the problem. Can you, please, describe
what you do (step by step) the expected and the obtained result?

**Comment by fu123456** [comment]
Specifically, I use Helm-bibtex in Emacs to open a pdf file using llpp, then I work for a while and may forgot that I have opened this pdf file, so I use Helm-bibtex to open this pdf file. But actually, this pdf file have been opened in a window, but open it in another window. Therefore, I want to a pdf file only opened in a window.

**Comment by fu123456** [comment]
This characteristic is very often common in mainstream pdf readers, such as Foxidreader, Evince, Okular. So why llpp again open a pdf file I have opened again?

**Comment by fu123456** [comment]
I execute a command "llpp temp.pdf" and again execute this command "llpp temp.pdf". As a result, I have two windows for a same pdf file. So how to avoid this?

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> I execute a command "llpp temp.pdf" and again execute this command
> "llpp temp.pdf". As a result, I have two windows for a same pdf
> file. So how to avoid this?

Thanks for an explanation. And you get that by writing a wrapper script
like:

#!/bin/sh
fuser $1 | read pid; xdotool search --pid $pid --name llpp windowactivate

plus the fallback logic for the situation where there aren't any llpp
instances visiting that document

IOW this functionality does not exist in core llpp.

**Comment by fu123456** [comment]
It does not work. It outputs the following error: Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

My system is Manjaro.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> It does not work. It outputs the following error: Defaulting to search
> window name, class, and classname
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

Works here... You can also try the remote option...

**Comment by fu123456** [comment]
Can you show me a complete bash script to solve this issue? It now seems to does not work. Also outputs errors:Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

**Comment by fu123456** [comment]
I use i3wm window manager.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> I use i3wm window manager.

I use that as well and the exact line i posted is what i have used. FWIW

fuser document.pdf | read pid; xdotool search --pid $pid --name llpp windowactivate                            
Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

when no llpp instance was running

**Comment by fu123456** [comment]
It does not work in your computer?

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> It does not work in your computer?

It does work when there is a matching llpp instance running.

**Comment by fu123456** [comment]
It does not work for me.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> It does not work for me.

Try full path name.

**Comment by fu123456** [comment]
(1)fuser /home/fg/gang_highlight_dataset.pdf | read pid; xdotool search --pid $pid --name 'llpp /home/fg/gang_highlight_dataset.pdf' windowactivate   (this does work well).
(2) fuser $1 | read pid; xdotool search --pid $pid --name `echo \'$window_name\'` windowactivate, does not work. Note $1 is /home/fg/gang_highlight_dataset.pdf. The error is :Defaulting to search window name, class, and classname
xdotool: Unknown command: /home/fg/gang_highlight_dataset.pdf'
Run 'xdotool help' if you want a command list

**Comment by fu123456** [comment]
Here, window_name="llpp $1"

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> (1)fuser /home/fg/gang_highlight_dataset.pdf | read pid; xdotool
> search --pid $pid --name 'llpp /home/fg/gang_highlight_dataset.pdf'
> windowactivate (this does work well).
> (2) fuser $1 | read pid; xdotool search --pid $pid --name `echo
> \'$window_name\'` windowactivate, does not work. Note $1 is
> /home/fg/gang_highlight_dataset.pdf. The error is :Defaulting to
> search window name, class, and classname
> xdotool: Unknown command: /home/fg/gang_highlight_dataset.pdf'
> Run 'xdotool help' if you want a command list

Just use --name llpp

**Comment by fu123456** [comment]
It does not work:
--------------------------
λ ~/ llpp_only_one_window_for_a_same_pdf_file.sh /home/fg/gang_highlight_dataset.pdf
/home/fg/gang_highlight_dataset.pdf:
Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
----------------------------------------------
My script is:
-------------------
#!/bin/sh
fuser $1 | read pid; xdotool search --pid $pid --name llpp windowactivate
------------------

**Comment by fu123456** [comment]
I very need this characteristic of llpp, since I often open many many pdf files as a computer research.

**Comment by fu123456** [comment]
If I run the following command: fuser /home/fg/gang_highlight_dataset.pdf | read pid; xdotool
 search --pid $pid --name llpp  windowactivate, the it does not correctly match the window I wan to go.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> If I run the following command: fuser
> /home/fg/gang_highlight_dataset.pdf | read pid; xdotool
>  search --pid $pid --name llpp windowactivate, the it does not
> correctly match the window I wan to go.

Use $(reaspath $1) instead of plain $1, should work.

**Comment by fu123456** [comment]
It also does not work, with same error.

**Comment by fu123456** [comment]
However, this command "fuser /home/fg/gang_highlight_dataset.pdf | read pid; xdotool search --pid $pid --name 'llpp /home/fg/gang_highlight_dataset.pdf' windowactivate " works well for me.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> It also does not work, with same error.

You have to be specific, what exactly does not work.

**Comment by fu123456** [comment]
this script does not work:
#!/bin/bash
path=$(realpath $1)
fuser $path | read pid; xdotool search --pid $pid --name llpp windowactivate

So I want to know this works well on your computer ?
The error with me is also :
λ ~/ llpp_only_one_window_for_a_same_pdf_file.sh /home/fg/gang_highlight_dataset.pdf
/home/fg/gang_highlight_dataset.pdf:
Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> this script does not work:
> #!/bin/bash
> path=$(realpath $1)
> fuser $path | read pid; xdotool search --pid $pid --name llpp windowactivate
>
> So I want to know this works well on your computer ?
> The error with me is also :
> λ ~/ llpp_only_one_window_for_a_same_pdf_file.sh
> /home/fg/gang_highlight_dataset.pdf
> /home/fg/gang_highlight_dataset.pdf:
> Defaulting to search window name, class, and classname
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

Following works. For documents that mupdf keeps open at least (pdfs work
image files (tested jpeg) do not)

#!/bin/sh
path="$(realpath $1)"
fuser "$path" 2>/dev/null | {
    read pid
    xdotool search --pid $pid --name llpp windowactivate
}

**Comment by fu123456** [comment]
Also output same error:
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> Also output same error:
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

Works here, provided that llpp visiting specific file was started.

**Comment by fu123456** [comment]
yes, --name llpp does not work, while --name llpp $path does work well for me. Thanks.

**Comment by fu123456** [comment]
Why is this function considered as the default function of llpp? I personally feel that it is very common in other pdf readers, such as Foxidreader, Evince, Okular.

**Comment by fu123456** [comment]
For Okular, it provide a paramter --unique for this purpose. So I feel that this function can be added to it for enhancing this pdf reader.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> Why is this function considered as the default function of llpp? I
> personally feel that it is very common in other pdf readers, such as
> Foxidreader, Evince, Okular.

Because i don't need/use it and nobody else imprlemented it.

**Comment by fu123456** [comment]
Thanks.

**Comment by zhenjieliang** [comment]
> fuser /home/fg/gang_highlight_dataset.pdf | read pid; xdotool search --pid $pid --name 'llpp /home/fg/gang_highlight_dataset.pdf' windowactivate

still not works. bugs as follows:

activate 
Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

**Comment by zhenjieliang** [comment]
> yes, --name llpp does not work, while --name llpp $path does work well for me. Thanks.

@fu123456 could you share your complete bash file here?

I run the command 

```
#!/bin/sh
path="$(realpath $1)"
fuser "$path" 2>/dev/null | {
    read pid
    xdotool search --pid $pid --name llpp windowactivate
}
```

or 

```
#!/bin/sh
path="$(realpath $1)"
fuser "$path" 2>/dev/null | {
    read pid
    xdotool search --pid $pid --name llpp $path windowactivate
}
```

neither works.

bugs as follows

activate 
Defaulting to search window name, class, and classname
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

**Comment by moosotc** [comment]
zhenjieliang <notifications@github.com> writes:

>> yes, --name llpp does not work, while --name llpp $path does work
> well for me. Thanks.
>
> @fu123456 could you share your complete bash file here?
>
> I run the command 
>
> ```
> #!/bin/sh
> path="$(realpath $1)"
> fuser "$path" 2>/dev/null | {
>     read pid
>     xdotool search --pid $pid --name llpp windowactivate
> }
> ```
>
> or 
>
> ```
> #!/bin/sh
> path="$(realpath $1)"
> fuser "$path" 2>/dev/null | {
>     read pid
>     xdotool search --pid $pid --name llpp $path windowactivate
> }
> ```
>
> neither works.
>

1. second one is wrong because of the "llpp $path" is not quoted.
2. "--name llpp" can (and should) be replaced with "--class llpp"
3. i just tried it here (by hand in the terminal) and it works for me

> bugs as follows
>
> activate 
> Defaulting to search window name, class, and classname
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

I've seen this error in the past, don't remember the remedy (or indeed
if there is one). Also this is WM dependent, which one do you use?

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> zhenjieliang <notifications@github.com> writes:
>

[..]

>
>> bugs as follows
>>
>> activate 
>> Defaulting to search window name, class, and classname
>> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
>
> I've seen this error in the past, don't remember the remedy (or indeed
> if there is one). Also this is WM dependent, which one do you use?

One more remark, this would only work for files that mupdf (the library)
keeps open. It looks like PDFs [1] are but PNGs [2] aren't.

[1] Are all documents?
[2] Aren't all images?

**Comment by zhenjieliang** [comment]
@moosotc Thanks for your kindly help!
I used i3wm as my window manager. Now my shell script nameed modified_llpp.sh  listed below

```
#!/bin/sh
path="$(realpath $1)"
fuser "$path" 2>/dev/null | {
    read pid
    xdotool search --pid $pid --class llpp windowactivate
}
```

and then I run my command in terminal as (and the htmltools.pdf has not been opened yet)

```
sh modifed_llpp.sh /home/liangzhenjie/Downloads/htmltools.pdf
```

the bug remains
> Defaulting to search window name, class, and classname
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)

but if I run the command as (and the copula.pdf has been opened already)
```
sh modifed_llpp.sh /home/liangzhenjie/Downloads/copula.pdf
```

then not bug reported and wont open the copula.pdf twice.


Once again, thanks very much for your help! @moosotc

**Comment by zhenjieliang** [comment]
> moosotc@gmail.com writes:
> zhenjieliang ***@***.***> writes:
> [..]
> > bugs as follows > > activate > Defaulting to search window name, class, and classname > XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1) I've seen this error in the past, don't remember the remedy (or indeed if there is one). Also this is WM dependent, which one do you use?
> One more remark, this would only work for files that mupdf (the library) keeps open. It looks like PDFs [1] are but PNGs [2] aren't. [1] Are all documents? [2] Aren't all images?

Sorry I dont follow your idea about the pdfs and png things.

my llpp keeps opened and all are pdf files.

Is there any thing related with my i3wm window manager?

**Comment by moosotc** [comment]
zhenjieliang <notifications@github.com> writes:

> @moosotc Thanks for your kindly help!
> I used i3wm as my window manager. Now my shell script nameed
> modified_llpp.sh listed below
>
> ```
> #!/bin/sh
> path="$(realpath $1)"
> fuser "$path" 2>/dev/null | {
>     read pid
>     xdotool search --pid $pid --class llpp windowactivate
> }
> ```
>

This pipline always "succeeds" so to speak, and hence xdotool is being
fed an empty pid, there must be some way to "abort" the pipeline if
fuser exits with a non-zero status, but i cannot immediately think of a
neat way to do that.

**Comment by moosotc** [comment]
zhenjieliang <notifications@github.com> writes:

>> moosotc@gmail.com writes:
>> zhenjieliang ***@***.***> writes:
>> [..]
>> > bugs as follows > > activate > Defaulting to search window name,
>> > class, and classname > XGetWindowProperty[_NET_WM_DESKTOP] failed
>> > (code=1) I've seen this error in the past, don't remember the
>> > remedy (or indeed if there is one). Also this is WM dependent,
>> > which one do you use?
>> One more remark, this would only work for files that mupdf (the
>> library) keeps open. It looks like PDFs [1] are but PNGs [2]
>> aren't. [1] Are all documents? [2] Aren't all images?
>
> Sorry I dont follow your idea about the pdfs and png things.

I'm just saying that fuser approach will not work for images (mupdf does
not keep the files open and fuser will always fail)
>
> my llpp keeps opened and all are pdf files.

That's then things should work once the fuser issue (described
previously) is fixed.

>
> Is there any thing related with my i3wm window manager? 

Not really, i also use i3wm.

**Comment by zhenjieliang** [comment]
My latest version of shell script works, listed as follows

```
#!/bin/sh
path="$(realpath $1)"
fuser "$path" 2>/dev/null | {
    read pid
if [ -z "$pid" ]
then
      llpp $path > /dev/null 2>&1 &
else
      xdotool search --pid $pid --class "llpp $path" windowactivate
fi

}
```

Thanks for @moosotc and @fu123456

**Comment by moosotc** [comment]
zhenjieliang <notifications@github.com> writes:

> My latest version of shell script works, listed as follows

Great!

>
> ```
> #!/bin/sh
> path="$(realpath $1)"
> fuser "$path" 2>/dev/null | {
>     read pid
> if [ -z "$pid" ]
> then
>       llpp $path > /dev/null 2>&1 &
> else
>       xdotool search --pid $pid --class "llpp $path" windowactivate
> fi
>
> }
> ```
>
> Thanks for @moosotc and @fu123456 

I would have done it slightly differently, but it would be mostly
bikeshedding (even though, obviously, checking the exit code of fuser
invocation is superior to testing pid for emptiness)
