### ISSUE TITLE
support xsel

### ISSUE THREAD

**Issue by aeosynth** [moosotc/llpp#125]
xclip has issues with my editor (kakoune), and i'd like to have just one clipboard utility.

https://github.com/mawww/kakoune/issues/2325

**Comment by moosotc** [comment]
James Campos <notifications@github.com> writes:

> xclip has issues with my editor (kakoune), and i'd like to have just
> one clipboard utility.
>
> https://github.com/mawww/kakoune/issues/2325

Just set the selection-command to xsel in llpp.conf, or there is a
problem with that?

**Comment by aeosynth** [comment]
that works, thanks
