### ISSUE TITLE
How to input Chinese character

### ISSUE THREAD

**Issue by luckyCoderLi** [moosotc/llpp#127]
When i make a bookmark,I can't input Chinese character by fcitx-irime,Could you can help me,thanks

**Comment by moosotc** [comment]
彬 <notifications@github.com> writes:

> When i make a bookmark,I can't input Chinese character by
> fcitx-irime,Could you can help me,thanks

I've installed fcitx-rime (not sure if i need _i_rime or it was just a
typo on your part) no idea how to use it though. It might work (given
that hanzi do not require complex shaping), still i wouldn't be too
suprised that it will blow in one way or the other. (I also don't think
that the default UI font has CJK coverage)

**Comment by aeghn** [comment]
I made a workaround to this (xdotool, zenity is needed):

```
#!/usr/bin/env bash

TEXT=$(zenity  --text "输入汉字" --entry)

echo -n "$TEXT" | xclip -i

xdotool key shift+Insert
```
Save it as a script and bind a shortcut key to it.

**Comment by zhenjieliang** [comment]
Thanks @aeghn

this works for me

`#!/bin/sh

zenity --text "输入汉字" --entry | xclip -sel clip

xdotool key shift+Insert
sleep 0.1
xdotool key Return
`
