### ISSUE TITLE
Pax not working

### ISSUE THREAD

**Issue by Amooti73** [moosotc/llpp#128]
I hope I am not misusing this forum!  This is actually a question that I have posted on unix stackexchange:

https://unix.stackexchange.com/questions/578128/how-is-pax-used-by-ppll-pdf-viewer

Perhaps the question will be linked to this repository anyway, but I thought I would have nothing to lose by adding the above link!

Thanks!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I hope I am not misusing this forum!  This is actually a question that
> I have posted on unix stackexchange:
>
> https://unix.stackexchange.com/questions/578128/how-is-pax-used-by-ppll-pdf-viewer
>
> Perhaps the question will be linked to this repository anyway, but I
> thought I would have nothing to lose by adding the above link!
>
> Thanks!

No problem. PAX is an acronym for "Point And X" so you point to the
word/line/whatever and press 'x' :)

P.S. A bit curious why it's called ppll in the question.

**Comment by Amooti73** [comment]
Thanks for your quick reply!

I will correct my typo tomorrow morning and revisit the program.

In other words, "pax" in llpp has no connection with the unix archiving
utility! Is that correct?

I"m usually in bed by now and I have left my computer, that's why it will
be tomorrow!

John

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks for your quick reply!
>
> I will correct my typo tomorrow morning and revisit the program.
>
> In other words, "pax" in llpp has no connection with the unix archiving
> utility! Is that correct?

That is correct, pax in llpp has no connection to posix pax utilty.

>
> I"m usually in bed by now and I have left my computer, that's why it will
> be tomorrow!
>

**Comment by Amooti73** [comment]
After understanding what llpp "pax" is not, I must admit that I remain ignorant of what is supposed to happen when you

> point to the word/line/whatever and press 'x'

Please forgive my ignorance!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> After understanding what llpp "pax" is not, I must admit that I remain
> ignorant of what is supposed to happen when you
>
>> point to the word/line/whatever and press 'x'
>

The text that in under the cursor is being piped to the pax-command.
There is a video demonstrating my main use of the feature - dictionary
lookup [1]

> Please forgive my ignorance!

Can't blame you, the documentation is simply not there.

[1] https://www.youtube.com/watch?v=4Kt4Z8o3AFE

**Comment by Amooti73** [comment]
Thanks!
I now see what is supposed to happen!
Of course, the YouTube video refers to "dicx" and I did find the [commit for dicx](29916e0cadcdf0ee3136fc3b4655b3c8b0d01a7b). I also was able to toggle the pax mode on and also make the required settings in the llpp.conf file.  However, so far, nothing happens.

Reading the commit, it refers to some requirements like sdvc and rofi, which I have.  However, it also refers to some fonts which I have tried to download and install but I am getting errors, which I have so far been unable to solve.

Maybe it's not worth the effort, but if you have any suggestions, I would welcome them.  I guess this is, perhaps, now a new issue.  On the other hand, it is still about the use of pax!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks!
> I now see what is supposed to happen!
> Of course, the YouTube video refers to "dicx" and I did find the
> [commit for dicx](29916e0cadcdf0ee3136fc3b4655b3c8b0d01a7b). I also
> was able to toggle the pax mode on and also make the required settings
> in the llpp.conf file.  However, so far, nothing happens.
>
> Reading the commit, it refers to some requirements like sdvc and rofi,
> which I have.  However, it also refers to some fonts which I have
> tried to download and install but I am getting errors, which I have so
> far been unable to solve.
>

The commit also mentions that any font can be used. (I no longer even
have font mentioned in the commit here (it was eliminated via
https://www.youtube.com/watch?v=LhMRAjX95k0 method))

> Maybe it's not worth the effort, but if you have any suggestions, I
> would welcome them.  I guess this is, perhaps, now a new issue.  On
> the other hand, it is still about the use of pax!

As a start i would have tested that sdcv works (has dictionaries etc),
$ sdcv -n --utf8-input --utf8-output "moo" 
then you can test that dicx works, then you should probably make sure
somehow that dicx is being called at all.

**Comment by Amooti73** [comment]
Thanks once more!
I have set a font in the config file and made a successful test of sdcv.  However, once more, I am not sure how to "test that dicx works" or how to make sure it is being called!
Oh, well!
I am still open to receiving your advice!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks once more!
> I have set a font in the config file and made a successful test of
> sdcv.  However, once more, I am not sure how to "test that dicx works"
> or how to make sure it is being called!
> Oh, well!
> I am still open to receiving your advice!

Whoops, dicx is not part of llpp but rather my collection of "stuff" [1]

The script also uses links [2] to access urban dictionary (quite easy to
comment out (i)relevant parts though)

[1] https://github.com/moosotc/snippets/blob/master/bin/dicx
[2] http://links.twibright.com/download.php

**Comment by Amooti73** [comment]
Thanks once more!

I have "closed shop" for the night, but I'll check it out tomorrow and let
you know of the progress!

**Comment by Amooti73** [comment]
Some reasonable progress!
I made an executable file for dicx and saved it in my ~/bin file which is in my path variable and I also installed links using apt.
The result is that, if I select a word by clicking and dragging the cursor over it, although nothing is seen to happen, if I run dicx with rofi, the selected word appears and pressing Enter will display the definitions. The definition from Urban dictionary is included at the end after those from sdcv.
Although this functionality is useful, perhaps pax is supposed to display the definitions immediately without having to manually call dicx with rofi.
I await your feedback!
Thanks!

**Comment by Amooti73** [comment]
I thought I would also attach a screenshot of some errors, in case they are informative, although I can't say exactly what might trigger them or whether they have any relation to pax, etc.

![llpp-errorlog-2020-04-09](https://user-images.githubusercontent.com/28224877/78869051-98ed1980-7a4c-11ea-831b-eaff48602b1e.png)

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Some reasonable progress!
> I made an executable file for dicx and saved it in my ~/bin file which
> is in my path variable and I also installed links using apt.
> The result is that, if I select a word by clicking and dragging the
> cursor over it, although nothing is seen to happen, if I run dicx with
> rofi, the selected word appears and pressing Enter will display the
> definitions. The definition from Urban dictionary is included at the
> end after those from sdcv.
> Although this functionality is useful, perhaps pax is supposed to
> display the definitions immediately without having to manually call
> dicx with rofi.
> I await your feedback!
> Thanks!

Have you enabled pax, with -M for instance?

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I thought I would also attach a screenshot of some errors, in case
> they are informative, although I can't say exactly what might trigger
> them or whether they have any relation to pax, etc.
>
> ![llpp-errorlog-2020-04-09](https://user-images.githubusercontent.com/28224877/78869051-98ed1980-7a4c-11ea-831b-eaff48602b1e.png)

I've passed this down to the principal mupdf author:
<ator> malc_: embedded font issues, if there's no observed problem, probably
       harmless  [13:58]
<ator> some embedded fonts don't embed all the glyphs they refer to  [13:59]
<ator> most often the 'space' character is missing

**Comment by Amooti73** [comment]
Thanks for getting feed back from the mupdf person. I'll assume it's harmless and it doesn't really seem to happen in connections with pax.

The answer to your question about enabling pax is yes, I have it enabled.  Since the selected word does get fed in to dicx, I guess something is working!
I just viewed the first YouTube video about llpp + dicx to confirm that rofi seemed to open "spontaneously", which it seems to, at least with the selected word so that one would just press Enter, I guess, to see the definitions. I also noticed pax being turned on in the video.

Thanks for keeping up this "dialogue"!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks for getting feed back from the mupdf person. I'll assume it's
> harmless and it doesn't really seem to happen in connections with pax.
>
> The answer to your question about enabling pax is yes, I have it
> enabled.  Since the selected word does get fed in to dicx, I guess
> something is working!
> I just viewed the first YouTube video about llpp + dicx to confirm
> that rofi seemed to open "spontaneously", which it seems to, at least
> with the selected word so that one would just press Enter, I guess, to
> see the definitions. I also noticed pax being turned on in the video.

It just that links (part of the dicx) goes to a remote http server and
that takes nondeterministic amount of time, otherwise dicx should be as
fast as sdcv itself.

>
> Thanks for keeping up this "dialogue"!

No problem!

**Comment by Amooti73** [comment]
Thanks!

So, I just experimented by commenting out lines 20-22 of the dicx script, but it seemed to make no difference. I still had to open rofi "manually" to run dicx. We also have pretty good internet here, so the lookup by links may not cause a big lag.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks!
>
> So, I just experimented by commenting out lines 20-22 of the dicx
> script, but it seemed to make no difference. I still had to open rofi
> "manually" to run dicx. We also have pretty good internet here, so the
> lookup by links may not cause a big lag.

diff --git a/bin/dicx b/bin/dicx
index dffaacd..902c716 100755
--- a/bin/dicx
+++ b/bin/dicx
@@ -17,7 +17,7 @@ pag() {                                                 \
 phrase="$($src | eval $rofi -markup -p 'Lookup: ')"
 {
     sdcv -n --utf8-input --utf8-output "$phrase"
-    printf "Urban\n"
-    links -dump "https://www.urbandictionary.com/define.php?term=$phrase" \
-        | sed -n '1,/Top def/d;/Get the mug/q;p'
+#    printf "Urban\n"
+#    links -dump "https://www.urbandictionary.com/define.php?term=$phrase" \
+#        | sed -n '1,/Top def/d;/Get the mug/q;p'
 } | pag

**Comment by Amooti73** [comment]
You seem to have posted a proposed edit to the dicx script, but I am not sure whether you are proposing that I do something or you have already done something!  

As I mentioned in my previous post, commenting out the lines for links did not seem to help.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> You seem to have posted a proposed edit to the dicx script, but I am
> not sure whether you are proposing that I do something or you have
> already done something!
>
> As I mentioned in my previous post, commenting out the lines for links
> did not seem to help.

It's a patch that comments out the links lines "properly" (just to
minimize the unknowns). In anycase it's hard for me to guess what might
be wrong, perhaps you can provide the precise reproduction scenario.

**Comment by Amooti73** [comment]
Thanks, once more!
I was certainly puzzled but finally figured out that if you had sent me a patch, I probably need to apply it! Never having done that before, I found these [patching directions](https://gist.github.com/nepsilon/22bc62a23f785716705c) and they worked! However, I believe it was the same as I had done earlier by directly inserting the hash marks to comment out the lines.

As far as providing the "precise reproduction scenario", I will need to think about what that means but if you have time to let me know the needed details, aside from the OS, I'll gladly try to supply them.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks, once more!
> I was certainly puzzled but finally figured out that if you had sent
> me a patch, I probably need to apply it! Never having done that
> before, I found these [patching
> directions](https://gist.github.com/nepsilon/22bc62a23f785716705c) and
> they worked! However, I believe it was the same as I had done earlier
> by directly inserting the hash marks to comment out the lines.

Great.

>
> As far as providing the "precise reproduction scenario", I will need
> to think about what that means but if you have time to let me know the
> needed details, aside from the OS, I'll gladly try to supply them.

That basically means that you specify exactly what you did
(step-by-step) the expected and obtained result.

**Comment by Amooti73** [comment]
OK, but that will be tomorrow because I have commitments just now! Thanks!

**Comment by Amooti73** [comment]
Regarding what I did, I am not sure where to start from.  However, 
1. I installed llpp because of the continuous scrolling that mupdf-gl lacked.
2. Around the same time, I accidentally came across references to both rofi and teiler. Rofi was useful because I am a teacher who projects various materials in i3 windows and forgets what teaching material is in which window! Teiler made it easier to take screenshots. So I installed all three programs on Saturday, April 4th. 
3. As you now know well, the reference to "pax" in the llpp help confused me and you came to my rescue! However, as far as I know, I didn't do anything about trying to get pax to function until the day before yesterday, that is Wednesday, April 8th, and anything I did is, I believe, clear from these multiple posts! However, looking back, I
1. Downloaded the dicx script and saved it as an executable file in ~/bin
2. Made the llpp config settings indicated in the dicx commit, including setting a font.
3. Installed links and tested sdcv
4. Tested pax after commenting out links in dicx.
5. Finally, this morning, after thinking that sdcv might be searching too many dictionaries ("sdcv -l" lists eleven dictionaries!) I edited dicx to limit it to one dictionary, but that didn't have any effect, even with the patched version of dicx.
That's what I can say! The only other step might be sending config/log files, but I'll rely on your suggestions.
Thanks!

**Comment by Amooti73** [comment]
I guess I left out the "expected and obtained result"

The overall expected result of having the dicx script along working sdcv and links installations as well as the required pax settings in the llpp config file is that upon selecting a word and pressing "x" that rofi would automatically open with the "Lookup: " prompt and the selected word displayed whereupon pressing "Enter" would display the definitions.

The obtained result is "defective" only in that I need to manually open rofi using "Super + d". The rest works in that when rofi opens, it does have the "Lookup: " prompt and the selected word.

Maybe that is good enough, though the video of llpp + dicx seemed to show the expected result.

**Comment by Amooti73** [comment]
Yikes!

I have just discovered that the whole problem is the particular pdf I have
been using!!!

I just decided to try others and it works perfectly!

That is

"Point and x"

There is no need even to drag the cursor over the word. Just

-point to the word and
-press x

and rofi opens! Wow!

Thanks for your patience!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I guess I left out the "expected and obtained result"
>
> The overall expected result of having the dicx script along working
> sdcv and links installations as well as the required pax settings in
> the llpp config file is that upon selecting a word and pressing "x"
> that rofi would automatically open with the "Lookup: " prompt and the
> selected word displayed whereupon pressing "Enter" would display the
> definitions.
>
> The obtained result is "defective" only in that I need to manually
> open rofi using "Super + d". The rest works in that when rofi opens,
> it does have the "Lookup: " prompt and the selected word.
>
> Maybe that is good enough, though the video of llpp + dicx seemed to show the expected result.

I still do not understand the issue. [1] is step by step screencast [2]
of what i do here to make llpp,pax,dicx,rofi work. (I have also verified
that it works with virgin config (my adding "-c /dev/null" to the llpp
invocation ) where pax is enabled (-M) and command command is set to
'dicx -' "by hand" in the 'i' screen)

[1] https://www.boblycat.org/~malc/scratch/pax.mkv
[2] Sorry for not having some screen key to show that i indeed press 'X'

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Yikes!
>
> I have just discovered that the whole problem is the particular pdf I have
> been using!!!
>

PDFs can be tricky like that indeed.

> I just decided to try others and it works perfectly!
>

Great.

> That is
>
> "Point and x"
>
> There is no need even to drag the cursor over the word. Just
>
> -point to the word and
> -press x
>
> and rofi opens! Wow!
>
> Thanks for your patience!

You are welcome.

[..snip..]

**Comment by Amooti73** [comment]
Just fyi, just as a guess, I opened the nonworking pdf in pdfchain and
"repaired" it and it no longer "misbehaves"!

However, I have no idea about what exactly needed repair!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Just fyi, just as a guess, I opened the nonworking pdf in pdfchain and
> "repaired" it and it no longer "misbehaves"!
>
> However, I have no idea about what exactly needed repair!

Not an PDF expert myself. You can ask mupdf people on #mupdf channel of
freenode IRC network.

[..snip..]

**Comment by Amooti73** [comment]
Just checked and saw that pdfchain is a gui for pdftk.
The man page for pdftk says it will
"Repair a PDF's corrupted XREF table and stream lengths, if possible."
Whatever that means!

**Comment by Amooti73** [comment]
Just a footnote:
I "played around" with your dicx script and made one to look up stuff in wikipedia.  It probably needs a lot of improvement to, say, handle disambiguation, but it works in a crude way.  I named it ["wikx"](https://gist.github.com/Amooti73/f99dfbd59f8141ab7e982e0bd1f327e4).
If you change the pax-command, it kind of works!
If I can be of any help to you, please let me know, although I really am quite amateur.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Just a footnote:
> I "played around" with your dicx script and made one to look up stuff
> in wikipedia.  It probably needs a lot of improvement to, say, handle
> disambiguation, but it works in a crude way.  I named it
> ["wikx"](https://gist.github.com/Amooti73/f99dfbd59f8141ab7e982e0bd1f327e4).
> If you change the pax-command, it kind of works!
> If I can be of any help to you, please let me know, although I really
> am quite amateur.

Cool :) Though (if i read the script correctly) it requires "wikit" and
off the top of my head i don't know what that is and rather would not
second quess. The (main) reason that dicx lives outside llpp it requires
sdcv.

**Comment by Amooti73** [comment]
That's what I was wondering about, that is, is it very easy for dicx to be part of llpp?  It is as if it is a "plugin"!  That would be the same for "wikx".  I did put a link to a tecmint page about wikit which has to be installed with npm after installing json and npm! I did install them today, but wikit wouldn't work at first because the installed files had dos endings but I finally succeeded in using dos2unix to edit them as per the first answer in [this post](https://stackoverflow.com/questions/18492897/env-node-r-no-such-file-or-directory-with-cordova-cli), even though it seemed to be about macos.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> That's what I was wondering about, that is, is it very easy for dicx
> to be part of llpp?  It is as if it is a "plugin"!  That would be the
> same for "wikx".  I did put a link to a tecmint page about wikit which
> has to be installed with npm after installing json and npm! I did
> install them today, but wikit wouldn't work at first because the
> installed files had dos endings but I finally succeeded in using
> dos2unix to edit them as per the first answer in [this
> post](https://stackoverflow.com/questions/18492897/env-node-r-no-such-file-or-directory-with-cordova-cli),
> even though it seemed to be about macos.

Easy yes. Prudent? I don't know. And would rather avoid having to deal
with CRLF questions if i can help it :)

**Comment by Amooti73** [comment]
As the saying goes, "Fools rush in where angels fear to tread"!

Best wishes!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> As the saying goes, "Fools rush in where angels fear to tread"!
>
> Best wishes!

Heh, had to rely on wikipedia [1] to look it up. Cood thing Conkeror [2]
has wikix like funtionality built in. Not even sure if things like that
speak for or against wikix idea in llpp (given that i have to rely on
palemoon to run conkeror these days... sigh)

[1] https://en.wikipedia.org/wiki/Fools_rush_in_where_angels_fear_to_tread
[2] http://www.conkeror.org/

**Comment by Amooti73** [comment]
Back again!  I became busy, as I will explain.

I never heard of "palemoon" so I had to look it up, but I got the impression that both palemoon and conkerer are browsers.

I don't know whether I was obsessed or just concentrating, but a connection came to me between the pax and a script that I had found in a reply to an [AskUbuntu post](https://askubuntu.com/questions/280475/how-can-instantaneously-extract-text-from-a-screen-area-using-ocr-tools) and use very often to copy any text on the computer screen, ocr it accurately and store it in the clipboard.

So, I just started trying to adapt the ideas of dictionary and wikipedia lookup.  Partly, I realized that in llpp one would have to find a way to be able to choose between wikipedia and sdcv.  Then there was the issue of Wikipedia returning a number of results for the same search.  That was the hardest to solve!

So, I have just uploaded all the scripts to GitHub as "gists". Here is the url:
https://gist.github.com/Amooti73

I also managed to map all of them in my config file for .i3, though it took me some time to get it working until I discovered "bindsym --release"!

Of course, as usual, I have neglected all my duties to my students and others.  On the other hand it was Easter weekend...  Hopefully, I will get back on track tomorrow!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Back again!  I became busy, as I will explain.
>
> I never heard of "palemoon" so I had to look it up, but I got the
> impression that both palemoon and conkerer are browsers.
>

Both palemoon and conkeror have wikipedia entires i believe, so i will
not try to outdo good article authors.

> I don't know whether I was obsessed or just concentrating, but a
> connection came to me between the pax and a script that I had found in
> a reply to an [AskUbuntu
> post](https://askubuntu.com/questions/280475/how-can-instantaneously-extract-text-from-a-screen-area-using-ocr-tools)
> and use very often to copy any text on the computer screen, ocr it
> accurately and store it in the clipboard.
>
> So, I just started trying to adapt the ideas of dictionary and
> wikipedia lookup.  Partly, I realized that in llpp one would have to
> find a way to be able to choose between wikipedia and sdcv.  Then
> there was the issue of Wikipedia returning a number of results for the
> same search.  That was the hardest to solve!
>

Yeah given that there is no way to have different actions for PAX things
aren't as easy in this regard. (Maybe '|' can be of some use, not sure)

> So, I have just uploaded all the scripts to GitHub as "gists". Here is the url:
> https://gist.github.com/Amooti73
>

Braces on line 12 puzzle me (that's probably why always just use `test`
instead of [[ ]] syntax)

> I also managed to map all of them in my config file for .i3, though it
> took me some time to get it working until I discovered "bindsym
> --release"!
>
> Of course, as usual, I have neglected all my duties to my students and
> others.  On the other hand it was Easter weekend...  Hopefully, I will
> get back on track tomorrow!

Situation in Nairobi is a lot "better" than it is here it seems, as the
city is in lockdown and everyone (including students) are quaranteened
in their homes till the end of the April at least.

**Comment by Amooti73** [comment]
Thanks!
I did check out the home pages for palemoon and conkeror.  I have gotten quite used to using w3m, especially in a terminal where I can just open another tmux window for it to look up stuff.  I also like being able to put the text of the page in vim with Esc-e. Otherwise, I'm not above using chrome!

I can't say much about the brackets, except that I copied it from the code in the [YouTube video](https://www.youtube.com/watch?v=PN7aypozVn4&feature=emb_rel_end) and I think it had something to do with handling an "empty response".

Another footnote, though it may not be a big deal is that these methods that use a screen capture cannot something that has a line break so easily.

Finally, schools in Nairobi are also closed and movement is restricted, it is just that since we broke off in the middle of the semester, I should still be working on some notes for the students, etc. and communicating by email. I think they are trying to keep things under control (compared to my home town of New York), though, with our less developed health care, things could still become disastrous.  I hope you are safe!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks!
> I did check out the home pages for palemoon and conkeror.  I have
> gotten quite used to using w3m, especially in a terminal where I can
> just open another tmux window for it to look up stuff.  I also like
> being able to put the text of the page in vim with Esc-e. Otherwise,
> I'm not above using chrome!
>

Well, as a emacs user myself conkeror is indispensible. An while i have
used w3m in the past it has been supplanted by links almost two decades
ago :) As a non vim user i have no idea what Esc-e does in it.

> I can't say much about the brackets, except that I copied it from the
> code in the [YouTube
> video](https://www.youtube.com/watch?v=PN7aypozVn4&feature=emb_rel_end)
> and I think it had something to do with handling an "empty response".
>
> Another footnote, though it may not be a big deal is that these
> methods that use a screen capture cannot something that has a line
> break so easily.
>

Try as i may, i cannot parse tha above paragraph.

> Finally, schools in Nairobi are also closed and movement is
> restricted, it is just that since we broke off in the middle of the
> semester, I should still be working on some notes for the students,
> etc. and communicating by email. I think they are trying to keep
> things under control (compared to my home town of New York), though,
> with our less developed health care, things could still become
> disastrous.  I hope you are safe!

Judgng by the numbers i have heard on the news Nairobi is a safer place
the New York presently...

**Comment by Amooti73** [comment]
Since I installed links2 last week for some reason, I'll give it a try.  I didn't know any better and forget how I "got into" w3m.  It seems w3m is still maintained by a Japanese group and there was a release sometime last year. I have read of the vim vs emacs wars and I am definitely addicted to vim.

I left out a word in the paragraph about the shortcoming of the screen capture.  "..cannot something.." should have been "...cannot handle something...".  I just meant that the screen capture uses a rectangle which you can't drag from the middle of one line to its end and then on to the beginning of the next line as you can with click and drag text selection.  However, if you were still referring to the brackets in the previous paragraph, I can't add anything.  I really don't "know" shell scripting!  I only copy and paste, try to guess what things do, maybe refer to the man page occasionally and keep tweaking.  If I'm lucky, something eventually works!

Yes, Nairobi is safer for now.  I was supposed to go for home leave at the beginning of June, but it is unlikely now!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Since I installed links2 last week for some reason, I'll give it a
> try.  I didn't know any better and forget how I "got into" w3m.  It
> seems w3m is still maintained by a Japanese group and there was a
> release sometime last year. I have read of the vim vs emacs wars and I
> am definitely addicted to vim.
>
> I left out a word in the paragraph about the shortcoming of the screen
> capture.  "..cannot something.." should have been "...cannot handle
> something...".  I just meant that the screen capture uses a rectangle
> which you can't drag from the middle of one line to its end and then
> on to the beginning of the next line as you can with click and drag
> text selection.  However, if you were still referring to the brackets
> in the previous paragraph, I can't add anything.  I really don't
> "know" shell scripting!  I only copy and paste, try to guess what
> things do, maybe refer to the man page occasionally and keep tweaking.
> If I'm lucky, something eventually works!
>

Yes i meant the "something" paragraph. As for c&p... Well yeah sometimes
it works indeed :)

> Yes, Nairobi is safer for now.  I was supposed to go for home leave at
> the beginning of June, but it is unlikely now!

Sorry :(

**Comment by Amooti73** [comment]
I got carried away when I came across [this page](https://github.com/davatorium/rofi/wiki/User-scripts) and thought it would be a "good idea" (ha, ha!) to put my scripts there.  However, it seemed necessary to combine the scripts instead of having two scripts connected by a pipe.  I finally succeeded with two--dict.sh and wikx.sh--but the third one, for the disambiguation "defeated me" (as we say over here) so I posted it as a [question](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de).

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I got carried away when I came across [this
> page](https://github.com/davatorium/rofi/wiki/User-scripts) and
> thought it would be a "good idea" (ha, ha!) to put my scripts there.
> However, it seemed necessary to combine the scripts instead of having
> two scripts connected by a pipe.  I finally succeeded with
> two--dict.sh and wikx.sh--but the third one, for the disambiguation
> "defeated me" (as we say over here) so I posted it as a
> [question](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de).

The amount of remarks/questions regarding the script i have would
overwhelm the e-mail so i will refrain using this medium to try and
address them, if you want we can meet on IRC to try and iron this out.

**Comment by Amooti73** [comment]
Thanks for the quick reply.  I can't say I am surprised that you have questions as I'm sure there must be a lot of "unorthodox" stuff there.  BTW, I found I was combining "bin/sh" with "bin/bash"!  However, I found the shellcheck program and that, at least, showed me some helpful stuff, mostly about the use of quotes.

Please let me know how to meet you on IRC.  It is new to me!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Thanks for the quick reply.  I can't say I am surprised that you have
> questions as I'm sure there must be a lot of "unorthodox" stuff there.
> BTW, I found I was combining "bin/sh" with "bin/bash"!  However, I
> found the shellcheck program and that, at least, showed me some
> helpful stuff, mostly about the use of quotes.
>
> Please let me know how to meet you on IRC.  It is new to me!

https://en.wikipedia.org/wiki/Irc The network where i am presently is
freenode, get yourself an IRC client and join the channel #lshprob there.

**Comment by Amooti73** [comment]
hexchat and xchat are already installed.  Hexchat is asking me to choose a network, but I don't know which to choose or how to decide.

**Comment by Amooti73** [comment]
Good morning!

The commented script is here:

http://tpaste.us/ky9b

thanks!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Good morning!
>
> The commented script is here:
>
> http://tpaste.us/ky9b
>
> thanks!

My comments: http://tpaste.us/ObW6

I think it's better if you will write me directly (my e-mail address is
in git), this will reduce the need to use pastes and "abuse" of
bug-tracker. (IRC is also there)

**Comment by Amooti73** [comment]
Let me check! Thanks!

**Comment by Amooti73** [comment]
Unfortunately, I can't see your email.  I assume by saying it's in "git", you mean it is somewhere in your github repository, but I don't see it.
I was actually stuck with little progress but started to just try a few different things using the terminal and it is now working, except that the script halts (not freezes) before displaying the "disambiguation list" in rofi.  If I press Ctrl-C, rofi opens with the list and the rest (selecting from the list and displaying the result for the selection) completes normally.  The script is so messy that I just want to clean it up before sending it.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Unfortunately, I can't see your email.  I assume by saying it's in
> "git", you mean it is somewhere in your github repository, but I don't
> see it.

Every commit has an author and more often than not this inculdes the
e-mail, so in the llpp checkout on your local machine you can do:

$ git show | grep Author

And this will give you my e-mail.

> I was actually stuck with little progress but started to just try a
> few different things using the terminal and it is now working, except
> that the script halts (not freezes) before displaying the
> "disambiguation list" in rofi.  If I press Ctrl-C, rofi opens with the
> list and the rest (selecting from the list and displaying the result
> for the selection) completes normally.  The script is so messy that I
> just want to clean it up before sending it.

Cool, will wait for it then.

**Comment by Amooti73** [comment]
Sorry to be ignorant, but I, as usual, used "git clone" to get your repo in my Downloads folder and install it from there.  When I tried to read about checkout, it seemed to be more of a command than a "location" where I should run git show!

**Comment by Amooti73** [comment]
Never mind, I just found the email address in one of the "adoc docs" in the ~/Downloads/llpp/adoc folder!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Sorry to be ignorant, but I, as usual, used "git clone" to get your
> repo in my Downloads folder and install it from there.  When I tried
> to read about checkout, it seemed to be more of a command than a
> "location" where I should run git show!

cd into Downloads/llpp and there you can use the git command i showed in
the previous message.

**Comment by Amooti73** [comment]
I just emailed it to you.

**Comment by Amooti73** [comment]
Hi!
Sorry but I just wanted to answer my own [question](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de) and give you credit for your help.  

However, I thought it better to ask your permission before putting your name with with a link to your github account.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> Hi!
> Sorry but I just wanted to answer my own
> [question](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de)
> and give you credit for your help.
>
> However, I thought it better to ask your permission before putting
> your name with with a link to your github account.

I don't mind, thanks for asking.

**Comment by Amooti73** [comment]
I have finished posting things on
[unix & linux stackexchange](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de/580723#580723)
and on
the [wikit issue](https://github.com/KorySchneider/wikit/issues/33)
I had posted.

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I have finished posting things on
> [unix & linux
> stackexchange](https://unix.stackexchange.com/questions/580208/three-bash-scripts-work-together-i-e-script1-script2-script3-give-the-de/580723#580723)
> and on
> the [wikit issue](https://github.com/KorySchneider/wikit/issues/33)
> I had posted.

Nice.

"The unfinished business is whether or not there is a way to send all
the disambiguation results to a file with wikit." is imho the crux of
the matter.

**Comment by Amooti73** [comment]
I was thinking of closing my wikit "issue" and posting a "feature request", but I don't see that option on the wikit repo. It doesn't seem like it would be too hard to do in that wikit has these flags:

> --all  -a  Print all sections of the article (the full page). 
> Recommended to pipe into a reader e.g. less

I have even set the script (wikx.sh) on my machine for that option which works with rofi which is a kind of "reader".
So, can something similar be done to output all the disambiguation results?

Although I probably can't afford to keep spending time on this, I have been thinking either just to drop the screen capture method for simply having rofi open and type in the item to be searched or or find a way to keep the screen capture but also abort it with a key press to move to this other method!

**Comment by moosotc** [comment]
John Flood <notifications@github.com> writes:

> I was thinking of closing my wikit "issue" and posting a "feature
> request", but I don't see that option on the wikit repo. It doesn't
> seem like it would be too hard to do in that wikit has these flags:
>
>> --all  -a  Print all sections of the article (the full page). 
>> Recommended to pipe into a reader e.g. less
>
> I have even set the script (wikx.sh) on my machine for that option
> which works with rofi which is a kind of "reader".
> So, can something similar be done to output all the disambiguation results?
>
> Although I probably can't afford to keep spending time on this, I have
> been thinking either just to drop the screen capture method for simply
> having rofi open and type in the item to be searched or or find a way
> to keep the screen capture but also abort it with a key press to move
> to this other method!

I can only say that there is very little i can do about wikit, i don't
even speak js.

**Comment by Amooti73** [comment]
No problem!  You have given me a lot of your time. It's not urgent...for some reason, I just keep thinking up stuff.
Rofi is just somehow helpful in the way you can call it up and just as quickly "dismiss" it.
