### ISSUE TITLE
key bindings mixed up on external keyboard

### ISSUE THREAD

**Issue by tg-x** [moosotc/llpp#129]
key bindings are mixed up when using multiple keyboards with different layouts

apparently llpp uses keycode of the first keyboard, instead of the reported keysym,
that's why on an external keyboard with a different layout the key bindings are mixed up.

`xev` output for internal keyboard:

```
KeyPress event, serial 95, synthetic NO, window 0x12600001,
    root 0x169, subw 0x0, time 518920769, (467,785), root:(2794,802),
    state 0x0, keycode 46 (keysym 0x6e, n), same_screen YES,
    XLookupString gives 1 bytes: (6e) "n"
    XmbLookupString gives 1 bytes: (6e) "n"
    XFilterEvent returns: False

KeyPress event, serial 50, synthetic NO, window 0x12600001,
    root 0x169, subw 0x0, time 519868431, (-102,970), root:(2225,987),
    state 0x0, keycode 57 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False
```

`xev` output for external keyboard with different layout:
```
KeyPress event, serial 95, synthetic NO, window 0x12600001,
    root 0x169, subw 0x0, time 518932871, (467,785), root:(2794,802),
    state 0x0, keycode 57 (keysym 0x6e, n), same_screen YES,
    XLookupString gives 1 bytes: (6e) "n"
    XmbLookupString gives 1 bytes: (6e) "n"
    XFilterEvent returns: False
```

in this example pressing `n` on the external keyboard would be detected as `b`

**Comment by tg-x** [comment]
upon further testing seems like this issue occurs when the layouts are different on the two keyboards, such that llpp matches keycodes with keysyms according to the first keyboard, updated the description

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> upon further testing seems like this issue occurs when the layouts are
> different on the two keyboards, such that llpp matches keycodes with
> keysyms according to the first keyboard, updated the description

Not sure what to do. At the minimum i will need reproduction steps,
those have to be precise to avoid playing never ending second guessing
game, plus expected vs obtained results.

**Comment by tg-x** [comment]
example:

set default keyboard layout then set external keyboard to different layout
```
# setxkbmap dvorak
# setxkbmap -device `xinput list --id-only 'some external keyboard'` us
```

then launch `llpp`:
- press `i` on internal keyboard, the info screen appears as expected
- press `i` on external keyboard, it is recognized as if i pressed `c` on the internal keyboard

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> example:
>
> set default keyboard layout then set external keyboard to different layout
> ```
> # setxkbmap dvorak
> # setxkbmap -device `xinput list --id-only 'some external keyboard'` us
> ```
>
> then launch `llpp`:
> - press `i` on internal keyboard, the info screen appears as expected
> - press `i` on external keyboard, it is recognized as if i pressed `c`
> on the internal keyboard

Thanks. Thing is: wsi/x11 only updates keymaps when it receives
keymapnotify event, in my WM one can "force it by" having llpp lose and
receive focus... I don't know how to handle this "proprely" though...

**Comment by tg-x** [comment]
apparently there's a `MappingNotify` event that is sent once whenever I switch keyboards.

1. launch `xev`
```
...

KeymapNotify event, serial 32, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```

2. press `i` on internal keyboard (no MappingNotify before switching keyboard)
```
KeyPress event, serial 32, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535233763, (-294,272), root:(2033,881),
    state 0x0, keycode 42 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535233849, (-294,272), root:(2033,881),
    state 0x0, keycode 42 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

3. press `i` on external keyboard (MappingNotify sent)
```
MappingNotify event, serial 35, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyPress event, serial 35, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535239327, (-294,273), root:(2033,882),
    state 0x0, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535239431, (-294,273), root:(2033,882),
    state 0x0, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

4. press `i` on internal keyboard (another MappingNotify sent)
```
MappingNotify event, serial 36, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyPress event, serial 36, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535242129, (-294,273), root:(2033,882),
    state 0x0, keycode 42 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x6200001,
    root 0x169, subw 0x0, time 535242208, (-294,273), root:(2033,882),
    state 0x0, keycode 42 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> apparently there's a `MappingNotify` event that is sent once whenever I switch keyboards.
>
> 1. launch `xev`

diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index 837024c..04a2d99 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -565,6 +565,7 @@ let readresp sock =
 
   | 11 ->                               (* keymapnotify *)
      state.keymap <- E.a;
+     vlog "keymapnotify";
      let s = getkeymapreq state.mink (state.maxk-state.mink-1) in
      sendwithrep sock s (updkmap sock);
      state.capslmask <- 0;

This will print "keymapnotify" whenever llpp receives this event (given
that verbose mode is enabled (which it will be if one presses '-'
followed by 'v' in llpp)). What i see is that just pressing a key on a
second keyboard with qwerty does not result in keymapnotify event,
switching focus in my WM does... Once again i'm not entirely sure what
to do about it.

**Comment by tg-x** [comment]
Seems like `llpp` should handle the `MappingNotify` event (id 34) as well, and adjust its keymap when that is received. Perhaps handling it the same way as `KeymapNotify` would be sufficient?

Docs: [xproto](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#events:MappingNotify), [xlib](https://tronche.com/gui/x/xlib/events/window-state-change/mapping.html)

**Comment by tg-x** [comment]
also, how to enable logging with `vlog` ?

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> Seems like `llpp` should handle the `MappingNotify` event (id 34) as
> well, and adjust its keymap when that is received. Perhaps handling it
> the same way as `KeymapNotify` would be sufficient?
>
> Docs:
> [xproto](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#events:MappingNotify),
> [xlib](https://tronche.com/gui/x/xlib/events/window-state-change/mapping.html)

Mapping notify is not something that is triggered externally the way i
undertstand it, it will be generated when certain requests are made
(SetModifierMapping for instance)

In any case adding 34 handler (just using 11 | 34 in code) does nothing
(as expected). I guess xlib does something that i do not..

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> also, how to enable logging with `vlog` ?

Like the following

diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index 837024c..aab2f10 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -22,6 +22,7 @@ type visiblestate =
   | FullyObscured
 ;;
 
+let vlog = dolog;;
 type wid = int and screenno = int and vid = int and atom = int;;
 
 external glxinit : string -> wid -> screenno -> vid = "ml_glxinit";;
@@ -563,8 +564,9 @@ let readresp sock =
      state.t#visible vis;
      vlog "visibility %d" v;
 
-  | 11 ->                               (* keymapnotify *)
+  | 34 | 11 ->                               (* keymapnotify *)
      state.keymap <- E.a;
+     vlog "keymapnotify";
      let s = getkeymapreq state.mink (state.maxk-state.mink-1) in
      sendwithrep sock s (updkmap sock);
      state.capslmask <- 0;
@@ -581,7 +583,7 @@ let readresp sock =
        let atom = r32 resp 12 in
        if atom = state.deleatom
        then state.t#quit;
-     vlog "atom %#x" atom
+       vlog "atom %#x" atom
 
   | 21 ->                               (* reparent *)
      vlog "reparent"

**Comment by tg-x** [comment]
indeed, focusing the window triggers a `KeymapNotify` event,
however there's no `MappingNotify` received ever.

> also, how to enable logging with `vlog` ?
ah that's with `-` `v` and `-` `-`d

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> indeed, focusing the window triggers a `KeymapNotify` event,
> however there's no `MappingNotify` received ever.
>

MappingNotify

   MappingNotify                           
   request: { Modifier, Keyboard, Pointer} 
   first-keycode, count: CARD8             

   This event is sent to all clients. There is no mechanism to express
   disinterest in this event. The detail indicates the kind of change that
   occurred: Modifiers for a successful SetModifierMapping, Keyboard for a
   successful ChangeKeyboardMapping, and Pointer for a successful
   SetPointerMapping. If the detail is Keyboard, then first-keycode and count
   indicate the range of altered keycodes.

Puzzling all in all...

>> also, how to enable logging with `vlog` ?
> ah that's with `-` `v` and `-` `-`d

-d has a bit diffirent purpose though, not really connected to vlog

Keyboard handling in X11 is the part that was the most problematic for
me from the start.

**Comment by tg-x** [comment]
[Effect of XKB on Core Protocol Requests](https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#Effect_of_XKB_on_Core_Protocol_Requests):
> The server notifies interested clients of keyboard map changes in one of two ways. It sends XkbMapNotify to clients that have explicitly selected them and core protocol MappingNotify events to clients that have not. Once a client requests XkbMapNotify events, the server stops sending it MappingNotify events to inform it of keyboard changes. 

however, i dont see any MapNotify events either,
when disabling xkb by commenting out the following, MappingNotify events start to arrive:

```
           sendwithrep
             sock s
             (fun resp ->
               let supported = r8 resp 1 in
               state.xkb <- supported != 0
             )

```

with xkb enabled likely would have to enable the MapNotify events via [XkbSelectEvents](https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#Selecting_Events)

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> [Effect of XKB on Core Protocol Requests](https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#Effect_of_XKB_on_Core_Protocol_Requests):
>> The server notifies interested clients of keyboard map changes in one of two ways. It sends XkbMapNotify to clients that have explicitly selected them and core protocol MappingNotify events to clients that have not. Once a client requests XkbMapNotify events, the server stops sending it MappingNotify events to inform it of keyboard changes. 

Disabling Xkb makes it so that Notify events are delivered when
switching layouts set with setxkbmap [1] (raison d'etre for Xkb [2] if my
memory serves me)

>
> however, i dont see any MapNotify events either,
> when disabling xkb by commenting out the following, MappingNotify events start to arrive:
>
> ```
>            sendwithrep
>              sock s
>              (fun resp ->
>                let supported = r8 resp 1 in
>                state.xkb <- supported != 0
>              )
>
> ```
>
> with xkb enabled likely would have to enable the MapNotify events via [XkbSelectEvents](https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#Selecting_Events)

Now _this_ ought to be explored. thank you kindly, i will try to look into
it in a bit.

[1] https://github.com/moosotc/snippets/blob/master/.config/i3/config#L205
[2] 02e9fbb66a86d3637ab906de32123a632a419dfe

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> TG × ⊙ <notifications@github.com> writes:
>

[..snip..]

>
> Now _this_ ought to be explored. thank you kindly, i will try to look into
> it in a bit.
>

And my 15 minute hack-job/stab-at-it was a failure, keyboard handling in
X11 is beyond by limited powers. So, what i'm tryng to say is that it
looks as if i do not have the energy/motivation to pursue this,
sorry. If you want to have a go at it i would be more than happy to help
though.

**Comment by tg-x** [comment]
tried to send an `XkbSelectEvents` message, but still no events:
```
             (fun resp ->
               let supported = r8 resp 1 in
               state.xkb <- supported != 0;

               if supported != 0 then
                 let s = Bytes.create 16 in
                 w8 s 0 maj;   (* XKB *)
                 w8 s 1 1;     (* XKBSelectEvents *)
                 w16 s 2 4;    (* request-length *)
                 w16 s 4 0x0100; (* DEVICESPEC: XkbUseCoreKbd *)
                 w16 s 6 0x0FFF; (* EVENTTYPE *)
                 w16 s 8 0x0FFF; (* MAPPARTMASK *)
                 sendstr s sock
             );
```

so i guess a workaround is to not switch keyboards without switching focus,
or have a config option to disable xkb (does that have any side effects?)

**Comment by moosotc** [comment]
TG × ⊙ <notifications@github.com> writes:

> tried to send an `XkbSelectEvents` message, but still no events:
> ```
>              (fun resp ->
>                let supported = r8 resp 1 in
>                state.xkb <- supported != 0;
>
>                if supported != 0 then
>                  let s = Bytes.create 16 in
>                  w8 s 0 maj;   (* XKB *)
>                  w8 s 1 1;     (* XKBSelectEvents *)
>                  w16 s 2 4;    (* request-length *)
>                  w16 s 4 0x0100; (* DEVICESPEC: XkbUseCoreKbd *)
>                  w16 s 6 0x0FFF; (* EVENTTYPE *)
>                  w16 s 8 0x0FFF; (* MAPPARTMASK *)
>                  sendstr s sock
>              );
> ```
>
> so i guess a workaround is to not switch keyboards without switching focus,
> or have a config option to disable xkb (does that have any side effects?)

Yes there is an effect, as, i think, i've said ealier: you lose the
ablity to switch layouts and have llpp be notified via an event (to
reread the keybard mapping, cf updkmap)

And FWIW i did something similar but from within C
(wsi/x11/xlib.c:ml_glxcompleteinit) and with similar net result (ie
none)
