### ISSUE TITLE
Anki deck doesn't exist anymore

### ISSUE THREAD

**Issue by Dupond** [moosotc/llpp#130]
Hello,

In the man page, the link to the key bindings doesn't exist anymore ("This shared item is no longer available.").

Best regards,
Dupond

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> Hello,
>
> In the man page, the link to the key bindings doesn't exist anymore
> ("This shared item is no longer available.").
>

Thanks for heads up, https://github.com/moosotc/llpp/pull/112 or in
other words - i just merged the Anki stuff... should i remove it from
adoc?

**Comment by Dupond** [comment]
Sorry, but where did you merge it ? I can't find it...

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> Sorry, but where did you merge it ? I can't find it...

I don't undrestand the question, maybe
https://github.com/moosotc/llpp/commit/7d03bf6cd582741fd5f2096eee0f8190a4ffa8f5
answers it?

**Comment by Dupond** [comment]
It's amazing how it's hard sometimes to understand each other...

I had seen your commit, but I thought you had merged the full list of default key bindings. Obviously, you haven't.

So I see two solutions here : either do merge this full list into the man page, or re-create the Anki deck.

I think simply remove it from adoc would be a problem : we (users) need some documentation ; I rather think that some info could still be added to the adoc : for example, what are the formats recognized by llpp (epub, etc.), and which dependencies (if any) are needed to read those formats.

Anyway, thanx for this greaaaat PDF viewer (which is much more than that) !

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> It's amazing how it's hard sometimes to understand each other...
>
> I had seen your commit, but I thought you had merged the full list of
> default key bindings. Obviously, you haven't.
>
> So I see two solutions here : either do merge this full list into the
> man page, or re-create the Anki deck.
>

I'd prefer the first option, but someone else would have to do it, i
have no idea what was in the deck and how to replicate it.

> I think simply remove it from adoc would be a problem : we (users)
> need some documentation ; I rather think that some info could still be
> added to the adoc : for example, what are the formats recognized by
> llpp (epub, etc.), and which dependencies (if any) are needed to read
> those formats.
>

I'm very bad at writing documentation, so wait for others to do it for
me, unfortunatelly it's a rare occurence.

> Anyway, thanx for this greaaaat PDF viewer (which is much more than that) !

You are most welcome.

**Comment by Dupond** [comment]
An easy solution could be to simply add the content of `help.ml` to the manpage.

I'd have two questions here :

- I can't find this `help.ml` file on my computer : isn't it installed with `llpp` ? Or is it because I'm not using the latest git version ? (I use `llpp v31-dirty` from the Arch repos).
- Are all the key bindings defined in the `llpp` code described in `help.ml` ?

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> An easy solution could be to simply add the content of `help.ml` to
> the manpage.
>
> I'd have two questions here :
>
> - I can't find this `help.ml` file on my computer : isn't it installed
> with `llpp` ? Or is it because I'm not using the latest git version ?

https://github.com/moosotc/llpp/blob/master/help.ml

> (I use `llpp v31-dirty` from the Arch repos).
> - Are all the key bindings defined in the `llpp` code described in `help.ml` ?

No, help.ml is a "best effort" thing.

**Comment by Dupond** [comment]
So... In which file (in `llpp` code) are all those key bindings defined ?

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> So... In which file (in `llpp` code) are all those key bindings defined ?

Key presses are handled in main.ml.
