### ISSUE TITLE
llpp.conf overwritten each time a file is opened

### ISSUE THREAD

**Issue by Dupond** [moosotc/llpp#131]
Hello,

I use Arch with llpp v31-dirty, fitz 1.16.1, ocaml 4.09.1/64 bit.

My `.config/llpp.conf` is overwritten each time I open a PDF file, so I have no way to set my custom preferences.

Thanx for the help,
Best regards,
Dupond

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> Hello,
>
> I use Arch with llpp v31-dirty, fitz 1.16.1, ocaml 4.09.1/64 bit.
>
> My `.config/llpp.conf` is overwritten each time I open a PDF file, so
> I have no way to set my custom preferences.
>

Not sure what you mean. There is: "Save these parameters as global
defaults at exit" in the info ('i') screen, you can also edit the
"defaults" section of llpp.conf in your text editor.

**Comment by Dupond** [comment]
> you can also edit the "defaults" section of llpp.conf in your text editor

That's what I'm doing : I edit my `.config/llpp.conf` file, save it, exit it. But then if I open any PDF file, my `llpp.conf`is overwritten with the default values I had *before* editing it.

Hope it's understandable now...

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

>> you can also edit the "defaults" section of llpp.conf in your text editor
>
> That's what I'm doing : I edit my `.config/llpp.conf` file, save it,
> exit it. But then if I open any PDF file, my `llpp.conf`is overwritten
> with the default values I had *before* editing it.
>
> Hope it's understandable now...

I think i do, but this shouldn't happen and thus is puzzling, can you
share the "edited" conf file?

**Comment by Dupond** [comment]
I'm really sorry : I had not understood well how the `llpp.conf` file works.

I was trying to delete some lines in the `llpp.conf` file, and, seeing them recreated each time `llpp` was launched, I thought that the whole file was overwritten ; obviously, it's not ! Only the missing lines are re-added, but the ones I had modified haven't changed.

Sorry for the noise and thank you very much for the help you (tried to) provide,
Have a nice day !

**Comment by moosotc** [comment]
Dupond <notifications@github.com> writes:

> I'm really sorry : I had not understood well how the `llpp.conf` file works.

Oh :)

>
> I was trying to delete some lines in the `llpp.conf` file, and, seeing
> them recreated each time `llpp` was launched, I thought that the whole
> file was overwritten ; obviously, it's not ! Only the missing lines
> are re-added, but the ones I had modified haven't changed.
>
> Sorry for the noise and thank you very much for the help you (tried to) provide,
> Have a nice day !

Goot to know that things do work as intended.
