### ISSUE TITLE
Zoom to A4 size (Or a user defined size)

### ISSUE THREAD

**Issue by amosbird** [moosotc/llpp#132]
Hi, is there a way to zoom to real A4 size in llpp? Is that even possible? (due to different monitor size and resolution). Or perhaps llpp allows to zoom to a pre-defined zoom level?

**Comment by moosotc** [comment]
Amos Bird <notifications@github.com> writes:

> Hi, is there a way to zoom to real A4 size in llpp? Is that even
> possible? (due to different monitor size and resolution). Or perhaps
> llpp allows to zoom to a pre-defined zoom level?

Not really, no. You can play around with Ctrl-[1..4] and there is always
-Z option but llpp does not look at the pixel density of the monitor.
