### ISSUE TITLE
Disable errors globally

### ISSUE THREAD

**Issue by sudo-nice** [moosotc/llpp#134]
Some PDF and EPUB files I often view, have errors, so every time I open such a file, the error window would pop at the bottom of the window, and I have to press <kbd>e</kbd> followed by <kbd>Return</kbd>, to get rid of the error message.
It would be nice to be able to disable displaying errors completely.

P.S. Thank you for the best viewer!

**Comment by moosotc** [comment]
sudo-nice <notifications@github.com> writes:

> Some PDF and EPUB files I often view, have errors, so every time I
> open such a file, the error window would pop at the bottom of the
> window, and I have to press <kbd>e</kbd> followed by
> <kbd>Return</kbd>, to get rid of the error message.
> It would be nice to be able to disable displaying errors completely.

I don't think that even an optional way to disable error nagging is a
way to go, things do go wrong and 'see no evil, hear no evil' only sweeps
them under the rug, can you point to the document that causes problems
for you?

All that said unconditional disabling nagging is easy:

diff --git a/main.ml b/main.ml
index cbebce9..27f8530 100644
--- a/main.ml
+++ b/main.ml
@@ -1154,7 +1154,7 @@ let act cmds =
   | "emsg", args ->
      Buffer.add_string state.errmsgs args;
      Buffer.add_char state.errmsgs '\n';
-     state.newerrmsgs <- true;
+     (* state.newerrmsgs <- true; *)
      postRedisplay "error message"
 
   | "progress", args ->

>
> P.S. Thank you for the best viewer!

Thanks for kind words :)

**Comment by sudo-nice** [comment]
>can you point to the document that causes problems for you?

Here is an EPUB for example: http://jyotirmoy.net/others/rust-book.epub

Thank you for the patch, will try it later. :smile:
