### ISSUE TITLE
create tag v32

### ISSUE THREAD

**Issue by wamserma** [moosotc/llpp#135]
v31 is not compatible with muPDF 1.17 and quite a few fixes have happened since v31 was tagged.

Tagging some version after
77a0f680be07d6ca61ae3b5d242a681c6bf3f436
as 'v32' would make downstream packaging a bit easier, e.g. [here](https://github.com/NixOS/nixpkgs/pull/88919)

**Comment by moosotc** [comment]
Markus Wamser <notifications@github.com> writes:

> v31 is not compatible with muPDF 1.17 and quite a few fixes have
> happened since v31 was tagged.
>
> Tagging some version after
> 77a0f680be07d6ca61ae3b5d242a681c6bf3f436
> as 'v32' would make downstream packaging a bit easier,
> e.g. [here](https://github.com/NixOS/nixpkgs/pull/88919)

Thanks for heads up. There is a certain issue (with PDF outline) and
another with executable stack that mupdf developers might address. I
want to sync once that happens, if not i'll tag v32 with watever the
head will be in, say, two days.
