### ISSUE TITLE
Building llpp stopped with an error using Linux on Fedora 32 with gcc-10

### ISSUE THREAD

**Issue by s-usr** [moosotc/llpp#136]
Building llpp stopped with an error using Linux on Fedora 32 with gcc-10.

collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
ocamlc -custom str.cma unix.cma -o build/llpp  build/link.o build/cutils.o build/version.o build/lablGL/ml_gl.o build/lablGL/ml_glarray.o build/lablGL/ml_raw.o build/wsi/x11/keysym2ucs.o build/wsi/x11/xlib.o build/utils.cmo build/keys.cmo build/wsi/x11/wsi.cmo build/utf8syms.cmo build/lablGL/raw.cmo build/lablGL/gl.cmo build/lablGL/glPix.cmo build/lablGL/glMisc.cmo build/lablGL/glTex.cmo build/lablGL/glFunc.cmo build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo build/confstruct.cmo build/config.cmo build/ffi.cmo build/glutils.cmo build/lablGL/glMat.cmo build/listview.cmo build/help.cmo build/lablGL/glClear.cmo build/main.cmo -cclib "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL -lX11" failed
fail 62 sec

**Comment by nojb** [comment]
Just guessing, this may be the issue described in https://discuss.ocaml.org/t/opam-switch-create-and-gcc10/5864 involving the `-fno-common` flag and gcc 10. See also https://github.com/ocaml/ocaml/pull/9180

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

> Building llpp stopped with an error using Linux on Fedora 32 with gcc-10.
>
> collect2: error: ld returned 1 exit status
> File "_none_", line 1:
> Error: Error while building custom runtime system
> ocamlc -custom str.cma unix.cma -o build/llpp build/link.o
> build/cutils.o build/version.o build/lablGL/ml_gl.o
> build/lablGL/ml_glarray.o build/lablGL/ml_raw.o
> build/wsi/x11/keysym2ucs.o build/wsi/x11/xlib.o build/utils.cmo
> build/keys.cmo build/wsi/x11/wsi.cmo build/utf8syms.cmo
> build/lablGL/raw.cmo build/lablGL/gl.cmo build/lablGL/glPix.cmo
> build/lablGL/glMisc.cmo build/lablGL/glTex.cmo build/lablGL/glFunc.cmo
> build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo
> build/confstruct.cmo build/config.cmo build/ffi.cmo build/glutils.cmo
> build/lablGL/glMat.cmo build/listview.cmo build/help.cmo
> build/lablGL/glClear.cmo build/main.cmo -cclib
> "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL
> -lX11" failed
> fail 62 sec

ld doesn't tell what is wrong in this case.. can you try nuking the
contents of build directory (sans mupdf) and rebuilding it anew?

**Comment by moosotc** [comment]
Nicolás Ojeda Bär <notifications@github.com> writes:

> Just guessing, this may be the issue described in
> https://discuss.ocaml.org/t/opam-switch-create-and-gcc10/5864
> involving the `-fno-common` flag and gcc 10. See also
> https://github.com/ocaml/ocaml/pull/9180

I have 10.1 and never seen this... (puzzled)

**Comment by nojb** [comment]
> I have 10.1 and never seen this... (puzzled)

Which version of OCaml? The issue I referred to was fixed in OCaml 4.09.1 and later.

**Comment by moosotc** [comment]
Nicolás Ojeda Bär <notifications@github.com> writes:

>> I have 10.1 and never seen this... (puzzled)
>
> Which version of OCaml? The issue I referred to was fixed in OCaml
> 4.09.1 and later.

Let's find out
build.bash:91

overs="$(ocamlc -vnum 2>/dev/null)" || overs=""
test "$overs" = "4.10.0" || {
    url=https://caml.inria.fr/pub/distrib/ocaml-4.10/ocaml-4.10.0.tar.xz

So 4.10.0 is the only supported version :)

**Comment by s-usr** [comment]
> s-usr <notifications@github.com> writes:
> Building llpp stopped with an error using Linux on Fedora 32 with gcc-10. collect2: error: ld returned 1 exit status File "_none_", line 1: Error: Error while building custom runtime system ocamlc -custom str.cma unix.cma -o build/llpp build/link.o build/cutils.o build/version.o build/lablGL/ml_gl.o build/lablGL/ml_glarray.o build/lablGL/ml_raw.o build/wsi/x11/keysym2ucs.o build/wsi/x11/xlib.o build/utils.cmo build/keys.cmo build/wsi/x11/wsi.cmo build/utf8syms.cmo build/lablGL/raw.cmo build/lablGL/gl.cmo build/lablGL/glPix.cmo build/lablGL/glMisc.cmo build/lablGL/glTex.cmo build/lablGL/glFunc.cmo build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo build/confstruct.cmo build/config.cmo build/ffi.cmo build/glutils.cmo build/lablGL/glMat.cmo build/listview.cmo build/help.cmo build/lablGL/glClear.cmo build/main.cmo -cclib "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL -lX11" failed fail 62 sec
> ld doesn't tell what is wrong in this case.. can you try nuking the contents of build directory (sans mupdf) and rebuilding it anew?

Yes, just did so. Deleted everything in 'build' dir except mupdf and 'bash build.bash build'. Same result, except now it took 3 sec. It looks like what has been proposed; an issue with gcc-10 becoming more stringent. I have recently tried to compile two analytical software package and both failed with gcc-10. Others noted that things worked fine with gcc-5, 6, and 7.

I checked my version of ocaml; it is  4.10.0.

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

>> s-usr <notifications@github.com> writes:
>> Building llpp stopped with an error using Linux on Fedora 32 with
>> gcc-10. collect2: error: ld returned 1 exit status File "_none_",
>> line 1: Error: Error while building custom runtime system ocamlc
>> -custom str.cma unix.cma -o build/llpp build/link.o build/cutils.o
>> build/version.o build/lablGL/ml_gl.o build/lablGL/ml_glarray.o
>> build/lablGL/ml_raw.o build/wsi/x11/keysym2ucs.o
>> build/wsi/x11/xlib.o build/utils.cmo build/keys.cmo
>> build/wsi/x11/wsi.cmo build/utf8syms.cmo build/lablGL/raw.cmo
>> build/lablGL/gl.cmo build/lablGL/glPix.cmo build/lablGL/glMisc.cmo
>> build/lablGL/glTex.cmo build/lablGL/glFunc.cmo
>> build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo
>> build/confstruct.cmo build/config.cmo build/ffi.cmo
>> build/glutils.cmo build/lablGL/glMat.cmo build/listview.cmo
>> build/help.cmo build/lablGL/glClear.cmo build/main.cmo -cclib
>> "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL
>> -lX11" failed fail 62 sec
>> ld doesn't tell what is wrong in this case.. can you try nuking the
>> contents of build directory (sans mupdf) and rebuilding it anew?
>
> Yes, just did so. Deleted everything in 'build' dir except mupdf and
> 'bash build.bash build'. Same result, except now it took 3 sec. It
> looks like what has been proposed; an issue with gcc-10 becoming more
> stringent. I have recently tried to compile two analytical software
> package and both failed with gcc-10. Others noted that things worked
> fine with gcc-5, 6, and 7.
>
> I checked my version of ocaml; it is  4.10.0.

Here:

- gcc --version
gcc (GCC) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

- ~/xsrc/llpp/build/bin/ocaml -version
The OCaml toplevel, version 4.10.0

I have no idea what might be wrong.. Maybe it's 10.0 that is at fault
here or maybe it depends on ld[.bfd]... No clue sorry.

**Comment by s-usr** [comment]
> Here: - gcc --version gcc (GCC) 10.1.0 Copyright (C) 2020 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. - ~/xsrc/llpp/build/bin/ocaml -version The OCaml toplevel, version 4.10.0 I have no idea what might be wrong.. Maybe it's 10.0 that is at fault here or maybe it depends on ld[.bfd]... No clue sorry.

Thanks. We can maybe close this issue. From my experience, the package will compile after a while. This often happens with updated dependencies, fixed bugs, etc.

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

>> Here: - gcc --version gcc (GCC) 10.1.0 Copyright (C) 2020 Free
> Software Foundation, Inc. This is free software; see the source for
> copying conditions. There is NO warranty; not even for MERCHANTABILITY
> or FITNESS FOR A PARTICULAR PURPOSE. - ~/xsrc/llpp/build/bin/ocaml
> -version The OCaml toplevel, version 4.10.0 I have no idea what might
> be wrong.. Maybe it's 10.0 that is at fault here or maybe it depends
> on ld[.bfd]... No clue sorry.
>
> Thanks. We can maybe close this issue. From my experience, the package
> will compile after a while. This often happens with updated
> dependencies, fixed bugs, etc.

It would have been nice to got to the bottom of this, can you, please,
list versions of: gcc, binutils, libc. Which variant of ld is being used
(bfd? gold?) Can you try building with clang?

**Comment by s-usr** [comment]
gcc: 10.1.1 20200507
binutils: 2.34-3 
ld: GNU version 2.34-3 | Under /usr/bin I have ld, ld.gold, and ld.bfd. ld is dynamically linked to ld.bfd as /usr/bin/ld -> /etc/alternatives/ld -> /usr/bin/ld.bfd. Changing the link to ld.gold did not impact the result for both -cc cc and -cc clang.

What I can see now is that the result I provided earlier relates in fact to clang. Here is the result for 
# LLPP_CC=cc bash build.bash build
generating build/confstruct.ml
  utils.ml -> utils.cmo
  keys.ml -> keys.cmo
 wsi.mli -> wsi.cmi
  wsi/x11/wsi.mli -> wsi/x11/wsi.cmi
 wsi/x11/wsi.ml -> wsi/x11/wsi.cmo
 utf8syms.ml -> utf8syms.cmo
 lablGL/raw.ml -> lablGL/raw.cmo
     lablGL/gl.ml -> lablGL/gl.cmo
    lablGL/glPix.ml -> lablGL/glPix.cmo
    lablGL/glMisc.ml -> lablGL/glMisc.cmo
   lablGL/glTex.ml -> lablGL/glTex.cmo
   lablGL/glFunc.ml -> lablGL/glFunc.cmo
    lablGL/glDraw.ml -> lablGL/glDraw.cmo
   lablGL/glArray.ml -> lablGL/glArray.cmo
     parser.ml -> parser.cmo
     build/confstruct.ml -> confstruct.cmo
    config.ml -> config.cmo
   ffi.ml -> ffi.cmo
  glutils.ml -> glutils.cmo
  lablGL/glMat.ml -> lablGL/glMat.cmo
 listview.ml -> listview.cmo
 help.mli -> help.cmi
 help.ml -> help.cmo
 lablGL/glClear.ml -> lablGL/glClear.cmo
 main.mli -> main.cmi
main.ml -> main.cmo
link.c -> link.o
./link.c: In function 'setuppbo':
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./link.c:3489:23: note: in expansion of macro 'GPA'
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |                       ^~~
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3490 |         && GPA (glUnmapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
./link.c:3490:12: note: in expansion of macro 'GPA'
 3490 |         && GPA (glUnmapBufferARB)
      |            ^~~
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3490 |         && GPA (glUnmapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~
 3491 |         && GPA (glMapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~
./link.c:3491:12: note: in expansion of macro 'GPA'
 3491 |         && GPA (glMapBufferARB)
      |            ^~~
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3490 |         && GPA (glUnmapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~
 3491 |         && GPA (glMapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~
 3492 |         && GPA (glBufferDataARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~
./link.c:3492:12: note: in expansion of macro 'GPA'
 3492 |         && GPA (glBufferDataARB)
      |            ^~~
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3490 |         && GPA (glUnmapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~
 3491 |         && GPA (glMapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~
 3492 |         && GPA (glBufferDataARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
 3493 |         && GPA (glGenBuffersARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~
./link.c:3493:12: note: in expansion of macro 'GPA'
 3493 |         && GPA (glGenBuffersARB)
      |            ^~~
./link.c:3488:18: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 3488 | #define GPA(n) (*(uintptr_t *) &state.n = (uintptr_t) wsigladdr (#n))
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3489 |     state.bo_usable = GPA (glBindBufferARB)
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3490 |         && GPA (glUnmapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~
 3491 |         && GPA (glMapBufferARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~
 3492 |         && GPA (glBufferDataARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
 3493 |         && GPA (glGenBuffersARB)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~
 3494 |         && GPA (glDeleteBuffersARB);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
./link.c:3494:12: note: in expansion of macro 'GPA'
 3494 |         && GPA (glDeleteBuffersARB);
      |            ^~~
cc1: all warnings being treated as errors
ocamlc -cc cc -ccopt "-g -std=c99 -O2 -I build/mupdf/include -I build/mupdf/thirdparty/freetype/include -Wall -Werror -Wextra -pedantic -DCACHE_PAGEREFS -D_POSIX_C_SOURCE -MMD -MF build/link.o.dep -MT_ -o build/link.o" ./link.c failed
fail 3 sec

**Comment by s-usr** [comment]
root# LLPP_CC=clang bash build.bash build
generating build/confstruct.ml
  utils.ml -> utils.cmo
  keys.ml -> keys.cmo
 wsi.mli -> wsi.cmi
  wsi/x11/wsi.mli -> wsi/x11/wsi.cmi
 wsi/x11/wsi.ml -> wsi/x11/wsi.cmo
 utf8syms.ml -> utf8syms.cmo
 lablGL/raw.ml -> lablGL/raw.cmo
     lablGL/gl.ml -> lablGL/gl.cmo
    lablGL/glPix.ml -> lablGL/glPix.cmo
    lablGL/glMisc.ml -> lablGL/glMisc.cmo
   lablGL/glTex.ml -> lablGL/glTex.cmo
   lablGL/glFunc.ml -> lablGL/glFunc.cmo
    lablGL/glDraw.ml -> lablGL/glDraw.cmo
   lablGL/glArray.ml -> lablGL/glArray.cmo
     parser.ml -> parser.cmo
     build/confstruct.ml -> confstruct.cmo
    config.ml -> config.cmo
   ffi.ml -> ffi.cmo
  glutils.ml -> glutils.cmo
  lablGL/glMat.ml -> lablGL/glMat.cmo
 listview.ml -> listview.cmo
 help.mli -> help.cmi
 help.ml -> help.cmo
 lablGL/glClear.ml -> lablGL/glClear.cmo
 main.mli -> main.cmi
main.ml -> main.cmo
link.c -> link.o
cutils.c -> cutils.o
version.c -> version.o
lablGL/ml_gl.c -> lablGL/ml_gl.o
./lablGL/ml_gl.c:36:14: warning: assigning to 'value *' (aka 'long *') from 'const value *' (aka 'const long *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
      gl_exn = caml_named_value("glerror");
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
lablGL/ml_glarray.c -> lablGL/ml_glarray.o
lablGL/ml_raw.c -> lablGL/ml_raw.o
./lablGL/ml_raw.c:166:13: warning: passing 'const char *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    memcpy (String_val(ret), Bp_val(Addr_raw(raw))+s, l);
            ^~~~~~~~~~~~~~~
/usr/lib64/ocaml/caml/mlvalues.h:265:23: note: expanded from macro 'String_val'
#define String_val(x) ((const char *) Bp_val(x))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/string.h:43:39: note: passing argument to parameter '__dest' here
extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
                                      ^
1 warning generated.
wsi/x11/keysym2ucs.c -> wsi/x11/keysym2ucs.o
wsi/x11/xlib.c -> wsi/x11/xlib.o
linking build/llpp
/usr/bin/ld: error: build/link.o: requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
.....
/usr/bin/ld: error: build/mupdf/build/native/libmupdf-third.a(mqc.o): requires unsupported dynamic reloc 11; recompile with -fPIC
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
ocamlc -custom str.cma unix.cma -o build/llpp  build/link.o build/cutils.o build/version.o build/lablGL/ml_gl.o build/lablGL/ml_glarray.o build/lablGL/ml_raw.o build/wsi/x11/keysym2ucs.o build/wsi/x11/xlib.o build/utils.cmo build/keys.cmo build/wsi/x11/wsi.cmo build/utf8syms.cmo build/lablGL/raw.cmo build/lablGL/gl.cmo build/lablGL/glPix.cmo build/lablGL/glMisc.cmo build/lablGL/glTex.cmo build/lablGL/glFunc.cmo build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo build/confstruct.cmo build/config.cmo build/ffi.cmo build/glutils.cmo build/lablGL/glMat.cmo build/listview.cmo build/help.cmo build/lablGL/glClear.cmo build/main.cmo -cclib "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL -lX11" failed
fail 3 sec

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

- ls -l /usr/bin/ld   
-rwxr-xr-x 2 root root 1711264 May 21 21:38 /usr/bin/ld
nuc:~
- pacman -Qo /usr/bin/ld 
/usr/bin/ld is owned by binutils 2.34-5
nuc:~
- 

here BFD version is used

> root# LLPP_CC=clang bash build.bash build
> generating build/confstruct.ml
>   utils.ml -> utils.cmo
>   keys.ml -> keys.cmo
>  wsi.mli -> wsi.cmi
>   wsi/x11/wsi.mli -> wsi/x11/wsi.cmi
>  wsi/x11/wsi.ml -> wsi/x11/wsi.cmo
>  utf8syms.ml -> utf8syms.cmo
>  lablGL/raw.ml -> lablGL/raw.cmo
>      lablGL/gl.ml -> lablGL/gl.cmo
>     lablGL/glPix.ml -> lablGL/glPix.cmo
>     lablGL/glMisc.ml -> lablGL/glMisc.cmo
>    lablGL/glTex.ml -> lablGL/glTex.cmo
>    lablGL/glFunc.ml -> lablGL/glFunc.cmo
>     lablGL/glDraw.ml -> lablGL/glDraw.cmo
>    lablGL/glArray.ml -> lablGL/glArray.cmo
>      parser.ml -> parser.cmo
>      build/confstruct.ml -> confstruct.cmo
>     config.ml -> config.cmo
>    ffi.ml -> ffi.cmo
>   glutils.ml -> glutils.cmo
>   lablGL/glMat.ml -> lablGL/glMat.cmo
>  listview.ml -> listview.cmo
>  help.mli -> help.cmi
>  help.ml -> help.cmo
>  lablGL/glClear.ml -> lablGL/glClear.cmo
>  main.mli -> main.cmi
> main.ml -> main.cmo
> link.c -> link.o
> cutils.c -> cutils.o
> version.c -> version.o
> lablGL/ml_gl.c -> lablGL/ml_gl.o
> ./lablGL/ml_gl.c:36:14: warning: assigning to 'value *' (aka 'long *') from 'const value *' (aka 'const long *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
>       gl_exn = caml_named_value("glerror");
>              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> lablGL/ml_glarray.c -> lablGL/ml_glarray.o
> lablGL/ml_raw.c -> lablGL/ml_raw.o
> ./lablGL/ml_raw.c:166:13: warning: passing 'const char *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
>     memcpy (String_val(ret), Bp_val(Addr_raw(raw))+s, l);
>             ^~~~~~~~~~~~~~~
> /usr/lib64/ocaml/caml/mlvalues.h:265:23: note: expanded from macro 'String_val'
> #define String_val(x) ((const char *) Bp_val(x))
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/string.h:43:39: note: passing argument to parameter '__dest' here
> extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
>                                       ^
> 1 warning generated.
> wsi/x11/keysym2ucs.c -> wsi/x11/keysym2ucs.o
> wsi/x11/xlib.c -> wsi/x11/xlib.o
> linking build/llpp
> /usr/bin/ld: error: build/link.o: requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
> .....
> /usr/bin/ld: error: build/mupdf/build/native/libmupdf-third.a(mqc.o): requires unsupported dynamic reloc 11; recompile with -fPIC

So *both* mupdf-third and link.o need to be fPIC... weird
> collect2: error: ld returned 1 exit status
> File "_none_", line 1:
> Error: Error while building custom runtime system
> ocamlc -custom str.cma unix.cma -o build/llpp  build/link.o build/cutils.o build/version.o build/lablGL/ml_gl.o build/lablGL/ml_glarray.o build/lablGL/ml_raw.o build/wsi/x11/keysym2ucs.o build/wsi/x11/xlib.o build/utils.cmo build/keys.cmo build/wsi/x11/wsi.cmo build/utf8syms.cmo build/lablGL/raw.cmo build/lablGL/gl.cmo build/lablGL/glPix.cmo build/lablGL/glMisc.cmo build/lablGL/glTex.cmo build/lablGL/glFunc.cmo build/lablGL/glDraw.cmo build/lablGL/glArray.cmo build/parser.cmo build/confstruct.cmo build/config.cmo build/ffi.cmo build/glutils.cmo build/lablGL/glMat.cmo build/listview.cmo build/help.cmo build/lablGL/glClear.cmo build/main.cmo -cclib "-Lbuild/mupdf/build/native -lmupdf -lmupdf-third -lpthread -lGL -lX11" failed
> fail 3 sec

I need to sleep on it...

**Comment by s-usr** [comment]
Yes, on my system ld is linked to ld.bfd as the default. 
sudo rpm -qf /usr/bin/ld gives binutils-2.34-3.fc32.x86_64. You have a bit newer version binutils.

As I recompiled with -fPIC, the error became: 'cannot be used when making a PIE object; recompile with -fPIE'. 
root# LLPP_CC=clang XCFLAGS=-fPIC bash build.bash build

Recompiling with -fPIE, the error message stayed the same.
root# LLPP_CC=clang XCFLAGS=-fPIE bash build.bash build
'.... cannot be used when making a PIE object; recompile with -fPIE'.

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

> Yes, on my system ld is linked to ld.bfd as the default. 
> sudo rpm -qf /usr/bin/ld gives binutils-2.34-3.fc32.x86_64. You have a
> bit newer version binutils.
>
> As I recompiled with -fPIC, the error became: 'cannot be used when
> making a PIE object; recompile with -fPIE'.
> root# LLPP_CC=clang XCFLAGS=-fPIC bash build.bash build
>
> Recompiling with -fPIE, the error message stayed the same.
> root# LLPP_CC=clang XCFLAGS=-fPIE bash build.bash build
> '.... cannot be used when making a PIE object; recompile with -fPIE'.

Btw which ocaml version does that SuSE (?) comes with?

**Comment by s-usr** [comment]
GNU/Linux | Fedora 32 | ocaml is 4.10.0.

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

> GNU/Linux | Fedora 32 | ocaml is 4.10.0. 

I have committed some build system "improvements" do they make any
difference for you?

**Comment by s-usr** [comment]
Thanks. Good news: Before downloading the latest build, the issue got resolved. I managed to download the very latest gcc and binutils packages, which are supposed to be officially released as part of Fedora 33 in October. With the news versions, compiling worked flawlessly.

* gcc 10.1.1 20200618 (Red Hat 10.1.1-2) (GCC)
* binutils 2.34.0-7
* GNU ld version 2.34.0.20200522
* The OCaml toplevel, version 4.11.0+dev2-2020-04-22. This, however, does not make a difference because llpp downloads and locally installs ocaml 4.10.0. 

[admin]$ sudo git clone https://github.com/moosotc/llpp.git
[admin]$ cd llpp
[admin llpp]$ sudo mkdir build
[admin llpp]$ sudo sh misc/getmupdf.sh build/mupdf
[admin llpp]$ sudo bash build.bash build
make: Entering directory '/opt/llpp/build/mupdf'
    CC ...
configure: Configuring OCaml version 4.10.0
...
make -C runtime  all
...
main.ml -> main.cmo
link.c -> link.o
cutils.c -> cutils.o
version.c -> version.o
lablGL/ml_gl.c -> lablGL/ml_gl.o
lablGL/ml_glarray.c -> lablGL/ml_glarray.o
lablGL/ml_raw.c -> lablGL/ml_raw.o
wsi/x11/keysym2ucs.c -> wsi/x11/keysym2ucs.o
wsi/x11/xlib.c -> wsi/x11/xlib.o
linking build/llpp
153 sec

**Comment by s-usr** [comment]
I also deleted the llpp directory, cloned the latest llpp anew, rebuilt mupdf and llpp. Compiling went just fine and generated the llpp binary. Great job!

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

> Thanks. Good news: Before downloading the latest build, the issue got
> resolved. I managed to download the very latest gcc and binutils
> packages, which are supposed to be officially released as part of
> Fedora 33 in October. With the news versions, compiling worked
> flawlessly.
>

Great.

> * gcc 10.1.1 20200618 (Red Hat 10.1.1-2) (GCC)
> * binutils 2.34.0-7
> * GNU ld version 2.34.0.20200522
> * The OCaml toplevel, version 4.11.0+dev2-2020-04-22. This, however,
> does not make a difference because llpp downloads and locally installs
> ocaml 4.10.0.
>
> [admin]$ sudo git clone https://github.com/moosotc/llpp.git
> [admin]$ cd llpp
> [admin llpp]$ sudo mkdir build
> [admin llpp]$ sudo sh misc/getmupdf.sh build/mupdf
> [admin llpp]$ sudo bash build.bash build
> make: Entering directory '/opt/llpp/build/mupdf'
>     CC ...
> configure: Configuring OCaml version 4.10.0
> ...
> make -C runtime  all
> ...
> main.ml -> main.cmo
> link.c -> link.o
> cutils.c -> cutils.o
> version.c -> version.o
> lablGL/ml_gl.c -> lablGL/ml_gl.o
> lablGL/ml_glarray.c -> lablGL/ml_glarray.o
> lablGL/ml_raw.c -> lablGL/ml_raw.o
> wsi/x11/keysym2ucs.c -> wsi/x11/keysym2ucs.o
> wsi/x11/xlib.c -> wsi/x11/xlib.o
> linking build/llpp
> 153 sec

You really should reconsider such a gratuitous sudo usage, building llpp
dose not require any special privileges.

**Comment by moosotc** [comment]
s-usr <notifications@github.com> writes:

> I also deleted the llpp directory, cloned the latest llpp anew,
> rebuilt mupdf and llpp. Compiling went just fine and generated the
> llpp binary. Great job!

Even though i went to some lengths to make build system sane i must
confess that sometimes i do a "fresh" installs, BUT to avoid hammering
mupdfs repository getmupdf.sh can use existing clone via cloneargs
environment variable, like so:

cloneargs='--reference /path/to/mupdf' sh misc/getmupdf.sh build/mupdf

Glad that things worked for you in the end.

**Comment by s-usr** [comment]
Thanks. I agree it is a bad habit to use 'sudo' all the time. I use /opt for all my extra packages, and sometimes get "permission denied". So, it became a habit to use 'sudo' with all installs to avoid such message.
