### ISSUE TITLE
Do not allow bookmark duplicates

### ISSUE THREAD

**Issue by sudo-nice** [moosotc/llpp#137]
Surprisingly, it's possible to have several bookmarks with the same title:

```
<bookmarks>
<item title='m' page='149'/>
<item title='m' page='148'/>
<item title='Quick (page 150) (bookmarked on 06/07/2020 at 13:20)' page='149'/>
<item title='Quick (page 149) (bookmarked on 06/07/2020 at 13:20)' page='148'/>
<item title='Quick (page 118) (bookmarked on 05/07/2020 at 14:54)' page='117'/>
</bookmarks>
```
It feels more natural for a new bookmark to overwrite the old one with the same title. Maybe it would be better to have only one quick bookmark too. That could have made it less necessary to be able to delete bookmarks (ref.: https://github.com/moosotc/llpp/issues/47)

**Comment by moosotc** [comment]
sudo-nice <notifications@github.com> writes:

> Surprisingly, it's possible to have several bookmarks with the same title:
>
> ```
> <bookmarks>
> <item title='m' page='149'/>
> <item title='m' page='148'/>
> <item title='Quick (page 150) (bookmarked on 06/07/2020 at 13:20)' page='149'/>
> <item title='Quick (page 149) (bookmarked on 06/07/2020 at 13:20)' page='148'/>
> <item title='Quick (page 118) (bookmarked on 05/07/2020 at 14:54)' page='117'/>
> </bookmarks>
> ```
> It feels more natural for a new bookmark to overwrite the old one with
> the same title. Maybe it would be better to have only one quick
> bookmark too. That could have made it less necessary to be able to
> delete bookmarks (ref.: https://github.com/moosotc/llpp/issues/47)

Will have to reacquaint myself with bookmarking code first, but given
that the idea does not sound insane... i wlll... Thanks!

**Comment by moosotc** [comment]
Does the following do what you want?

diff --git a/main.ml b/main.ml
index a7773b2..19ab1c9 100644
--- a/main.ml
+++ b/main.ml
@@ -3216,7 +3216,9 @@ let quickbookmark ?title () =
           )
        | Some title -> title
      in
-     state.bookmarks <- (title, 0, Oanchor (getanchor1 l)) :: state.bookmarks
+     let bookmarks = List.filter (fun (title', _, _) -> title != title')
+                       state.bookmarks in
+     state.bookmarks <- (title, 0, Oanchor (getanchor1 l)) :: bookmarks
 ;;
 
 let setautoscrollspeed step goingdown =

**Comment by sudo-nice** [comment]
Hmm, didn't really work for me, I still managed to create duplicates:

```
<bookmarks>
<item title='Quick (page 155) (bookmarked on 06/07/2020 at 20:53)' page='154'/>
<item title='Quick (page 155) (bookmarked on 06/07/2020 at 20:53)' page='154'/>
<item title='m' page='154'/>
<item title='m' page='154'/>
</bookmarks>
```
Is there anything I can do to debug this?

**Comment by moosotc** [comment]
sudo-nice <notifications@github.com> writes:

> Hmm, didn't really work for me, I still managed to create duplicates:
>

I have used the wrong comparison operator != vs <> , physical vs
structural inequality, try replacing != with <> in the path. Tell me if
that works, thanks, sorry.

**Comment by moosotc** [comment]
This might(only compile tested) work better

diff --git a/main.ml b/main.ml
index a7773b2..cefd2ef 100644
--- a/main.ml
+++ b/main.ml
@@ -3200,6 +3200,11 @@ let enteroutlinemode, enterbookmarkmode, enterhistmode =
   , mkenter `history "history is empty" sh )
 ;;
 
+
+let addbookmark title a =
+  let b = List.filter (fun (title', _, _) -> title <> title') state.bookmarks in
+  state.bookmarks <- (title, 0, Oanchor a) :: b;;
+
 let quickbookmark ?title () =
   match state.layout with
   | [] -> ()
@@ -3216,7 +3221,7 @@ let quickbookmark ?title () =
           )
        | Some title -> title
      in
-     state.bookmarks <- (title, 0, Oanchor (getanchor1 l)) :: state.bookmarks
+     addbookmark title (getanchor1 l)
 ;;
 
 let setautoscrollspeed step goingdown =
@@ -3654,8 +3659,7 @@ let viewkeyboard key mask =
   | Ascii 'm' ->
      let ondone s =
        match state.layout with
-       | l :: _ when nonemptystr s ->
-          state.bookmarks <- (s, 0, Oanchor (getanchor1 l)) :: state.bookmarks
+       | l :: _ when nonemptystr s -> addbookmark s @@ getanchor1 l
        | _ -> ()
      in
      enttext ("bookmark: ", E.s, None, textentry, ondone, true)

**Comment by sudo-nice** [comment]
The last one patch works nicely.
Thank you very much for your help and the great piece of software! :+1:

**Comment by moosotc** [comment]
sudo-nice <notifications@github.com> writes:

> The last one patch works nicely.
> Thank you very much for your help and the great piece of software! :+1: 

Heh, thank you for kind words, i'll commit it now then..
