### ISSUE TITLE
Fullscreen toggle behaves abnormally when window is maximised 

### ISSUE THREAD

**Issue by edo0** [moosotc/llpp#138]
I am running llpp 31-1 on Arch, using XFCE as desktop environment.
I have encountered the following situations

- llpp window is NOT maximised
Shortcut "f" toggles full screen as intended

- llpp window IS maximised
-- Pressing "f" once will enter fullscreen mode
Now, from fullscreen mode
-- Pressing "f" once will not sort any action (no flickering, absolutely nothing)
-- Pressing "f" another time will exit fullscreen mode

What intrigues me the most is that the second "f" keystroke can be performed any time, and will be effective even after performing other keystrokes (e.g. turning page, searching, etc)

Please let me know if I can provide any more info to help debugging this !

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> I am running llpp 31-1 on Arch, using XFCE as desktop environment.
> I have encountered the following situations
>
> - llpp window is NOT maximised
> Shortcut "f" toggles full screen as intended
>
> - llpp window IS maximised
> -- Pressing "f" once will enter fullscreen mode
> Now, from fullscreen mode
> -- Pressing "f" once will not sort any action (no flickering,
> absolutely nothing)
> -- Pressing "f" another time will exit fullscreen mode
>
> What intrigues me the most is that the second "f" keystroke can be
> performed any time, and will be effective even after performing other
> keystrokes (e.g. turning page, searching, etc)
>
> Please let me know if I can provide any more info to help debugging this !

I have installed xfwm4 and can rerpduce the maximized-fullscreen
problem, will look into it. Can't quite figure out what you inrugued you
thogh. This bight take some time, need to reacquaint myself with NETWM
spec first... Thanks for the report.

**Comment by edo0** [comment]
Oh, sorry, I didn't express myself properly. I do not have any blackground in engineering or computer sciences, and maybe my amazement at the first "f" being sort of stored indefinitely (and not like, cleared after other keystrokes), before the second "f" keystroke brings me out of fullscreen, felt like a peculiar behaviour I never encountered before. As I was saying, in between the 2 "f"s I could navigate the document, search words containing f, etc.

I am glad my bug report is of any use, and wish to thank you for your work on this nifty and amazingly fast programme, I have been using it for a day and already enjoying it a lot

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Oh, sorry, I didn't express myself properly. I do not have any
> blackground in engineering or computer sciences, and maybe my
> amazement at the first "f" being sort of stored indefinitely (and not
> like, cleared after other keystrokes), before the second "f" keystroke
> brings me out of fullscreen, felt like a peculiar behaviour I never
> encountered before. As I was saying, in between the 2 "f"s I could
> navigate the document, search words containing f, etc.
>
> I am glad my bug report is of any use, and wish to thank you for your
> work on this nifty and amazingly fast programme, I have been using it
> for a day and already enjoying it a lot

This makes thing "work" here (for xfwm4 running inside Xephyr session at
least), would be nice if you could try it.

diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index 837024c..13783a3 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -978,7 +978,7 @@ let setup disp sock rootwid screennum w h =
                state.maxhatom <- r32 resp 8;
              );
            sendintern
-             sock (~> "_NET_WM_STATE_FULLSCREEN") true (fun resp ->
+             sock (~> "_NET_WM_STATE_FULLSCREEN") false (fun resp ->
                state.fulsatom <- r32 resp 8;
                if state.fulsatom != 0
                then

**Comment by edo0** [comment]
Sorry, I have tried building it with that parameter changed, but am having some difficulties along the building process.
Would you mind copy pasting for me the commands you used to correctly build llpp? (I may have made some mistake around the mupdf compilation folder tree)

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Sorry, I have tried building it with that parameter changed, but am
> having some difficulties along the building process.
> Would you mind copy pasting for me the commands you used to correctly
> build llpp? (I may have made some mistake around the mupdf compilation
> folder tree)

  nuc:~/xsrc/llpp
  - bash build.bash build
  2 sec

Follow instructions from BUILDING file[1]


[1] https://github.com/moosotc/llpp/blob/master/BUILDING

**Comment by edo0** [comment]
Thank you very much. I have followed the build instructions to the letter, after having changed that "true" parameter to "false" in `/wsi/x11/wsi.ml.`
After finishing building, I did `sudo cp /home/user/llpp/build/llpp /usr/bin/llpp`
Unfortunately, for me the issue seems to persist

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Thank you very much. I have followed the build instructions to the
> letter, after having changed that "true" parameter to "false" in
> `/wsi/x11/wsi.ml.`
> After finishing building, I did `sudo cp /home/user/llpp/build/llpp
> /usr/bin/llpp`
> Unfortunately, for me the issue seems to persist

What does "llpp -v" say on your machine? Here the output is:

- llpp -v
llpp v32-29-g8d7cd07-dirty, fitz 1.17.0, ocaml 4.10.0/64 bit
configuration file: /home/malc/.config/llpp.conf

and

- git diff
diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index 837024c..13783a3 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -978,7 +978,7 @@ let setup disp sock rootwid screennum w h =
                state.maxhatom <- r32 resp 8;
              );
            sendintern
-             sock (~> "_NET_WM_STATE_FULLSCREEN") true (fun resp ->
+             sock (~> "_NET_WM_STATE_FULLSCREEN") false (fun resp ->
                state.fulsatom <- r32 resp 8;
                if state.fulsatom != 0
                then

**Comment by edo0** [comment]
I can confirm correspondence of outputs

```
llpp -v
llpp v32-29-g8d7cd07-dirty, fitz 1.17.0, ocaml 4.10.0/64 bit
```
and

```
git diff
diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index 837024c..13783a3 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -978,7 +978,7 @@ let setup disp sock rootwid screennum w h =
                state.maxhatom <- r32 resp 8;
              );
            sendintern
-             sock (~> "_NET_WM_STATE_FULLSCREEN") true (fun resp ->
+             sock (~> "_NET_WM_STATE_FULLSCREEN") false (fun resp ->
                state.fulsatom <- r32 resp 8;
                if state.fulsatom != 0
                then

```

**Comment by edo0** [comment]
I shall CORRECT myself
Now, while maximized, "f" toggle works perfectly

**Comment by edo0** [comment]
The reason why it did not work for me at first, is because now I have set in the `/home/user/.config/llpp.conf ` file
<defaults
    width='1920'
    height='1080'

This still "breaks" the "f" toggle, so that the current situation is
> window not maximized and resized to smaller than full screen dimension: "f" toggle works
> window maximized (double click on the window titlebar: "f" toggle works
> window opened at 1920x1080: two "f" keystrokes needed to exit fullscreen

**Comment by edo0** [comment]
PS: Clearly 1920x1080 is a wrong size for a window to open at, because the screen estate is less than 1080p vertically (due to titlebar and menubar). Decreasing to a sensible height _solves definitely the issue_.
Any other value in excess of the maximal height instead presents the same issue with "double f" to exit fullscreen

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> PS: Clearly 1920x1080 is a wrong size for a window to open at, because
> the screen estate is less than 1080p vertically (due to titlebar and
> menubar). Decreasing to a sensible height _solves definitely the
> issue_.
> Any other value in excess of the maximal height instead presents the
> same issue with "double f" to exit fullscreen

That is an issue with xfwm4 i'm afraid, good news that with the patch
applied this situation should not normally arise (though it can be
artificially triggered)

**Comment by edo0** [comment]
Thank you again for looking into it! Have a good day!!

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Thank you again for looking into it! Have a good day!!

You are welcome, please close the bug if the commit i have just pushed
fixes things for you, thanks.
