### ISSUE TITLE
How to change default copy command?

### ISSUE THREAD

**Issue by The-Steel-Talon** [moosotc/llpp#139]
How to change default copy command?

**Comment by moosotc** [comment]
Adcock <notifications@github.com> writes:

> How to change default copy command?

Not sure what you mean. My guess would be you want "selection-command"
and it's right there in the config file also in the 'i' screen under:
Extended parameters -> selection command.

**Comment by The-Steel-Talon** [comment]
But what happens when I press 'y' ?
How to change the command that is executed when 'y' is pressed?

**Comment by moosotc** [comment]
Adcock <notifications@github.com> writes:

> But what happens when I press 'y' ?
> How to change the command that is executed when 'y' is pressed?

selection command is used for both

**Comment by The-Steel-Talon** [comment]
Then selecting text does the same thing.
Then why have 'y' at all?

**Comment by moosotc** [comment]
Adcock <notifications@github.com> writes:

> Then selecting text does the same thing.
> Then why have 'y' at all?

Because somitems i have difficulty using the mouse, and having the
ability to select target's URL and then paste it into the browser of the
choice is handy for me.

**Comment by The-Steel-Talon** [comment]
Can it be used in a way that I would select using mouse and then copy with 'y' ?
Or any way to achieve similar effect.
So that pressing certain key would copy selection to clipboard.
I want this cause, I want to select text correctly first then copy it.

**Comment by moosotc** [comment]
Adcock <notifications@github.com> writes:

> Can it be used in a way that I would select using mouse and then copy with 'y' ?
> Or any way to achieve similar effect.
> So that pressing certain key would copy selection to clipboard.
> I want this cause, I want to select text correctly first then copy it.

Currently one selects a text when one is done he releases primary mouse
button the seclected text gets piped to the selection-command a command
that you can set to anything you like... A script file for
isnstance.. It can do whatevery you put into it...
