### ISSUE TITLE
Feature Request : Add DjVu support

### ISSUE THREAD

**Issue by The-Steel-Talon** [moosotc/llpp#140]
Can you please Add DjVu support?

**Comment by moosotc** [comment]
I experimented with djvulibre in the past (cf. https://repo.or.cz/llpp.git/shortlog/refs/heads/dejavu) but the effort went nowhere... someone would have to step up and maintain it, i do not want to do it myself, sorry. Sorry for taking so long to reply  the notification about this issue never hit my mailbox.

**Comment by The-Steel-Talon** [comment]
Thanks for replying.
