### ISSUE TITLE
How to bind "shift+space" to go to the previous page?

### ISSUE THREAD

**Issue by otakutyrant** [moosotc/llpp#142]
I checked https://wiki.archlinux.org/index.php/Llpp#Custom_key_bindings and https://github.com/nojb/llpp/issues/10, but still didn't find out how to do it.

Here is my config, and it does not work:

```
<llppconfig>
  <defaults ... >
    <keymap mode='view'>
      <map in='shift-space' out=delete>
    </keymap>
  </defaults>
</llppconfig>
```

**Comment by moosotc** [comment]
otakutyrant <notifications@github.com> writes:

> I checked https://wiki.archlinux.org/index.php/Llpp#Custom_key_bindings and https://github.com/nojb/llpp/issues/10, but still didn't find out how to do it.
>
> Here is my config, and it does not work:
>
> ```
> <llppconfig>
>   <defaults ... >
>     <keymap mode='view'>
>       <map in='shift-space' out=delete>

Make ith "<map in='shift-space' out='delete'/>" and it'll work.

>     </keymap>
>   </defaults>
> </llppconfig>
> ```

**Comment by otakutyrant** [comment]
It works as you said. Sorry for my oversight.
