### ISSUE TITLE
I hope I can vertically center the view on the current search result automatically

### ISSUE THREAD

**Issue by otakutyrant** [moosotc/llpp#143]
It is boring to press "zz" everytime when I am iterating every search result, because the absence of preceding context is a big problem.

It can be better if you make the default behavior of searching be vertically centering the view automatically. In other words, when searching something, the current searched result always appeared in the center if possible.

**Comment by moosotc** [comment]
otakutyrant <notifications@github.com> writes:

> It is boring to press "zz" everytime when I am iterating every search
> result, because the absence of preceding context is a big problem.
>
> It can be better if you make the default behavior of searching be
> vertically centering the view automatically. In other words, when
> searching something, the current searched result always appeared in
> the center if possible.

(There are reasons why that won't work with the way searching is
implemented currently, so... no it's presently impossbile to do that.
At least i don't feel like i was deceptive - help screen has a caveat
section)

**Comment by otakutyrant** [comment]
Oh, what a pity. It is kind of you to give me the feedback anyway.

**Comment by moosotc** [comment]
otakutyrant <notifications@github.com> writes:

> Oh, what a pity. It is kind of you to give me the feedback anyway.

It's just that this is one of the "least happy" about areas and at the
same time it's the one i don't particularly want to touch... Searching
in pdf's is unpleasant... than again mupdf devopers have have done some
woork in this area not so long ago and perhaps it's time to revisit
things... Maybe i will be hit by a sudden urge to do something in this
area, then again maybe not... Sorry
