### ISSUE TITLE
关于缩放的过度动画

### ISSUE THREAD

**Issue by YLXDXX** [moosotc/llpp#145]
没有缩放的过度，在进行缩放的时候屏幕会有闪烁感，可否添加缩放的过度动画，就像mupdf浏览器那样在缩放的几乎没有过度感

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> 没有缩放的过度，在进行缩放的时候屏幕会有闪烁感，可否添加缩放的过度动画，
> 就像mupdf浏览器那样在缩放的几乎没有过度感

对不起， 我不会说中文

**Comment by YLXDXX** [comment]
不好意思

when I use mupdf to zoom a pdf  document, animation of zoom is nature，but when I use llpp to a pdf document , animation of zoom is sharp，you can see this when you watch below two videos.


[see.zip](https://github.com/moosotc/llpp/files/5060720/see.zip)

Can  an  animation of zoom be added ?

I can't use right English.  sorry 。。。

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> 不好意思
>
> when I use mupdf to zoom a pdf document, animation of zoom is nature，
> but when I use llpp to a pdf document , animation of zoom is sharp，
> you can see this when you watch below two videos.
>
>
> [see.zip](https://github.com/moosotc/llpp/files/5060720/see.zip)
>

Okay, now i understand what you mean. And progressive zoom is the first
item in the todo file. Mupdf is synchronous and as such it always awatis
for the document to be fully rendered before (re)displaying stuff and
you happen to like the side effect of that, ther are other side effects
that i find objectionable.

> Can  an  animation of zoom be added ?
>

Judging by how long this was on the todo list - no... I'll keep trying
nonetheless

> I can't use right English.  sorry 。。。

I can assure you that your English is infinitely better than my
Putonghua.
