### ISSUE TITLE
a problem about secondary mouse button to zoom a area

### ISSUE THREAD

**Issue by YLXDXX** [moosotc/llpp#146]
When I use the right mouse button to zoom in a certain area of the page, the result can not be displayed on the screen completely (only a part of the selected area).

Sometimes the selection area can be displayed completely, and sometimes it won’t work. The smaller the selected area, the more serious the problem.

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> When I use the right mouse button to zoom in a certain area of the
> page, the result can not be displayed on the screen completely (only a
> part of the selected area).
>
> Sometimes the selection area can be displayed completely, and
> sometimes it won’t work. The smaller the selected area, the more
> serious the problem.

I do not gollow that, sorry, can you provide reproduction steps?

**Comment by YLXDXX** [comment]
[Screen Capture_llpp_20200826172042.zip](https://github.com/moosotc/llpp/files/5128859/Screen.Capture_llpp_20200826172042.zip)

I recorded a video, the first one shows no screen centered, the second one does not show (out of range), and the third one shows only part of it.

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> [Screen
> Capture_llpp_20200826172042.zip](https://github.com/moosotc/llpp/files/5128859/Screen.Capture_llpp_20200826172042.zip)
>
> I recorded a video, the first one shows no screen centered, the second
> one does not show (out of range), and the third one shows only part of
> it.

I see the problem, thanks, do you have a link to the document that is
used in the video, your llpp.conf file can help too.

**Comment by YLXDXX** [comment]
[Create New Archive.zip](https://github.com/moosotc/llpp/files/5129033/Create.New.Archive.zip)

All in here

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> [Create New
> Archive.zip](https://github.com/moosotc/llpp/files/5129033/Create.New.Archive.zip)
>
> All in here

Thanks.

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> [Create New
> Archive.zip](https://github.com/moosotc/llpp/files/5129033/Create.New.Archive.zip)
>
> All in here

muPDF author says that the PDF is bad... if you can reproduce it with
some other document cool, otherwise it's probably pointless trying to
figure out what's wrong when the underlying test case is suspect

**Comment by YLXDXX** [comment]
I use Google translate, PDF's problem?
when I use other pdf, this problem same


------------------ Original ------------------

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> I use Google translate, PDF's problem?
> when I use other pdf, this problem same

Yes the PDF is broken, but that's not the source of the problem here,
you would have to provide step by step scenario how to reproduce the
problem. Listing the expected and obtained results, aswel as the links
to all the needed materials... Is the problem reproducible with just an
image? Some .PNG or .JPG..

**Comment by YLXDXX** [comment]
All my local pdf files (text, png, jpg, tif, etc.) have this problem. All I did was simply open the file and view it.

Today I took a closer look at the problem and found that I used the right mouse button to select an area to zoom in. The enlarged image of this area cannot fit on my entire screen.

It’s not the problem with my pdf file, it should be caused by incorrect calculation of the enlarged area size.

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> All my local pdf files (text, png, jpg, tif, etc.) have this
> problem. All I did was simply open the file and view it.
>
> Today I took a closer look at the problem and found that I used the
> right mouse button to select an area to zoom in. The enlarged image of
> this area cannot fit on my entire screen.
>
> It’s not the problem with my pdf file, it should be caused by
> incorrect calculation of the enlarged area size.

I can't repreduce the problem since i don't really understand what the
problem is! Once again - you would have to give me step-by-step
instructions with expected and obtained result at the junction points,
it would be nice if the documen where one(me) could see the issue is a
simple image file.

**Comment by YLXDXX** [comment]
ok, for example:

1. Use the following command to generate a pdf file.
```
img2pdf --output out.pdf  picture.png
```
2. Use llpp to open the generated pdf file.
```
llpp out.pdf
```
3.Use the right mouse button to zoom to a specific area.

4.The result is that the selected area does not completely appear on the screen。

The test file is packaged.
[example.zip](https://github.com/moosotc/llpp/files/5135795/example.zip)

**Comment by moosotc** [comment]
YLXDXX <notifications@github.com> writes:

> ok, for example:
>
> 1. Use the following command to generate a pdf file.
> ```
> img2pdf --output out.pdf  picture.png
> ```
> 2. Use llpp to open the generated pdf file.
> ```
> llpp out.pdf
> ```

You can use llpp on the png, there should be no need to convert it to
pdf, the behavior should be the same (can you verify that the behavior
is indeed the same?)

> 3.Use the right mouse button to zoom to a specific area.
>
> 4.The result is that the selected area does not completely appear on
> the screen。

It does "completely appear on the screen" on my machine. FWIW:

  nuc:~
  - llpp -v
  llpp v32-77-g151fd5c, fitz 1.17.0, ocaml 4.10.0/64 bit
  configuration file: /home/malc/.config/llpp.conf
  nuc:~
  - cd xsrc/llpp 
  nuc:~/xsrc/llpp
  - git describe --tags
  v32-77-g151fd5c
  nuc:~/xsrc/llpp

>
> The test file is packaged.
> [example.zip](https://github.com/moosotc/llpp/files/5135795/example.zip)

谢谢

**Comment by YLXDXX** [comment]
This may a exceptional case, thanks for your reply.
