### ISSUE TITLE
[Design] Giving llpp more modern looks

### ISSUE THREAD

**Issue by edo0** [moosotc/llpp#147]
I myself usually put aesthetics way after functionality on the priorities list, but nonetheless I thought that maybe a slightly more modern colour palette as default option may help to win some new users' initial reluctance towards giving the software a try.

This is the palette I have used, partly take from Evince.
```
    background-color='245/246/247'
    paper-color='255/255/255/0'
    scrollbar-color='163/163/163/178'
    scrollbar-handle-color='0/0/30/60'
    texture-color='0/0/0/0'
```
Please find a preview below (disregard the size of the scrollbars)
![Screenshot_2020-09-13_21-52-39](https://user-images.githubusercontent.com/16632292/93027358-b9bd2a80-f5fb-11ea-9b07-4d350406e7bb.png)

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> I myself usually put aesthetics way after functionality on the
> priorities list, but nonetheless I thought that maybe a slightly more
> modern colour palette as default option may help to win some new
> users' initial reluctance towards giving the software a try.
>
> This is the palette I have used, partly take from Evince.
> ```
>     background-color='245/246/247'
>     paper-color='255/255/255/0'
>     scrollbar-color='163/163/163/178'
>     scrollbar-handle-color='0/0/30/60'
>     texture-color='0/0/0/0'
> ```

Rill try it for a few days..

> Please find a preview below (disregard the size of the scrollbars)
> ![Screenshot_2020-09-13_21-52-39](https://user-images.githubusercontent.com/16632292/93027358-b9bd2a80-f5fb-11ea-9b07-4d350406e7bb.png)

Disregarding them was easy - there are none on the screenshot. I don't
like the lack of contrast between scrollbar and its handle though.

Thanks.

**Comment by edo0** [comment]
Thank you for considering it!
And yes, I do agree that for a sane default the handle needs a starker contrast. Let me know if you want me to look after it, or you will experiment with it yourself :)

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Thank you for considering it!

Anytime :)

> And yes, I do agree that for a sane default the handle needs a starker
> contrast. Let me know if you want me to look after it, or you will
> experiment with it yourself :)

I won't be experimenting with it myself, i will, however, look at any
suggestions you might have.

**Comment by edo0** [comment]
![70-70-70-150 scrollbar](https://user-images.githubusercontent.com/16632292/93141510-d462d280-f6d3-11ea-8d91-33cb682383f0.png)
I have been playing with the palette a bit more: this is the result I obtain by setting 
` scrollbar-handle-color='70/70/70/150'` 
in
```
    background-color='245/246/247'
    paper-color='255/255/255/0'
    scrollbar-color='163/163/163/178'
    scrollbar-handle-color='70/70/70/150'

```

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> ![70-70-70-150
> scrollbar](https://user-images.githubusercontent.com/16632292/93141510-d462d280-f6d3-11ea-8d91-33cb682383f0.png)
> I have been playing with the palette a bit more: this is the result I
> obtain by setting
> ` scrollbar-handle-color='70/70/70/150'` 
> in
> ```
>     background-color='245/246/247'
>     paper-color='255/255/255/0'
>     scrollbar-color='163/163/163/178'
>     scrollbar-handle-color='70/70/70/150'
>
> ```

Nope, why? Just open the info screen (by pressing 'i') For me it is very
hard to tell at a glance that the scrollbar is even there.

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> edo0 <notifications@github.com> writes:
>
>> ![70-70-70-150
>> scrollbar](https://user-images.githubusercontent.com/16632292/93141510-d462d280-f6d3-11ea-8d91-33cb682383f0.png)
>> I have been playing with the palette a bit more: this is the result I
>> obtain by setting
>> ` scrollbar-handle-color='70/70/70/150'` 
>> in
>> ```
>>     background-color='245/246/247'
>>     paper-color='255/255/255/0'
>>     scrollbar-color='163/163/163/178'
>>     scrollbar-handle-color='70/70/70/150'
>>
>> ```
>
> Nope, why? Just open the info screen (by pressing 'i') For me it is very
> hard to tell at a glance that the scrollbar is even there.

I did an unscientific exploration of what scrollbar in firefox (gtk3)
looks like on my machine and came with the following...

diff --git a/genconfstr.sh b/genconfstr.sh
index 3c5d1f1..6dab46f 100644
--- a/genconfstr.sh
+++ b/genconfstr.sh
@@ -92,8 +92,8 @@ g sliceheight sliceheight 24
 g thumbw width 76
 g bgcolor rgb "(0.5, 0.5, 0.5)"
 g papercolor rgba "(1.0, 1.0, 1.0, 0.0)"
-g sbarcolor rgba "(0.64, 0.64, 0.64, 0.7)"
-g sbarhndlcolor rgba "(0.0, 0.0, 0.0, 0.7)"
+g sbarcolor rgba "(0.8, 0.8, 0.8, 0.7)"
+g sbarhndlcolor rgba "(0.49, 0.51, 0.52, 0.7)"
 g texturecolor rgba "(0.0, 0.0, 0.0, 0.0)"
 i tilew 2048
 i tileh 2048

**Comment by edo0** [comment]
Ok, so with
`    scrollbar-handle-color='49/51/52/70'`
this is the result
![49-51-52-70](https://user-images.githubusercontent.com/16632292/93268734-40f5d400-f79d-11ea-8501-3d4c84dcc4da.png)
![49-51-52-70 - F1](https://user-images.githubusercontent.com/16632292/93268903-8914f680-f79d-11ea-81c4-ed763c622b40.png)

While with
`    scrollbar-handle-color='0/0/0/70'`
this is the result
![0-0-0-70](https://user-images.githubusercontent.com/16632292/93269094-ddb87180-f79d-11ea-9ad0-5099af3c640f.png)
![0-0-0-70- F1](https://user-images.githubusercontent.com/16632292/93269099-dee99e80-f79d-11ea-93b2-3e98cbcc3c0f.png)

**Comment by edo0** [comment]
Changing also the sidebar under the handle, these are the sort of results
![Screenshot_2020-09-15_23-55-23](https://user-images.githubusercontent.com/16632292/93269347-51f31500-f79e-11ea-8b10-8a19a1ef2611.png)
![Screenshot_2020-09-15_23-55-56](https://user-images.githubusercontent.com/16632292/93269348-528bab80-f79e-11ea-90fc-dd8bc8d3947b.png)

**Comment by moosotc** [comment]
edo0 <notifications@github.com> writes:

> Changing also the sidebar under the handle, these are the sort of results
> ![Screenshot_2020-09-15_23-55-23](https://user-images.githubusercontent.com/16632292/93269347-51f31500-f79e-11ea-8b10-8a19a1ef2611.png)
> ![Screenshot_2020-09-15_23-55-56](https://user-images.githubusercontent.com/16632292/93269348-528bab80-f79e-11ea-90fc-dd8bc8d3947b.png)

Sending screenshots is pointless. If you want my opinion send patches to
genconfstr.sh or llpp.conf excerpts, this way i can test them here and
form an opinion after trying.
