### ISSUE TITLE
Short delay after pressing `q`

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#149]
There is a short delay after I press `q` to quit. There is no delay if I press `Q`. 

Is it possible to make `llpp` close a document first and then save configuration in the background?

By the way, I don't know which version introduced the current history navigation. It's awesome! No more confusing jumps.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> There is a short delay after I press `q` to quit. There is no delay if
> I press `Q`.
>
> Is it possible to make `llpp` close a document first and then save
> configuration in the background?

No. However i was annayed by the slowness too (due to digesting for
the future) and tried to addressed it in:
56507f69d06efb74edcfeaa73e1cbeef0958eaf9

In my case the length of the delay was entirely dependent on the size
(in bytes) of the document.

Does your compiled binary include this commit?

The reason for digesting is that in the future one might move the
document around yet retain the per-document settings.

**Comment by JunnanZ** [comment]
Yes, I have that commit. I'm not sure what you meant by "digesting"? I just wonder if we could move that operation to another place, preferably after the document is closed, or if that's not possible maybe after opening the document, to make the user experience better.

My delay seems to be irrelevant of the file size. I tried one over 10M and one 200K and I couldn't tell the difference (opening is faster for the smaller file though).

**Comment by JunnanZ** [comment]
By the way, I don't seem to remember I had this delay before but I still could move the file and retain the settings.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> By the way, I don't seem to remember I had this delay before but I
> still could move the file and retain the settings.

Digest in the case of llpp is
https://en.wikipedia.org/wiki/Cryptographic_hash_function md5 to be
exact. So when you ask llpp to quit it computes digest of the file that
contains the document, the commit i referenced before is simply an
optmization to skip digesting if the file does not appear to have
changed (uning "good enough" heuristic) and it worked before because
prior to digesting llpp just looked if it visited the same file based
not on the digest but the path to the  file. One of the advantages of
digesting is the name can be different yet the settings remain, hope
that makes sense.

As for the slow down, i would have to have precise steps to reproduce
bad behaviour first.

**Comment by JunnanZ** [comment]
Thanks for the explanation.

So can't we compute the digest in the background right after opening a file instead of before closing a file? In that way, interacting with the document wouldn't be interrupted.

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Thanks for the explanation.
>
> So can't we compute the digest in the background right after opening a
> file instead of before closing a file? In that way, interacting with
> the document wouldn't be interrupted.

We can, But I'd rather have you give me the exact steps to reproduce
your problem so that i can fix it properly.

**Comment by JunnanZ** [comment]
How? Basically I can clearly feel the difference between closing a document using `q` and `Q`. It happens for any document.

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> How? Basically I can clearly feel the difference between closing a
> document using `q` and `Q`. It happens for any document.

I don't, that's the main thing - i have no idea why you feel the way you
feel and without more details i never will.

Does the perceptible slowdown happen with a new (empty) config file?
$ llpp -c /tmp/just-trying.conf

**Comment by JunnanZ** [comment]
No! It's much faster! So does it mean that my conf file is too large? Holy shit my `llpp.conf` has 12k lines. How do I slim it down?

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> No! It's much faster! So does it mean that my conf file is too large?
> Holy shit my `llpp.conf` has 12k lines. How do I slim it down?

Back it up (just in case). Then do a '$ llpp -gc' this will remove all
the entries for missing document files...

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> It's down to 8k now. The speed is noticably faster and the delay can
> be ignored. I can only notice the delay when the cpu is throttled on
> power saving anyway.

Nice.

>
> I will manually get rid of some entries later.
>
> Thank you!

You are welcome.

**Comment by JunnanZ** [comment]
I wrote a small python script to get rid of entries I no longer need. I'm posting it here in case anybody needs it. 

```python
import xml.etree.ElementTree as ET
from datetime import date
tree = ET.parse('llpp.conf')
root = tree.getroot()

for doc in root.findall('doc'):
    # skip entries with bookmarks
    if doc.find('bookmarks'):
        continue
    # remove entries older than 2019.9.1
    ts = int(doc.get('last-visit'))
    dt = date.fromtimestamp(ts)
    if dt < date(2019, 9, 1):
        root.remove(doc)
    # remove entries whose path contains the keyword
    if "keyword" in doc.get('path'):
        root.remove(doc)

tree.write('llpp_new.conf')
```

I think this issue can be closed.

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> I wrote a small python script to get rid of entries I no longer need. I'm posting it here in case anybody needs it. 
>

Thanks!

> ```python
> import xml.etree.ElementTree as ET
> from datetime import date
> tree = ET.parse('llpp.conf')
> root = tree.getroot()
>
> for doc in root.findall('doc'):
>     # skip entries with bookmarks
>     if doc.find('bookmarks'):
>         continue
>     # remove entries older than 2019.9.1
>     ts = int(doc.get('last-visit'))
>     dt = date.fromtimestamp(ts)
>     if dt < date(2019, 9, 1):
>         root.remove(doc)
>     # remove entries whose path contains the keyword
>     if "keyword" in doc.get('path'):
>         root.remove(doc)
>
> tree.write('llpp_new.conf')
> ```
>
> I think this issue can be closed.

If you create something (misc/gcext.py) "git am"able i'll gladly commit
it.

**Comment by JunnanZ** [comment]
First time doing this. Does the following work?

**Comment by JunnanZ** [comment]
Okay, how about this.

```
From b966a49aefb4e348721213cec54e51431d7426c1 Mon Sep 17 00:00:00 2001
From: Junnan Zhang <zhangjunnan1224@gmail.com>
Date: Mon, 21 Sep 2020 18:42:18 +0800
Subject: [PATCH] Add python script to clean llpp.conf

---
 misc/gcext.py | 19 +++++++++++++++++++
 1 file changed, 19 insertions(+)
 create mode 100644 misc/gcext.py

diff --git a/misc/gcext.py b/misc/gcext.py
new file mode 100644
index 0000000..09ac867
--- /dev/null
+++ b/misc/gcext.py
@@ -0,0 +1,19 @@
+import xml.etree.ElementTree as ET
+from datetime import date
+tree = ET.parse('llpp.conf')
+root = tree.getroot()
+
+for doc in root.findall('doc'):
+    # skip entries with bookmarks
+    if doc.find('bookmarks'):
+        continue
+    # remove entries older than 2019.9.1
+    ts = int(doc.get('last-visit'))
+    dt = date.fromtimestamp(ts)
+    if dt < date(2019, 9, 1):
+        root.remove(doc)
+    # remove entries whose path contains the keyword
+    if "keyword" in doc.get('path'):
+        root.remove(doc)
+
+tree.write('llpp_new.conf')
-- 
2.28.0
```

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Okay, how about this.

https://github.com/moosotc/llpp/commit/630ce66ac69d133bbfbcca0ed647c73a4978571c

谢谢

**Comment by JunnanZ** [comment]
😀 Glad I could finally contribute something to this great project. By the way, do you accept donation?

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> 😀 Glad I could finally contribute something to this great project. By
> the way, do you accept donation?

If you have money to spare - https://advancethecure4ms.org/donate Thanks
:) Knowing that there is at least one person who is willing to part with
hard earned possessions for something you have created is nice. Thanks :)

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Okay, how about this.

It'd be more intellectually pleasing for some (i.e. me) to have the
script accept three arguments, namely:

1) path to the config file
2) path to the output file (that if absent defaults to the input one)
3) "-d date" option to specify (currently hardcoded) cutoff date

Something like:

$ python3 /path/to/gcext.py ~/.config/llpp.conf \
  -o /some/where/ppll.conf -d $(date -d '-10 days' +%s)

[..]

**Comment by JunnanZ** [comment]
Yeah, indeed. I was thinking about the same thing yesterday. I will work on that.

**Comment by JunnanZ** [comment]
Hope this works.   From 2aab059f1f1c13c1cddcfb9aa0d32ed4406b1996 
Mon Sep 17 00:00:00 2001 From: Junnan Zhang 
<zhangjunnan1224@gmail.com> Date: Tue, 22 Sep 2020 22:46:19 +0800 
Subject: [PATCH] Make gcext.py a command line tool that takes 
arguments  --- 
 misc/gcext.py | 51 
 +++++++++++++++++++++++++++++++++++++++++++++------ 1 file 
 changed, 45 insertions(+), 6 deletions(-) 
 
diff --git a/misc/gcext.py b/misc/gcext.py index 09ac867..110d412 
100644 --- a/misc/gcext.py +++ b/misc/gcext.py @@ -1,19 +1,58 @@ 
+import argparse +import os 
 import xml.etree.ElementTree as ET 
-from datetime import date tree = ET.parse('llpp.conf') + +parser 
-= argparse.ArgumentParser() +parser.add_argument( +    '-i', + 
-dest='input', +    type=str, +    metavar='SOURCE', + 
-help='path to your llpp.conf; default to ~/.config/llpp.conf', + 
-default='~/.config/llpp.conf') +parser.add_argument( +    '-d', + 
-dest='timestamp', +    type=int, +    help='entries saved earlier 
-than this date will be removed') +parser.add_argument( +    '-k', 
-+    dest='keyword', +    type=str, +    help='entries with path 
-matching the keyword will be removed') 
-+parser.add_argument(dest='dest', +                    type=str, 
-+                    metavar='DEST', + 
-help='path to output config file') + +args = parser.parse_args() 
-+source = args.input +cts = args.timestamp +keyword = 
-args.keyword +dest = args.dest + +tree = 
-ET.parse(os.path.expanduser(source)) 
 root = tree.getroot()  
+print('Removing the following entries in llpp.conf:') +i = 0 
 for doc in root.findall('doc'): 
     # skip entries with bookmarks if doc.find('bookmarks'): 
         continue 
     # remove entries older than 2019.9.1 ts = 
     int(doc.get('last-visit')) 
-    dt = date.fromtimestamp(ts) if dt < date(2019, 9, 1): +    if 
-    cts is not None and ts < cts: +        print(doc.get('path')) 
         root.remove(doc) 
+        i += 1 +        continue 
     # remove entries whose path contains the keyword 
-    if "keyword" in doc.get('path'): +    if keyword is not None 
and keyword in doc.get('path'): +        print(doc.get('path')) 
         root.remove(doc) 
+        i += 1 
  
-tree.write('llpp_new.conf') +print(i, 'entries have been 
removed.', +      'The new configuration file has been saved to', 
dest) +tree.write(dest) --  2.28.0   On Mon, Sep 21 2020 at

**Comment by JunnanZ** [comment]
What a disaster that was. How about now?   From 
2aab059f1f1c13c1cddcfb9aa0d32ed4406b1996 Mon Sep 17 00:00:00 2001 
From: Junnan Zhang <zhangjunnan1224@gmail.com> Date: Tue, 22 Sep 
2020 22:46:19 +0800 Subject: [PATCH] Make gcext.py a command line 
tool that takes arguments  --- 
 misc/gcext.py | 51 
 +++++++++++++++++++++++++++++++++++++++++++++------ 1 file 
 changed, 45 insertions(+), 6 deletions(-) 
 
diff --git a/misc/gcext.py b/misc/gcext.py index 09ac867..110d412 
100644 --- a/misc/gcext.py +++ b/misc/gcext.py @@ -1,19 +1,58 @@ 
+import argparse +import os 
 import xml.etree.ElementTree as ET 
-from datetime import date tree = ET.parse('llpp.conf') + +parser 
-= argparse.ArgumentParser() +parser.add_argument( +    '-i', + 
-dest='input', +    type=str, +    metavar='SOURCE', + 
-help='path to your llpp.conf; default to ~/.config/llpp.conf', + 
-default='~/.config/llpp.conf') +parser.add_argument( +    '-d', + 
-dest='timestamp', +    type=int, +    help='entries saved earlier 
-than this date will be removed') +parser.add_argument( +    '-k', 
-+    dest='keyword', +    type=str, +    help='entries with path 
-matching the keyword will be removed') 
-+parser.add_argument(dest='dest', +                    type=str, 
-+                    metavar='DEST', + 
-help='path to output config file') + +args = parser.parse_args() 
-+source = args.input +cts = args.timestamp +keyword = 
-args.keyword +dest = args.dest + +tree = 
-ET.parse(os.path.expanduser(source)) 
 root = tree.getroot()  
+print('Removing the following entries in llpp.conf:') +i = 0 
 for doc in root.findall('doc'): 
     # skip entries with bookmarks if doc.find('bookmarks'): 
         continue 
     # remove entries older than 2019.9.1 ts = 
     int(doc.get('last-visit')) 
-    dt = date.fromtimestamp(ts) if dt < date(2019, 9, 1): +    if 
-    cts is not None and ts < cts: +        print(doc.get('path')) 
         root.remove(doc) 
+        i += 1 +        continue 
     # remove entries whose path contains the keyword 
-    if "keyword" in doc.get('path'): +    if keyword is not None 
and keyword in doc.get('path'): +        print(doc.get('path')) 
         root.remove(doc) 
+        i += 1 
  
-tree.write('llpp_new.conf') +print(i, 'entries have been 
removed.', +      'The new configuration file has been saved to', 
dest) +tree.write(dest) --  2.28.0

**Comment by JunnanZ** [comment]
Sorry, last try. It should work now.

From 2aab059f1f1c13c1cddcfb9aa0d32ed4406b1996 Mon Sep 17 00:00:00 2001
From: Junnan Zhang <zhangjunnan1224@gmail.com>
Date: Tue, 22 Sep 2020 22:46:19 +0800
Subject: [PATCH] Make gcext.py a command line tool that takes arguments

---
 misc/gcext.py | 51 +++++++++++++++++++++++++++++++++++++++++++++------
 1 file changed, 45 insertions(+), 6 deletions(-)

diff --git a/misc/gcext.py b/misc/gcext.py
index 09ac867..110d412 100644
--- a/misc/gcext.py
+++ b/misc/gcext.py
@@ -1,19 +1,58 @@
+import argparse
+import os
 import xml.etree.ElementTree as ET
-from datetime import date
-tree = ET.parse('llpp.conf')
+
+parser = argparse.ArgumentParser()
+parser.add_argument(
+    '-i',
+    dest='input',
+    type=str,
+    metavar='SOURCE',
+    help='path to your llpp.conf; default to ~/.config/llpp.conf',
+    default='~/.config/llpp.conf')
+parser.add_argument(
+    '-d',
+    dest='timestamp',
+    type=int,
+    help='entries saved earlier than this date will be removed')
+parser.add_argument(
+    '-k',
+    dest='keyword',
+    type=str,
+    help='entries with path matching the keyword will be removed')
+parser.add_argument(dest='dest',
+                    type=str,
+                    metavar='DEST',
+                    help='path to output config file')
+
+args = parser.parse_args()
+source = args.input
+cts = args.timestamp
+keyword = args.keyword
+dest = args.dest
+
+tree = ET.parse(os.path.expanduser(source))
 root = tree.getroot()
 
+print('Removing the following entries in llpp.conf:')
+i = 0
 for doc in root.findall('doc'):
     # skip entries with bookmarks
     if doc.find('bookmarks'):
         continue
     # remove entries older than 2019.9.1
     ts = int(doc.get('last-visit'))
-    dt = date.fromtimestamp(ts)
-    if dt < date(2019, 9, 1):
+    if cts is not None and ts < cts:
+        print(doc.get('path'))
         root.remove(doc)
+        i += 1
+        continue
     # remove entries whose path contains the keyword
-    if "keyword" in doc.get('path'):
+    if keyword is not None and keyword in doc.get('path'):
+        print(doc.get('path'))
         root.remove(doc)
+        i += 1
 
-tree.write('llpp_new.conf')
+print(i, 'entries have been removed.',
+      'The new configuration file has been saved to', dest)
+tree.write(dest)
-- 
2.28.0

**Comment by JunnanZ** [comment]
Below is the help message of the script. To be safer, I didn't use a default output path.

```
usage: gcext.py [-h] [-i SOURCE] [-d TIMESTAMP] [-k KEYWORD] DEST

positional arguments:
  DEST          path to output config file

optional arguments:
  -h, --help    show this help message and exit
  -i SOURCE     path to your llpp.conf; default to ~/.config/llpp.conf
  -d TIMESTAMP  entries saved earlier than this date will be removed
  -k KEYWORD    entries with path matching the keyword will be removed
```

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Sorry, last try. It should work now.
>

Applied with slightly changed subject line. Thanks.

[..]
