### ISSUE TITLE
Can't invert colors

### ISSUE THREAD

**Issue by ycny** [moosotc/llpp#15]
Hi,

in F1 menu, there is an option:
`-l invert colors`
Small problem is that the flag looks like big `i` or small `l`, but the big problem is non of these keys inverts colors. Also, the flag for `-l toggle proportional display` looks the same as for inverting colors. 
I was testing this on stable 22 version and git master; on many pdfs. In mupdf, the `i` key is working as it should. 

So, what is the correct key to invert colors?

**Comment by moosotc** [comment]
ycny <notifications@github.com> writes:

> Hi,
>
> in F1 menu, there is an option:
> `-l invert colors`
> Small problem is that the flag looks like big `i` or small `l`, but
> the big problem is non of these keys inverts colors Also, the flag for
> `-l toggle proportional display` looks the same as for inverting
> colors
> I was testing this on stable 22 version and git master; on many pdfs
> In mupdf, the `i` key is working as it should
>
> So, what is the correct key to invert colors?

-I works here (note this _IS_ capital i (I)) there's another way to do
that press 'i' (small i) nevigate and expand "Extended parameters" and
enable "invert colors".

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/moosotc/llpp/issues/15

-- 
mailto:moosotc@gmail.com

**Comment by ycny** [comment]
Capital `i` doesn't work here. I've even checked shitf+i and `i` with caps lock on. 
Inverting is working when using extended parameters menu. 
I'll check this one more time on completely different machine on Saturday and give an update. 

Maybe it is worth to note that I'm using packages from Arch AUR - llpp or llpp-git.

**Comment by moosotc** [comment]
ycny <notifications@github.com> writes:

> Capital `i` doesn't work here. I've even checked shitf+i and `i` with
> caps lock on.

Does `pacman -S xdotool' and then (when llpp is running):
$ xdotool search --class llpp key 0x2d I
work?

> Inverting is working when using extended parameters menu. 
> I'll check this one more time on completely different machine on
> Saturday and give an update.
>
> Maybe it is worth to note that I'm using packages from Arch AUR - llpp
> or llpp-git.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/moosotc/llpp/issues/15#issuecomment-165608967

-- 
mailto:moosotc@gmail.com

**Comment by ycny** [comment]
Ok, I have to confess that this is the first time I've noticed `-` (0x2D) key. I was trying to press just one letter as in mupdf. 
So, typicall PEBKAC, sorry:)

**Comment by moosotc** [comment]
ycny <notifications@github.com> writes:

> Ok, I have to confess that this is the first time I've noticed `-`
> (0x2D) key. I was trying to press just one letter as in mupdf.
> So, typicall PEBKAC, sorry:)

Hah :)

-- 
mailto:moosotc@gmail.com
