### ISSUE TITLE
Flickers when going to the next page but not when going to the previous page

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#150]
Going to the next page usually causes a flicker (with the checkerboard background). However, going to the previous page doesn't unless I do it for many pages at once. llpp seems to cache the previous pages but not the next pages. (Or probably it's upstream?)

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Going to the next page usually causes a flicker (with the checkerboard
> background). However, going to the previous page doesn't unless I do
> it for many pages at once. llpp seems to cache the previous pages but
> not the next pages. (Or probably it's upstream?)

Cache size is set by pixmap-cache-size configuration parameter, and llpp
tries to cache forward/backward everything that fits into this size. The
default is 32 megabytes, which might be too small for modern display
sizes and you might want to bump it higher (on this machine with 4k
monitor i've set it to 128 megybypes and do not suffer from cache being
too small too fit more than one page of worth of pixmap at modern
resolutions)

**Comment by JunnanZ** [comment]
I've done some testing. I don't think it's about cache size. The 
problem is that llpp doesn't preload forward but only preload 
backward.

Here is how to reproduce:

1. Open a large file or use a small cache size. Make sure that it 
spans the whole screen. (The issue is gone if I fit the whole page 
to screen.) Go to the first page and press space consecutively.

2. Go to the last page and press del consecutively.

On my computer, for case 1 it flickers every time but for case 2 
it only flickers the first time I press del.

**Comment by JunnanZ** [comment]
Thanks for the explanation. My llpp doesn't recognize "-d" but I 
think I found out what's wrong here.

The code seems to suggest that how much it preloads depends on 
window width and height. So I tested it by resizing the llpp 
window. Forward preloading works when the window is shrunk to a 
certain point and it stops working when the window size is too 
large.

I changed the multiplier from 3 to 5 in the code and it now 
preloads fine.

My guess is for forward preloading, the current page is also part 
of what is to be preloaded. If the multiplier is small, it can't 
preload all of the next page, hence the flicker. On the other 
hand, it immediately starts preloading the previous page, so 
backward preloading works fine for me.

Is that how llpp preloads?

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Thanks for the explanation. My llpp doesn't recognize "-d" but I 
> think I found out what's wrong here.

-d _within_ llpp, i.e. type '-' and then 'd' this activates debuging
mode and

-v, activates the verbose mode, llpp prints some information to standard
output/error. llpp must have been started from a terminal for those
messages to be observed.

To reiterate those are _not_ command line options.

>
> The code seems to suggest that how much it preloads depends on 
> window width and height. So I tested it by resizing the llpp 
> window. Forward preloading works when the window is shrunk to a 
> certain point and it stops working when the window size is too 
> large.
>
> I changed the multiplier from 3 to 5 in the code and it now 
> preloads fine.
>
> My guess is for forward preloading, the current page is also part 
> of what is to be preloaded. If the multiplier is small, it can't 
> preload all of the next page, hence the flicker. On the other 
> hand, it immediately starts preloading the previous page, so 
> backward preloading works fine for me.
>

The current visible area always takes precedence. Things that "limit"
preloading are the cache and tile sizes

> Is that how llpp preloads?
>

The most relevant part is the cache memory limit, which is too small by
default, but you can bump it.

llpp loads currentryl visible stuff and _tries_ to load one screenful
that precedes current point and one screenfull that follows.

It does so by creating an artificial layout and trying to (pre)load it
(so that things work for virtual layouts too (i.e. in multi/split column
modes))

[..]

**Comment by JunnanZ** [comment]
Oh I see the problem. It loads one screenful before and after, not one page before and after. For me the page size is usually larger than the screen. That's why llpp doesn't preload the next page. Anyway, I think the issue is resolved on my end. I'm closing this.

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> Oh I see the problem. It loads one screenful before and after, not one
> page before and after. For me the page size is usually larger than the
> screen. That's why llpp doesn't preload the next page. Anyway, I think
> the issue is resolved on my end. I'm closing this.

In general, page by page operations make no sense for llpp, case in
point: https://www.boblycat.org/~malc/main.pdf it has one, albeit very
tall, page...
