### ISSUE TITLE
Does llpp support midnight mode?

### ISSUE THREAD

**Issue by fu123456** [moosotc/llpp#151]
I have read help manual, and found that it does not support midnight mode and other backgrounds with different colors. So would you like to add this feature in the future? Very thanks.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> I have read help manual, and found that it does not support midnight
> mode and other backgrounds with different colors. So would you like to
> add this feature in the future? Very thanks.

I don't know what "midnight mode" is. There are 5 user settable colors
currently, namely:
 background
 paper
 scrollbar
 scrollbar handle
 texture

Mybe setting those can achieve the effect you desire.

**Comment by fu123456** [comment]
I try to set them, but it seems to not work. I want to black background, white texts. The figures are with white background and have normal colors.

**Comment by fu123456** [comment]
![Selection_001](https://user-images.githubusercontent.com/22411577/97784684-95fc7680-1ba0-11eb-9c2e-1f64595f5f34.png)
like this.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> ![Selection_001](https://user-images.githubusercontent.com/22411577/97784684-95fc7680-1ba0-11eb-9c2e-1f64595f5f34.png)
> like this.

You might want to try color inversion, inside llpp window type '-' and
then 'i' this will invert the colors.

**Comment by fu123456** [comment]
Thanks. It should be "I" rather than 'i'. It does work.

**Comment by moosotc** [comment]
GF <notifications@github.com> writes:

> Thanks. It should be "I" rather than 'i'. It does work.

Oh, blimey. Can you please close the issue then?
