### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#152]
It seems that this issue has never been mentioned before.

I thought it was hard to achieve but I just found that auto scrolling is pretty smooth.

Is there a reason to not use the same mechanism for scrolling with arrow keys?

**Comment by moosotc** [comment]
Junnan Zhang <notifications@github.com> writes:

> It seems that this issue has never been mentioned before.
>
> I thought it was hard to achieve but I just found that auto scrolling
> is pretty smooth.
>
> Is there a reason to not use the same mechanism for scrolling with arrow keys?

I have removed this, called "ghyll scroll", in
8447e5976c9f0db8f541b3b8fa4520ad2f376d62. The benefits, just one for me
- vanity of an author, just aren’t worth it. Auto scrolling advances by
auto-scroll-step pixels every so often, smoothness there is just a
function of the a-s-step value. OTOH "ghyll scroll" used ease-in ease-out
approach.

**Comment by JunnanZ** [comment]
I see. Thanks.

**Comment by SyndromeDayna** [comment]
> The benefits, just one for me - vanity of an author, just aren’t worth it

So, the issue is closed because the developer doesn't understand the purpose of smooth scrolling? This feature is very important for most people. That's why all popular applications turn it on by default.
