### ISSUE TITLE
vertical-scrollbar-visible='false' not working

### ISSUE THREAD

**Issue by prosoitos** [moosotc/llpp#153]
Thanks for a **very fast** pdf reader!

Setting `vertical-scrollbar-visible='false'` in llpp.conf doesn't have any effect in my system.

An easy workaround was to set `scroll-bar-width='0'`, so not big deal (and not sure whether this is reproducible or something specific to my local system for some reason).

Thanks!

**Comment by prosoitos** [comment]
Oh. And now this is working as well.

I think that the fact that llpp.conf gets re-created each time llpp is open is what caused me to wrongly open issues when everything was working fine.

My sincere apologies for this and thank you for a really cool pdf reader. It is much faster than the one I used before and I will now make llpp my default pdf tool.

As a side note, maybe having the info on doc path, last visited, etc. in a separate file would make things cleaner? This would prevent llpp to edit llpp.conf each time it runs and that would make customizing and testing a lot easier.

**Comment by prosoitos** [comment]
(Done in #155).

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> Closed #153.

Too mad it was closed without (self-deprecating) commentary and i have
no idea what was wrong!

**Comment by prosoitos** [comment]
What was wrong is that I was editing a ghost llpp.conf file that had no effect because llpp.conf had been auto-edited while llpp ran and my text editor did not refresh. So it was entirely user error :smile:

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> What was wrong is that I was editing a ghost llpp.conf file that had
> no effect because llpp.conf had been auto-edited while llpp ran and my
> text editor did not refresh. So it was entirely user error :smile:

No problem at all. FWIW you might want to investigate -c option, it
might me useful. As for not refreshing, my emacs [1] notifies me when
trying to save a file whos master copy has been changed on disk.

[1] This e-mail was written in emacs too (Gnus) so all the "neat"
    smileys got replaced with :textual-descriptions: I have no idea what
    "slightly-something-smile" really is and too old and grumpy to go
    and see for myself on github - désolé!
