### ISSUE TITLE
Unable to rebinding keys to capital letters

### ISSUE THREAD

**Issue by prosoitos** [moosotc/llpp#156]
Hello,

I seem to be unable to get this to work:

```html
<map in='shift-n' out='pgdown'/>
<map in='shift-p' out='pgup'/>
```

Any idea why? `in='shift-space'` works, but `in='shift-[letter]'` doesn't. I also tried using the capital letters directly (`in='N'` and `in='P'`) with no more luck.

Thanks!

**Comment by moosotc** [comment]
This sucks - yeah. 'shift-P' works as does 'shift-0x50'. This sucks - yeah.

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> Hello,
>
> I seem to be unable to get this to work:
>
> ```html
> <map in='shift-n' out='pgup'/>
> <map in='shift-p' out='pgdown'/>
> ```
>
> Any idea why? `in=shift-space` works, but `shift-[letter]` doesn't. I
> also tried using the capital letter `N` and `P` with no more luck.

To really bring back the point: neither "shift-p" nor "P" will work, as
X11 mill report keycode that translates into keysym for ’P’
(i.e. uppercase version) and the mask that includes ’shift’

Hope that clarifies things some.

**Comment by prosoitos** [comment]
Ah great! Thank you for giving me the solution :slightly_smiling_face: I guess I'll close this then.
