### ISSUE TITLE
llpp is getting suspended in background (tries to read stdin)

### ISSUE THREAD

**Issue by bbukh** [moosotc/llpp#157]
First, I want to thank for the amazing pdf viewer. I have been using it for years.

A couple of days ago, I downloaded and compiled the latest git version of llpp on freshly-installed Debian 10. It exhibits a new undesirable behavior.

If I start llpp in background via "llpp somefile.pdf &", then switch to terminal to do something, then when I switch back the llpp is frozen, and there is a message in the terminal "[1]  + suspended (tty input)  llpp somefile.pdf". Apparently, llpp is trying to read stdin when it is in background, and so is getting suspended by the shell. Being a pdf viewer, I see no reason for llpp to read stdin at all, and so assume that it is a bug. 

Let me know if you need any additional information.

**Comment by moosotc** [comment]
Boris Bukh <notifications@github.com> writes:

> First, I want to thank for the amazing pdf viewer. I have been using
> it for years.
>

Thank you :)

> A couple of days ago, I downloaded and compiled the latest git version
> of llpp on freshly-installed Debian 10. It exhibits a new undesirable
> behavior.
>
> If I start llpp in background via "llpp somefile.pdf &", then switch
> to terminal to do something, then when I switch back the llpp is
> frozen, and there is a message in the terminal "[1] + suspended (tty
> input) llpp somefile.pdf". Apparently, llpp is trying to read stdin
> when it is in background, and so is getting suspended by the
> shell. Being a pdf viewer, I see no reason for llpp to read stdin at
> all, and so assume that it is a bug.
>
> Let me know if you need any additional information.

Does following help?

diff --git a/main.ml b/main.ml
index 5e5c062..2487452 100644
--- a/main.ml
+++ b/main.ml
@@ -4702,12 +4702,13 @@ let () =
       doreap := false;
       reap ()
     );
-    let r = [!S.ss; !S.wsfd; !S.stderr] in
+    let r = [!S.ss; !S.wsfd] in
     let r =
       match !optrfd with
       | None -> r
       | Some fd -> fd :: r
     in
+    let r = if !redirstderr then !S.stderr :: r else r in
     if !redisplay
     then (
       Glutils.redisplay := false;

**Comment by bbukh** [comment]
Yes, that fixed it. Thanks.
