### ISSUE TITLE
Is it possible to increase the size of the step for the up and down commands?

### ISSUE THREAD

**Issue by prosoitos** [moosotc/llpp#158]
I was wondering whether it is possible to set key bindings to go up/down 5 lines for instance.

Thank you!

**Comment by prosoitos** [comment]
Never mind. I found it. I thought that `scroll-step` referred to mouse scrolling, but I just found out that it is actually about the up and down commands (so exactly what I wanted) 🙂 

Sorry for the noise... 😳

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> I was wondering whether it is possible to set key bindings to go
> up/down 5 lines for instance.
>
> Thank you!

Not really, there is no such thing as line to begin with (just consider
the fact that the document is an image) You can adjust some things in
the preferences though (scroll step and page scrolling factor)

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> Never mind. I found it. I thought that `scroll-step` referred to mouse
> scrolling, but I just found out that it is actually about the up and
> down commands (so exactly what I wanted) 🙂
>
> Sorry for the noise... 😳 

Oh, cool, periodically i amaze myself by my suprhuman ability to fix
bugs years before they are filled.
