### ISSUE TITLE
llpp open a pdf file, but can not scroll down

### ISSUE THREAD

**Issue by xiaodongcentury** [moosotc/llpp#160]
Dear developer,
First thanks your great work!
Recently, i open a pdf file, the left corner displays: (press “e" to review error messages), so i press "e", and there are many errors, but i select "clear", then the pdf file can not scroll to next page.
i use acrobat reader on Windows, or chromium on Debian Sid, the pdf file display well.
so i can not solve the problem but seek help from you, and the pdf file see below attachment.
Many thanks.
[20201.pdf](https://github.com/moosotc/llpp/files/5902683/20201.pdf)

**Comment by xiaodongcentury** [comment]
If you need a english pdf file, i'll show you later.

**Comment by moosotc** [comment]
The problem is intermittent, trying to get to the bottom of it.
