### ISSUE TITLE
Signed pdf files

### ISSUE THREAD

**Issue by glykos** [moosotc/llpp#161]
Recent versions of mupdf can deal with signed pdf files and validate the signatures if they exist. 
It would be nice if llpp could also support this feature in the future.

**Comment by moosotc** [comment]
Unfortunately i know nothing about signed documents and how they are used.

**Comment by glykos** [comment]
Thanks, I'm closing this, it is no big deal.

**Comment by moosotc** [comment]
"Nicholas M. Glykos" <notifications@github.com> writes:

> Thanks, I'm closing this, it is no big deal.

I'll ask mupdf developers about what this task entails despite closure,
maybe it's a minute job, who knows?
