### ISSUE TITLE
showing the current position in a status bar

### ISSUE THREAD

**Issue by sharethewisdom** [moosotc/llpp#162]
In order to know which pages to print, I often need to loop up the current page (position) in the pdf. I find the info overlay hard to use, and I think that showing this information while scrolling/browsing could be useful. I also think that an option for a permanent status bar at the bottom of the screen would be a good idea.

**Comment by moosotc** [comment]
You can press '=' to get needed information.

**Comment by sharethewisdom** [comment]
Thanks, sorry I missed that. Could it be made permanently visible?

**Comment by moosotc** [comment]
Bart De Roy <notifications@github.com> writes:

> Thanks, sorry I missed that. Could it be made permanently visible?

No, technically it is possible though.
