### ISSUE TITLE
A few enhancement ideas

### ISSUE THREAD

**Issue by HinTak** [moosotc/llpp#163]
I think F1 needs to receive more mentions in docs, and perhaps it should work as a toggle - rather than requiring esc to get out , the esc was not obvious.

There was a typo in the control-+/control-- for zoom-in/out.

I'd like a constant-width mode (there is a constant height mode). I wonder how hard it would be?

**Comment by HinTak** [comment]
Oh, and thanks for an interesting usage of mupdf!

**Comment by moosotc** [comment]
ctrl-+ _AND_ ctrl-= both zoom in. and you are welcome. However i'm not sure what you mean by "mentions in the docs"

**Comment by HinTak** [comment]
I mean F1 is mentioned in the middle of the KEY BIINGINGS: 

```
KEY BINDINGS
       Open a document with llpp, then press F1 or alt-h to switch to help mode.
```

It probably can/should be last sentence in DESCRIPTION ? Like, "Press F1 for help".

**Comment by HinTak** [comment]
Took a while tabethabaldwin figure out how to get out of "=" (it just disappears by itself on next scroll) - I was expecting it to be a toggle. "e" also does not do anything interesting... (the pdf I was reading seems to have a corrupted jpeg).

By the way, how attached are you to "existing behavior" (like F1 into toggle, and perhaps not doing esc)? And adherence to being compatible to less?

**Comment by moosotc** [comment]
HinTak ***@***.***> writes:

> Took a while tabethabaldwin figure out how to get out of "=" (it just
> disappears by itself on next scroll) - I was expecting it to be a
> toggle. "e" also does not do anything interesting... (the pdf I was
> reading seems to have a corrupted jpeg).

'e' doesn't do anything interesting because there were no errors yet, if
there were then it would bring one to the list of them.

As you have noticed '=' is not a toggle. Following, kind of, does what
you want for up and down _keyboard_ initiated scrolls.

<map in='j' out='down ='/>
<map in='k' out='up ='/>

(The above basically translates j keypress into a pair of down arrow
 followed by an equal sign)

It appears to me that you want something else though, namely -
persistent indicator that tracks internal movement and always displays
current position regardless of the source, be it: keyboard, mouse or
remote command, no such functionality exists.

>
> By the way, how attached are you to "existing behavior" (like F1 into
> toggle, and perhaps not doing esc)? And adherence to being compatible
> to less?

Small things like that(e.g. keyboard shortcuts) tend to get hardwired
into the spine, so to speak. Keyboard i'm currently typing on does not
even have F1, it's accessible via Fn layer.

**Comment by HinTak** [comment]
No, I don't want persistent display of movement, etc. I was just expecting "=" to be a toggle, because it was not obvious how to get the info to go away. I only found accidentally that it goes away when I gave up and just continue scrolling.

I think the two "surprising" things I have so far, are that I expected "information ovelays" like F1 and =, to be toggles; so I'd probably like those to be changed (and may try to to that myself).

There was one other 'surprise': if I accidentally pressing 'esc' twice instead of once while in F1/help, the whole llpp quits. But I guess you or probably others are probably quite attached to having esc as "quit" in normal viewing and would object to that being removed.

**Comment by moosotc** [comment]
HinTak ***@***.***> writes:

> No, I don't want persistent display of movement, etc. I was just
> expecting "=" to be a toggle, because it was not obvious how to get
> the info to go away. I only found accidentally that it goes away when
> I gave up and just continue scrolling.

I don't understand - a toggle of what?

>
> I think the two "surprising" things I have so far, are that I expected
> "information ovelays" like F1 and =, to be toggles; so I'd probably
> like those to be changed (and may try to to that myself).
>
> There was one other 'surprise': if I accidentally pressing 'esc' twice
> instead of once while in F1/help, the whole llpp quits. But I guess
> you or probably others are probably quite attached to having esc as
> "quit" in normal viewing and would object to that being removed.

<map in='esc' out=''/>
I think this is mentioned somewhere, Arch Linux's llpp wike page maybe.

**Comment by HinTak** [comment]
I mean I want pressing F1 again, get one out of help mode; and pressing "=" again, remove the page info.

**Comment by moosotc** [comment]
HinTak ***@***.***> writes:

> I mean I want pressing F1 again, get one out of help mode; and
> pressing "=" again, remove the page info.

Okay. That's not how things work currently.
