### ISSUE TITLE
Autoscroll speed is too high 

### ISSUE THREAD

**Issue by grayich** [moosotc/llpp#164]
Autoscroll speed is too high 
The step of changing the speed is also very large
There is no indication of the current speed either

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

> Autoscroll speed is too high 
> The step of changing the speed is also very large
> There is no indication of the current speed either

Okay, i'll remove autoscrolling. Part of the functionality can be
implemented via '-remote' interface.

**Comment by moosotc** [comment]
***@***.*** writes:

> grayich ***@***.***> writes:
>
>> Autoscroll speed is too high 
>> The step of changing the speed is also very large
>> There is no indication of the current speed either
>
> Okay, i'll remove autoscrolling. Part of the functionality can be
> implemented via '-remote' interface.

Or you can try playing around with update interval and find the value
that isn't too high, like so:

diff --git a/main.ml b/main.ml
index 93255d8..1b0f6b6 100644
--- a/main.ml
+++ b/main.ml
@@ -4739,7 +4739,7 @@ let () =
                 else y
             in
             gotoxy !S.x y;
-            deadline +. 0.01
+            deadline +. 0.9
          | _ -> infinity
        in
        loop newdeadline

**Comment by grayich** [comment]
> Okay, i'll remove autoscrolling.

Nonono, do not) This is a useful feature.

tried "deadline +. 0.9", it started jumping abruptly

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

>> Okay, i'll remove autoscrolling.
>
> Nonono, do not) This is a useful feature.
>
> tried "deadline +. 0.9", it started jumping abruptly  

What is the value of autoscroll step? The default - 0.01 means that llpp
will do some work (autoscrolling) or whatever is needed 100 times per
second, 0.9 is not abrupt it's just a very long (relatively speaking)
interval - 1.1111... seconds. You can try playing around with this value
to find something that suits you, and default autoscrollstep is 2 the
only value that is lower than that is 1, but if 2 is too high i doubt
that 1 will make a world of a difference, hence this, alternative,
approach.

**Comment by grayich** [comment]
Where to change the autoscrollstep ?
And can make it equal to 0.5 ?

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

> Where to change the autoscrollstep ?
> And can make it equal to 0.5 ?

'autoscrollstep' along most other tunables can be managed in the info
mode.

Pressing 'i' will bring you there. Tunables are saved in the
configuration file, 'llpp -v' shows the location of the configuration
file.

'autoscrollstep' is an integer value, so no - setting it to 0.5 is
impossible.

**Comment by moosotc** [comment]
***@***.*** writes:

> grayich ***@***.***> writes:
>
>> Where to change the autoscrollstep ?
>> And can make it equal to 0.5 ?
>
> 'autoscrollstep' along most other tunables can be managed in the info
> mode.

Forgot to add that - pressing up/down while autoscrolling is active
increases/decreases autoscrollstep, iow makes scrolling go
faster/slower. (This is mentioned in the help screen)

>
> Pressing 'i' will bring you there. Tunables are saved in the
> configuration file, 'llpp -v' shows the location of the configuration
> file.
>
> 'autoscrollstep' is an integer value, so no - setting it to 0.5 is
> impossible.

**Comment by grayich** [comment]
>  pressing up/down while autoscrolling is active increases/decreases autoscrollstep

Yes.  That's exactly the problem. Too big a change step!

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

>> pressing up/down while autoscrolling is active increases/decreases
> autoscrollstep
>
> Yes.  That's exactly the problem. Too big a change step!

Cool, please close the issue if (re)setting the value solves your problem.

**Comment by grayich** [comment]
Nothing will work without changing  "i autoscrollstep 2" >> "f autoscrollstep 0.2"

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

> Nothing will work without changing "i autoscrollstep 2" >> "f
> autoscrollstep 0.2"

Sorry, i do not understand what you are trying to say.

**Comment by grayich** [comment]
Sorry i can't explain better

**Comment by moosotc** [comment]
grayich ***@***.***> writes:

> Sorry i can't explain better
>

You can change it. By pressing up/down while autoscroll is active or in
the setup screen.
