### ISSUE TITLE
Modify text colour

### ISSUE THREAD

**Issue by darrSonik** [moosotc/llpp#165]
Is there any option to change the text colour of PDFs? I know I can change the paper colour, but is it possible to change the text colour of the PDF?

I didn't find any helpful resources on the internet.

**Comment by moosotc** [comment]
Asaduzzaman Noor ***@***.***> writes:

> Is there any option to change the text colour of PDFs? I know I can
> change the paper colour, but is it possible to change the text colour
> of the PDF?

No, there is no such an option. Out of curiosity - why do you want to do
that?

>
> I didn't find any helpful resources on the internet.

**Comment by darrSonik** [comment]
I use my computer mostly at night. Therefore, if I change the paper colour to dark, it gets easy on my eyes. But, if the text colour isn't changed (usually text colour of a pdf is black), then it's unnatural to read black text on a dark paper.

This is the reason.
If there is no such option, then I should close this issue, perhaps!

**Comment by moosotc** [comment]
Asaduzzaman Noor ***@***.***> writes:

> I use my computer mostly at night. Therefore, if I change the paper
> colour to dark, it gets easy on my eyes. But, if the text colour isn't
> changed (usually text colour of a pdf is black), then it's unnatural
> to read black text on a dark paper.
>
> This is the reason.
> If there is no such option, then I should close this issue, perhaps!

Thanks for an explanation. The way _I_ understand things, you can not,
in general, do that. The best thing llpp can offer is brightness
control, accessible via '[' (decrease) and ']' (increase), but other
than that... sorry. Authors of mupdf might have better ideas, methods to
contact them are listed at:
     https://artifex.com/support/open-source/
