### ISSUE TITLE
PDF Highlighting

### ISSUE THREAD

**Issue by TobiasKlosek** [moosotc/llpp#166]
Hello!

First of all thanks for this amazing PDF-Reader. 

I just started to use it and am curios if there is a way to highlight specific lines since in the help there is a keybinding for "dehighlight"..

**Comment by moosotc** [comment]
TK_ ***@***.***> writes:

> Hello!
>
> First of all thanks for this amazing PDF-Reader. 
>
> I just started to use it and am curios if there is a way to highlight
> specific lines since in the help there is a keybinding for
> "dehighlight"..

Hey.

Searching, copying and PAX ("Point And X" mode) highlight relevant parts
of the text, and if one wants to remove this highlighting one can press
'U'.

Apart from that there's no way to highligh things.

**Comment by TobiasKlosek** [comment]
Ok thanks, I was hoping there is some basic highlighting implemented, so that i can see the highlighted text in other viewers as well.. 

Nevermind, nice app! So customizable!

**Comment by moosotc** [comment]
TK_ ***@***.***> writes:

> Ok thanks, I was hoping there is some basic highlighting implemented,
> so that i can see the highlighted text in other viewers as well..
>
> Nevermind, nice app! So customizable!

Ah you prabably mean annotations, there is support from the most basic
form of them (Ctrl + 2nd mouse button). mupdf-gl (probably - not sure)
has more sophisticated annotation support.

**Comment by TobiasKlosek** [comment]
I already encountered this! That is super useful, but im speaking of highlighting in general in form of an Textline/Area-Highlight of the content of the PDF itself in an specific color:
![image](https://user-images.githubusercontent.com/61796661/116794455-53731280-aacd-11eb-970c-f82f4e8024d3.png)
 
My usecase would be to use llpp as my default pdf-viewer and highlight specific things and save the highlighted pdf to access it mobile via handy for e.g.

**Comment by moosotc** [comment]
TK_ ***@***.***> writes:

> I already encountered this! That is super useful, but im speaking of
> highlighting in general in form of an Textline/Area-Highlight of the
> content of the PDF itself in an specific color:
> ![image](https://user-images.githubusercontent.com/61796661/116794455-53731280-aacd-11eb-970c-f82f4e8024d3.png)

Gotcha, llpp has no support for this, mupdf-gl might - not sure.

>  
> My usecase would be to use llpp as my default pdf-viewer and highlight
> specific things and save the highlighted pdf to access it mobile via
> handy for e.g.

P.S. Surprised that "Reinforcement learning" wasn't quoted in that
     snippet..
