### ISSUE TITLE
EPUB links in 'Table of contents'-mode don't work

### ISSUE THREAD

**Issue by PRESFIL** [moosotc/llpp#167]
Steps to reproduce:

1. Open EPUB-file
2. Press <kbd>o</kbd>
3. Click on any entry with link or select and press <kbd>Enter</kbd>
4. `llpp` does not jumps to page

Similar bug in `zathura`: https://git.pwmt.org/pwmt/zathura/-/issues/187
`llpp` version: `33.r489.g45967da-1`, AUR-version from https://aur.archlinux.org/packages/llpp-git/
Ocaml version: `4.11.1-1`

**Comment by moosotc** [comment]
PRESFIL ***@***.***> writes:

> Steps to reproduce:
>
> 1. Open EPUB-file
> 2. Press <kbd>o</kbd>
> 3. Click on any entry with link or select and press <kbd>Enter</kbd>
> 4. `llpp` does not jumps to page
>
> Similar bug in `zathura`: https://git.pwmt.org/pwmt/zathura/-/issues/187
> `llpp` version: `33.r489.g45967da-1`, AUR-version from
> https://aur.archlinux.org/packages/llpp-git/
> Ocaml version: `4.11.1-1`

Thanks for the report, the issue should be fixed now.

**Comment by PRESFIL** [comment]
With the latest commits, everything worked! Thanks for the instant response!

Was the reason really the same as in `zathura-pdf-mupdf`?
