### ISSUE TITLE
EPUB following any link leads to first page

### ISSUE THREAD

**Issue by PRESFIL** [moosotc/llpp#168]
Steps to reproduce:

1. Open EPUB-file
2. Click on any link
3. `llpp` always jump to first page in file

Similar bug in `zathura`: https://git.pwmt.org/pwmt/zathura-pdf-mupdf/-/issues/18
`llpp` version: `33.r489.g45967da-1`, AUR-version from https://aur.archlinux.org/packages/llpp-git/
Ocaml version: `4.11.1-1`

**Comment by PRESFIL** [comment]
With the latest commits, everything worked! Thanks for the instant response!

Was the reason really the same as in `zathura-pdf-mupdf`?

**Comment by moosotc** [comment]
PRESFIL ***@***.***> writes:

> With the latest commits, everything worked! Thanks for the instant response!
>
> Was the reason really the same as in `zathura-pdf-mupdf`?

I don't know. But it's a distinct possibility.

**Comment by PRESFIL** [comment]
OK.
