### ISSUE TITLE
Opening links inserted in annotations

### ISSUE THREAD

**Issue by AdrienLemaire** [moosotc/llpp#170]
Hi,

I have received pdfs with links that should be opened by double-clicking on an icon itself added through an annotation.

![](https://i.imgur.com/qJkrWVt.png)

I can't seem able to double-click on it. When simply clicking, it shows this screen

![](https://i.imgur.com/FAPD5fE.png)

The institution sending these pdfs recommends using the pdf xchange viewer tool, but since it's a windows software... 

I went over the `h` screen, but couldn't find a way to open that link. Did I miss it ? Else, do you think this feature could be added to llpp ?

**Comment by moosotc** [comment]
Adrien Lemaire ***@***.***> writes:

> Hi,
>
> I have received pdfs with links that should be opened by
> double-clicking on the icon.
>
> ![](https://i.imgur.com/qJkrWVt.png)
>
> I can't seem able to double-click on it. When simply clicking, it
> shows this screen
>
> ![](https://i.imgur.com/FAPD5fE.png)
>
> The institution sending these pdfs recommends using the pdf xchange
> viewer tool, but since it's a windows software...
>
> I went over the `h` screen, but couldn't find a way to open that
> link. Did I miss it ? Else, do you think this feature could be added
> to llpp ?

Judging by the screenshots those appear to be annotations. And llpp
"opened" them - ie had shown the associated text.

https://pymupdf.readthedocs.io/en/latest/annot.html

**Comment by AdrienLemaire** [comment]
@moosotc I'm not sure if you understood my request. 
This icon is an image annotation with a url embedded. It should be clickable, but the llpp feature is preventing it.

I know nothing about llpp, but maybe there are 2 ways to go about it? 
* detect if an image has an embedded url and add a [Open link]  in the Edit/Delete/Copy annotation menu
* Show non-text annotation content in the annotation edit field.

I was wondering if the text annotation was opened first, preventing me from opening the icon annotation, so I tried deleting it, but I confirm that llpp is treating the icon as an empty annotation:

![](https://i.imgur.com/sLM5oVV.png)

**Comment by moosotc** [comment]
Adrien Lemaire ***@***.***> writes:

> @moosotc I'm not sure if you understood my request. 
> This icon is an image annotation with a url embedded. It should be
> clickable, but the llpp feature is preventing it.
>
> I know nothing about llpp, but maybe there are 2 ways to go about it? 
> * detect if an image has an embedded url and add a [Open link] in the
> Edit/Delete/Copy annotation menu
> * Show non-text annotation content in the annotation edit field.
>
> I was wondering if the text annotation was opened first, preventing me
> from opening the icon annotation, so I tried deleting it, but I
> confirm that llpp is treating the icon as an empty annotation:
>
> ![](https://i.imgur.com/sLM5oVV.png)

Can you share this pdf? What happens when you try to click on the
annotation in other viewers (mupdf-gl, okular, evince, firefox's
embedded viewer)?

**Comment by AdrienLemaire** [comment]
@moosotc no luck with mupdf. It found a fileattachment object, but I couldn't open it.

It worked with evince thought ! :tada: 
![](https://i.imgur.com/Tlysl9L.png)

It is not a link as I assumed, but an entire 2Mb file embedded in that pdf.

Here's the file: 
[CorrectionLEMAIRE_SAKURA AMELIE_CPFR_DEV02.pdf](https://github.com/moosotc/llpp/files/6566150/CorrectionLEMAIRE_SAKURA.AMELIE_CPFR_DEV02.pdf)

**Comment by moosotc** [comment]
Adrien Lemaire ***@***.***> writes:

> @moosotc no luck with mupdf. It found a fileattachment object, but I
> couldn't open it.
>

Annotation rectangles on page 5 overlap so clicking on a pin icon might
be impossible (depending on the application). With mupdf you can click
near the pin which most likely will select the overlapping annotation
("Sakura ..."), the fact of selecting any (i gueess) annotation will
open annotation editor on the right, where you can select annotation
#130 ("File attachment") selecting this(130th entry) will allow you to
save it.

I'm not going to add annotation files to llpp, sorry, too much work.

> It worked with evince thought ! :tada: 
> ![](https://i.imgur.com/Tlysl9L.png)
>
> It is not a link as I assumed, but an entire 2Mb file embedded in that pdf.
>
> Here's the file: 
> [CorrectionLEMAIRE_SAKURA
> AMELIE_CPFR_DEV02.pdf](https://github.com/moosotc/llpp/files/6566150/CorrectionLEMAIRE_SAKURA.AMELIE_CPFR_DEV02.pdf)

Thanks!
