### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by bbukh** [moosotc/llpp#174]
I am trying to compile llpp on a new machine, running a Ubuntu 20.04 with some modifications that I do not know in detail (it is a work machine). I am following the build instructions in BUILDING. I fetched mupdf+prereqs successfully, but the compilation fails with the folllowing message:

> generating build/confstruct.ml
  keys.cmi
 wsi/x11/wsi.cmi
 utils.cmi
 utf8syms.cmo
   parser.cmi
   confstruct.cmo
  config.cmo
 uiutils.cmi
 help.cmi
  lablGL/raw.cmi
 glutils.cmi
   lablGL/gl.cmi
  lablGL/glPix.cmi
 lablGL/glTex.cmi
 lablGL/glMisc.cmi
 lablGL/glMat.cmi
 lablGL/glFunc.cmi
 lablGL/glDraw.cmi
 lablGL/glClear.cmi
 lablGL/glArray.cmi
 ffi.cmo
 main.cmi
main.cmo
keys.cmo
wsi/x11/wsi.cmo
utils.cmo
parser.cmo
uiutils.cmo
help.cmo
lablGL/raw.cmo
glutils.cmo
lablGL/gl.cmo
lablGL/glPix.cmo
lablGL/glTex.cmo
File "./lablGL/glTex.ml", line 116, characters 23-35:
116 | let gen_texture () =  (gen_textures 1).(0)
                             ^^^^^^^^^^^^
Warning 6 [labels-omitted]: label len was omitted in the application of this function.
lablGL/glMisc.cmo
lablGL/glMat.cmo
lablGL/glFunc.cmo
lablGL/glDraw.cmo
lablGL/glClear.cmo
lablGL/glArray.cmo
link.o
cc1: error: too many filenames given.  Type cc1 --help for usage
cc1: fatal error: build/link.d: No such file or directory
compilation terminated.
ocamlc -ccopt "-g -std=c11 -I build/mupdf/include -I build/mupdf/thirdparty/freetype/include -Wall -Werror -Wextra -pedantic -O2 -D_POSIX_C_SOURCE -DGL_H='<GL/gl.h>' -include ./diag.h -DFIXME=0 -DTEXT_TYPE=GL_TEXTURE_RECTANGLE_ARB -MMD -MF build/link.o.dep -MT_ -o build/link.o" ./link.c failed
build failed

Since the error message mentions cc1, my gcc version is "gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0" if that helps.

**Comment by moosotc** [comment]
Boris Bukh ***@***.***> writes:

> I am trying to compile llpp on a new machine, running a Ubuntu 20.04
> with some modifications that I do not know in detail (it is a work
> machine). I am following the build instructions in BUILDING. I fetched
> mupdf+prereqs successfully, but the compilation fails with the
> folllowing message:
>
>> generating build/confstruct.ml
>   keys.cmi
>  wsi/x11/wsi.cmi
>  utils.cmi
>  utf8syms.cmo
>    parser.cmi
>    confstruct.cmo
>   config.cmo
>  uiutils.cmi
>  help.cmi
>   lablGL/raw.cmi
>  glutils.cmi
>    lablGL/gl.cmi
>   lablGL/glPix.cmi
>  lablGL/glTex.cmi
>  lablGL/glMisc.cmi
>  lablGL/glMat.cmi
>  lablGL/glFunc.cmi
>  lablGL/glDraw.cmi
>  lablGL/glClear.cmi
>  lablGL/glArray.cmi
>  ffi.cmo
>  main.cmi
> main.cmo
> keys.cmo
> wsi/x11/wsi.cmo
> utils.cmo
> parser.cmo
> uiutils.cmo
> help.cmo
> lablGL/raw.cmo
> glutils.cmo
> lablGL/gl.cmo
> lablGL/glPix.cmo
> lablGL/glTex.cmo
> File "./lablGL/glTex.ml", line 116, characters 23-35:
> 116 | let gen_texture () =  (gen_textures 1).(0)
>                              ^^^^^^^^^^^^
> Warning 6 [labels-omitted]: label len was omitted in the application of this function.
> lablGL/glMisc.cmo
> lablGL/glMat.cmo
> lablGL/glFunc.cmo
> lablGL/glDraw.cmo
> lablGL/glClear.cmo
> lablGL/glArray.cmo
> link.o
> cc1: error: too many filenames given.  Type cc1 --help for usage
> cc1: fatal error: build/link.d: No such file or directory
> compilation terminated.
> ocamlc -ccopt "-g -std=c11 -I build/mupdf/include -I build/mupdf/thirdparty/freetype/include -Wall -Werror -Wextra -pedantic -O2 -D_POSIX_C_SOURCE -DGL_H='<GL/gl.h>' -include ./diag.h -DFIXME=0 -DTEXT_TYPE=GL_TEXTURE_RECTANGLE_ARB -MMD -MF build/link.o.dep -MT_ -o build/link.o" ./link.c failed
> build failed
>
> Since the error message mentions cc1, my gcc version is "gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0" if that helps.
>

This is very similar to the issue i had with CI system.
a7a294f8978dd4607b538e6357a14b14c9443b5a
simply disabled CI on macOS.

What worked for me in _all_ cases is what ahbs does, i.e. compile via
'ccache', it would be nice if you could try it?

**Comment by bbukh** [comment]
I am sorry, but I do not see what I need to change inside the build script `build.bash`. Can you please be more explicit as to what I need to try?

**Comment by moosotc** [comment]
Boris Bukh ***@***.***> writes:

> I am sorry, but I do not see what I need to change inside the build
> script `build.bash`. Can you please be more explicit as to what I need
> to try?

Just try running ahbs script from the top level directory.

    cd llpp-checkout
    ./ahbs

**Comment by bbukh** [comment]
Success. This works.

**Comment by moosotc** [comment]
@nojb afact this is an ocaml problem, can you ask someone at INRIA perhaps?

**Comment by moosotc** [comment]
Boris Bukh ***@***.***> writes:

> Success. This works.
>

Great, thanks for testing.

**Comment by bbukh** [comment]
No problem. Thanks for the help, and for the great pdf viewer. Let me know if there is any other information about my system that you need as you try to track this issue down.

**Comment by moosotc** [comment]
Boris Bukh ***@***.***> writes:

> No problem. Thanks for the help, and for the great pdf viewer. Let me
> know if there is any other information about my system that you need
> as you try to track this issue down.

You are welcome. I have managed to reproduce the problem on my machine
(one just have to _NOT_ use ccache)

A week or two ago i have attempted to bisect OCaml but was unsuccessful.
