### ISSUE TITLE
llpp不能显示中文书签

### ISSUE THREAD

**Issue by fu123456** [moosotc/llpp#177]
打开一个pdf文件，按键o，显示书签，英文的显示是ok的，但是中文的都是框框。
这个是没有指定中文字体导致的吗？有什么解决办法？

**Comment by moosotc** [comment]
我不懂任何种类的中文

**Comment by fu123456** [comment]
Sorry. llpp can not show Chinese bookmark, although it can correctly show English bookmark.
The image with issues is as follows
![llpp_issue](https://user-images.githubusercontent.com/22411577/135309442-e215b32f-6dbf-4ed3-9f4b-5d5112e34ab6.png)
:

**Comment by moosotc** [comment]
GF ***@***.***> writes:

> Sorry. llpp can not show Chinese bookmark, although it can correctly show English bookmark.
> The image with issues is as follows
> ![llpp_issue](https://user-images.githubusercontent.com/22411577/135309442-e215b32f-6dbf-4ed3-9f4b-5d5112e34ab6.png)

Can you try specifying path to a UI font that contains CJK glyphs?
For instance:
  - llpp -f ~/.fonts/pan/LastResort.ttf /path/to/document/with-jck-outline.ext

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ just an example

**Comment by fu123456** [comment]
Yes, it does work.

**Comment by fu123456** [comment]
I also want to know how to set keybindings in the bookmark mode. In view mode, I can set <keymap mode='view'>. But in bookmark mode, how to set?
.
