### ISSUE TITLE
bleed

### ISSUE THREAD

**Issue by blueForestIcarus** [moosotc/llpp#178]
I'm still trying to work the details of this out, but I think there should be a way to view beyond the default margins of the document. 

ie. a way to view the bleed-zone, that many pdf's have, but don't by default show.

ex. by merely changing the content stream top level matrix transform, we go from this
![2021-10-11T20:07:35](https://user-images.githubusercontent.com/6549542/136874127-28035194-38ea-4cf5-9ade-75c35d4649ca.png)

to this
![2021-10-11T20:09:33](https://user-images.githubusercontent.com/6549542/136874128-bee0c85f-6cc2-4d7b-9b8a-65b3c5d00652.png)

Those features are in the pdf, past the edges. I've seen it on some orielly books as well.
I believe it is meant for industrial printing, where the pages are cut after being print. 
It would be nice to be able to view this outer content through a special mode.

**Comment by moosotc** [comment]
Erich Spaker ***@***.***> writes:

> I'm still trying to work the details of this out, but I think there
> should be a way to view beyond the default margins of the document.
>
> ie. a way to view the bleed-zone, that many pdf's have, but don't by
> default show.
>
> ex. by merely changing the content stream top level matrix transform,
> we go from this
> ![2021-10-11T20:07:35](https://user-images.githubusercontent.com/6549542/136874127-28035194-38ea-4cf5-9ade-75c35d4649ca.png)
>
> to this
> ![2021-10-11T20:09:33](https://user-images.githubusercontent.com/6549542/136874128-bee0c85f-6cc2-4d7b-9b8a-65b3c5d00652.png)
>
> Those features are in the pdf, past the edges. I've seen it on some
> orielly books as well.  I believe it is meant for industrial printing,
> where the pages are cut after being print.  It would be nice to be
> able to view this outer content through a special mode.
>

Document on the second screenshot can be "transformed" into the first
one by setting "trim-fuzz" ("Extended Parameters >> trim fuzz" in the
setup screen (i)) to something like "-20/-20/20/20" and then trimming the
document (-T). [Though, currently, this will only work for PDFs]

**Comment by moosotc** [comment]
Erich Spaker ***@***.***> writes:

> That does work for me.
>
> You might want to support cycling through artbox, bleedbox, trimbox,
> cropbox, and mediabox (whichever are available) with a key.
>

I might also want to minimize chances for slipping and introducing a
bugs that will lead to the collapse of civilization. But an ablity to
not use cropbox is as good stepping stone towards that goal as
any.

Thanks for testing!
