### ISSUE TITLE
Questions on bookmarks? namely, sort, rename

### ISSUE THREAD

**Issue by ragnarov** [moosotc/llpp#179]
Is there any way of renaming bookmarks?
Is there any way of sorting bookmarks?

**Comment by moosotc** [comment]
Ragnarov ***@***.***> writes:

> Is there any way of renaming bookmarks?
> Is there any way of sorting bookmarks?
>

Other than editing configuration file - no.

**Comment by ragnarov** [comment]
NP, but can you give me some instruction,
on how that file is written,
I think it is not hard,
I still want to know its structure

Thanks for replying btw.

**Comment by moosotc** [comment]
Ragnarov ***@***.***> writes:

> NP, but can you give me some instruction,
> on how that file is written,
> I think it is not hard,
> I still want to know its structure
>
> Thanks for replying btw.
>

It's an XML(-like) collection of records, here's an (unmodified) snippet
from llpp.conf on my machine:

<doc path='/home/malc/x/pdf/que/BLOCK_001-480_&#208;&#145;&#208;&#181;&#209;&#128;&#208;&#181;&#208;&#183;&#208;&#184;&#208;&#189;.pdf'
    key='14773663d39e2808670ba4e31fb35be2'
    page='181' visy='1.000000'
    width='2268'
    height='1900'
    under-cursor-info='true'
    presentation='true'
    fit-model='page'
    trim-margins='true'
    trim-fuzz='-10/-10/10/10'
    title='&#4;&#17;'
    last-visit='1616827466'
    dcf='BLOCK_001-480_&#208;&#145;&#208;&#181;&#209;&#128;&#208;&#181;&#208;&#183;&#208;&#184;&#208;&#189;.pdf.dcf'>
<bookmarks>
<item title='52-65' page='464' visy='1.000000'/>
<item title='Quick (page 130) (bookmarked on 09/01/2021 at 04:03)' page='129' visy='1.000000'/>
<item title='prim-40..51' page='463' visy='1.000000'/>
<item title='prim' page='460' visy='1.000000'/>
<item title='moo' page='57' rely='0.669831'/>
</bookmarks>
</doc>

You can just edit it [1] replacing the title strings.

[1] Like so:
    $ $EDITOR $(llpp -v | sed -n 's;configuration file: \(.*\);\1;p)
