### ISSUE TITLE
Small font on hi-dpi screens

### ISSUE THREAD

**Issue by perlatus** [moosotc/llpp#18]
I'm using xorg-server:1.18.0 with a configured DPI of 192 and a resolution of 3200x1800 on a laptop. The font of the command bar is pretty small. I know the font file can be specified, but what about the font size?

**Comment by moosotc** [comment]
perlatus <notifications@github.com> writes:

> I'm using xorg-server:1180 with a configured DPI of 192 and a
> resolution of 3200x1800 on a laptop The font of the command bar is
> pretty small I know the font file can be specified, but what about the
> font size?

Extended parameters -> ui font size

<llppconfig>
<ui-font size='20'/> ?

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/moosotc/llpp/issues/18

-- 
mailto:moosotc@gmail.com

**Comment by perlatus** [comment]
That fixed it (I just edited the config file, forgot to check .config/ ).
