### ISSUE TITLE
CPU spike upon opening of specific PDF files

### ISSUE THREAD

**Issue by edo0** [moosotc/llpp#182]
I have compiled the master version of llpp on Opensuse Tumbleweed.
Upon opening certain PDF files, I have noticed the CPU [i3 6100u] rising to a constant 25% usage, even when said files were minimized.
![Screenshot from 2022-01-20 00-26-56](https://user-images.githubusercontent.com/16632292/150236265-84127451-bc1a-4be1-9d04-cece30f339b7.png)
The second file in the screenshot is, for comparison, another PDF file which gave no problems

Below are a couple of the "problematic" files.
[Example 01.pdf](https://github.com/moosotc/llpp/files/7901227/INTMED.11.-.17.11.20.pdf)
[Example 02.pdf](https://github.com/moosotc/llpp/files/7901231/INTMED.12.-.19.11.20.pdf)

Thank you for looking into this!

**Comment by moosotc** [comment]
edo0 ***@***.***> writes:

> I have compiled the master version of llpp on Opensuse Tumbleweed.
> Upon opening certain PDF files, I have noticed the CPU [i3 6100u]
> rising to a constant 25% usage, even when said files were minimized.
> ![Screenshot from 2022-01-20
> 00-26-56](https://user-images.githubusercontent.com/16632292/150236265-84127451-bc1a-4be1-9d04-cece30f339b7.png)
> The second file in the screenshot is, for comparison, another PDF file
> which gave no problems
>
> Below are a couple of the "problematic" files.
> [Example 01.pdf](https://github.com/moosotc/llpp/files/7901227/INTMED.11.-.17.11.20.pdf)
> [Example 02.pdf](https://github.com/moosotc/llpp/files/7901231/INTMED.12.-.19.11.20.pdf)

Here (i3 8109u) the behavior is the same - no cpu consumption spikes,
have you tried feeding them to mupdf-gl?

**Comment by edo0** [comment]
Seems to have been my fault!
Apparently my system was missing some Mesa OpenGL libraries, after installing the following the problem went away.

```
  libdrm-devel libgbm-devel libOSMesa8 libOSMesa-devel libpciaccess-devel Mesa-devel
  Mesa-dri-devel Mesa-libEGL-devel Mesa-libglapi-devel Mesa-libGLESv1_CM-devel
  Mesa-libGLESv2-devel
```

**Comment by edo0** [comment]
I was wrong. The problem is still there, but I found out it's even more complex than I thought.

Opening a new file (let's call it [Example03](https://github.com/moosotc/llpp/files/7906615/Syncope.pdf)) first, and then Example 01 and Example 02, only Example 03 used 25% CPU (and an excess of RAM). 

![Screenshot from 2022-01-20 16-43-04](https://user-images.githubusercontent.com/16632292/150372386-e06892cb-3ebe-44f6-911f-d9ae77798d4a.png)

After closing Example 03, Example 01 and 02 went to 25% CPU, and re-opening Example 03 would not cause the spike
![Screenshot from 2022-01-20 16-43-57](https://user-images.githubusercontent.com/16632292/150372403-7b2446f8-ba62-4ef5-bf01-e50fac3970d1.png)

**Comment by moosotc** [comment]
edo0 ***@***.***> writes:

> I was wrong. The problem is still there, but I found out it's even
> more complex than I thought.
>
> Opening a new file (let's call it
> [Example03](https://github.com/moosotc/llpp/files/7906615/Syncope.pdf))
> first, and then Example 01 and Example 02, only Example 03 used 25%
> CPU (and an excess of RAM).
>
> ![Screenshot from 2022-01-20
> 16-43-04](https://user-images.githubusercontent.com/16632292/150372386-e06892cb-3ebe-44f6-911f-d9ae77798d4a.png)
>
> After closing Example 03, Example 01 and 02 went to 25% CPU, and
> re-opening Example 03 would not cause the spike ![Screenshot from
> 2022-01-20
> 16-43-57](https://user-images.githubusercontent.com/16632292/150372403-7b2446f8-ba62-4ef5-bf01-e50fac3970d1.png)
>

Please provide reproduction steps, i.e.: do
1) this
then
2) that
3) observe following

Thanks.

**Comment by edo0** [comment]
I have given up on openSUSE, will therefore not investigate this issue further. 
Thank you for your assistance!
