### ISSUE TITLE
Grey bar at the bottom of the screen

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#184]
Open any pdf file (for example, this one http://www.africau.edu/images/default/sample.pdf). There is a grey bar at the bottom which is not supposed to be there.
![2022-02-18_13-16](https://user-images.githubusercontent.com/11328339/154622276-1d3367f2-8bf6-4962-8efc-b125b2e2d4d8.png)

If I scroll down, the bar stays there until it reaches the top of the next page. Then the bar is gone (or it overlaps with the "page break", I can't be sure):
![2022-02-18_13-17](https://user-images.githubusercontent.com/11328339/154622366-cc993d26-329d-48fb-8b26-ca8e93fe78a5.png)

As I keep scrolling, the bar will reappear at the original position when the page break leaves the screen.

If I don't use any config there is no issue, so it must be how I set the colors. Here is my config:
```
<defaults
    width='1200'
    height='1000'
    scroll-bar-width='7'
    scroll-handle-height='50'
    horizontal-scrollbar-visible='false'
    vertical-scrollbar-visible='true'
    case-insensitive-search='true'
    preload='true'
    page-bias='0'
    scroll-step='30'
    auto-scroll-step='10'
    max-height-fit='true'
    highlight-links='false'
    under-cursor-info='false'
    vertical-margin='2'
    zoom='100'
    presentation='false'
    rotation-angle='0'
    fit-model='width'
    pixmap-cache-size='128M'
    tex-count='32'
    slice-height='1024'
    thumbnail-width='76'
    background-color='29/31/33'
    paper-color='255/255/255/0'
    scrollbar-color='163/163/163/0'
    scrollbar-handle-color='100/100/100/90'
    texture-color='29/31/33/0'
    tile-width='2048'
    tile-height='2048'
    mupdf-store-size='256M'
    aalevel='8'
    trim-margins='false'
    trim-fuzz='0/0/0/0'
    uri-launcher='xdg-open &quot;%s&quot;'
    path-launcher='emacsclient -c &quot;%s&quot;'
    color-space='rgb'
    invert-colors='true'
    brightness='0.900000'
    selection-command='xsel -i'
    paste-command='LC_CTYPE=UTF-8 xclip -o'
    synctex-command='SyncTeX-inverse.sh'
    pax-command='xclip -i -selection clipboard'
    askpass-command=''
    savepath-command='echo %s'
    update-cursor='true'
    hint-font-size='12'
    horizontal-scroll-step='24'
    page-scroll-scale='0.950000'
    wheel-scrolls-pages='false'
    remote-in-a-new-instance='false'
    point-and-x='false'
    point-and-x-mark='word'
    scroll-bar-on-the-left='false'
    last-visit='-9223372036854775808'
    edit-annotations-inline='true'
    coarse-presentation-positioning='false'
    use-document-css='true'
    dcf=''
    hint-charset='aoeuidhtns'
    rlw='420'
    rlh='595'
    rlem='11'>
```
(I switched off "invert colors" to make the bar more visible in the above screenshots.)

**Comment by moosotc** [comment]
Junnan Zhang ***@***.***> writes:

[..]

> If I don't use any config there is no issue, so it must be how I set the colors. Here is my config:
> ```
[..]

>     page-scroll-scale='0.950000'

This tells llpp that next/prev page command should really use 0.95 of
the page height. The geay bar is a visual indication where that
0.95*height is. Setting this value
(Setup/Extended parameters/page scroll scaling factor) to 1 will make
the "gray bar disappear".

[..]

**Comment by JunnanZ** [comment]
Awesome! This solves it. Thanks. I totally forgot why I set it to 0.95 in the first place.
