### ISSUE TITLE
White flashes when zooming in when colours are inverted.

### ISSUE THREAD

**Issue by SweepingBishops** [moosotc/llpp#185]
When zooming in while the colours are inverted, a white flash occurs.  
It is very disturbing to the eye.  
If the colours are not inverted the screen is momentarily darkened, but that isn't as much of a disturbance.  
Also it happens only on a new zoom value.  
I use Arch, the llpp package I use is from its repos.

**Comment by moosotc** [comment]
SweepingBishops ***@***.***> writes:

> When zooming in while the colours are inverted, a white flash occurs.  
> It is very disturbing to the eye.  
> If the colours are not inverted the screen is momentarily darkened, but that isn't as much of a disturbance.  
> Also it happens only on a new zoom value.  
>

I don't know what can be done about it short of actually implementing
progressive zoom, which had occupied top spot in the todo list [1] for
years) FWIW the rendering steps llpp performs while rendering in
inverted/normal mode are almost exactly the same.

[1] https://github.com/moosotc/llpp/blob/master/todo.org

**Comment by SweepingBishops** [comment]
I would be highly thankful if you got the progressive zooming done.  
But maybe when in inverted mode switching the rendering screen to black would be fine.  
Would that work?

**Comment by moosotc** [comment]
SweepingBishops ***@***.***> writes:

> I would be highly thankful if you got the progressive zooming done.  
> But maybe when in inverted mode switching the rendering screen to black would be fine.  
> Would that work?

I don't know. Have you tried other colors? Under
Setup/Extended parameters/Colors
background and paper?

**Comment by moosotc** [comment]
***@***.***> writes:

> SweepingBishops ***@***.***> writes:
>
>> I would be highly thankful if you got the progressive zooming done.  
>> But maybe when in inverted mode switching the rendering screen to black would be fine.  
>> Would that work?
>
> I don't know. Have you tried other colors? Under
> Setup/Extended parameters/Colors
> background and paper?

After looking at the code, i take that suggestion back, here's a patch
that makes zooming less jarring, maybe it will also work for you.

diff --git a/main.ml b/main.ml
index aacff4c..a2f439c 100644
--- a/main.ml
+++ b/main.ml
@@ -400,7 +400,8 @@ let drawtiles l color =
        let w = let lw = !S.winw - x in min lw w
        and h = let lh = !S.winh - y in min lh h in
        texe `blend;
-       GlDraw.color (0.8, 0.8, 0.8);
+       let c = if conf.invert then 0.2 else 0.8 in
+       GlDraw.color (c, c, c);
        Glutils.filledrect (float x) (float y) (float (x+w)) (float (y+h));
        texe `modulate;
        if w > 128 && h > fstate.fontsize + 10

**Comment by SweepingBishops** [comment]
Thanks! While it didn't solve it completely, it is a lot better.

**Comment by JunnanZ** [comment]
I think a related issue is that, when a page is loading, the blank page is now a white screen instead of a dark checkerboard like before. This causes flickers when I change pages quickly.

**Comment by moosotc** [comment]
Junnan Zhang ***@***.***> writes:

> I think a related issue is that, when a page is loading, the blank
> page is now a white screen instead of a dark checkerboard like
> before. This causes flickers when I change pages quickly.
>

You can change the color of place-holder/blank page
(Settings>Extended Parameters>Colors>paper|background) perhaps some
darker/colder color will be less jarring.

**Comment by JunnanZ** [comment]
I'm not sure how to change the color of a blank page. Neither changing "paper" nor "background" achieves that.

**Comment by moosotc** [comment]
Junnan Zhang ***@***.***> writes:

> I'm not sure how to change the color of a blank page. Neither changing "paper" nor "background" achieves that.
>

Yeah, i keep forgetting that it's actually hardcoded in the code, sorry,
cf:

https://github.com/moosotc/llpp/issues/185?notification_referrer_id=NT_kwDOAJ2NYbMzMTQ2NzYzNTMzOjEwMzI1MzQ1#issuecomment-1046332020

**Comment by JunnanZ** [comment]
Ah perfect. Thanks!
