### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by raffaem** [moosotc/llpp#187]
It looks like all the files were deleted.

Would it make sense to restore them and protest by messages and materials inside the README or the software itself?

This way this is uselessf

**Comment by moosotc** [comment]
Raffaele Mancuso ***@***.***> writes:

> It looks like all the files were deleted.

I did it intentionally.

>
> Would it make sense to restore them and protest by messages and
> materials inside the README or the software itself?
>
> This way this is uselessf

It was part of an attention grabbing plot. You can still clone the repo
and then check out the last working commit.
