### ISSUE TITLE
Wsi module not found

### ISSUE THREAD

**Issue by raffaem** [moosotc/llpp#188]
When I ran `bash build.bash build` it fails with the following error:

```
File "build/confstruct.ml", line 41, characters 72-89:
41 |       ; mk "birdseye"; mk "textentry"; mk "links"; mk "view" ]); hfsize=Wsi.fontsizescale 12; pgscale=1.; wheelbypage=false; stcmd={|echo SyncTex|}; riani=false; paxmark=MarkWord; leftscroll=false; title=Utils.E.s; lastvisit=0.0; annotinline=true; coarseprespos=false; css=Utils.E.s; usedoccss=true; key=Utils.E.s; pax=None; dcf=Utils.E.s; hcs={|aoeuidhtns|}; rlw=420; rlh=595; rlem=11;}
                                                                             ^^^^^^^^^^^^^^^^^
Error: Unbound module Wsi
ocamlc -I build -I build/wsi/x11 -g -strict-sequence -strict-formats -alert @all-missing-mli -o build/confstruct.cmo build/confstruct.ml failed
build failed
```

**Comment by moosotc** [comment]
Raffaele Mancuso ***@***.***> writes:

> When I ran `bash build.bash build` it fails with the following error:
>
> ```
> File "build/confstruct.ml", line 41, characters 72-89:
> 41 |       ; mk "birdseye"; mk "textentry"; mk "links"; mk "view" ]); hfsize=Wsi.fontsizescale 12; pgscale=1.; wheelbypage=false; stcmd={|echo SyncTex|}; riani=false; paxmark=MarkWord; leftscroll=false; title=Utils.E.s; lastvisit=0.0; annotinline=true; coarseprespos=false; css=Utils.E.s; usedoccss=true; key=Utils.E.s; pax=None; dcf=Utils.E.s; hcs={|aoeuidhtns|}; rlw=420; rlh=595; rlem=11;}
>                                                                              ^^^^^^^^^^^^^^^^^
> Error: Unbound module Wsi
> ocamlc -I build -I build/wsi/x11 -g -strict-sequence -strict-formats -alert @all-missing-mli -o build/confstruct.cmo build/confstruct.ml failed
> build failed
> ```
>

Please describe exactly what you did (including the checkout process),
step by step, so i could try to recreate it over here and, maybe, see
the problem.

**Comment by raffaem** [comment]
Oh it works again. It was probably some dependency downloaded from git :)

```
git clone https://github.com/moosotc/llpp
git reset --hard 04431d79a40dcc0215f87a2ad577f126a85c1e61
mkdir build && sh misc/getmupdf.sh build/mupdf
bash build.bash build
```

**Comment by moosotc** [comment]
Raffaele Mancuso ***@***.***> writes:

> Oh it works again. It was probably some dependency downloaded from git :)
>

That's a relief, thanks for getting to the bottom of it.

> ```
> git clone https://github.com/moosotc/llpp
> git reset --hard 04431d79a40dcc0215f87a2ad577f126a85c1e61
> mkdir build && sh misc/getmupdf.sh build/mupdf
> bash build.bash build
> ```

That was my go-to proceduer too, good to know that it still applies.

[..]
