### ISSUE TITLE
Annotations using visual external editor

### ISSUE THREAD

**Issue by arthurmitrano** [moosotc/llpp#19]
This is a tiny possible issue.

I've been using the annotations capabilities of llpp and they work quite well when using inline annotation. However, if I don't use inline, llpp uses the editor set in the environment variable EDITOR. If I start llpp from a terminal window everything works the way it should, that is, llpp halts and wait to edit the note in the terminal window from where llpp was called.

The problem occurs when llpp is started from a file manager or other source where we do not see the terminal window from where llpp is being called. Basically llpp halts and waits for me to edit the file in the terminal session that my openbox is running (which is possibly being halted too, not sure).

If I change the $EDITOR variable to a visual editor this does not happen. Nevertheless the note is note being modified at all. If a note was in the pdf already, when using a visual editor (like gvim), llpp seems to not open the annotation file, that is, gvim is started with an empty file.

I don't know why this happens. Perhaps, it is an issue with my machine, but I though it can be useful to submit as a possible issue, since vim seems to work fine but gvim do not.

**Comment by moosotc** [comment]
arthurmitrano <notifications@github.com> writes:

> This is a tiny possible issue
>
> I've been using the annotations capabilities of llpp and they work
> quite well when using inline annotation However, if I don't use
> inline, llpp uses the editor set in the environment variable EDITOR If
> I start llpp from a terminal window everything works the way it
> should, that is, llpp halts and wait to edit the note in the terminal
> window from where llpp was called
>
> The problem occurs when llpp is started from a file manager or other
> source where we do not see the terminal window from where llpp is
> being called Basically llpp halts and waits for me to edit the file in
> the terminal session that my openbox is running (which is possibly
> being halted too, not sure)
>
> If I change the $EDITOR variable to a visual editor this does not
> happen Nevertheless the note is note being modified at all If a note
> was in the pdf already, when using a visual editor (like gvim), llpp
> seems to not open the annotation file, that is, gvim is started with
> an empty file

Sorry I cannot parse that at all, just checked with llpp started from
dmenu and things seem to work as intended[1]. It would be nice if you
could state exactly what you do step-by-step with intended/obtained
results.

>
> I don't know why this happens Perhaps, it is an issue with my machine,
> but I though it can be useful to submit as a possible issue, since vim
> seems to work fine but gvim do not
>

[1] I do not have [g]vim so it was tested with emacs.

-- 
mailto:moosotc@gmail.com

**Comment by arthurmitrano** [comment]
I just tested with emacs as my EDITOR variable and it works.

So let me describe the simplest steps to reproduce the issue.

1. Add `export EDITOR=/usr/bin/gvim` to `.bashrc`.
2. Open llpp from a terminal window: open `xterm` and type `llpp sample.pdf`.
3. Click on annotation and then edit or create new annotation with `Shift+right_click`.

gvim opens, but it has no text in it, even if the annotation had some. Also, after adding text, save and exit from gvim, the annotation does not contain what was typed in gvim. The annotation is created, but it is unaltered in case of editing or empty in case of new annotation.

This does not happen if `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs`.

If using gvim, here are somethings I notice:
1. The `llpp*note` file is not being created in `/tmp/`. If `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs` it is created.
2. As soon as I click edit, gvim pops up, but I can still control llpp to move to other pages or add other annotations. This does not happen if `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs`.

Is there anything else I can try to pin point the problem?

**Comment by moosotc** [comment]
arthurmitrano <notifications@github.com> writes:

> I just tested with emacs as my EDITOR variable and it works.
>
> So let me describe the simplest steps to reproduce the issue.
>
> 1. Add `export EDITOR=/usr/bin/gvim` to `.bashrc`.
> 2. Open llpp from a terminal window: open `xterm` and type `llpp sample.pdf`.
> 3. Click on annotation and then edit or create new annotation with
> `Shift+right_click`.
>
> gvim opens, but it has no text in it, even if the annotation had
> some. Also, after adding text, save and exit from gvim, the annotation
> does not contain what was typed in gvim. The annotation is created,
> but it is unaltered in case of editing or empty in case of new
> annotation.
>
> This does not happen if `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs`.
>
> If using gvim, here are somethings I notice:
> 1. The `llpp*note` file is not being created in `/tmp/`. If
> `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs` it is created.
> 2. As soon as I click edit, gvim pops up, but I can still control llpp
> to move to other pages or add other annotations. This does not happen
> if `EDITOR=/usr/bin/vim` or `EDITOR=/usr/bin/emacs`.
>
> Is there anything else I can try to pin point the problem?
>

I've compiled vim and can observe the problem (with `vim -g', I suppose
gvim is just a shell script/alias that does the same). vim, apparently,
plays some games (like maybe forking itself when -g is specified) and so
llpp has no idea that the editor has completed it's job, though at this
point it's just a conjecture, I'll get back to it after getting some
sleep.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
arthurmitrano <notifications@github.com> writes:

[..snip..]

Yes it does fork itself...

   -g			Run using GUI (like "gvim")
   -f  or  --nofork	Foreground: Don't fork when starting GUI

So at this point the only option I can think of is:

EDITOR='vim -g -f' llpp

-- 
mailto:moosotc@gmail.com

**Comment by arthurmitrano** [comment]
OK. I see the problem you mentioned. This solution solves the problem if starting llpp from a terminal emulator, since we can create the `alias llpp='EDITOR="/usr/bin/gvim -f" llpp'`. However, if I'm starting llpp from a file manager (PCManFM) it seems not work unless i set `export EDITOR=/usr/bin/gvim -f` in my `.xinitrc`.

This way the EDITOR variable is only set in one shell (from X session). I think this solution is fine and works for me. Thanks for the help.

**Comment by arthurmitrano** [comment]
OK. I see the problem you mentioned. This solution solves the problem if starting llpp from a terminal emulator, since we can create the `alias llpp='EDITOR="/usr/bin/gvim -f" llpp'`. However, if I'm starting llpp from a file manager (PCManFM) it seems not work unless i set `export EDITOR=/usr/bin/gvim -f` in my `.xinitrc`.

This way the EDITOR variable is only set in one shell (from X session). I think this solution is fine and works for me. Thanks for the help.

**Comment by moosotc** [comment]
arthurmitrano <notifications@github.com> writes:

> OK. I see the problem you mentioned. This solution solves the problem
> if starting llpp from a terminal emulator, since we can create the
> `alias llpp='EDITOR="/usr/bin/gvim -f" llpp'`. However, if I'm
> starting llpp from a file manager (PCManFM) it seems not work unless i
> set `export EDITOR=/usr/bin/gvim -f` in my `.xinitrc`.
>
> This way the EDITOR variable is only set in one shell (from X
> session). I think this solution is fine and works for me. Thanks for
> the help.
>

Just create a wrapper script somewhere in your $PATH called `llppam' for
instance and doing something like:

#!/bin/sh
EDITOR='vim -g -f' exec llpp

-- 
mailto:moosotc@gmail.com

**Comment by arthurmitrano** [comment]
That's genius! Thanks for the advice.
