### ISSUE TITLE
Feature request: rudimentary annotation creation

### ISSUE THREAD

**Issue by ghennequin** [moosotc/llpp#2]
I see the latest version is able to display annotations, this is already quite something as far as Linux PDF viewers go! I wonder how far llpp developers are from implementing (even rudimentary) annotation creation (I'm thinking clicking somewhere on the pdf and being asked to enter some text). As an academic I'm desperately in need of this feature, but I don't want to use bloated (often proprietary) software to do that. (plus obviously it'd be great not to have to leave my favorite PDF pager, which ticks so many other boxes for me in the first place). I think in most cases people don't need support for the zillions types of annotations that the PDF format includes, often simple sticky notes are enough. Many thanks.

**Comment by moosotc** [comment]
Can you, please, point me to the application that supports this functionality so that i can study it's behavior, adding somewhat detailed instructions would be nice too, thanks.

**Comment by ghennequin** [comment]
PDF readers with annotation capabilities (e.g. Adobe acrobat reader for linux, when PDF annotations have been enabled by someone who's got a licensed version of acrobat) can add sticky notes of various kinds, highlight some pieces of text, ... and do many more things which, I suppose, most people don't need. The behaviour I'm looking for is to simply be able to click somewhere on the page, and enter a line or two of text annotation (which is perhaps the simplest type of annotation the PDF format supports). This text is then hidden inside a little yellow sticky-note sign on the PDF, which llpp apparently already knows how to handle (I can currently click on those sticky yellow signs and it displays the text on a single line, with option to copy it in the clipboard - this alone is a great step for me, since I no longer need to switch PDF viewer to see my collaborators' comments). 

Just being able to add this most basic form of annotation would be a godsend for academic linux users who want to give inline feedback on a manuscript. I suppose the most difficult bit, implementation-wise, is to understand the format of text annotations in PDF files - perhaps the camlpdf library (written in OCaml, so easily used within llpp presumably) might help there. Also, adding an annotation is a write operation, which breaks the spirit of a PDF pager; a possibility would be to outsource PDF annotation to some external tool. Just like llpp is able to send the PDF to lp for printing, it could send "path to PDF file + page number + coordinates of where the cursor was clicked + text that was entered for the annotation" to some external program which the user specifies in llpp.conf, and which could be written separately to handle the writing of annotations in the pdf file (then the user would need to do a "reload", but that's OK I guess).

**Comment by ghennequin** [comment]
it looks like writing the external script to add annotations would be [relatively easy](http://stackoverflow.com/questions/4427034/add-comments-to-pdf-files-automagically-with-regular-expressions). I'm happy to try. So I guess all we need is llpp being able to send the information I mentioned (path to PDF file, page number, position of click in some coordinates to be determined, and annotation text) to an external program specified in llpp.conf

**Comment by moosotc** [comment]
Thanks.

I've created an add-annots branch where adding basic annotations support is implemented, some
"documentation" is in the commit comment.

**Comment by ghennequin** [comment]
brilliant! Thanks very much, that was really fast. I didn't know you could use mupdf to add annotations, that seems to be indeed a much better solution than what I proposed originally.

I've tried replacing conf.savecmd by 

> Str.global_replace (Str.regexp "%s") state.path conf.savecmd

and then set savepath-command='echo "%s'' in llpp.conf, in order to automatically save into the same PDF, but I then get exceptions upon exit:

> error: expected object number
> error: expected object number
> error: Repair failed already - not trying again
> error: cannot parse object (168 0 R)
> error: cannot load object (168 0 R) into cache
> uncaught exception: cannot load object (168 0 R) into cache

so I suspect it's not OK to write into the same PDF (perhaps the file descriptor isn't closed yet?).

Minor things: 

- I think I'd rather type my notes directly in llpp, much like we can edit llpp.conf by entering text directly at the bottom
- perhaps an option to save the file once in a while (not just upon exit) using W or some other keyboard shortcup would be great too
- at some point, perhaps an option to remove notes would be nice too :)

I'm so glad to be able to annotate with llpp, thanks again a million.

**Comment by moosotc** [comment]
I've added the ability to enter annotation text "inline" (shift+button) got popup the editor use ctrl+shift+button. Deletion is now also supported. As for saving to the same file, i'll try to understand what's going on.

**Comment by ghennequin** [comment]
Thanks, everything works great, problem solved! Thanks for implementing this so quickly.
