### ISSUE TITLE
Pressing [ in help menu causes a crash

### ISSUE THREAD

**Issue by Torwori** [moosotc/llpp#20]
Reproduction steps:
1) Open any file
2) Press F1 - help pops up
3) Press the "[" key

Error message:
```Fatal error: exception Failure("[ class not closed by ]")```

System info:
Arch x86_64
Installed from AUR (version 22-2)
```llpp version unknown, fitz 1.8, ocaml 4.02.3/64 bit```

**Comment by moosotc** [comment]
Igor Šćekić <notifications@github.com> writes:

> Reproduction steps:
> 1) Open any file
> 2) Press F1 - help pops up
> 3) Press the "[" key
>
> Error message:
> ```Fatal error: exception Failure("[ class not closed by ]")```

Thanks for the report, should be fixed now.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Igor Šćekić <notifications@github.com> writes:

> Reproduction steps:
> 1) Open any file
> 2) Press F1 - help pops up
> 3) Press the "[" key
>
> Error message:
> ```Fatal error: exception Failure("[ class not closed by ]")```
>

I would appreciate if you would close the bug if
543de8414c3fad4b9932b1a615e4a201e58c4136 fix things for you.

-- 
mailto:moosotc@gmail.com

**Comment by Torwori** [comment]
It's fixed, thanks!
