### ISSUE TITLE
autoscrolling doesn’t respect the "max fit" setting

### ISSUE THREAD

**Issue by Idlusen** [moosotc/llpp#21]
If I’m getting "max fit" right, when it is set to true the scrolling is limited at the "top of window == top of first page" rather than "bottom of window == top of first page" and the similar situation for downward scrolling.

However this doesn’t hold when autoscrolling: autoscrolling downwards loops when the bottom of the document is at the top, and upwards when the top of the document is at the top, regardless of the "max fit" value.

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> If I’m getting "max fit" right, when it is set to true the scrolling
> is limited at the "top of window == top of first page" rather than
> "bottom of window == top of first page" and the similar situation for
> downward scrolling.
>

Sorry I'm a bit obtuse, can you provide step by step secnario with the
intended and obtained results. Don't want to second guess.

> However this doesn’t hold when autoscrolling: autoscrolling downwards
> loops when the bottom of the document is at the top, and upwards when
> the top of the document is at the top, regardless of the "max fit"
> value.
>

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by Idlusen** [comment]
Okay I was writing a detailed answer but maybe I’m the one second guessing. What is the purpose of max fit?

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> Okay I was writing a detailed answer but maybe I’m the one second
> guessing. What is the purpose of max fit?
>

Try pressing End key with and without it - that's the best way I can
describe it, sorry.

-- 
mailto:moosotc@gmail.com

**Comment by Idlusen** [comment]
Okay that’s what I thought!
So here is my original answer:
I open a pdf file, max fit being set to true. If I hold "manual scrolling down" ie. "j" or "down arrow", the scrolling stops at the bottom of the last page. Back to the top with "g", and then "a" to autoscroll: it doesn’t loop back when the bottom of the last page is at the bottom of the window but when it is at the top (we can see the default background of llpp while we couldn’t in the first case).

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> Okay that’s what I thought!
> So here is my original answer:
> I open a pdf file, max fit being set to true. If I hold "manual
> scrolling down" ie. "j" or "down arrow", the scrolling stops at the
> bottom of the last page. Back to the top with "g", and then "a" to
> autoscroll: it doesn’t loop back when the bottom of the last page is
> at the bottom of the window but when it is at the top (we can see the
> default background of llpp while we couldn’t in the first case).
>

diff --git a/main.ml b/main.ml
index 0be1eb7..b0c1f71 100644
--- a/main.ml
+++ b/main.ml
@@ -6639,10 +6639,11 @@ let () =
             match state.autoscroll with
             | Some step when step != 0 ->
                 let y = state.y + step in
+                let fy = if conf.maxhfit then state.winh else 0 in
                 let y =
                   if y < 0
-                  then state.maxy
-                  else if y >= state.maxy then 0 else y
+                  then state.maxy - fy
+                  else if y >= state.maxy - fy then 0 else y
                 in
                 if state.mode = View
                 then gotoy_and_clear_text y

Should do what you want (if I managed to understand your problem)

-- 
mailto:moosotc@gmail.com

**Comment by Idlusen** [comment]
It does, thanks!
A small problem, but I had to point it out for the sake of consistency.
