### ISSUE TITLE
Invert color of images separately

### ISSUE THREAD

**Issue by Idlusen** [moosotc/llpp#22]
This would be nice.
I think there is two options: allow separate image inversion via a keybinding which adds a bit of complexity, or do not invert/double-invert by default which is problematic for pdf files consisting of images and is less flexible.

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> This would be nice.
> I think there is two options: allow separate image inversion via a
> keybinding which adds a bit of complexity, or do not
> invert/double-invert by default which is problematic for pdf files
> consisting of images and is less flexible.
>

I don't know what you mean by separate image inversion, does any other
application implement what you want? (so that I can look into feasibility
of adding this)

-- 
mailto:moosotc@gmail.com

**Comment by Idlusen** [comment]
I should have stated the basic problem: when you activate color inversion, "natural" images embedded in the pdf file are inverted too. I mean, you might prefer white text/black background over black text/white background, but surely purple trees and orange skies are problematic for most of us.

I do care a lot about color inversion in my everyday use of computers so while I do not remember an application implementing this, I sort of implemented a solution for firefox: since too much of the web is too bright for my taste, I invert the colors of the firefox window via an effect of the window manager, and a css rule inverts the colors of the images elements.

I’m not sure how color inversion is done in llpp, and if you rely on some sort of backend I guess it is not possible.
As for the two solutions I was proposing, I meant that one can try to be smart and always render embedded images without inversion at the expense of pdf files consisting mainly of images. Or the simple solution of adding a keybinding, but since you didn’t see what I meant I guess users could be confused too. Still the second option seems best to me.

I hope I made myself a bit clearer. It seems to be a simple issue to me but again I do not remember an application proposing it.

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> I should have stated the basic problem: when you activate color
> inversion, "natural" images embedded in the pdf file are inverted
> too. I mean, you might prefer white text/black background over black
> text/white background, but surely purple trees and orange skies are
> problematic for most of us.
>
> I do care a lot about color inversion in my everyday use of computers
> so while I do not remember an application implementing this, I sort of
> implemented a solution for firefox: since too much of the web is too
> bright for my taste, I invert the colors of the firefox window via an
> effect of the window manager, and a css rule inverts the colors of the
> images elements.
>
> I’m not sure how color inversion is done in llpp, and if you rely on
> some sort of backend I guess it is not possible.
> As for the two solutions I was proposing, I meant that one can try to
> be smart and always render embedded images without inversion at the
> expense of pdf files consisting mainly of images. Or the simple
> solution of adding a keybinding, but since you didn’t see what I meant
> I guess users could be confused too. Still the second option seems
> best to me.
>
> I hope I made myself a bit clearer. It seems to be a simple issue to
> me but again I do not remember an application proposing it.
>

Yes, sure. Hear you loud and clear:

a. Inversion is done at the most inappropriate place for your case, it's
   done via GL manipulation, i.e. it just puts rendered page on the
   screen with some magic that manipulates the color

b. Have you tried pressing [ and ]? This changes the brightness (once
   again via GL so images will be affected too)

c. I would suggest asking mupdf people if what you want is possible with
   vanilla mupdf(the application) currently (or in principle) (that is
   if page dimming('[' ']') does not fit your needs), if it is possible
   then certainly code can be added to do the same thing with llpp

-- 
mailto:moosotc@gmail.com

**Comment by Idlusen** [comment]
Yes I know about the brightness setting and I must say color inversion looks far better to me, so I will look on the mupdf side, but I have to mention: wouldn’t it be possible to process the embedded images as with my firefox example, where the images are inverted *back* to natural?

**Comment by moosotc** [comment]
Idlusen <notifications@github.com> writes:

> Yes I know about the brightness setting and I must say color inversion
> looks far better to me, so I will look on the mupdf side, but I have
> to mention: wouldn’t it be possible to process the embedded images as
> with my firefox example, where the images are inverted *back* to
> natural?
>

I have no clue where images are, a pet peeve of mine (what's under
identification doesn't identify images), so can not fix it, but in
general it is ofcourse doable. Just need to figure out how to identify
image data inside the page...

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
It's been nearly a year. And I still haven't done this, out of ideas how to handle all corner cases (two images blended together etc). So closing, sorry.
