### ISSUE TITLE
Error compiling on Debian

### ISSUE THREAD

**Issue by adeel** [moosotc/llpp#24]
Trying to compile on Debian, everything goes fine until:

```
$ sh build.sh build
+ ocamlc.opt -ccopt  -Wno-pointer-sign -O2 -o build/lablGL/ml_raw.o -c ./lablGL/ml_raw.c
+ ocamlc.opt -ccopt  -Wno-pointer-sign -O2 -o build/lablGL/ml_gl.o -c ./lablGL/ml_gl.c
+ ocamlc.opt -ccopt  -Wno-pointer-sign -O2 -o build/lablGL/ml_glarray.o -c ./lablGL/ml_glarray.c
+ ocamlc.opt -ccopt -I ./mupdf/include -I ./mupdf/thirdparty/freetype/include -Wextra -Wall -Werror -D_GNU_SOURCE -O -g -std=c99 -pedantic-errors -Wunused-parameter -Wsign-compare -Wshadow -o build/link.o -c ./link.c
+ /bin/sh ./mkhelp.sh ./KEYS v22-113-g71f6a1d
File "(stdin)", line 2, characters 21-22:
Error: Syntax error
```

The version I am trying to build is git commit 71f6a1dd53214e5881ff56ff6ad291d8bc52fc6f.

**Comment by moosotc** [comment]
Adeel Khan <notifications@github.com> writes:

> Trying to compile on Debian, everything goes fine until:
>
> ```
> $ sh build.sh build
> + ocamlc.opt -ccopt -Wno-pointer-sign -O2 -o build/lablGL/ml_raw.o -c
> ./lablGL/ml_raw.c
> + ocamlc.opt -ccopt -Wno-pointer-sign -O2 -o build/lablGL/ml_gl.o -c
> ./lablGL/ml_gl.c
> + ocamlc.opt -ccopt -Wno-pointer-sign -O2 -o build/lablGL/ml_glarray.o
> -c ./lablGL/ml_glarray.c
> + ocamlc.opt -ccopt -I ./mupdf/include -I
> ./mupdf/thirdparty/freetype/include -Wextra -Wall -Werror
> -D_GNU_SOURCE -O -g -std=c99 -pedantic-errors -Wunused-parameter
> -Wsign-compare -Wshadow -o build/link.o -c ./link.c
> + /bin/sh ./mkhelp.sh ./KEYS v22-113-g71f6a1d
> File "(stdin)", line 2, characters 21-22:
> Error: Syntax error
> ```

I would guess that your ocaml is too old, line 2 contains quoted string,
and according to ocaml refman those were introduced in version 4.02.

Given that quoted strings are used in quite a few places, other than
auxiliary mkhelp script, upgrade is necessary.

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by adeel** [comment]
You were right, thanks!  I installed OCaml 4.02 (following the instructions [here](http://software.opensuse.org/download.html?project=home%3Aocaml&package=ocaml)) and it's working now.
