### ISSUE TITLE
new user impressions

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#27]
hi, just some feedback from a new user of llpp (tried on the new os-x port)

shortcuts: j/k and g/G seem to be vim-inspired? as a vim user, i was expecting/hoping to see navigation shortcuts that are generally somewhat consistent with vim. in particular, i would have loved to see h/l for left/right (yes that would mean changing 'help'). also, g would then be gg (but i guess no harm there since pressing it twice would to nothing) similarly, navigating back from links would be ctrl-[. one could go all-out by allowing to jump to the next/previous block by } and {, and i'm sure there are a few more. not sure if this is desired though

block mode: this seems a cool feature. however i could not easily find out how to get out of a zoomed-block view back to where i was before? backspace did not do it. also alt-left seemed not doing it? this may be the mac version.

escape: i feel it's too easy to leave the application by pressing esc once. i use esc to get out of help but i often ended up quitting and having to relaunch. maybe only q or Q?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> hi, just some feedback from a new user of llpp (tried on the new os-x port)
>
> shortcuts: j/k and g/G seem to be vim-inspired? as a vim user, i was
> expecting/hoping to see navigation shortcuts that are generally
> somewhat consistent with vim. in particular, i would have loved to see
> h/l for left/right (yes that would mean changing 'help'). also, g
> would then be gg (but i guess no harm there since pressing it twice
> would to nothing) similarly, navigating back from links would be
> ctrl-[. one could go all-out by allowing to jump to the next/previous
> block by } and {, and i'm sure there are a few more. not sure if this
> is desired though
>

You can somewhat customize keyboard bindings:

http://repo.or.cz/llpp.git/blob/029aba29f38804a76d27d48245f282cf2ebfb09e:/misc/keys.txt

This will out of the box suppress 'esc' behavior that you hate so much.

> block mode: this seems a cool feature. however i could not easily find
> out how to get out of a zoomed-block view back to where i was before?
> backspace did not do it. also alt-left seemed not doing it? this may
> be the mac version.

Ctrl-0 will, almost, do tha I suppose.

>
> escape: i feel it's too easy to leave the application by pressing esc
> once. i use esc to get out of help but i often ended up quitting and
> having to relaunch. maybe only q or Q?
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/moosotc/llpp/issues/27

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
thanks. 

> This will out of the box suppress 'esc' behavior that you hate so much.

actually in my case this is aggravated by the fact that pressing and releasing ctrl on my computer also sends esc. (long story) for most people it's probably not as bad

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> hi, just some feedback from a new user of llpp (tried on the new os-x port)
>
> shortcuts: j/k and g/G seem to be vim-inspired? as a vim user, i was
> expecting/hoping to see navigation shortcuts that are generally
> somewhat consistent with vim. in particular, i would have loved to see
> h/l for left/right (yes that would mean changing 'help'). also, g
> would then be gg (but i guess no harm there since pressing it twice
> would to nothing) similarly, navigating back from links would be
> ctrl-[. one could go all-out by allowing to jump to the next/previous
> block by } and {, and i'm sure there are a few more. not sure if this
> is desired though
>
> block mode: this seems a cool feature. however i could not easily find
> out how to get out of a zoomed-block view back to where i was before?
> backspace did not do it. also alt-left seemed not doing it? this may
> be the mac version.
>
> escape: i feel it's too easy to leave the application by pressing esc
> once. i use esc to get out of help but i often ended up quitting and
> having to relaunch. maybe only q or Q?

https://wiki.archlinux.org/index.php/Llpp points to this
https://gist.github.com/Earnestly/7608794


-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
> http://repo.or.cz/llpp.git/blob/029aba29f38804a76d27d48245f282cf2ebfb09e:/misc/keys.txt This will out of the box suppress 'esc' behavior that you hate so much.

i have that file in misc/. what do i need to do with it to make it effective?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

>>
> http://repo.or.cz/llpp.git/blob/029aba29f38804a76d27d48245f282cf2ebfb09e:/misc/keys.txt
> This will out of the box suppress 'esc' behavior that you hate so
> much.
>
> i have that file in misc/. what do i need to do with it to make it effective?
>

It's explained here: https://wiki.archlinux.org/index.php/Llpp

-- 
mailto:moosotc@gmail.com
