### ISSUE TITLE
screen centering when searching

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#28]
it would be nice to get a few lines of context above the focused search result instead of having it at the very very top.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> it would be nice to get a few lines of context above the focused
> search result instead of having it at the very very top.
>

That's a bit harder than one would like, so no promises here.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
just to be clear, i did not mean actual lines but just a bit of space, say, 5% of the screen at the current zoom level

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> just to be clear, i did not mean actual lines but just a bit of space,
> say, 5% of the screen at the current zoom level
>

Just to put it into perspective, next searches will keep finding the
same thing over and over again, due to the naive way things are
implemented (i.e. search starts from the first visible thing on the
screen (almost))

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ah ok, i see.
