### ISSUE TITLE
trimming uniformly

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#29]
the trimming feature `-T` works great for increasing the size of the text on screen while keeping the whole page. i have a feature suggestion. it would be even nicer if all pages in a document could be trimmed by the exact same margins -- this gives a nicer look on screen. in order to do that and avoid cutting off text, one would take the union of the non-trimmed rectangles of all pages as the new trimming area. this will not give good results for all documents, so this would probably need to be an optional global trimming mode in addition to the per-page trimming as done currently.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> the trimming feature `-T` works great for increasing the size of the
> text on screen while keeping the whole page. i have a feature
> suggestion. it would be even nicer if all pages in a document could be
> trimmed by the exact same margins -- this gives a nicer look on
> screen. in order to do that and avoid cutting off text, one would take
> the union of the non-trimmed rectangles of all pages as the new
> trimming area. this will not give good results for all documents, so
> this would probably need to be an optional global trimming mode in
> addition to the per-page trimming as done currently.
>

Let me see if we are on the same page - would this be equivalent to
finding the page with the smallest margins and using this page area
(sans margins) as an ideal page size for all of them?

Thing is this wont work in general... (Consider documents where some
pages are in landscape while others in portrait mode)

All that said if an answer to the question in the first paragraph is
yes, then - yeah, that can be done (subject to some knob,
i.e. optionally)

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
> would this be equivalent to finding the page with the smallest margins and using this page area (sans margins) as an ideal page size for all of them?

almost, i think one would need the smallest of each individual margins (top, left, right, bottom).  i agree that it won't work in general; but for many types of documents it would (scientific articles etc). that's why i was proposing to make it optional.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

>> would this be equivalent to finding the page with the smallest
> margins and using this page area (sans margins) as an ideal page size
> for all of them?
>
> almost, i think one would need the smallest of each individual margins
> (top, left, right, bottom).  i agree that it won't work in general;
> but for many types of documents it would (scientific articles
> etc). that's why i was proposing to make it optional.
>

I know how to do it, but alas can not force myself to write any code for
it, all that comes to mind is inelegant, so this would have to wait for
sudden hit of inspiration, sorry. :(

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok. it's more of a nitpick anyways.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok. it's more of a nitpick anyways.
>

Would be nice if you could provide a link to the document where this
"problem" is evident, so if I, or somebody else, would be hit by
inspiration to implement things the testbed would be readily available.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok. it's more of a nitpick anyways.

Btw. have you tried setting fit model to 'width'? Page heights will be
different but at least widths will be the same.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
since this is not trivial to fix by adjusting the trimming, i'm going to describe the exact feature that i would find most useful.

instead of trimming, one leaves all pages at their original size. the user finds a viewport (i.e. a zoom level plus location of an anchor point of the page on the window) that maximizes her reading comfort by ommiting irrelevant header/footer information. she can then lock this viewport. from now on, scrolling is disabled and only page-flipping is allowed, which restores the same viewport for each page visited. potentially, block zooming could be still allowed. at anytime she can unlock the viewport again.

so, this relatively basic feature would be 'lock viewport' with a corresponding shortcut key.

so, the feature would be

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> since this is not trivial to fix by adjusting the trimming, i'm going
> to describe the exact feature that i would find most useful.
>
> instead of trimming, one leaves all pages at their original size. the
> user finds a viewport (i.e. a zoom level plus location of an anchor
> point of the page on the window) that maximizes her reading comfort by
> ommiting irrelevant header/footer information. she can then lock this
> viewport. from now on, scrolling is disabled and only page-flipping is
> allowed, which restores the same viewport for each page
> visited. potentially, block zooming could be still allowed. at anytime
> she can unlock the viewport again.
>
> so, this relatively basic feature would be 'lock viewport' with a
> corresponding shortcut key.
>
> so, the feature would be

Doesn't 'P' do this already?

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
i don't think so. when i select a zoomed-in viewport, press `P` and then press space, the view does not jump to the same viewport on the next page but somewhere between. maybe it jumps forward by one screenful?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i don't think so. when i select a zoomed-in viewport, press `P` and
> then press space, the view does not jump to the same viewport on the
> next page but somewhere between. maybe it jumps forward by one
> screenful?

Space jumps to the next page. Once again I urge you to provide a link to
some document (and perhaps detailed description of what you do, what the
results are and what results are actually wanted (down to current
keypresses))

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok i'll try. 

full page 1:

![screen shot 2016-07-14 at 11 13 59](https://cloud.githubusercontent.com/assets/177614/16834456/22310bd4-49b4-11e6-8c88-23acf8dc742e.png)

zoom it to maximize effective resolution:

![screen shot 2016-07-14 at 11 15 28](https://cloud.githubusercontent.com/assets/177614/16834490/48ed708c-49b4-11e6-8677-04719e62a355.png)

not press `P`. then press space. result:

![screen shot 2016-07-14 at 11 16 07](https://cloud.githubusercontent.com/assets/177614/16834509/6b6e4226-49b4-11e6-9023-6c5e58c0f3d0.png)

expected/desired result:

![screen shot 2016-07-14 at 11 17 17](https://cloud.githubusercontent.com/assets/177614/16834532/8a6797ea-49b4-11e6-9151-6bf4900e26d3.png)

you can try this with any pdf.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok i'll try. 
>
> full page 1:
>
> ![screen shot 2016-07-14 at 11 13
> 59](https://cloud.githubusercontent.com/assets/177614/16834456/22310bd4-49b4-11e6-8c88-23acf8dc742e.png)
>
> zoom it to maximize effective resolution:
>
> ![screen shot 2016-07-14 at 11 15
> 28](https://cloud.githubusercontent.com/assets/177614/16834490/48ed708c-49b4-11e6-8677-04719e62a355.png)
>
> not press `P`. then press space. result:
>
> ![screen shot 2016-07-14 at 11 16
> 07](https://cloud.githubusercontent.com/assets/177614/16834509/6b6e4226-49b4-11e6-9023-6c5e58c0f3d0.png)
>
> expected/desired result:
>
> ![screen shot 2016-07-14 at 11 17
> 17](https://cloud.githubusercontent.com/assets/177614/16834532/8a6797ea-49b4-11e6-9151-6bf4900e26d3.png)
>
> you can try this with any pdf. 
>

Okay. I think I've got what you want, and this is "almost" the same
result that you get when trimming, so question is - what exactly is
wrong when this document was opened, trimmed, fit model set to page and
trim fuzz to -10/-10/10/10?

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok i'll try. 
>

Also, so that my understanding of the "locked viewport" is correct does
following hack (only works for 'space' nagivation more or less) does
what you need?

diff --git a/main.ml b/main.ml
index 928e0fb..a44266e 100644
--- a/main.ml
+++ b/main.ml
@@ -4622,8 +4622,10 @@ let nextpage () =
             let y = clamp (pgscale state.winh) in
             gotoghyll y
           else
+            let curpagey = getpagey l.pageno in
+            let dy = state.y - curpagey in
             let pageno = min (l.pageno+1) (state.pagecount-1) in
-            gotoghyll (getpagey pageno)
+            gotoghyll (getpagey pageno + dy)
       | Cmulti ((c, _, _) as cl, _) ->
           if conf.presentation
             && (existsinrow l.pageno cl


-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
> what exactly is wrong when this document was opened, trimmed, fit model set to page and trim fuzz to -10/-10/10/10?

ok i tried this. i didn't know about the fuzz option. this is good because it avoids the text touching the border. overall it does almost all i wanted. what i still like more about my proposed feature is:
- no variability in size between pages
- one can choose to zoom in farther so that e.g. page numbers get cut away deliberately
- no trimming of the left/right borders
- potentially easier to use?

how do i need to apply the patch above if i want to try it?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

>> what exactly is wrong when this document was opened, trimmed, fit
> model set to page and trim fuzz to -10/-10/10/10?
>
> ok i tried this. i didn't know about the fuzz option. this is good
> because it avoids the text touching the border. overall it does almost
> all i wanted. what i still like more about my proposed feature is:
> - no variability in size between pages

I was thinking about this, but couldn't figure out a way to do it with
minimal effort, will think so more...

> - one can choose to zoom in farther so that e.g. page numbers get cut
> away deliberately

Hmm..

> - no trimming of the left/right borders

Hmm..

> - potentially easier to use?

Not necessarily easier to implement though.

>
> how do i need to apply the patch above if i want to try it?
>

git apply [path-to-patch]

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
another thought: actually the minimal implementation of the behavior i had in mind would be nothing but just two new movement commands: 

'go to the same viewport on the next/previous page'. 

one might even argue that the next page/previous page motions should default to that behavior, and to get alignment to the top of the screen one would have to use `t`? maybe too much..

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> another thought: actually the minimal implementation of the behavior i
> had in mind would be nothing but just two new movement commands:

The patch I've sent tries to implement this (sortof - what it does is -
it notes how offset of the current top from the page and tries to
preserve this offset while jumping to the next page)

>
> 'go to the same viewport on the next/previous page'. 
>
> one might even argue that the next page/previous page motions should
> default to that behavior, and to get alignment to the top of the
> screen one would have to use `t`? maybe too much..
>

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
i tried to apply it -- i got `fatal: corrupt patch at line 4` . the file i tried to apply had this content:
```
--- a/main.ml
+++ b/main.ml
@@ -4622,8 +4622,10 @@ let nextpage () =
let y = clamp (pgscale state.winh) in
gotoghyll y
else
+ let curpagey = getpagey l.pageno in
+ let dy = state.y - curpagey in
let pageno = min (l.pageno+1) (state.pagecount-1) in
- gotoghyll (getpagey pageno)
+ gotoghyll (getpagey pageno + dy)
| Cmulti ((c, _, _) as cl, _) ->
if conf.presentation
&& (existsinrow l.pageno cl
```

?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i tried to apply it -- i got `fatal: corrupt patch at line 4` . the
> file i tried to apply had this content:
> ```
> --- a/main.ml
> +++ b/main.ml
> @@ -4622,8 +4622,10 @@ let nextpage () =
> let y = clamp (pgscale state.winh) in
> gotoghyll y
> else
> + let curpagey = getpagey l.pageno in
> + let dy = state.y - curpagey in
> let pageno = min (l.pageno+1) (state.pagecount-1) in
> - gotoghyll (getpagey pageno)
> + gotoghyll (getpagey pageno + dy)
> | Cmulti ((c, _, _) as cl, _) ->
> if conf.presentation
> && (existsinrow l.pageno cl
> ```

This is whitespace damaged byond repair. I'm attaching the same thing so
that c&p or however you've created the file wouldn't affect things.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
thanks, i got an .eml file as an attachment but it looks the same as what i copy-and-pasted including line breaks? for reference, i copy-pasted this:

```
index 928e0fb..a44266e 100644
--- a/main.ml
+++ b/main.ml
@@ -4622,8 +4622,10 @@ let nextpage () =
let y = clamp (pgscale state.winh) in
gotoghyll y
else
+ let curpagey = getpagey l.pageno in
+ let dy = state.y - curpagey in
let pageno = min (l.pageno+1) (state.pagecount-1) in
- gotoghyll (getpagey pageno)
+ gotoghyll (getpagey pageno + dy)
| Cmulti ((c, _, _) as cl, _) ->
if conf.presentation
&& (existsinrow l.pageno cl
```

i'm not sure email attachments work over the github messaging system? it should be possible to attach a .txt file via the web interface though.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> thanks, i got an .eml file as an attachment but it looks the same as
> what i copy-and-pasted including line breaks? for reference, i
> copy-pasted this:

Grrr.. Try this then:

http://boblycat.org/~malc/1234patch.patch

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok, that worked. the forward motion with space is now exactly what i was looking for! works fine also if more than one page is visible.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> ok, that worked. the forward motion with space is now exactly what i
> was looking for! works fine also if more than one page is visible.
>

I'll see if I can plug something like this in somehow.

-- 
mailto:moosotc@gmail.com
