### ISSUE TITLE
Info mode regression

### ISSUE THREAD

**Issue by atmenta** [moosotc/llpp#3]
Hi,

Unless I am mistaken, the https://github.com/moosotc/llpp/commit/c92c03f3716af3c32448d67688b75b922b374578 commit resulted in the loss of some information (e.g. Author, Creator) from `Document` section of the info mode of llpp. Was this change intentional? If not, could you please restore this functionality? I have found it valuable.

Thank you in advance!

Attila

**Comment by moosotc** [comment]
Right you are, thanks for the report, should be fixed now.
