### ISSUE TITLE
feature wish: generated shortcut key table

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#30]
when pressing `h` one gets a legend of the default key maps. it would be nice if that could show the effective key maps instead.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> when pressing `h` one gets a legend of the default key maps. it would
> be nice if that could show the effective key maps instead.

Best thing, in the current scheme of things, that can be done is -
iterate over all "bindings" and add (say) to the help screen.

  User mappings
        h               left
        f               pgdown
        ctrl-u          ctrl-k

Cost/benefit ratio of such a change is not clear to me (I also loathe
the whole key mapping approach that I've taken, but it is what it is)

-- 
mailto:moosotc@gmail.com
