### ISSUE TITLE
config file handling

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#31]
like a number of people, i like to keep my config files in a synchronized directory and then symlink them to ~. this allows me to use several computers with the same setup. i was not able to make this work with llpp since the config file is rewritten by the program. is there a way to include a user-preference file somewhere in the config file, which does then not get overwritten?

**Comment by moosotc** [comment]
You either:

a. Want the symlink target to be overwritten when updating the config
b. Something else

a. can be done with a little bit of code
b. the whole semantics has to be specified (I do not use things like that so am in no position of
     creating the spec myself)

**Comment by nilsbecker** [comment]
i'm not sure if i follow a. what i would want is some way to share configuration between computers. since llpp rewrites the config file, this would mean that on each run of llpp, the newly rewritten config file would have to be re-synced. 

typically, syncable files are in a dedicated directory (Dropbox etc), so this would either to instruct llpp to read and write the config file to/from a specified non-standard location, or to use the symlink variant and somehow follow the symlink and update the file (is this what you mean by a?) both seem in principle doable.

an alternative would be to define a new 'include' directive that can be used in the ~/.config/llpp.conf file, which would be preserved on rewriting it, and which would allow one to specify a location for textual inclusion. this would then point to the synced file with shared customizations. 

for me any of these options would work. although following up the symlink and modifying its target seems a bit fishy maybe?

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i'm not sure if i follow a. what i would want is some way to share
> configuration between computers. since llpp rewrites the config file,
> this would mean that on each run of llpp, the newly rewritten config
> file would have to be re-synced.
>
> typically, syncable files are in a dedicated directory (Dropbox etc),
> so this would either to instruct llpp to read and write the config
> file to/from a specified non-standard location, or to use the symlink
> variant and somehow follow the symlink and update the file (is this
> what you mean by a?) both seem in principle doable.
>
> an alternative would be to define a new 'include' directive that can
> be used in the ~/.config/llpp.conf file, which would be preserved on
> rewriting it, and which would allow one to specify a location for
> textual inclusion. this would then point to the synced file with
> shared customizations.
>
> for me any of these options would work. although following up the
> symlink and modifying its target seems a bit fishy maybe?
>

Thank you. I'll meditate on the inclusion machinery.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> i'm not sure if i follow a. what i would want is some way to share
> configuration between computers. since llpp rewrites the config file,
> this would mean that on each run of llpp, the newly rewritten config
> file would have to be re-synced.
>
> typically, syncable files are in a dedicated directory (Dropbox etc),
> so this would either to instruct llpp to read and write the config
> file to/from a specified non-standard location, or to use the symlink
> variant and somehow follow the symlink and update the file (is this
> what you mean by a?) both seem in principle doable.

BTW (given that (very quick) meditation on the include, raises some hard
questions) what prevents you from running `llpp -c /path/to/the/config'
(inside a wrapper script maybe)?

#!/bin/sh
exec llpp -c /syncable/dir/llpp.conf "$@"

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
maybe that's just the simplest solution! will try it out soon.

**Comment by nilsbecker** [comment]
this seems to work. it may not be the most elegant since the config file is now synced on every run of llpp but i guess that's not a problem.

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> this seems to work. it may not be the most elegant since the config
> file is now synced on every run of llpp but i guess that's not a
> problem.
>

It would have synced every time either way, since the time of last
visit of the document is recorded.

-- 
mailto:moosotc@gmail.com
