### ISSUE TITLE
Horizontal scrolling in throttle mode

### ISSUE THREAD

**Issue by moosotc** [moosotc/llpp#32]
Current code sets x coordinate in response to user actions followed by gotoy family to
perform housekeeping, gotoy however respects maxwait/throttling and will not update
the layout corresponding to new x value leading to endless load/render/tile loops.

**Comment by nojb** [comment]
Is this an issue with the Cocoa code in #scroll ?

**Comment by moosotc** [comment]
Nicolas Ojeda Bar <notifications@github.com> writes:

> Is this an issue with the Cocoa code in #scroll ?
>

It's not specific to Cocoa in any shape or form. That said Cocoa is also
affected (#scroll follows the lead and sets state.x explicitly then
calls gotoy_and_clear_text), it's not a life threatening issue (well
depends on the definition), but an ugly reminder that bolting stuff on
to no end without plan and design can and will backfire.

Throttling is not set by default and (as most of things here) is
woefully undocumented. If not for the fact that I've advised Nils to use
it in a public medium I've would have been reluctant to shame myself in
bug-tracker.

-- 
mailto:moosotc@gmail.com
