### ISSUE TITLE
Add Licence file for public domain

### ISSUE THREAD

**Issue by LostArchives** [moosotc/llpp#37]
Hello,
I saw that the licence file for public domain was missing so I suggest to add it if you want :)

**Comment by moosotc** [comment]
Thanks.

I was agreeing with the content of LICENCE file until following:

+distribute this software, either in source code form or as a compiled
+binary, for any purpose, commercial or non-commercial, and by any
+means.

Compiled binary includes various bits of (L)GPLed software making the
combined work fall under GPL. I do not distribute binaries thus making
the point a bit moot. According to http://cr.yp.to/publicdomain.html
what is done currently is quite sufficient (cf. README)
