### ISSUE TITLE
screen centering when zooming with the mouse

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#41]
just updated to the new release. on os x, zooming with pinch gestures works fine. however, when zooming in, also the centering of the page shifts to the side.

i think two behaviors are reasonable
1. the point of the page under the mouse pointer stays the same when zooming
2. the point on the page that is at the center of the viewport stays at the center when zooming

currently, the page is aligned at the top left corner (or something like that) which is not ideal

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> just updated to the new release. on os x, zooming with pinch gestures
> works fine. however, when zooming in, also the centering of the page
> shifts to the side.
>
> i think two behaviors are reasonable
> 1. the point of the page under the mouse pointer stays the same when zooming
> 2. the point on the page that is at the center of the viewport stays
> at the center when zooming
>
> currently, the page is aligned at the top left corner (or something
> like that) which is not ideal

Thanks for heads up, pinch zooming is still not ideal - yeah, but it's
mostly up to Nicolás, I can only do so much (being under linux with a
plain old mouse(mostly keyboard to be perfectly honest)) Nevertheless
I'll probably look at it chance will present itself.

-- 
mailto:moosotc@gmail.com

**Comment by nilsbecker** [comment]
ok! actually i think pinch vs mouse + scroll wheel should behave the same way.

**Comment by nojb** [comment]
Acknowledged, will try to take a look at this soon.
