### ISSUE TITLE
slideshow mode

### ISSUE THREAD

**Issue by dotreloaded** [moosotc/llpp#42]
Thanks for this pdf reader. I know there's an auto-scrolling option but depending on what I'm reading it's either not useful (e.g., if the text is split into two columns) or disorientating and would prefer a slideshow mode. I'm thinking of something like `sxiv` or `feh`'s slideshow mode where the page would stay still then move to the next one after some time, allowing the user to choose that time delay. It could be triggered by a key command like `<num>s` where `num` is the time delay, and `s` could stop and restart it.

**Comment by moosotc** [comment]
dotreloaded <notifications@github.com> writes:

> Thanks for this pdf reader. I know there's an auto-scrolling option
> but depending on what I'm reading it's either not useful (e.g., if the
> text is split into two columns) or disorientating and would prefer a
> slideshow mode. I'm thinking of something like `sxiv` or `feh`'s
> slideshow mode where the page would stay still then move to the next
> one after some time, allowing the user to choose that time delay. It
> could be triggered by a key command like `<num>s` where `num` is the
> time delay, and `s` could stop and restart it.

With the following hack you can type:
-A-3a

'A' will set auto scroll step to '-3' (this will be interpreted as
number of seconds between transitions) and 'a' will enable auto
scrolling, so in effect the page will advance every three seconds. The
process can be toggled as usual - i.e. by typing 'a'.

Is that what you are after?

diff --git a/main.ml b/main.ml
index 9342cda..b75590f 100644
--- a/main.ml
+++ b/main.ml
@@ -1895,7 +1895,7 @@ let search pattern forward =
 let [@warning "-4"] intentry text key =
   let text =
     match key with
-    | Keys.Ascii ('0'..'9' as c) -> addchar text c
+    | Keys.Ascii (('0'..'9' | '-') as c) -> addchar text c
     | _ ->
        state.text <- "invalid key";
        text
@@ -6532,7 +6532,7 @@ let () =
          if state.ghyll == noghyll
          then
            match state.autoscroll with
-           | Some step when step != 0 ->
+           | Some step when step > 0 ->
               let y = state.y + step in
               let fy = if conf.maxhfit then state.winh else 0 in
               let y =
@@ -6544,6 +6544,9 @@ let () =
               then gotoxy_and_clear_text state.x y
               else gotoxy state.x y;
               deadline +. 0.01
+           | Some step when step < 0 ->
+              nextpage ();
+              deadline -. float step
            | _ -> infinity
          else deadline +. 0.01
        in

-- 
mailto:moosotc@gmail.com

**Comment by dotreloaded** [comment]
Yes, this is the idea I had in mind, thank you for this.

**Comment by moosotc** [comment]
dotreloaded <notifications@github.com> writes:

> Yes, this is the idea I had in mind, thank you for this.

Slightly different aproach.

diff --git a/KEYS b/KEYS
index f8fcbd5..3056a5b 100644
--- a/KEYS
+++ b/KEYS
@@ -22,7 +22,6 @@ t                       - align top of the screen with the top of the page
 <,>                     - rotate
 Ctrl-pageup/pagedown    - align top of the screen with first/last visible page
 F                       - go to hinted link
-a                       - autoscroll
 if auto scrolling is active:
     up/down arrows and mouse buttons 3/4 will make scrolling go faster/slower
 
@@ -95,6 +94,10 @@ h,F1                    - switch to help mode
 i                       - switch to info mode
 P                       - switch to "presentation" mode
 c                       - switch to previous column layout
+a                       - auto scroll mode
+S                       - slide show mode
+  (auto scroll step is interepreted as a delay (in seconds) between transitions)
+                          
 
 -----Tunables-----
 -i                      - toggle case sensitivity of searches
diff --git a/config.ml b/config.ml
index f1466c1..2780fe1 100644
--- a/config.ml
+++ b/config.ml
@@ -441,6 +441,7 @@ type state =
   ; mutable traw          : [`float] Raw.t
   ; mutable vraw          : [`float] Raw.t
   ; mutable lnava         : (pageno * linkno) option
+  ; mutable slideshow     : int
   }
  and hists =
    { pat : string circbuf
@@ -718,6 +719,7 @@ let state =
   ; traw          = Raw.create_static `float ~len:8
   ; vraw          = Raw.create_static `float ~len:8
   ; lnava         = None
+  ; slideshow     = 0
   }
 ;;
 
diff --git a/main.ml b/main.ml
index 53faee4..7d5faae 100644
--- a/main.ml
+++ b/main.ml
@@ -4680,6 +4680,13 @@ let viewkeyboard key mask =
   let ctrl = Wsi.withctrl mask in
   let open Keys in
   match Wsi.kc2kt key with
+  | Ascii 'S' ->
+     state.slideshow <- (state.slideshow lxor 1) lxor (state.slideshow land 2);
+     state.autoscroll <-
+       if state.slideshow land 1 = 1
+       then Some conf.autoscrollstep
+       else None
+
   | Ascii 'Q' -> exit 0
 
   | Ascii 'W' ->
@@ -6536,17 +6543,25 @@ let () =
          then
            match state.autoscroll with
            | Some step when step != 0 ->
-              let y = state.y + step in
-              let fy = if conf.maxhfit then state.winh else 0 in
-              let y =
-                if y < 0
-                then state.maxy - fy
-                else if y >= state.maxy - fy then 0 else y
-              in
-              if state.mode = View
-              then gotoxy_and_clear_text state.x y
-              else gotoxy state.x y;
-              deadline +. 0.01
+              if state.slideshow land 1 = 1
+              then (
+                if state.slideshow land 2 = 0
+                then state.slideshow <- state.slideshow lor 2
+                else if step < 0 then prevpage () else nextpage ();
+                deadline +. (float (abs step))
+              )
+              else
+                let y = state.y + step in
+                let fy = if conf.maxhfit then state.winh else 0 in
+                let y =
+                  if y < 0
+                  then state.maxy - fy
+                  else if y >= state.maxy - fy then 0 else y
+                in
+                if state.mode = View
+                then gotoxy_and_clear_text state.x y
+                else gotoxy state.x y;
+                deadline +. 0.01
            | _ -> infinity
          else deadline +. 0.01
        in

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Done in 886dd6c0cf25ee9affb41c4c6393e685b9560f08
