### ISSUE TITLE
Doubled utf8 encoding [Mac OS X]

### ISSUE THREAD

**Issue by 0xE0F** [moosotc/llpp#43]
If path to open file already in utf8 encoding then window title, history and status messages are in incorrect encoding due to unconditional conversion in main.ml.

For instance if one took this file:
[航空.pdf](https://github.com/moosotc/llpp/files/792084/default.pdf)
It would be something like this:
<img width="673" alt="encoding" src="https://cloud.githubusercontent.com/assets/426428/23194952/5264180e-f905-11e6-9c00-cdf41ef9e51a.png">

I did very little research and printed out args in hex:
arg 1: /Users/denisbarakhtanov/Downloads/Ëà™Á©∫.jpg [hex: 2f 55 73 65 72 73 2f 64 65 6e 69 73 62 61 72 61 6b 68 74 61 6e 6f 76 2f 44 6f 77 6e 6c 6f 61 64 73 2f e8 88 aa e7 a9 ba 2e 6a 70 67 ]

and at setTitle method in main_osx.m:
llpp[34363:3069734] Title to set: llpp èªç©º.jpg [hex: 6c 6c 70 70 20 c3 a8 c2 88 c2 aa c3 a7 c2 a9 c2 ba 2e 6a 70 67 ]

So it leads me to [main.ml](https://github.com/moosotc/llpp/blob/master/main.ml#L1092):
`Wsi.settitle ("ll. " ^ (mbtoutf8 (Filename.basename titlepath)));`

Clearly, when I removed `mbtoutf8 ` it worked just fine for the title.
So, there are several places where similar conversion are happened (like history output).
The question is - what main.ml expects as the input ?
I'm not very good in OCaml, so I didn't look at the linux version.

Here's a little patch if someone wants to reproduce it: [diff](https://github.com/moosotc/llpp/files/792138/llpp.txt)

**Comment by moosotc** [comment]
Duke <notifications@github.com> writes:

> If path to open file already in utf8 encoding then window title,
> history and status messages are in incorrect encoding due to
> unconditional conversion in main.ml.
>
> For instance if one took this file:
> [航空.pdf](https://github.com/moosotc/llpp/files/792084/default.pdf)
> It would be something like this:
> <img width="673" alt="encoding"
> src="https://cloud.githubusercontent.com/assets/426428/23194952/5264180e-f905-11e6-9c00-cdf41ef9e51a.png">
>
> I did very little research and printed out args in hex:
> arg 1: /Users/denisbarakhtanov/Downloads/Ëà™Á©∫.jpg [hex: 2f 55 73 65
> 72 73 2f 64 65 6e 69 73 62 61 72 61 6b 68 74 61 6e 6f 76 2f 44 6f 77
> 6e 6c 6f 61 64 73 2f e8 88 aa e7 a9 ba 2e 6a 70 67 ]
>
> and at setTitle method in main_osx.m:
> llpp[34363:3069734] Title to set: llpp èªç©º.jpg [hex: 6c 6c 70 70
> 20 c3 a8 c2 88 c2 aa c3 a7 c2 a9 c2 ba 2e 6a 70 67 ]
>
> So it leads me to
> [main.ml](https://github.com/moosotc/llpp/blob/master/main.ml#L1092):
> `Wsi.settitle ("ll. " ^ (mbtoutf8 (Filename.basename titlepath)));`
>
> Clearly, when I removed `mbtoutf8 ` it worked just fine for the title.
> So, there are several places where similar conversion are happened
> (like history output).
> The question is - what main.ml expects as the input ?
> I'm not very good in OCaml, so I didn't look at the linux version.
>
> Here's a little patch if someone wants to reproduce it:
> [diff](https://github.com/moosotc/llpp/files/792138/llpp.txt)

The problem is specific to macOS, under Linux (at least) with supplied
document things work as expected, the problem under macOS is with
mbstowcs inside somehow not being an identity link.c:mbtoutf8, @nojb any
hints?

-- 
mailto:moosotc@gmail.com

**Comment by nojb** [comment]
Hi @0xE0F, and thanks for the report ! I will take a look and report back here .

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Duke <notifications@github.com> writes:
>
>> If path to open file already in utf8 encoding then window title,
>> history and status messages are in incorrect encoding due to
>> unconditional conversion in main.ml.
>>
>> For instance if one took this file:
>> [航空.pdf](https://github.com/moosotc/llpp/files/792084/default.pdf)

[..snip..]

>
> The problem is specific to macOS, under Linux (at least) with supplied
> document things work as expected, the problem under macOS is with
> mbstowcs inside somehow not being an identity link.c:mbtoutf8, @nojb any
> hints?

I take that back, the attachment was named default.pdf therefore I had
no problems with it, but if `mv default.pdf 航空.pdf' is done before
opening it in llpp I can reproduce (sortof) the problem even on linux,
looking into it.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
``llpp -f "/path/to/Arial Unicode.ttf" 航空.pdf`` works as expected (../mupdf/resources/fonts/droid/DroidSansFallbackFull.ttf or any font with humongous coverage will work too I suppose)

**Comment by nojb** [comment]
OK, just got to work and was going to take a look, but @moosotc has already figured out the issue, great !
