### ISSUE TITLE
Text highlighting

### ISSUE THREAD

**Issue by hamidsafdari** [moosotc/llpp#45]
It would be really nice if the developers of llpp could add highlighting capabilities to it. I love llpp. It's fast, lightweight and easy to use. Most of the stuff sent to me are in pdf form and it kind of sucks to switch between llpp and some other tool like xournal or foxitreader. It would also be nice if the highlighting color and its opacity could be set on the fly. If not, setting it in the configuration would be enough too.

The readme says llpp uses mupdf as its backend. I looked at mupdf's changelog https://mupdf.com/news and they do support highlighting.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> It would be really nice if the developers of llpp could add
> highlighting capabilities to it. I love llpp. It's fast, lightweight
> and easy to use. Most of the stuff sent to me are in pdf form and it
> kind of sucks to switch between llpp and some other tool like xournal
> or foxitreader. It would also be nice if the highlighting color and
> its opacity could be set on the fly. If not, setting it in the
> configuration would be enough too.
>
> The readme says llpp uses mupdf as its backend. I looked at mupdf's
> changelog https://mupdf.com/news and they do support highlighting.

I'm not sure what you mean by text highlighting. Care to provide a link
to a video when the desired functionality is shown or just textual
description of steps and their effects?

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
So I found a youtube video that shows how this is done in Adobe Reader with different colors.
https://www.youtube.com/watch?v=0Y0WYBvXUW0

I also found this wikihow article that shows how it is done in four different pdf readers:
http://www.wikihow.com/Highlight-Text-in-a-PDF-Document

I really wish llpp could highlight lines in pdf documents like the number 4 in the wikihow article linked above. I'm thinking since llpp has a very basic UI (which I love) it could assign different keys to different colors. Like if I press Ctrk+H then I'm in highlight mode and the mouse shows it with a different cursor. Then if I click and drag the mouse on some text it is highlighted with the default color (other pdf readers use yellow by default). Again if I'm in highlight mode (I've already pressed the Ctrl+H shortcut) and I press 1, the highlight color changes to red, 2 changes it to green and so on. After I've highlighted my text by dragging the mouse cursor over it, the cursor can go back to normal mode.

**Comment by hamidsafdari** [comment]
I accidentally closed this issue. Sorry for that.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> So I found a youtube video that shows how this is done in Adobe Reader
> with different colors.
> https://www.youtube.com/watch?v=0Y0WYBvXUW0
>
> I also found this wikihow article that shows how it is done in four
> different pdf readers:
> http://www.wikihow.com/Highlight-Text-in-a-PDF-Document
>
> I really wish llpp could highlight lines in pdf documents like the
> number 4 in the wikihow article linked above. I'm thinking since llpp
> has a very basic UI (which I love) it could assign different keys to
> different colors. Like if I press Ctrk+H then I'm in highlight mode
> and the mouse shows it with a different cursor. Then if I click and
> drag the mouse on some text it is highlighted with the default color
> (other pdf readers use yellow by default). Again if I'm in highlight
> mode (I've already pressed the Ctrl+H shortcut) and I press 1, the
> highlight color changes to red, 2 changes it to green and so on. After
> I've highlighted my text by dragging the mouse cursor over it, the
> cursor can go back to normal mode.

I take it you also want the highlighting to persist, i.e. be saved when
the document is closed (kind of the way annotation support (shift+mouse
button 2 ) is done). That would require cooperation with mupdf and I'm
currently not sure whether the support in mupdf exists or not, have to
check.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Hamid Safdari <notifications@github.com> writes:
>
>> So I found a youtube video that shows how this is done in Adobe Reader
>> with different colors.
>> https://www.youtube.com/watch?v=0Y0WYBvXUW0
>>
>> I also found this wikihow article that shows how it is done in four
>> different pdf readers:
>> http://www.wikihow.com/Highlight-Text-in-a-PDF-Document
>>
>> I really wish llpp could highlight lines in pdf documents like the
>> number 4 in the wikihow article linked above. I'm thinking since llpp
>> has a very basic UI (which I love) it could assign different keys to
>> different colors. Like if I press Ctrk+H then I'm in highlight mode
>> and the mouse shows it with a different cursor. Then if I click and
>> drag the mouse on some text it is highlighted with the default color
>> (other pdf readers use yellow by default). Again if I'm in highlight
>> mode (I've already pressed the Ctrl+H shortcut) and I press 1, the
>> highlight color changes to red, 2 changes it to green and so on. After
>> I've highlighted my text by dragging the mouse cursor over it, the
>> cursor can go back to normal mode.
>
> I take it you also want the highlighting to persist, i.e. be saved when
> the document is closed (kind of the way annotation support (shift+mouse
> button 2 ) is done). That would require cooperation with mupdf and I'm
> currently not sure whether the support in mupdf exists or not, have to
> check.

Talked it over with mupdf author, and there is a support for those kind
of annotation of this kind (PDF_ANNOT_HIGHLIGHT), however:

 1. Color is currently hardcoded (one will be able to override it in an
    "autumn release")

 2. Opacity is currently hardcoded and will stay that way.

Other than that the implementation is possible - select text, compute
bounding rectangle, create highlight annotation with specified color,
save the document with updated annotation list (exactly the way it's
done currently for "regular" annotations).

If that's sufficient I can try to implement it eventually.

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
Sufficient? That's awesome.

Thanks a lot.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> Sufficient? That's awesome.
>
> Thanks a lot.

Here's a try, select a rectangle with a mouse holding control and second
mouse button, add annotation text and you should have a highlight
annotation. As with text annotations savepath-command must be set to the
command that will notify llpp where to save the modified document, for
instance savepath-command='echo /tmp/moo.pdf' `echo %s' will save things
back to the original document. As noted earlier, no support for setting
color (yet) or opacity (likely never).

diff --git a/config.ml b/config.ml
index 2780fe1..f6cdd68 100644
--- a/config.ml
+++ b/config.ml
@@ -337,7 +337,7 @@ type mpos = int * int
    | Mpan of mpos
    | Mscrolly | Mscrollx
    | Mzoom of (buttonno * step * mpos)
-   | Mzoomrect of (mpos * mpos)
+   | Mrectact of (mpos * mpos * (mpos * mpos -> unit))
    | Mnone
  and buttonno = int
  and step = int
diff --git a/link.c b/link.c
index cc0bc5d..970fec7 100644
--- a/link.c
+++ b/link.c
@@ -4326,6 +4326,45 @@ CAMLprim void ml_addannot (value ptr_v, value x_v, value y_v,
     CAMLreturn0;
 }
 
+CAMLprim void ml_addhighlightannot (value ptr_v, value rect_v,
+                                    value contents_v)
+{
+    CAMLparam3 (ptr_v, rect_v, contents_v);
+    pdf_document *pdf = pdf_specifics (state.ctx, state.doc);
+
+    if (pdf) {
+        float q[8];
+        pdf_annot *annot;
+        struct page *page;
+        int x0, y0, x1, y1;
+        char *s = String_val (ptr_v);
+
+        page = parse_pointer (__func__, s);
+        annot = pdf_create_annot (state.ctx,
+                                  pdf_page_from_fz_page (state.ctx,
+                                                         page->fzpage),
+                                  PDF_ANNOT_HIGHLIGHT);
+
+        x0 = Int_val (Field (rect_v, 0));
+        y0 = Int_val (Field (rect_v, 1));
+        x1 = Int_val (Field (rect_v, 2));
+        y1 = Int_val (Field (rect_v, 3));
+
+        q[0] = x0;
+        q[1] = y0;
+        q[2] = x1;
+        q[3] = y0;
+        q[4] = x1;
+        q[5] = y1;
+        q[6] = x0;
+        q[7] = y1;
+        pdf_set_annot_quad_points (state.ctx, annot, 1, q);
+        pdf_set_annot_contents (state.ctx, annot, String_val (contents_v));
+        state.dirty = 1;
+    }
+    CAMLreturn0;
+}
+
 CAMLprim void ml_delannot (value ptr_v, value n_v)
 {
     CAMLparam2 (ptr_v, n_v);
diff --git a/main.ml b/main.ml
index 0f5fdef..f05da86 100644
--- a/main.ml
+++ b/main.ml
@@ -41,6 +41,8 @@ external endtiles : unit -> unit = "ml_endtiles";;
 external addannot : opaque -> int -> int -> string -> unit = "ml_addannot";;
 external modannot : opaque -> slinkindex -> string -> unit = "ml_modannot";;
 external delannot : opaque -> slinkindex -> unit = "ml_delannot";;
+external addhighlightannot : opaque -> irect -> string -> unit
+  = "ml_addhighlightannot";;
 external hasunsavedchanges : unit -> bool = "ml_hasunsavedchanges";;
 external savedoc : string -> unit = "ml_savedoc";;
 external getannotcontents : opaque -> slinkindex
@@ -3001,7 +3003,7 @@ object (self)
     | Mpan _
     | Mscrollx
     | Mzoom _
-    | Mzoomrect _
+    | Mrectact _
     | Mnone -> coe self
 
   method pmotion x y =
@@ -4702,7 +4704,7 @@ let viewkeyboard key mask =
 
   | Escape | Ascii 'q' ->
      begin match state.mstate with
-     | Mzoomrect _ ->
+     | Mrectact _ ->
         resetmstate ();
         G.postRedisplay "kill rect";
      | Msel _
@@ -5471,7 +5473,7 @@ let scrollindicator () =
 
 let showsel () =
   match state.mstate with
-  | Mnone | Mscrolly | Mscrollx | Mpan _ | Mzoom _ | Mzoomrect _ ->
+  | Mnone | Mscrolly | Mscrollx | Mpan _ | Mzoom _ | Mrectact _ ->
      ()
 
   | Msel ((x0, y0), (x1, y1)) ->
@@ -5543,7 +5545,7 @@ let display () =
   postloop 0 state.layout;
   state.uioh#display;
   begin match state.mstate with
-  | Mzoomrect ((x0, y0), (x1, y1)) ->
+  | Mrectact ((x0, y0), (x1, y1), _) ->
      Gl.enable `blend;
      GlDraw.color (0.3, 0.3, 0.3) ~alpha:0.5;
      GlFunc.blend_func ~src:`src_alpha ~dst:`one_minus_src_alpha;
@@ -5585,7 +5587,9 @@ let zoomrect x y x1 y1 =
   resetmstate ();
 ;;
 
-let annot inline x y =
+let zoomrect1 ((x0, y0), (x1, y1)) = zoomrect x0 y0 x1 y1;;
+
+let textannot inline x y =
   match unproject x y with
   | Some (opaque, n, ux, uy) ->
      let add text =
@@ -5610,6 +5614,33 @@ let annot inline x y =
   | _ -> ()
 ;;
 
+let highlightannot inline ((x0, y0), (x1, y1)) =
+  match unproject x0 y0, unproject x1 y1 with
+  | Some (opaque1, n, ux0, uy0), Some (opaque2, _, ux1, uy1)
+       when opaque1 = opaque2 ->
+     let add text =
+       addhighlightannot opaque1 (ux0, uy0, ux1, uy1) text;
+       wcmd "freepage %s" (~> opaque1);
+       Hashtbl.remove state.pagemap (n, state.gen);
+       flushtiles ();
+       resetmstate ();
+       gotoxy state.x state.y
+     in
+     if inline
+     then
+       let ondone s = add s in
+       let mode = state.mode in
+       state.mode <- Textentry (
+                         ("annotation: ", E.s, None, textentry, ondone, true),
+                         fun _ -> state.mode <- mode);
+       state.text <- E.s;
+       enttext ();
+       G.postRedisplay "highlightannot"
+     else
+       add @@ getusertext E.s
+  | _ -> ()
+;;
+
 let zoomblock x y =
   let g opaque l px py =
     match rectofblock opaque px py with
@@ -5717,7 +5748,7 @@ let viewmouse button down x y mask =
        | Msel _
        | Mpan _
        | Mscrolly | Mscrollx
-       | Mzoomrect _
+       | Mrectact _
        | Mnone -> state.mstate <- Mzoom (n, 0, (0, 0))
      )
      else (
@@ -5778,22 +5809,26 @@ let viewmouse button down x y mask =
      then (
        if Wsi.withshift mask
        then (
-         annot conf.annotinline x y;
+         textannot conf.annotinline x y;
          G.postRedisplay "addannot"
        )
        else
          let p = (x, y) in
          Wsi.setcursor Wsi.CURSOR_CYCLE;
-         state.mstate <- Mzoomrect (p, p)
+         if Wsi.withctrl mask
+         then
+           state.mstate <- Mrectact (p, p, highlightannot conf.annotinline)
+         else
+           state.mstate <- Mrectact (p, p, zoomrect1)
      )
      else (
        match state.mstate with
-       | Mzoomrect ((x0, y0), _) ->
+       | Mrectact ((x0, y0), _, f) ->
           if abs (x-x0) > 10 && abs (y - y0) > 10
-          then zoomrect x0 y0 x y
+          then f ((x0, y0), (x, y))
           else (
             resetmstate ();
-            G.postRedisplay "kill accidental zoom rect";
+            G.postRedisplay "kill accidental rect";
           )
        | Msel _
        | Mpan _
@@ -5852,8 +5887,8 @@ let viewmouse button down x y mask =
           | Mzoom _ | Mscrollx | Mscrolly ->
              state.mstate <- Mnone
 
-          | Mzoomrect ((x0, y0), _) ->
-             zoomrect x0 y0 x y
+          | Mrectact ((x0, y0), _, f) ->
+             f ((x0, y0), (x, y))
 
           | Mpan _ ->
              Wsi.setcursor Wsi.CURSOR_INHERIT;
@@ -5967,8 +6002,8 @@ let uioh = object
             let x = min state.winw (max 0 x) in
             scrollx x
 
-         | Mzoomrect (p0, _) ->
-            state.mstate <- Mzoomrect (p0, (x, y));
+         | Mrectact (p0, _, f) ->
+            state.mstate <- Mrectact (p0, (x, y), f);
             G.postRedisplay "motion zoomrect";
       end;
       state.uioh
@@ -5998,7 +6033,7 @@ let uioh = object
 
       | LinkNav _ | View ->
          match state.mstate with
-         | Mpan _ | Msel _ | Mzoom _ | Mscrolly | Mscrollx | Mzoomrect _ -> ()
+         | Mpan _ | Msel _ | Mzoom _ | Mscrolly | Mscrollx | Mrectact _ -> ()
          | Mnone ->
             updateunder x y;
             if canselect ()
@@ -6602,6 +6637,8 @@ let () =
   | exception Quit ->
      Config.save leavebirdseye;
      if hasunsavedchanges ()
-     then save ()
+     then save ();
+     let s = Buffer.contents state.errmsgs in
+     if nonemptystr s then prerr_endline s
   | _ -> error "umpossible - infinity reached"
 ;;

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
Could you maybe attach the patch in a file here or mark it as code? I put together the two parts above and git is telling me the patch is corrupt at line 123.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> Could you maybe attach the patch in a file here or mark it as code? I
> put together the two parts above and git is telling me the patch is
> corrupt at line 123.

http://boblycat.org/~malc/anhi.patch

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
So I recursively cloned the repo and applied the patch. I get this error when I try to do `./build.sh build`

```
collect2: error: ld returned 1 exit status
File "_none_", line 1:
Error: Error while building custom runtime system
```
I googled and found out that I should change the order of some libraries but I'm not sure which libraries for llpp. I'm not even sure if it's llpp or the submodules.

I guess I should say that I'm on an Arch Linux.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> So I recursively cloned the repo and applied the patch. I get this
> error when I try to do `./build.sh build`
>
> ```
> collect2: error: ld returned 1 exit status
> File "_none_", line 1:
> Error: Error while building custom runtime system
> ```
> I googled and found out that I should change the order of some
> libraries but I'm not sure which libraries for llpp. I'm not even sure
> if it's llpp or the submodules.
>
> I guess I should say that I'm on an Arch Linux.

I'm on Arch also, and I've never seen the error you cite, llpp itself
doesn't have submodules, mupdf does. Just follow the instructions in
BUILDING file (making sure you have the correct ocaml version) and you
should be good to go.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> So I recursively cloned the repo and applied the patch. I get this
> error when I try to do `./build.sh build`
>
> ```
> collect2: error: ld returned 1 exit status
> File "_none_", line 1:
> Error: Error while building custom runtime system
> ```
> I googled and found out that I should change the order of some
> libraries but I'm not sure which libraries for llpp. I'm not even sure
> if it's llpp or the submodules.
>
> I guess I should say that I'm on an Arch Linux.

FWIW https://github.com/moosotc/llpp/issues/44 has a description how to
manually build things. Though `pacman -Si ocaml' claims that extra has a
proper (i.e. 4.04.0) compiler I have only tried self built one.

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
[out.txt](https://github.com/moosotc/llpp/files/899832/out.txt)

That's what I get when I try to build it.
I'm not good in C to be honest. I just know how to build stuff.

I googled [http://stackoverflow.com/questions/8714155/ftgl-undefined-references-everywere] (might not have found the right thing) and found that I should change the order of the libraries but since it's a custom build, I could say that the libraries are linked at the end of the build.sh file.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> [out.txt](https://github.com/moosotc/llpp/files/899832/out.txt)
>
> That's what I get when I try to build it.
> I'm not good in C to be honest. I just know how to build stuff.
>
> I googled
> [http://stackoverflow.com/questions/8714155/ftgl-undefined-references-everywere]
> (might not have found the right thing) and found that I should change
> the order of the libraries but since it's a custom build, I could say
> that the libraries are linked at the end of the build.sh file.

It appears that you are linking against system supplied libmupdf not the
local checkout as per BUILDING instructions. Try following BUILDING
instructions to the letter and it should work.

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
Tried to build it with shake 
`shake -j0 [build/llpp.native]`
told me `j` is not a valid argument. 

This is what ghc gives me:
```
Shakefile.hs:3:1: error:
    Failed to load interface for ‘Data.List.Extra’
    Use -v to see a list of the files searched for.

Shakefile.hs:6:1: error:
    Failed to load interface for ‘Development.Shake’
    Use -v to see a list of the files searched for.

Shakefile.hs:7:1: error:
    Failed to load interface for ‘Development.Shake.Util’
    Use -v to see a list of the files searched for.

Shakefile.hs:8:1: error:
    Failed to load interface for ‘Development.Shake.Classes’
    Use -v to see a list of the files searched for.

Shakefile.hs:9:1: error:
    Failed to load interface for ‘Development.Shake.FilePath’
    Use -v to see a list of the files searched for.

```

The build file says I should go to llpp/mupdf and do 
`git checkout c6531e339d7a919f2e58b65d08d859e5ac335688` 
which gives me 
`fatal: reference is not a tree: c6531e339d7a919f2e58b65d08d859e5ac335688`

so I skipped that part and did the rest
`git submodule update --recursive` (succeeded silently I guess)
and 
`make build=native libs`
which was a success.

The I ran `sh build.sh build` in the llpp folder again and I got the same error as I was talking about above (in the out.txt) file.

You're saying I'm linking against system libraries. How do I link it against the submodule libraries?

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> Tried to build it with shake 
> `shake -j0 [build/llpp.native]`
> told me `j` is not a valid argument. 
>
> This is what ghc gives me:
> ```
> Shakefile.hs:3:1: error:
>     Failed to load interface for ‘Data.List.Extra’
>     Use -v to see a list of the files searched for.
>
> Shakefile.hs:6:1: error:
>     Failed to load interface for ‘Development.Shake’
>     Use -v to see a list of the files searched for.
>
> Shakefile.hs:7:1: error:
>     Failed to load interface for ‘Development.Shake.Util’
>     Use -v to see a list of the files searched for.
>
> Shakefile.hs:8:1: error:
>     Failed to load interface for ‘Development.Shake.Classes’
>     Use -v to see a list of the files searched for.
>
> Shakefile.hs:9:1: error:
>     Failed to load interface for ‘Development.Shake.FilePath’
>     Use -v to see a list of the files searched for.
>
> ```

The above is why I've to maintain two "build systems" shake and ad-hoc
shell ones... Debugging ghc issues is far beyond my modest abilities.

>
> The build file says I should go to llpp/mupdf and do 
> `git checkout c6531e339d7a919f2e58b65d08d859e5ac335688` 
> which gives me 
> `fatal: reference is not a tree: c6531e339d7a919f2e58b65d08d859e5ac335688`

Before this checkout command do a `git pull' inside llpp/mupdf then
proceed as described. What happened, I suppose, is that you had a
preciously pulled stuff, but long ago for it not to have c6531e339d... commit.
>
> so I skipped that part and did the rest
> `git submodule update --recursive` (succeeded silently I guess)
> and 
> `make build=native libs`
> which was a success.
>
> The I ran `sh build.sh build` in the llpp folder again and I got the
> same error as I was talking about above (in the out.txt) file.
>
> You're saying I'm linking against system libraries. How do I link it
> against the submodule libraries?

Just to clarify the terms, mupdf that you have inside llpp is not a
submodule just a local checkout of mupdf, build.sh should always link
against this local one, but in your case it's out of date. As for system
libraries I've just deduced it from linker error message which
referenced things inside /usr/lib.

If the above suggestion (git pull before git checkout) fails try to
repeat all the steps afresh, i.e. create new prestine directory clone
llpp there and perform all the steps specified in BUILDING.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

Btw. build will fail again write me so we can arrange a live debugging
session on irc or something.

-- 
mailto:moosotc@gmail.com

**Comment by hamidsafdari** [comment]
Actually, doing `git pull` in `llpp/mupdf` did the trick. Everything was OK after that.

**Comment by hamidsafdari** [comment]
About the annotation feature added:

When I draw with over some text by holding the Ctrl key and the right mouse button llpp interrupts (while I'm dragging the mouse) and asks for annotation. Most of the time, I don't even want to input something. I just want to highlight some text. The text itself is the key point in the paragraph that I want to see faster when I come back to that page.

I've noticed that when that part of text is highlighted, I have to do Ctrl+S to save the pdf file. Can this be automated? Although even saving it right now results in llpp saying `don't know where to save the modified document`.

I don't want to be picky but in other PDF viewers that have highlighting capabilities, we select text and then the text is highlighted. I mean, most of the time it doesn't look like a rectangle. If that's too much work then this basic method will do too.

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> About the annotation feature added:
>
> When I draw with over some text by holding the Ctrl key and the right
> mouse button llpp interrupts (while I'm dragging the mouse) and asks
> for annotation. Most of the time, I don't even want to input
> something. I just want to highlight some text. The text itself is the
> key point in the paragraph that I want to see faster when I come back
> to that page.

It "interrupts" once you've finished selecting the rectangle if it
interrupts while you are still dragging that's a bug.

>
> I've noticed that when that part of text is highlighted, I have to do
> Ctrl+S to save the pdf file. Can this be automated? Although even
> saving it right now results in llpp saying `don't know where to save
> the modified document`.
>

There is no Ctrl+S key combination in llpp at all... 'W' (that's capital
W) does the unconditional saving.

You have to set the savepath-command to `echo %s' for instance, the
changes will be saved back to the original file upon exit.

> I don't want to be picky but in other PDF viewers that have
> highlighting capabilities, we select text and then the text is
> highlighted. I mean, most of the time it doesn't look like a
> rectangle. If that's too much work then this basic method will do too.

Highlihgt annotation in PDF work with rectangles this means that what
other PDF viewers probably do is converting the selection into a set of
rectangles and save that, it's doable and not too hard but extremely
boring to implement.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Hamid Safdari <notifications@github.com> writes:

> About the annotation feature added:
>
> When I draw with over some text by holding the Ctrl key and the right
> mouse button llpp interrupts (while I'm dragging the mouse) and asks
> for annotation. Most of the time, I don't even want to input
> something. I just want to highlight some text. The text itself is the
> key point in the paragraph that I want to see faster when I come back
> to that page.
>
> I've noticed that when that part of text is highlighted, I have to do
> Ctrl+S to save the pdf file. Can this be automated? Although even
> saving it right now results in llpp saying `don't know where to save
> the modified document`.
>
> I don't want to be picky but in other PDF viewers that have
> highlighting capabilities, we select text and then the text is
> highlighted. I mean, most of the time it doesn't look like a
> rectangle. If that's too much work then this basic method will do too.

The caption-less version is at:
https://www.boblycat.org/~malc/anhi2.patch

Can't force myself to code anything, so this this version is as good as
it gets until ye olde monster of inspiration possesses me again, sorry.

-- 
mailto:moosotc@gmail.com

**Comment by crocket** [comment]
I would switch from okular to llpp if llpp had a highlighter.

**Comment by moosotc** [comment]
Manoel Vilela <notifications@github.com> writes:

> This was implemented or closed because will not be implemented?

I closed it because no one checked whether the patch [1] does what
was needed.

[1] https://www.boblycat.org/~malc/anhi2.patch

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
20NE <notifications@github.com> writes:

> love llpp, but I need highlight feature badly.
> both anhi.patch and anhi2.patch built failed

It would take some effort to bring anhi2 upto speed with the changes
that went into llpp, and i'm not sure whether the pager is the right
tool for the job or not (maybe a proper editor is in order?)

If history behind anvhi[2] has thought me anything is that some times
people think that they want a feature and then don't even test it.

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
20NE <notifications@github.com> writes:

> With highlight feature, llpp will be perfect for me.
> Thanks for your work.

I can suggest only following:

2819bcd is the revision that anhi1 should apply cleanly against, so you
can try patching that revision and see if it suits your needs or not, if
the answer is "yes" only then I can see about bring things up to date.

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
Looks like nobody tested the patch (anhi2.patch), so I did it. Had to checkout a commit from Apr 2017.

Anyway, the results look great and I can save the annotated file after changing `savepath-command`. However, when I try to open the file in another reader (I tried evince, mupdf, and pdf-tools in emacs), it turned out that mupdf still worked great but the other two rendered a weird hourglass shape (see pic below) in place of the yellow annotation.
![weird_shape_annotation](https://user-images.githubusercontent.com/11328339/51806104-bd3a5b80-22c9-11e9-99e7-d26e192f5daf.png)

I think it's because they both use poppler. I haven't tried adobe on Windows. I guess it would be a no issue if only I read those files, lol, but certainly it'd be great to show others my annotated files.


Test report above. Please feel free to do whatever you want, @moosotc . It's still my favorite pdf reader.

**Comment by moosotc** [comment]
Tor Andersson noted the discrepancy between reality and the specification (cf. http://git.ghostscript.com/?p=mupdf.git;a=blob;f=source/pdf/pdf-appearance.c;h=3cbe2f78506960968dd4f2682d79b2f0cf700c58;hb=HEAD#l374) the anvhi2.patch was prepared before said commit was made, this, I guess, is the reason why you see what you see. "Fixing" it just a question of rearranging the quad points in the patch.

**Comment by JunnanZ** [comment]
Thanks, moosotc.

Whether to resurrect the patch is up to you. Text annotation is the feature I wanted but never really needed. I'm pretty satisfied with the current llpp. If I want to annotate something, I just fire up another application from `Ctrl+p`.

The comment you linked is interesting. It explains the shape but doesn't explain the color.

**Comment by pyDeamon** [comment]
>  I'm pretty satisfied with the current llpp. If I want to annotate something, I just fire up another application from `Ctrl+p`.

@JunnanZ  @moosotc

Regarding that tip. I just  do:
```
path-launcher='evince %s'
```
However, it would be even better if there is a way to pass page number. Like 

```
path-launcher='evince %s -p %d'
```
Is that possible?

**Comment by moosotc** [comment]
"MiKe A." ***@***.***> writes:

>>  I'm pretty satisfied with the current llpp. If I want to annotate something, I just fire up another application from `Ctrl+p`.
>
> @JunnanZ  @moosotc
>
> Regarding that tip. I just  do:
> ```
> path-launcher='evince %s'
> ```
> However, it would be even better if there is a way to pass page number. Like 
>
> ```
> path-launcher='evince %s -p %d'
> ```
> Is that possible?
>

Not right now. For instance: what would be the logic when more than one
page is visible?

**Comment by pyDeamon** [comment]
@moosotc The smallest page number maybe?

**Comment by moosotc** [comment]
"MiKe A." ***@***.***> writes:

> @moosotc The smallest page number maybe?

This simply takes the first page number in the list of "visible" pages,
plus: i have only compile tested it no idea if it really does anything
useful.

https://github.com/moosotc/llpp/issues/45#issuecomment-1028683741diff --git a/help.ml b/help.ml
index 93cd219..b21ae27 100644
--- a/help.ml
+++ b/help.ml
@@ -172,7 +172,7 @@ o Text searching is very naive|}
 open Utils
 
 let gotourl launcher url =
-  let command = Str.global_replace Utils.Re.percent url launcher in
+  let command = Str.global_replace Utils.Re.percents url launcher in
   try ignore @@ spawn command []
   with exn -> dolog "failed to execute `%s': %s" command @@ exntos exn
 
diff --git a/main.ml b/main.ml
index 0618ad0..aacff4c 100644
--- a/main.ml
+++ b/main.ml
@@ -61,7 +61,17 @@ let launchpath () =
   if emptystr conf.pathlauncher
   then adderrmsg "path launcher" "command set"
   else
-    let cmd = Str.global_replace Re.percent !S.path conf.pathlauncher in
+    let n =
+      match !S.layout with
+      | l :: _ -> string_of_int l.pageno
+      | _ -> E.s
+    in
+    let cmd = Str.global_replace Re.percents !S.path conf.pathlauncher in
+    let cmd =
+      if nonemptystr n
+      then Str.global_replace Re.percentp n cmd
+      else cmd
+    in
     match spawn cmd [] with
     | exception exn ->
        adderrfmt "spawn" "failed to execute `%s': %s" cmd @@ exntos exn
@@ -2790,7 +2800,7 @@ let gotounder = function
             "don't know where to save attachment"
      else
        let filename = Ffi.getfileannot opaque slinkindex in
-       let savecmd = Str.global_replace Re.percent filename conf.savecmd in
+       let savecmd = Str.global_replace Re.percents filename conf.savecmd in
        let path =
          getcmdoutput
            (adderrfmt savecmd
@@ -3118,7 +3128,7 @@ let save () =
   then adderrmsg "savepath-command is empty"
          "don't know where to save modified document"
   else
-    let savecmd = Str.global_replace Re.percent !S.path conf.savecmd in
+    let savecmd = Str.global_replace Re.percents !S.path conf.savecmd in
     let path =
       getcmdoutput
         (adderrfmt savecmd "failed to obtain path to the saved copy: %s")
diff --git a/utils.ml b/utils.ml
index 9035a3a..80eccde 100644
--- a/utils.ml
+++ b/utils.ml
@@ -113,7 +113,8 @@ let getenvdef name def =
 
 module Re = struct
   let crlf = Str.regexp "[\r\n]"
-  let percent = Str.regexp "%s"
+  let percents = Str.regexp "%s"
+  let percentp = Str.regexp "%p"
   let whitespace = Str.regexp "[ \t]"
 end
 
diff --git a/utils.mli b/utils.mli
index 24671aa..eddc006 100644
--- a/utils.mli
+++ b/utils.mli
@@ -41,7 +41,8 @@ val getenvdef : string -> string -> string
 module Re :
   sig
     val crlf : Str.regexp
-    val percent : Str.regexp
+    val percents : Str.regexp
+    val percentp : Str.regexp
     val whitespace : Str.regexp
   end
 val addchar : string -> char -> string

**Comment by pyDeamon** [comment]
@moosotc I appreciate your help. I am not familiar with the language at all. 

It would be great if you test it and document it when you have time!

**Comment by moosotc** [comment]
"MiKe A." ***@***.***> writes:

> @moosotc I appreciate your help. I am not familiar with the language at all. 
>
> It would be great if you test it and document it when you have time!
>

After patching the source and setting path-launcher to
 echo 'path "%s" page %p'
 (i.e. path-launcher='echo &apos;path &quot;%s&quot; page %p&apos;' in
  llpp.conf)

pressing 'Ctrl-p' while viewing a document spat:
 "path "/home/malc/x/pdf/pdf_reference_1-7.pdf" page 27"
to the console. Pressing '=' inside this document yields
 "Pages 28,29 of 1310 [2.10%]" in the status line.

**Comment by pyDeamon** [comment]
@moosotc Thanks, but the code is still difficult for me. Do I have to change all files, or only utils.ml?
If there is a fork or commit number it would be easier.

**Comment by moosotc** [comment]
"MiKe A." ***@***.***> writes:

> @moosotc Thanks, but the code is still difficult for me. Do I have to change all files, or only utils.ml?
> If there is a fork or commit number it would be easier.

There isn't. You can follow these instructions though:

1. Read https://github.com/moosotc/llpp/blob/master/BUILDING
2. Navigate to the directory with llpp's sources
3. curl https://tpaste.us/BgZW -o pp.patch
4. patch -i pp.patch
5. bash build.bash build

**Comment by pyDeamon** [comment]
@moosotc  It is working fair enough now. Thanks a lot!
