### ISSUE TITLE
Need to press b twice to toggle scrollbar if vertical-scrollbar-visible is set to false in conf

### ISSUE THREAD

**Issue by dotreloaded** [moosotc/llpp#46]
A very minor bug. If I set vertical-scrollbar-visible to false in my llpp.conf, I have to press `b` twice in order to toggle the scrollbar. Toggle logic must be assuming it starts as visible.

**Comment by moosotc** [comment]
dotreloaded <notifications@github.com> writes:

> A very minor bug. If I set vertical-scrollbar-visible to true in my
> llpp.conf, I have to press `b` twice in order to toggle the
> scrollbar. Toggle logic must be assuming it starts as visible.

I probably don't understand something vertical-scrollbar-visible is
true by default.

The relevant piece of code is:

  | Ascii 'b' ->
     conf.scrollb <- if conf.scrollb = 0 then (scrollbvv lor scrollbhv) else 0;
     G.postRedisplay "toggle scrollbar";

-- 
mailto:moosotc@gmail.com

**Comment by dotreloaded** [comment]
I messed up when I made the issue, I meant to say false.

**Comment by moosotc** [comment]
Please try with a fresh checkout

**Comment by dotreloaded** [comment]
Made a mistake with making this issue... In my llpp.conf, I had `horizontal-scrollbar-visible='true'` and `vertical-scrollbar-visible='false'`, so it wasn't a bug, only hiding the horizontal scrollbar that I forgot about and couldn't see because I usually don't have my stuff zoomed in so much. It's a little strange to have one action to toggle both that makes sure they both have the same visibility state but two separate startup options for visibility. Is anyone so picky about scrollbars that they'd want to have only visible? I don't think it's a big deal anyway, I'll close this.

**Comment by moosotc** [comment]
dotreloaded <notifications@github.com> writes:

> Made a mistake with making this issue... In my llpp.conf, I had
> `horizontal-scrollbar-visible='true'` and
> `vertical-scrollbar-visible='false'`, so it wasn't a bug, only hiding
> the horizontal scrollbar that I forgot about and couldn't see because
> I usually don't have my stuff zoomed in so much. It's a little strange
> to have one action to toggle both that makes sure they both have the
> same visibility state but two separate startup options for
> visibility. Is anyone so picky about scrollbars that they'd want to
> have only visible? I don't think it's a big deal anyway, I'll close
> this.

One has to allot two keys for both scrollbars visibility toggling, I
don't know which one to choose. It wouldn't have been a problem if the
approach to keyboard handling wasn't so ad-hoc, but things are what they
are sadly, IOW - technically it's not a problem at all.

-- 
mailto:moosotc@gmail.com
