### ISSUE TITLE
Make it possible to delete llpp bookmarks.

### ISSUE THREAD

**Issue by crocket** [moosotc/llpp#47]
Currently, there is no way to delete llpp bookmarks in llpp.
I often add and delete bookmarks for my workflow.

**Comment by Docbroke** [comment]
How about opening llpp.conf and editing bookmarks. Thought it would be much better to do through the running application.

**Comment by Ristovski** [comment]
Any news on this?

**Comment by moosotc** [comment]
Rafael Ristovski <notifications@github.com> writes:

> Any news on this?

I forgot about it. Will take a look soonish.

**Comment by moosotc** [comment]
Rafael Ristovski <notifications@github.com> writes:

> Any news on this?

Here's the mock-up (with known issues). Ctrl-delete to remove bookmark.

diff --git a/main.ml b/main.ml
index 7e2d4c9..97c9254 100644
--- a/main.ml
+++ b/main.ml
@@ -1975,7 +1975,9 @@ class outlinelistview ~zebra ~source =
          let first = max 0 (active - fstate.maxrows) in
          postRedisplay "outline end";
          coe {< m_active = active; m_first = first >}
-
+      | Delete when ctrl ->
+         source#delactive m_active;
+         coe self
       | Delete|Escape|Insert|Enter|Ascii _|Code _|Ctrl _|Backspace|Fn _ ->
          super#key key mask
   end;;
@@ -3137,6 +3139,21 @@ class outlinesoucebase fetchoutlines = object (self)
     let active = self#calcactive anchor in
     m_active <- active;
     m_first <- firstof m_first active
+
+  method delactive active =
+    let items =
+      let rec fold i accu =
+        if i = -1
+        then accu
+        else
+          let accu = if i = active then accu else m_items.(i) :: accu in
+          fold (pred i) accu
+      in
+      fold (Array.length m_items - 1) []
+    in
+    self#reset state.anchor @@ Array.of_list items;
+    state.bookmarks <- items;
+    postRedisplay "deletion"
 end
 ;;
