### ISSUE TITLE
Portable bookmarks

### ISSUE THREAD

**Issue by crocket** [moosotc/llpp#48]
Currently, bookmarks are lost when a PDF file is renamed or moved to a new directory or a new system.

To make bookmarks portable, there are at least a few solutions to immobile bookmark problem.

1. Embed llpp bookmarks into PDF metadata? I don't know if PDF has metadata.
2. Bundle llpp bookmarks and a PDF file into a bundle file
3. Implement highlight annotator.  Show list of annotations by scanning each page of a PDF file. Categorize annotations by page number. Make it easy to save annotations into PDF file.

**Comment by moosotc** [comment]
1. Yes it does
2. Not quite sure what you mean by that
3. If by highlight annotator you mean rectangle annotation it's doable.
    Scanning would be sort of expensive for largeish and/or complex documents.
    Not sure what you mean by making it easy.

Anyway it took me 4 months to reply to this issue the fact that leads me to conclude that I won't be doing that myself, and given that there's no-one else to do that - it won't be done atl all :( Sorry for both

I doubt that those are hard things to do, it's just that I lack motivation, sorry once again.

Closing

**Comment by crocket** [comment]
How can I make llpp embed bookmarks into PDF and retrieve them from PDF?

**Comment by moosotc** [comment]
crocket <notifications@github.com> writes:

> How can I make llpp embed bookmarks into PDF and retrieve them from PDF?

You can't, not at the moment at least. I believe, though not 100% sure,
that PDF has some (outline like) support for this, whether it's true or
not is a question better answered by the people who are more intimately
familiar with the format, such as the folks on irc.freenode.net #mupdf
channel.

-- 
mailto:moosotc@gmail.com
