### ISSUE TITLE
Terminates on numpad key press

### ISSUE THREAD

**Issue by mpoquet** [moosotc/llpp#49]
Hello,

llpp terminates when I press any numeric key from my numeric keypad (0,1,...,9) with the following error:
```
Fatal error: exception Invalid_argument("Char.chr")
```
I do not think that this is desired, as pressing unbound classical keys does not cause termination.

I'm using a french azerty keyboard (image below).
![azerty keyboard layout](https://upload.wikimedia.org/wikipedia/commons/c/ca/Azerty_fr.svg)

**Comment by moosotc** [comment]
mpoquet <notifications@github.com> writes:

> Hello,
>
> llpp terminates when I press any numeric key from my numeric keypad
> (0,1,...,9) with the following error:
> ```
> Fatal error: exception Invalid_argument("Char.chr")
> ```
> I do not think that this is desired, as pressing unbound classical
> keys does not cause termination.
>
> I'm using a french azerty keyboard (image below).
> ![azerty keyboard
> layout](https://upload.wikimedia.org/wikipedia/commons/c/ca/Azerty_fr.svg)

Thanks for the report, the problem is real and should be solved now by
the latest commit.

-- 
mailto:moosotc@gmail.com

**Comment by mpoquet** [comment]
Everything seems fine on a3e6ad6, thanks for the quick fix. :)
