### ISSUE TITLE
Fatal error: exception Invalid_argument("Char.chr")

### ISSUE THREAD

**Issue by nemoload** [moosotc/llpp#50]
I usually write the page's number to get to it but when I do that from the numeric keypad llpp crashes with this error message `Fatal error: exception Invalid_argument("Char.chr")`
This is the name and the code of the number one key in my keypad `keycode 87 (keysym 0xffb1, KP_1)`

**Comment by moosotc** [comment]
Ahmed Khaled <notifications@github.com> writes:

> I usually write the page's number to get to it but when I do that from
> the numeric keypad llpp crashes with this error message `Fatal error:
> exception Invalid_argument("Char.chr")`
> This is the name and the code of the number one key in my keypad
> `keycode 87 (keysym 0xffb1, KP_1)`

This should have been fixed in a3e6ad6451cb9ef6c538d643eabc00443aeb0461
What commit are you on?

-- 
mailto:moosotc@gmail.com
