### ISSUE TITLE
Wayland backend

### ISSUE THREAD

**Issue by moosotc** [moosotc/llpp#52]
SDL2 (supports wayland) backend could be done with relative ease (SDL1 experiment was done a couple of years ago, don't remember where the code for it ended up)

**Comment by moosotc** [comment]
Nah

**Comment by freed00m** [comment]
@moosotc nah? like llpp will never have native wayland support?

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> @moosotc nah? like llpp will never have native wayland support? 

'nah' as in - i wont be the one doing it.

-- 
mailto:moosotc@gmail.com
