### ISSUE TITLE
There is a way to reload a already opened PDF?

### ISSUE THREAD

**Issue by ryukinix** [moosotc/llpp#56]
I'm export LaTeX pdfs and need to open and close is painful, I just not find yet a way to reload the current pdf from the filesystem. Probably is possible, but I didn't found how I can do that.

Well, anyway, there is a way?

**Comment by ryukinix** [comment]
Sorry, I was using a weird and old version. 

Is just press `r` ou call `reload`.

**Comment by moosotc** [comment]
There's https://github.com/moosotc/llpp/blob/master/misc/llpp.inotify which was contributed by a TeX user to reload the document automatically whenever it changes.

**Comment by ryukinix** [comment]
Thanks!
