### ISSUE TITLE
Wrong page numbers with "=" in multi-column view

### ISSUE THREAD

**Issue by bonidydy** [moosotc/llpp#57]
In multi-column view the page numbers of pages visible on screen reported with "=" are wrong. The function counts properly all pages of the preceding visible rows and only first page of the last row.  If only one row is visible (which is also the last row) it counts only the first page. So for example in two-column view with 4 first pages on the screen it reports that pages 1 to 3 are visible. If only the first two pages are visible it reports only page 1. The same behaviour is reproducible for more columns.

**Comment by moosotc** [comment]
bonidydy <notifications@github.com> writes:

> In multi-column view the page numbers of pages visible on screen
> reported with "=" are wrong. The function counts properly all pages of
> the preceding visible rows and only first page of the last row.  If
> only one row is visible (which is also the last row) it counts only
> the first page. So for example in two-column view with 4 first pages
> on the screen it reports that pages 1 to 3 are visible. If only the
> first two pages are visible it reports only page 1. The same behaviour
> is reproducible for more columns.

Thanks for heads up. The location description indeed does not properly
take multi-column mode into account. Does the following work for you?

diff --git a/main.ml b/main.ml
index eb13a41..81cbbf1 100644
--- a/main.ml
+++ b/main.ml
@@ -3317,8 +3317,11 @@ let setcheckers enabled =
 ;;
 
 let describe_location () =
-  let fn = page_of_y state.y in
-  let ln = page_of_y (state.y + state.winh - 1) in
+  let layout = layout state.x state.y state.winw state.winh in
+  let fn, ln = List.fold_left (fun (fn, ln) l ->
+                   min l.pageno fn, max l.pageno ln
+                 ) (max_int, min_int) layout
+  in
   let maxy = maxy () in
   let percent =
     if maxy <= 0

-- 
mailto:moosotc@gmail.com
