### ISSUE TITLE
Resolution change causes llpp to crash

### ISSUE THREAD

**Issue by sealj553** [moosotc/llpp#58]
I use a laptop and switch between the built-in screen and external monitors when I'm at my desk. I run a script that uses xrandr to change my screen settings. When I have llpp open and switch between monitors, it appears to crash. It only shows the background color and will not respond to any input. I cannot close the window, I have to use pkill to close it.

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> I use a laptop and switch between the built-in screen and external
> monitors when I'm at my desk. I run a script that uses xrandr to
> change my screen settings. When I have llpp open and switch between
> monitors, it appears to crash. It only shows the background color and
> will not respond to any input. I cannot close the window, I have to
> use pkill to close it.

Hmm, I only have one monitor, so it would be a bit hard for me to
reproduce it, do you simply use something like: `xrandr --output DP2' to
"switch monitors"?

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> I use a laptop and switch between the built-in screen and external
> monitors when I'm at my desk. I run a script that uses xrandr to
> change my screen settings. When I have llpp open and switch between
> monitors, it appears to crash. It only shows the background color and
> will not respond to any input. I cannot close the window, I have to
> use pkill to close it.

Need precise reproduction steps. Dusted off an old CRT monitor but naive
first try attempt to hit the problem was unsuccessfull.

-- 
mailto:moosotc@gmail.com

**Comment by sealj553** [comment]
Thanks for the reply.
It happens when going from laptop to external or vice versa.
Going from laptop to external in my script, I use:
```
laptop="LVDS1"
monitor1="DP3"
monitor2="HDMI2"
...
xrandr --output $laptop --off
xrandr --output $monitor1 --mode 1920x1080 --rate 144.00 --primary
xrandr --output $monitor2 --mode 1920x1080 --right-of $monitor1
```
and going external to laptop:
```
xrandr --output $monitor1 --off
xrandr --output $monitor2 --off
xrandr --output $laptop --mode 1600x900 --primary
```
I just tested it again to make sure and had the same result. I've added a screenshot of the window.
![12-07-02 40 25-screenshot](https://user-images.githubusercontent.com/8863960/33704166-58fdc620-daf9-11e7-8abe-3ace80e85046.png)

**Comment by sealj553** [comment]
I think I know what's causing it. I have my compositor disabled (I usually use compton) because it was causing me some trouble. I just started it and was unable to reproduce the problem again.

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> Thanks for the reply.
> It happens when going from laptop to external or vice versa.
> Going from laptop to external in my script, I use:
> ```
> laptop="LVDS1"
> monitor1="DP3"
> monitor2="HDMI2"
> ...
> xrandr --output $laptop --off
> xrandr --output $monitor1 --mode 1920x1080 --rate 144.00 --primary
> xrandr --output $monitor2 --mode 1920x1080 --right-of $monitor1
> ```
> and going external to laptop:
> ```
> xrandr --output $monitor1 --off
> xrandr --output $monitor2 --off
> xrandr --output $laptop --mode 1600x900 --primary
> ```
> I just tested it again to make sure and had the same result. I've
> added a screenshot of the window.
> ![12-07-02 40
> 25-screenshot](https://user-images.githubusercontent.com/8863960/33704166-58fdc620-daf9-11e7-8abe-3ace80e85046.png)

So you have three monitors. I am so far unable to reproduce this with
just two and playing some xrandr games. Does this happen with just two
on your end?

To solve this I will need a way to reproduce it here or get more
information from you. I'll be on irc.freenode.net #3monissue, please
contact me there or reply here that you are unable to, thanks.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> I think I know what's causing it. I have my compositor disabled (I
> usually use compton) because it was causing me some trouble. I just
> started it and was unable to reproduce the problem again.

I'm not using any compositor either... This is puzzling.

-- 
mailto:moosotc@gmail.com

**Comment by sealj553** [comment]
I was just testing it with only two monitors, and I think I have another clue. It only freezes when all outputs are disabled at some point.
When I switch from monitor A to B by turning A off, then turning on B -> crash
But when I switch from A to B by keeping A on, turning B on, then turning A off, it's fine

My script does it the first way because my graphics card doesn't support the resolution of all 3 monitors at once.

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> I was just testing it with only two monitors, and I think I have
> another clue. It only freezes when all outputs are disabled at some
> point.
> When I switch from monitor A to B by turning A off, then turning on B -> crash
> But when I switch from A to B by keeping A on, turning B on, then
> turning A off, it's fine
>
> My script does it the first way because my graphics card doesn't
> support the resolution of all 3 monitors at once.

Suppose you start with only one monitor enabled if you xrandr --off it
and then xrandr --auto it, does llpp stop accepting input?

-- 
mailto:moosotc@gmail.com

**Comment by sealj553** [comment]
Correct. Just tried it a few times, the last time took two tries for it to "crash".

**Comment by moosotc** [comment]
Jackson Seal <notifications@github.com> writes:

> Correct. Just tried it a few times, the last time took two tries for
> it to "crash".

Take-aways:

a. I can't reproduce it here
b. Multiple monitors is a red-herring
c. Not entirely clearly what compositing manager has to do with it
d. Best bet is to discuss it on irc, when at least semi real-time
   debugging would be possible

-- 
mailto:moosotc@gmail.com

**Comment by sealj553** [comment]
Alright, I'll be available to join you on irc sometime within a day or two.
Thanks for the help.
