### ISSUE TITLE
Zooming is backwards

### ISSUE THREAD

**Issue by legendre6891** [moosotc/llpp#60]
After yesterday's commit `0f57b48a6aa59287e0a167d3610a070261f4c0f4`, scrolling with the mousewheel is reversed: a scroll up event now causes the page to zoom *out* instead of *in*, unlike most other applications (e.g. Firefox, Chromium, other PDF viewers). Likewise, scrolling down is a zoom-in instead of a zoom-out.

**Comment by moosotc** [comment]
Kevin Li <notifications@github.com> writes:

> After yesterday's commit `0f57b48a6aa59287e0a167d3610a070261f4c0f4`,
> scrolling with the mousewheel is reversed: a scroll up event now
> causes the page to zoom *out* instead of *in*, unlike most other
> applications (e.g. Firefox, Chromium, other PDF viewers). Likewise,
> scrolling down is a zoom-in instead of a zoom-out.

After 0f57b48a6aa59287e0a167d3610a070261f4c0f4 fiasco I'm reluctant to
close things myself, please do so if things are fixed by
c6547926989b0435397ccaa6fb0d90f27dbfe2b5, thanks.

-- 
mailto:moosotc@gmail.com

**Comment by legendre6891** [comment]
Thanks! It's fixed now.
