### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#62]
The only color customization that I can find in the config file is background color. Is it possible to change other colors like scroll bar and status bar?

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> The only color customization that I can find in the config file is
> background color. Is it possible to change other colors like scroll
> bar and status bar?

Not currently, nobody ever needed this. Relatively straightforward but
will require some amount of quite boring code.

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
Understand. Thank you.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Understand. Thank you.

Thing is, it will require 3 config knobs (colors of scollbar, scollbar
handle and status bar) not the end of the world but tedious to write :(

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
No worries. Just leave it here. 

Btw, great pdf reader! The best I can find regarding speed and usability.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> No worries. Just leave it here. 
>
> Btw, great pdf reader! The best I can find regarding speed and usability. 

Thanks for kind words, I'm also of the opinion that it's kind of neat.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> No worries. Just leave it here. 

Implemented it, but not sure if I want to commit +47 lines or not, but
at least you can give it a try and decide whether it's worth it or not
or not.

>
> Btw, great pdf reader! The best I can find regarding speed and usability. 

diff --git a/config.ml b/config.ml
index 407b937..edb9c6c 100644
--- a/config.ml
+++ b/config.ml
@@ -248,7 +248,9 @@ type conf =
   ; mutable sliceheight    : sliceheight
   ; mutable thumbw         : width
   ; mutable jumpback       : bool
-  ; mutable bgcolor        : (float * float * float)
+  ; mutable bgcolor        : rgb
+  ; mutable sbarcolor      : rgba
+  ; mutable sbarhndlcolor  : rgba
   ; mutable bedefault      : bool
   ; mutable tilew          : int
   ; mutable tileh          : int
@@ -299,6 +301,8 @@ type conf =
    | Ohistory of (filename * conf * outline list * x * anchor * filename)
  and outline = (caption * outlinelevel * outlinekind)
  and outlinelevel = int
+ and rgb = (float * float * float)
+ and rgba = (float * float * float * float)
 ;;
 
 type page =
@@ -521,6 +525,8 @@ let defconf =
   ; thumbw         = 76
   ; jumpback       = true
   ; bgcolor        = (0.5, 0.5, 0.5)
+  ; sbarcolor      = (0.64, 0.64, 0.64, 0.7)
+  ; sbarhndlcolor  = (0.0, 0.0, 0.0, 0.7)
   ; bedefault      = false
   ; tilew          = 2048
   ; tileh          = 2048
@@ -1040,6 +1046,8 @@ let config_of c attrs =
       | "thumbnail-width" -> { c with thumbw = max 2 (int_of_string v) }
       | "persistent-location" -> { c with jumpback = bool_of_string v }
       | "background-color" -> { c with bgcolor = color_of_string v }
+      | "scrollbar-color" -> { c with sbarcolor = rgba_of_string v }
+      | "scrollbar-handle-color" -> { c with sbarhndlcolor = rgba_of_string v }
       | "tile-width" -> { c with tilew = max 2 (int_of_string v) }
       | "tile-height" -> { c with tileh = max 2 (int_of_string v) }
       | "mupdf-store-size" ->
@@ -1220,6 +1228,8 @@ let setconf dst src =
   dst.coarseprespos  <- src.coarseprespos;
   dst.css            <- src.css;
   dst.usedoccss      <- src.usedoccss;
+  dst.sbarcolor      <- src.sbarcolor;
+  dst.sbarhndlcolor  <- src.sbarhndlcolor;
   dst.pax            <-
     if src.pax = None
     then None
@@ -1549,6 +1559,7 @@ let add_attrs bb always dc c time =
   and oF s a b = o (always || a <> b) "%s='%f'" s a
   and oL s a b = o (always || a <> b) "%s='%Ld'" s a
   and oc s a b = o (always || a <> b) "%s='%s'" s (color_to_string a)
+  and oA s a b = o (always || a <> b) "%s='%s'" s (rgba_to_string a)
   and oC s a b = o (always || a <> b) "%s='%s'" s (CSTE.to_string a)
   and oR s a b = o (always || a <> b) "%s='%s'" s (irect_to_string a)
   and oFm s a b = o (always || a <> b) "%s='%s'" s (FMTE.to_string a)
@@ -1620,6 +1631,8 @@ let add_attrs bb always dc c time =
   oi "thumbnail-width" c.thumbw dc.thumbw;
   ob "persistent-location" c.jumpback dc.jumpback;
   oc "background-color" c.bgcolor dc.bgcolor;
+  oA "scrollbar-color" c.sbarcolor dc.sbarcolor;
+  oA "scrollbar-handle-color" c.sbarhndlcolor dc.sbarhndlcolor;
   oi "tile-width" c.tilew dc.tilew;
   oi "tile-height" c.tileh dc.tileh;
   oI "mupdf-store-size" c.mustoresize dc.mustoresize;
diff --git a/main.ml b/main.ml
index 3164af7..782d17b 100644
--- a/main.ml
+++ b/main.ml
@@ -3611,6 +3611,18 @@ let enterinfomode =
                        Printf.sprintf "bad color `%s': %s" v @@ exntos exn
                  )
     in
+    let rgba name get set =
+      src#string name
+                 (fun () -> rgba_to_string (get ()))
+                 (fun v ->
+                   try
+                     let c = rgba_of_string v in
+                     set c
+                   with exn ->
+                     state.text <-
+                       Printf.sprintf "bad color `%s': %s" v @@ exntos exn
+                 )
+    in
     let oldmode = state.mode in
     let birdseye = isbirdseye state.mode in
 
@@ -3860,6 +3872,12 @@ let enterinfomode =
       colorp "background color"
              (fun () -> conf.bgcolor)
              (fun v -> conf.bgcolor <- v; setbgcol v);
+      rgba "scrollbar color"
+           (fun () -> conf.sbarcolor)
+           (fun v -> conf.sbarcolor <- v);
+      rgba "scrollbar handle color"
+           (fun () -> conf.sbarhndlcolor)
+           (fun v -> conf.sbarhndlcolor <- v);
       src#bool "crop hack"
                (fun () -> conf.crophack)
                (fun v -> conf.crophack <- v);
@@ -5465,13 +5483,14 @@ let scrollindicator () =
 
   Gl.enable `blend;
   GlFunc.blend_func ~src:`src_alpha ~dst:`one_minus_src_alpha;
-  GlDraw.color (0.64, 0.64, 0.64) ~alpha:0.7;
+  let (r, g, b, alpha) = conf.sbarcolor in
+  GlDraw.color (r, g, b) ~alpha;
   filledrect (float x0) 0. (float x1) (float state.winh);
   filledrect
     (float hx0) (float (state.winh - sbh))
-    (float (hx0 + state.winw)) (float state.winh)
-  ;
-    GlDraw.color (0.0, 0.0, 0.0) ~alpha:0.7;
+    (float (hx0 + state.winw)) (float state.winh);
+  let (r, g, b, alpha) = conf.sbarhndlcolor in
+  GlDraw.color (r, g, b) ~alpha;
 
   filledrect (float x0) ph (float x1) (ph +. sh);
   let pw = pw +. float hx0 in
diff --git a/utils.ml b/utils.ml
index 33f1390..30964f7 100644
--- a/utils.ml
+++ b/utils.ml
@@ -121,6 +121,13 @@ let color_of_string s =
                )
 ;;
 
+let rgba_of_string s =
+  Scanf.sscanf
+    s "%d/%d/%d/%d" (fun r g b a ->
+      (float r /. 255.0, float g /. 255.0, float b /. 255.0, float a /. 255.0)
+    )
+;;
+
 let color_to_string (r, g, b) =
   let r = truncate (r *. 255.0)
   and g = truncate (g *. 255.0)
@@ -128,6 +135,14 @@ let color_to_string (r, g, b) =
   Printf.sprintf "%d/%d/%d" r g b
 ;;
 
+let rgba_to_string (r, g, b, a) =
+  let r = truncate (r *. 255.0)
+  and g = truncate (g *. 255.0)
+  and b = truncate (b *. 255.0)
+  and a = truncate (a *. 255.0) in
+  Printf.sprintf "%d/%d/%d/%d" r g b a
+;;
+
 let abspath path =
   if Filename.is_relative path
   then

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
@moosotc Took me a while to figure out how to apply the patch and build it. It looks great! It's also nice to be able to change the alpha.

Thank you so much for the effort!

**Comment by prosoitos** [comment]
Still on the subject of colors, is it possible to make the darker "mask" less dark when hint is activated?

I am not being very clear here I'm afraid, so here is an example:

If I want to follow a link and type F to activate links, everything gets so dark that is is hard to read anything. It is fine when there are few links, but to select one link in a table of content for instance, it would be easier (at least for me) to be able to read things a little more easily by not having everything get quite so dark.

Is there a way to do this?

Thank you!!!

**Comment by moosotc** [comment]
`diff --git a/genconfstruct.sh b/genconfstruct.sh
index 3ff036a..3c28801 100644
--- a/genconfstruct.sh
+++ b/genconfstruct.sh
@@ -131,6 +131,7 @@ P pax
 g dcf dcf Utils.E.s
 s hcs "{|aoeuidhtns|}"
 b remaphtns false
+f teintensity 0.4
 
 cat <<EOF
 }
diff --git a/main.ml b/main.ml
index 93255d8..eeba778 100644
--- a/main.ml
+++ b/main.ml
@@ -2401,6 +2401,9 @@ let enterinfomode =
         src#string "   scale"
           (fun () -> string_of_float conf.colorscale)
           (fun v -> conf.colorscale <- bound (float_of_string v) 0.0 1.0);
+        src#string "   text entry intensity"
+          (fun () -> string_of_float conf.teintensity)
+          (fun v -> conf.teintensity <- bound (float_of_string v) 0.0 1.0);
       );
     );
 
@@ -3695,7 +3698,7 @@ let birdseyekeyboard key mask
 let drawpage l =
   let color =
     match !S.mode with
-    | Textentry _ -> U.scalecolor 0.4
+    | Textentry _ -> U.scalecolor conf.teintensity
     | LinkNav _ | View -> U.scalecolor 1.0
     | Birdseye (_, _, pageno, hooverpageno, _) ->
        if l.pageno = hooverpageno
`

**Comment by moosotc** [comment]
https://boblycat.org/~malc/scratch/tei.patch adds a configuration parameter that controls brightness when text entry is in effect

**Comment by prosoitos** [comment]
OK. Thank you! I will look into this.
