### ISSUE TITLE
Specifying `synctex-command` in the command prompt

### ISSUE THREAD

**Issue by OVlasiuk** [moosotc/llpp#63]
A feature request: support passing the SyncTeX destination as a command line parameter. 
Currently only done in the .confg file. Would make it possible e.g. to support different Vim servers simultaneously in a plugin like [vimtex](https://github.com/lervag/vimtex).

**Comment by moosotc** [comment]
Oleksandr Vlasiuk <notifications@github.com> writes:

> A feature request: support passing the SyncTeX destination as a
> command line parameter.
> Currently only done in the .confg file. Would make it possible e.g. to
> support different Vim servers simultaneously in a plugin like
> [vimtex](https://github.com/lervag/vimtex).

Are you asking for `llpp -synctex-command ...'? (Not a vim, nor
(sync)tex user myself) What will this option buy you?

Not that this is hard feature to implement it's just that things can get
hairy if the same information can be obtained from multiple sources
(config file, command line).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Oleksandr Vlasiuk <notifications@github.com> writes:

> A feature request: support passing the SyncTeX destination as a
> command line parameter.
> Currently only done in the .confg file. Would make it possible e.g. to
> support different Vim servers simultaneously in a plugin like
> [vimtex](https://github.com/lervag/vimtex).

This was compile tested only... No idea if it works nor if that's what
you wanted.

diff --git a/main.ml b/main.ml
index a752ca4..9ab5f2c 100644
--- a/main.ml
+++ b/main.ml
@@ -6233,6 +6233,7 @@ let () =
   let rootwid = ref 0 in
   let openlast = ref false in
   let doreap = ref false in
+  let stcmd = ref E.s in
   let csspath = ref None in
   selfexec := Sys.executable_name;
   Arg.parse
@@ -6284,6 +6285,8 @@ let () =
 
         ("-embed", Arg.Set_int rootwid, "<window-id> Embed into window");
 
+        ("-stcmd", Arg.Set_string stcmd,
+         "<path-to-synctex> overrides config value");
         ("-origin", Arg.String (fun s -> state.origin <- s),
          "<origin> <undocumented>");
        ]
@@ -6299,6 +6302,9 @@ let () =
   if not (Config.load !openlast)
   then dolog "failed to load configuration";
 
+  if nonemptystr !stcmd
+  then conf.stcmd <- !stcmd;
+
   begin match !pageno with
   | Some pageno -> state.anchor <- (pageno, 0.0, 0.0)
   | None -> ()

-- 
mailto:moosotc@gmail.com

**Comment by OVlasiuk** [comment]
Wow, that was quick! Thanks a lot!

> Are you asking for `llpp -synctex-command ...'?

I am indeed thinking about something like that. 

> What will this option buy you?

Vim would be able to launch multiple instances of llpp with different `--servername`s. Than the reverse search from llpp would bring up the correct file in Vim, even if working on multiple files.
