### ISSUE TITLE
Please add an option to use filename as window title.

### ISSUE THREAD

**Issue by agguser** [moosotc/llpp#65]
Currently, title in pdf metadata, if exists, is used as window title. Is there a way to force using pdf filename as window title? (without modifying pdf metadata)

**Comment by moosotc** [comment]
agguser <notifications@github.com> writes:

> Currently, title in pdf metadata, if exists, is used as window
> title. Is there a way to force using pdf filename as window title?
> (without modifying pdf metadata)

Using filename as a title is easy, adding an option to do that is too,
but I don't want to, there are way too many config and command line
options already. What's the rationale?

diff --git a/main.ml b/main.ml
index c84288b..4f80c11 100644
--- a/main.ml
+++ b/main.ml
@@ -1819,7 +1819,7 @@ let act cmds =
          if c = "Title"
          then (
            conf.title <- v;
-           Wsi.settitle v;
+           (* Wsi.settitle v; *)
            args
          )
          else

-- 
mailto:moosotc@gmail.com

**Comment by agguser** [comment]
The reason is that some pdfs have arbitrary metadata title and character encoding! The title may be  meaningless or even unreadable.

**Comment by moosotc** [comment]
agguser <notifications@github.com> writes:

> The reason is that some pdfs have arbitrary metadata title and
> character encoding! The title may be meaningless or even unreadable.

Point. Do you have an example of such a document?

-- 
mailto:moosotc@gmail.com

**Comment by agguser** [comment]
Try http://www.mcic.or.jp/otayori/download/thai/thai-kotoba.pdf (Its title is "<82B182C682CE8169835E83438CEA816A2E786C73>".)

**Comment by moosotc** [comment]
agguser <notifications@github.com> writes:

> Try http://www.mcic.or.jp/otayori/download/thai/thai-kotoba.pdf (Its
> title is "<82B182C682CE8169835E83438CEA816A2E786C73>".)

There's nothing wrong about that. That ofcourse depends on the
definition of wrong. (Makes me wonder though is <82...> a hex dump of
bytes making a unicode string in some encoding?)

Problem is there are too many ways to achieve what you want:

* command line option
* preferences setting
* hot key to switch/cycle between available sources of title string
* ...

They are in (reverse)order of my preference at this instant.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> agguser <notifications@github.com> writes:
>
>> Try http://www.mcic.or.jp/otayori/download/thai/thai-kotoba.pdf (Its
>> title is "<82B182C682CE8169835E83438CEA816A2E786C73>".)
>
> There's nothing wrong about that. That ofcourse depends on the
> definition of wrong. (Makes me wonder though is <82...> a hex dump of
> bytes making a unicode string in some encoding?)
>
> Problem is there are too many ways to achieve what you want:
>
> * command line option
> * preferences setting
> * hot key to switch/cycle between available sources of title string
> * ...
>
> They are in (reverse)order of my preference at this instant.

The command line way:

diff --git a/main.ml b/main.ml
index c84288b..bc43112 100644
--- a/main.ml
+++ b/main.ml
@@ -57,6 +57,7 @@ external isexternallink : string -> bool = "ml_isexternallink";;
 external copysel : Unix.file_descr -> opaque -> unit = "ml_copysel";;
 
 let selfexec = ref E.s;;
+let ignoredoctitlte = ref false;;
 let opengl_has_pbo = ref false;;
 
 let drawstring size x y s =
@@ -1819,7 +1820,8 @@ let act cmds =
          if c = "Title"
          then (
            conf.title <- v;
-           Wsi.settitle v;
+           if not !ignoredoctitlte
+           then Wsi.settitle v;
            args
          )
          else
@@ -6293,6 +6295,8 @@ let () =
 
         ("-origin", Arg.String (fun s -> state.origin <- s),
          "<origin> <undocumented>");
+
+        ("-no-title", Arg.Set ignoredoctitlte, " ignore document title")
        ]
     )
     (fun s -> state.path <- s)

-- 
mailto:moosotc@gmail.com

**Comment by agguser** [comment]
Either command-line or config file option would be okay; I want to always use filename as title.
By the way, is this "feature" will be included in the master source?

**Comment by moosotc** [comment]
agguser <notifications@github.com> writes:

> Either command-line or config file option would be okay; I want to
> always use filename as title.
> By the way, is this "feature" will be included in the master source?

I don't know.

-- 
mailto:moosotc@gmail.com
