### ISSUE TITLE
Flashing when resizing

### ISSUE THREAD

**Issue by dkasak** [moosotc/llpp#67]
llpp flashes annoyingly when its window is resized, displaying a checkerboard pattern in a fraction of a second before restoring the document. I use a tiling window manager and adjust my window sizes rather frequently so this is fairly distracting.

Is this something that can be solved?

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

> llpp flashes annoyingly when its window is resized, displaying a
> checkerboard pattern in a fraction of a second before restoring the
> document. I use a tiling window manager and adjust my window sizes
> rather frequently so this is fairly distracting.
>
> Is this something that can be solved?

I don't know how to solve it. What happens is:
 a. the window gets resized
 b. the document needs to be rerendered to fill the new area

Question is: what to show while it is rendering? Also there's no
indication how long the rendering will take (think complex/large
document/image)

Even if one takes the contents of the window prior to resize and shows
that there will still be flashing. So I basically don't know how to
handle this "properly", nor what "properly" really implies.

-- 
mailto:moosotc@gmail.com

**Comment by dkasak** [comment]
> Even if one takes the contents of the window prior to resize and shows that there will still be flashing.

I think this might still be the answer. It seems that this is what zathura does and there's no noticeable flickering.

You say that there'd still be flashing, but I think these are two different kinds of flashing. Let's say that `A` is the buffer's contents prior to issuing a command and `A'` is the desired contents once the command is executed and its result rendered.

Currently, what happens is this:

    A -> C -> A'

`C` here is any content that is perceptually unrelated to either `A` or `A'`, e.g. the checkerboard pattern. If llpp rendered in the background, displaying the old contents up until the point that it is ready to switch to `A'`, the situation would be this:

    A -> A'

This still doesn't mean that there would be zero latency between issuing the command and displaying the new state (which is what I understood you meant when you said there'd still be flashing), but this wouldn't be as jarring because there no perceptually unrelated contents would be interposed between the two states.

Of course, in situations where the rendering takes a long time, the lag between the two states would be noticeable. I still think that's better than flashing something completely visually unrelated in each screen update. I noticed from testing that zathura seems to detect when rendering is going to take a while and display and empty page with only "Loading..." displayed on it. Importantly, this doesn't happen for all screen updates, just those whose rendering duration crosses some threshold. However, llpp is so fast in most cases I've seen that this would probably be unnecessary to implement.

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> Even if one takes the contents of the window prior to resize and
> shows that there will still be flashing.
>
> I think this might still be the answer. It seems that this is what
> zathura does and there's no noticeable flickering.

Wonder if you can describe (algorithmically/pseudo-codeish) what all of
this entails, I might implement it (then again I might not)

>
> You say that there'd still be flashing, but I think these are two
> different kinds of flashing. Let's say that `A` is the buffer's
> contents prior to issuing a command and `A'` is the desired contents
> once the command is executed and its result rendered.
>
> Currently, what happens is this:
>
>     A -> C -> A'
>
> `C` here is any content that is perceptually unrelated to either `A`
> or `A'`, e.g. the checkerboard pattern. If llpp rendered in the
> background, displaying the old contents up until the point that it is
> ready to switch to `A'`, the situation would be this:
>
>     A -> A'
>

Sure, but depending on the region it _WOULD_ flash, just picture mostly
uniform white page with, say, green rectangle somewhere and the resizing
that somehow makes this rectangle the only thing that is visible...

> This still doesn't mean that there would be zero latency between
> issuing the command and displaying the new state (which is what I
> understood you meant when you said there'd still be flashing), but
> this wouldn't be as jarring because there no perceptually unrelated
> contents would be interposed between the two states.


As noted above, this depends entirely on the contents of the thing being
rendered.

>
> Of course, in situations where the rendering takes a long time, the
> lag between the two states would be noticeable. I still think that's
> better than flashing something completely visually unrelated in each
> screen update. I noticed from testing that zathura seems to detect
> when rendering is going to take a while and display and empty page
> with only "Loading..." displayed on it. Importantly, this doesn't
> happen for all screen updates, just those whose rendering duration
> crosses some threshold. However, llpp is so fast in most cases I've
> seen that this would probably be unnecessary to implement.

llpp (btw. you can turn checkers off) actually shows a "Loading..."
message too, just open some document and press and hold Ctrl-+ for a
while, should be noticeable.


To reiterate, I don't have clear idea what to do about this thing and in
general the resizing already involves some special code (coalescing of
window size requests springs to mind) and I'm not too thrilled with
adding more nor do I believe that there's a bulletproof way to do it
in the first place.

-- 
mailto:moosotc@gmail.com

**Comment by dkasak** [comment]
> Sure, but depending on the region it _WOULD_ flash, just picture mostly uniform white page with, say, green rectangle somewhere and the resizing that somehow makes this rectangle the only thing that is visible...

Hmm... Can you please describe in more operational terms what exactly would flash in this scenario? It sounds to me like you're describing two states ("all white with a bit of green" and "all green") and a single transition between them. However, that's not what I'm observing with each resize and zoom. I'm seeing three states ("all white with a bit of green", "checkerboard" and "all green") with two transitions in total. This is what is visually jarring and what I was referring to as "flashing".

Maybe we're not seeing the same thing because there's some kind of difference depending on the configuration/environment? I actually tried recording a video of me zooming in/out in the same document in both zathura and llpp, but the visible checkerboard flashing actually isn't noticeable in it (though it was during recording), but that may just be an artifact of the recording method I used.

> To reiterate, I don't have clear idea what to do about this thing and in general the resizing already involves some special code (coalescing of window size requests springs to mind) and I'm not too thrilled with adding more nor do I believe that there's a bulletproof way to do it in the first place.

I understand your reluctance to complicate the code. However, the behaviour I'm seeing is very distracting, not just when resizing but also when zooming (but curiously not so much when switching between pages with `<number>g`), so I'm beginning to suspect we're not seeing exactly the same thing.

**Comment by dkasak** [comment]
Also, I'm not ignoring your request for pseudocode, but I'll need to test some more and understand the problem better to be able to come up with something useful.

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> Sure, but depending on the region it _WOULD_ flash, just picture
>> mostly uniform white page with, say, green rectangle somewhere and
>> the resizing that somehow makes this rectangle the only thing that
>> is visible...
>
> Hmm... Can you please describe in more operational terms what exactly
> would flash in this scenario? It sounds to me like you're describing
> two states ("all white with a bit of green" and "all green") and a
> single transition between them. However, that's not what I'm observing
> with each resize and zoom. I'm seeing three states ("all white with a
> bit of green", "checkerboard" and "all green") with two transitions in

                                                     three surely?

> total. This is what is visually jarring and what I was referring to as
> "flashing".
>
> Maybe we're not seeing the same thing because there's some kind of
> difference depending on the configuration/environment? I actually
> tried recording a video of me zooming in/out in the same document in
> both zathura and llpp, but the visible checkerboard flashing actually
> isn't noticeable in it (though it was during recording), but that may
> just be an artifact of the recording method I used.

My method would have been:

$ ffmpeg -y -s 2560x1440 -framerate 60 -f x11grab -i :0.0 flashing.mp4

>
>> To reiterate, I don't have clear idea what to do about this thing
>> and in general the resizing already involves some special code
>> (coalescing of window size requests springs to mind) and I'm not too
>> thrilled with adding more nor do I believe that there's a
>> bulletproof way to do it in the first place.
>
> I understand your reluctance to complicate the code. However, the
> behaviour I'm seeing is very distracting, not just when resizing but
> also when zooming (but curiously not so much when switching between
> pages with `<number>g`), so I'm beginning to suspect we're not seeing
> exactly the same thing.

I think we are seeing the same thing after all, but it would be nice to
have a confirmation, perhaps the ffmpeg invocation line I've presented
earlier would work in your setup? (-s <your-screen-dimensions-not-mine>)

-- 
mailto:moosotc@gmail.com

**Comment by dkasak** [comment]
> three surely?

Hmm, what do you mean? I'm counting three different states (i.e. pictures), but only two changes between them. Unless you're counting the initial rendering too.

Anyway, [here is the video](https://vimeo.com/253841572). I had to use `-vsync 2` because the flickering wasn't visible otherwise. I also recorded zathura for comparison. The flickering is still even more pronounced and consistent on the screen than in the video, though.

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> three surely?
>
> Hmm, what do you mean? I'm counting three different states
> (i.e. pictures), but only two changes between them. Unless you're
> counting the initial rendering too.

I did.

>
> Anyway, [here is the video](https://vimeo.com/253841572). I had to use
> `-vsync 2` because the flickering wasn't visible otherwise. I also
> recorded zathura for comparison. The flickering is still even more
> pronounced and consistent on the screen than in the video, though.

Okay, this is to be expected and in case of zooming can be rectified by
setting throttle to something (1,2,inf whatever), throttle will do
nothing for geometry changes though.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> three surely?
>
> Hmm, what do you mean? I'm counting three different states
> (i.e. pictures), but only two changes between them. Unless you're
> counting the initial rendering too.
>
> Anyway, [here is the video](https://vimeo.com/253841572). I had to use
> `-vsync 2` because the flickering wasn't visible otherwise. I also
> recorded zathura for comparison. The flickering is still even more
> pronounced and consistent on the screen than in the video, though.

Following is not a fix by any stretch, still I do wonder whether it
improves things for you.

diff --git a/main.ml b/main.ml
index bd23403..24608b4 100644
--- a/main.ml
+++ b/main.ml
@@ -5558,7 +5558,8 @@ let showrects =
 let display () =
   GlDraw.color (scalecolor2 conf.bgcolor);
   GlClear.color (scalecolor2 conf.bgcolor);
-  GlClear.clear [`color];
+  if conf.maxwait = None || state.winw > state.w
+  then GlClear.clear [`color];
   List.iter drawpage state.layout;
   let rects =
     match state.mode with

-- 
mailto:moosotc@gmail.com

**Comment by dkasak** [comment]
It doesn't seem to do anything for me, unfortunately. However, I did notice that the flicker was much better on two particular zoom levels, namely 89 and 99, yet not entirely inexistant; it does happen every several zooms. When zooming between these two levels, the flickering almost never happens (though it still does to a degree). I'm not sure why that would be.

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

> It doesn't seem to do anything for me, unfortunately. However, I did

Was throttling enabled when you tested?

> notice that the flicker was much better on two particular zoom levels,
> namely 89 and 99, yet not entirely inexistant; it does happen every
> several zooms. When zooming between these two levels, the flickering
> almost never happens (though it still does to a degree). I'm not sure
> why that would be.

Me neither unfortunately.

-- 
mailto:moosotc@gmail.com

**Comment by dkasak** [comment]
> Was throttling enabled when you tested?

I tested with both throttling on and off. There doesn't seem to be much difference.

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

> It doesn't seem to do anything for me, unfortunately. However, I did
> notice that the flicker was much better on two particular zoom levels,
> namely 89 and 99, yet not entirely inexistant; it does happen every
> several zooms. When zooming between these two levels, the flickering
> almost never happens (though it still does to a degree). I'm not sure
> why that would be.

FWIW if you are alternating between two zoom levels caching might be the
reason.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> Was throttling enabled when you tested?
>
> I tested with both throttling on and off. There doesn't seem to be
> much difference.

Weird, with following variant and throttling set to inf I get no
flickering when just Ctrl-+ is held...

diff --git a/main.ml b/main.ml
index bd23403..14d604e 100644
--- a/main.ml
+++ b/main.ml
@@ -5608,6 +5608,11 @@ let display () =
   Wsi.swapb ();
 ;;
 
+let display () =
+  if state.layout != []
+  then display ()
+;;
+
 let zoomrect x y x1 y1 =
   let x0 = min x x1
   and x1 = max x x1

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> Was throttling enabled when you tested?
>
> I tested with both throttling on and off. There doesn't seem to be
> much difference.

Note (to my future self at least)

When macos support was added (pinch zooming imlemented)- pivot zoom came
to life, however as part of it's job it has a potential (well obligation
really) to change the position within viewed document (via gotoxy), this
in turn unconditionally (without respecting throttling) schedules a
redisplay, hence "flashing" during zooming. Takeaway - software is not
composable.

A possible fix for that (and resizing the window too) might indeed be
what I've described before i.e. take the contents of the window prior to
resize/zoom and show that instead of checkers/sold-color when drawing
the view, that however has it's own challenges (just dumping the
backbuffer to a texture and presenting that wont cut it (partly due to
UI elements that are part of the backbuffer)).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Denis Kasak <notifications@github.com> writes:

>> Was throttling enabled when you tested?
>
> I tested with both throttling on and off. There doesn't seem to be
> much difference.

After playing with resizing (zooming is another issue altogether) it
became evident that in my setting (mesa,i915,i3 in all floating mode)
flashing is evident when resizing llpp's window even without opened
document. What apparently happens is:

If background pixel is set(for llpp it is) damaged window regions are
filled with background pixel before the application has a chance to draw
these regions itself.

"Showcaser" (for my setup):

for f in $(seq 10 1000); do xdotool search --class llpp windowsize $f $f; done

Setting background color to red (background-color='255/0/0' in
llpp.conf) makes the problem much more noticeable.

Not setting background-pixel at all a'la the patch bellow, removes
flashing for me.

diff --git a/wsi/x11/wsi.ml b/wsi/x11/wsi.ml
index e9b6155..4978c09 100644
--- a/wsi/x11/wsi.ml
+++ b/wsi/x11/wsi.ml
@@ -29,6 +29,7 @@ external glxcompleteinit : unit -> unit = "ml_glxcompleteinit";;
 external swapb : unit -> unit = "ml_swapb";;
 external setcursor : cursor -> unit = "ml_setcursor";;
 external setwinbgcol : int -> unit = "ml_setbgcol";;
+let setwinbgcol _ = if false then setwinbgcol 0xff0000;;
 
 let onot = object
     method display         = ()
@@ -303,7 +304,7 @@ let sendintern sock s onlyifexists f =
 ;;
 
 let createwindowreq wid parent x y w h bw eventmask vid depth mid =
-  let s = makereq 1 48 12 in
+  let s = makereq 1 44 11 in
   w8 s 1 depth;
   w32 s 4 wid;
   w32 s 8 parent;
@@ -314,15 +315,13 @@ let createwindowreq wid parent x y w h bw eventmask vid depth mid =
   w16 s 20 bw;
   w16 s 22 0;                           (* copyfromparent *)
   w32 s 24 vid;                         (* visual *)
-  w32 s 28 0x280a;                      (* valuemask =
-                                         | background pixel
+  w32 s 28 0x2808;                      (* valuemask =
                                          | border pixel
                                          | event mask
                                          | colormap *)
-  w32 s 32 0;                           (* background pixel *)
-  w32 s 36 0;                           (* border pixel*)
-  w32 s 40 eventmask;
-  w32 s 44 mid;
+  w32 s 32 0;                           (* border pixel*)
+  w32 s 36 eventmask;
+  w32 s 40 mid;
   s;
 ;;
 

-- 
mailto:moosotc@gmail.com
