### ISSUE TITLE
Opening the same file twice

### ISSUE THREAD

**Issue by JunnanZ** [moosotc/llpp#68]
Opening the same file twice will generate two llpp instances. Is there a easy way to make llpp aware that the document is already opened and redirect me to that document? For example, evince does this.

**Comment by moosotc** [comment]
Junnan <notifications@github.com> writes:

> Opening the same file twice will generate two llpp instances. Is there
> a easy way to make llpp aware that the document is already opened and
> redirect me to that document? For example, evince does this.

There is no builtin support for that. Following script might work
though. Needs xdotool[1] and fuser part of psmisc[2] to work.

#!/bin/sh
set -e
test -n "$1"
pid=$(fuser "$1" 2>/dev/null) &&
    xdotool search --sync --pid $pid llpp windowactivate ||
    llpp "$*"

[1] http://www.semicomplete.com/projects/xdotool
[2] http://psmisc.sourceforge.net/changelog.html

-- 
mailto:moosotc@gmail.com

**Comment by JunnanZ** [comment]
Thank you. I made a small change to your snippet due to a seemingly bug of `xdotool`.

```
#!/bin/sh
set -e
test -n "$1"
pid=$(fuser "$1" 2>/dev/null) &&
    xdotool search --sync --pid $pid getwindowid windowactivate ||
    llpp "$*"
```
