### ISSUE TITLE
Searching scrolls pdf to the right off the window when the pdf is zoomed in

### ISSUE THREAD

**Issue by adfaure** [moosotc/llpp#71]
Hi, everything is in the title :)
![screenshot from 2018-03-09 11-02-16](https://user-images.githubusercontent.com/8026586/37202114-e5e2e10a-2389-11e8-8c0e-d51ea0bae266.png)

My current version is : 
```
llpp -v                
llpp version unknown, fitz 1.12.0, ocaml 4.05.0/64 bit
configuration path: /home/adfaure/.config/llpp.conf
```

**Comment by moosotc** [comment]
Adrien FAURE <notifications@github.com> writes:

> Hi

This "Hi" is the entire content of the e-mail message with bug
notification. Had to fire up a browser and visit github to see the
picture. And even with picture can't say i understand the problem, can
you, please, provide more details? (Ideally - reproduction scenario with
expected/obtained results)

-- 
mailto:moosotc@gmail.com

**Comment by adfaure** [comment]
Yes, sorry I failed, I fired up my message too soon :)

I am running on archlinux.

The steps to reproduce are:

- Open a pdf
- Zoom in
- Look for a word (/word_to_search)

Llpp performs the search well, but instead of centering the pdf it shifts it to the right.

I use a custom configuration: 
```xml
<llppconfig>
<ui-font size='20'/>
<defaults
    width='1200'
    height='1000'
    scroll-bar-width='12'
    scroll-handle-height='12'
    horizontal-scrollbar-visible='false'
    vertical-scrollbar-visible='true'
    case-insensitive-search='true'
    preload='true'
    page-bias='0'
    scroll-step='24'
    auto-scroll-step='2'
    max-height-fit='true'
    crop-hack='false'
    throttle='false'
    highlight-links='true'
    under-cursor-info='false'
    vertical-margin='2'
    zoom='100'
    presentation='false'
    rotation-angle='0'
    persistent-bookmarks='true'
    fit-model='page'
    pixmap-cache-size='64M'
    tex-count='32'
    slice-height='1024'
    thumbnail-width='76'
    persistent-location='true'
    background-color='0/0/0'
    tile-width='2048'
    tile-height='2048'
    mupdf-store-size='256M'
    checkers='true'
    aalevel='8'
    trim-margins='false'
    trim-fuzz='0/0/0/0'
    uri-launcher='xdg-open &quot;%s&quot;'
    path-launcher='lp &quot;%s&quot;'
    color-space='rgb'
    invert-colors='false'
    brightness='1.000000'
    selection-command='xsel -i'
    synctex-command='echo SyncTex'
    pax-command='cat'
    askpass-command=''
    savepath-command=''
    update-cursor='true'
    hint-font-size='12'
    horizontal-scroll-step='24'
    page-scroll-scale='1.000000'
    use-pbo='true'
    wheel-scrolls-pages='false'
    remote-in-a-new-instance='false'
    point-and-x='false'
    point-and-x-mark='word'
    scroll-bar-on-the-left='false'
    last-visit='-9223372036854775808'
    edit-annotations-inline='true'
    coarse-presentation-positioning='false'
    use-document-css='true'>
<keymap mode='help'>
<map in='q' out='esc'/>
</keymap>
<keymap mode='outline'>
<map in='q' out='esc'/>
</keymap>
<keymap mode='view'>
<map in='tab' out='o'/>
<map in='q' out=''/>
<map in='f2' out='ctrl-3'/>
<map in='f1' out='ctrl-0'/>
<map in='f5' out='P'/>
<map in='pgup' out='del'/>
<map in='esc' out=''/>
<map in='ctrl-pgup' out='del'/>
<map in='pgdown' out='space'/>
<map in='right' out='space'/>
<map in='ctrl-pgdown' out='space'/>
<map in='left' out='del'/>
</keymap>
</defaults>
</llppconfig>
```

**Comment by moosotc** [comment]
Adrien FAURE <notifications@github.com> writes:

> Yes, sorry I failed, I fired up my message too soon :)
>
> I am running on archlinux.
>
> The steps to reproduce are:
>
> - Open a pdf
> - Zoom in
> - Look for a word (/word_to_search)
>
> Llpp performs the search well, but instead of centering the pdf it
> shifts it to the right.

Thank you. Can reproduce it. Will see what can be done.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Adrien FAURE <notifications@github.com> writes:

Does replacing "state.winw/2" with "truncate x0-state.winw/2" at line
1607 in main.ml help?

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by LemonBoy** [comment]
>  Does replacing "state.winw/2" with "truncate x0-state.winw/2" at line 1607 in main.ml help?

Only so slightly, in some edge cases the match is off-screen even with that modification.
