### ISSUE TITLE
zooming on mac

### ISSUE THREAD

**Issue by nilsbecker** [moosotc/llpp#75]
hi, congrats on the new release. i was able to build it successfully on os x 10.12 with ocaml 4.06.1, following the instructions in BUILDING. 

zooming with pinch-zoom using a trackpad on the mac works in general, as well as two-finger scrolling up/down and left/right. (incidentally, ctrl+scroll does not zoom contrary to the help page)

however, when zooming, centering is problematic. my experience is this:

open a document, zoom to fit the page width. now zoom out (away). the document stays centered, and zooms out. fine. 
now zoom back in. until the page width is reached again, everything is fine. zooming even closer, the page moves sideways, out of the field of view. this happens the more drastically, the more off-center the cursor is located. 
in addition, when zooming back out, the document moves away even more, until it is finally reset to center when the page with is reached again.

this behavior happens with all 'fit models'. 

in effect, zooming by trackpad is not really usable. to make it better, zooming should re-center the page continuously so that the fixed point of the zooming operation coincides with the cursor location. at least when the zoom level is closer than a page width; for zooming further away than the page width, auto-centering the page is fine.

**Comment by nilsbecker** [comment]
i should add that a similar undesired shift happens in the up-down direction

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

> hi, congrats on the new release. i was able to build it successfully
> on os x 10.12 with ocaml 4.06.1, following the instructions in
> BUILDING.

Great!

>
> zooming with pinch-zoom using a trackpad on the mac works well in
> general, as well as two-finger scrolling up/down and
> left/right. (incidentally, ctrl+scroll does not zoom contrary to the
> help page)
>
> however, when zooming, centering is problematic. my experience is this:
>
> open a document, zoom to fit the page width. now zoom out (away). the
> document stays centered, and zooms out. fine.
> now zoom in. until the page width is reached again, everything is
> fine. zooming even closer, the page moves sideways, out of the field
> of view. this happens the more drastically, the more off-center the
> cursor is located.
> in addition, when zooming back out, the document moves away even more,
> until it is finally reset to center when the page with is reached
> again.
>
> this behavior happens with all 'fit models'. 
>
> in effect, zooming by trackpad is not really usable. to make it
> better, zooming should re-center the page continuously so that the
> fixed point of the zooming operation coincides with the cursor
> location. at least when the zoom level is closer than a page width;
> for zooming further away than the page width, auto-centering the page
> is fine.

Thank you for the report, step by step reproduction scenario for dummies
(i.e. me) would be great.

I'll into it a bit later, too tired now (lack of sleep).

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
nilsbecker <notifications@github.com> writes:

[..snip..]

> in effect, zooming by trackpad is not really usable. to make it
> better, zooming should re-center the page continuously so that the
> fixed point of the zooming operation coincides with the cursor
> location. at least when the zoom level is closer than a page width;
> for zooming further away than the page width, auto-centering the page
> is fine.

@nojb i can easily reproduce this, care to take a look, my mac foo is
only enough to get the thing to compile :(

-- 
mailto:moosotc@gmail.com

**Comment by nojb** [comment]
Yes, I will take a look as well (and again, apologies for the delay in tacking the bug reports - I have a full plate at work at the moment and very little time left outside of that).

**Comment by moosotc** [comment]
Nicolás Ojeda Bär <notifications@github.com> writes:

> Yes, I will take a look as well (and again, apologies for the delay in
> tacking the bug reports - I have a full plate at work at the moment
> and very little time left outside of that).

No worries... In the mean time build system became even awesomer...

-- 
mailto:moosotc@gmail.com

**Comment by nojb** [comment]
Trying to figure this one out. @moosotc could you please help me understand the meaning of the arguments to `pivotzoom`? (in particular, `x` and `y` are they window coordinates, or "page" coordinates?)
```ocaml
let pivotzoom ?(vw=min state.w state.winw)
              ?(vh=min (state.maxy-state.y) state.winh)
              ?(x=vw/2) ?(y=vh/2) zoom =
  let w = float state.w /. zoom in
  let hw = w /. 2.0 in
  let ratio = float vh /. float vw in
  let hh = hw *. ratio in
  let x0 = float x -. hw
  and y0 = float y -. hh in
  gotoxy (state.x - truncate x0) (state.y + truncate y0);
  setzoom zoom;
;;

let pivotzoom ?vw ?vh ?x ?y zoom =
  if nogeomcmds state.geomcmds
  then
    if zoom > 1.0
    then pivotzoom ?vw ?vh ?x ?y zoom
    else setzoom zoom
;;
```

**Comment by nojb** [comment]
Also, what is the logic behind the condition `zoom > 1.0` ?

**Comment by nojb** [comment]
> in particular, x and y are they window coordinates, or "page" coordinates?

OK, they are window coordinates.

**Comment by moosotc** [comment]
Nicolás Ojeda Bär <notifications@github.com> writes:

> Also, what is the logic behind the condition `zoom > 1.0` ?

If my memory serves me, it's there to make the document centered inside
the view, otherwise zooming is reduced to pivotzoom.

-- 
mailto:moosotc@gmail.com
