### ISSUE TITLE
llpp crashes on key-press

### ISSUE THREAD

**Issue by LemonBoy** [moosotc/llpp#76]
Pressing the WiFi toggle on my laptop triggers this event:

```
KeyPress event, serial 36, synthetic NO, window 0x1a00001,
    root 0x115, subw 0x0, time 211252, (590,607), root:(591,624),
    state 0x0, keycode 255 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

The `keycode 255` part is what makes llpp crash and burn in `getkeysym`

```
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "./wsi/x11/wsi.ml", line 465, characters 13-43
Called from file "./wsi/x11/wsi.ml", line 494, characters 20-39
Called from file "./wsi/x11/wsi.ml", line 659, characters 4-17
Called from file "./main.ml", line 6556, characters 12-27
Called from file "./main.ml", line 6570, characters 7-17
Called from file "./main.ml", line 6584, characters 8-21
```

**Comment by moosotc** [comment]
LemonBoy <notifications@github.com> writes:

> Pressing the WiFi toggle on my laptop triggers this event:
>
> ```
> KeyPress event, serial 36, synthetic NO, window 0x1a00001,
>     root 0x115, subw 0x0, time 211252, (590,607), root:(591,624),
>     state 0x0, keycode 255 (keysym 0x0, NoSymbol), same_screen YES,
>     XLookupString gives 0 bytes: 
>     XmbLookupString gives 0 bytes: 
>     XFilterEvent returns: False
> ```
>
> The `keycode 255` part is what makes llpp crash and burn in `getkeysym`
>
> ```
> Fatal error: exception Invalid_argument("index out of bounds")
> Raised by primitive operation at file "./wsi/x11/wsi.ml", line 465,
> characters 13-43
> Called from file "./wsi/x11/wsi.ml", line 494, characters 20-39
> Called from file "./wsi/x11/wsi.ml", line 659, characters 4-17
> Called from file "./main.ml", line 6556, characters 12-27
> Called from file "./main.ml", line 6570, characters 7-17
> Called from file "./main.ml", line 6584, characters 8-21
> ```

Hmm... The keyboard handling in X11 core is very hard to get right for
me. Given that i do not have wifi button on this standard keyboard was
wondering if you can somehow simulate it with xdotool or other synthetic
event propagation method?

-- 
mailto:moosotc@gmail.com

**Comment by LemonBoy** [comment]
Sure thing, just use `xmodmap` like this:
- Create a file containing
```
keycode 255 = F21
```
- Load it
```
xmodmap <file>
```
- Fire it
```
sleep 2 && xdotool key F21
```

**Comment by moosotc** [comment]
LemonBoy <notifications@github.com> writes:

> Sure thing, just use `xmodmap` like this:
> - Create a file containing
> ```
> keycode 255 = F21
> ```
> - Load it
> ```
> xmodmap <file>
> ```
> - Fire it
> ```
> sleep 2 && xdotool key F21
> ```

Perfect, thank you! Reproducible, head scratching begins.

P.S. xmodmap -e "keycode 255 = F21" avoids using temporary files

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Would be nice if you could close this if the committed fix works for you.

**Comment by LemonBoy** [comment]
The latest commit fixes the crash, thanks for the quick response!
