### ISSUE TITLE
Separate config and history

### ISSUE THREAD

**Issue by LemonBoy** [moosotc/llpp#78]
I think the latter should be split from the `llpp.conf` file and stashed in another xdg-compliant(?) place

**Comment by moosotc** [comment]
LemonBoy <notifications@github.com> writes:

> I think the latter should be split from the `llpp.conf` file and
> stashed in another xdg-compliant(?) place

Yeah, but i don't feel like writing it...

-- 
mailto:moosotc@gmail.com

**Comment by freed00m** [comment]
@moosotc  And what about having a flag for ignoring the history all together? I don't care about history I just want to keep my config versioned in git and it llpp.conf keep changing cause file has been openned.

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> @moosotc And what about having a flag for ignoring the history all
> together? I don't care about history I just want to keep my config
> versioned in git and it llpp.conf keep changing cause file has been
> openned.

Wouldn't (ab)using -c option work then? Something like (completely
untested) wrapper script:

#!/bin/sh
trap 'rm /tmp/moollpp.conf' EXIT
llpp -c /tmp/moollpp.conf $*

-- 
mailto:moosotc@gmail.com

**Comment by JJK96** [comment]
Maybe this should be reopened to give someone else the opportunity to write it.
I really think this should be separated.

**Comment by moosotc** [comment]
Jan-Jaap Korpershoek <notifications@github.com> writes:

> Maybe this should be reopened to give someone else the opportunity to
> write it.  I really think this should be separated.

feel free.
