### ISSUE TITLE
Please support jumping to a relative page

### ISSUE THREAD

**Issue by agguser** [moosotc/llpp#79]
For example, on page 10, <kbd>2+</kbd> would go to page 12, <kbd>2-</kbd> to page 8. This is useful when a "table of contents" page is not on the last page, i.e. "printed" page numbers are not the same as "file" page numbers.

**Comment by moosotc** [comment]
agguser <notifications@github.com> writes:

> For example, on page 10, <kbd>2+</kbd> would go to page 12,
> <kbd>2-</kbd> to page 8. This is useful when a "table of contents"
> page is not on the last page, i.e. "printed" page numbers are not the
> same as "file" page numbers.

Have you tried setting page bias?

-- 
mailto:moosotc@gmail.com

**Comment by agguser** [comment]
"Page bias" solves the problem. Thanks.
