### ISSUE TITLE
Title: PDF pager -> More than a PDF pager

### ISSUE THREAD

**Issue by tuncer** [moosotc/llpp#8]
The title "PDF pager" omits all the other media llpp can display. Shouldn't it be changed to, for example, say "More than a PDF pager"?

**Comment by moosotc** [comment]
Humility is a virtue

**Comment by tuncer** [comment]
A little advertizing doesn't hurt, given that it support .cbz, .\<IMAGE\>, and .epub as well.

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> A little advertizing doesn't hurt, given that it support .cbz,
> .\<IMAGE\>, and .epub as well.
>

Not to forget https://github.com/moosotc/llpp/tree/dejavu but it still
is a pdf pager for me...

-- 
mailto:moosotc@gmail.com

**Comment by tuncer** [comment]
Should I close this, then?

**Comment by moosotc** [comment]
Tuncer Ayaz <notifications@github.com> writes:

> Should I close this, then?
>

Yes, thanks.

-- 
mailto:moosotc@gmail.com
