### ISSUE TITLE
Build error w/o _GNU_SOURCE

### ISSUE THREAD

**Issue by LemonBoy** [moosotc/llpp#82]
I'm afraid there's still some more work to do since the build fails because the following symbols aren't defined:

- `sigjmp_buf`
- `sigsetjmp`
- `fdopen`

Also, why is ocaml 4.07 required to build llpp? It builds just fine with 4.06 and, after all, 4.07 isn't released yet.

**Comment by LemonBoy** [comment]
Yep, that works.

**Comment by moosotc** [comment]
As for 4.07, i was under impression that -get-config-var is available there. Will go to 4.06 given that there is an "official" tarball with better compression.

**Comment by moosotc** [comment]
LemonBoy <notifications@github.com> writes:

[..snip..]

>
> Also, why is ocaml 4.07 required to build llpp? It builds just fine
> with 4.06 and, after all, 4.07 isn't released yet.

Two reasons why:

a. To test the fetching portions of build procedure by dog-fooding
b. ocamlrun in 4.07 is not linked against ncurses, making the produced
   '-custom' binaries more "portable"

-- 
mailto:moosotc@gmail.com
