### ISSUE TITLE
CBZ crop issue

### ISSUE THREAD

**Issue by Aanok** [moosotc/llpp#83]
I have a specific .cbz file such that the first page is in 1345x1864 resolution, the second is 2726x1864, all others are 1280x1864.
Only the first page is rendered correctly. All other are cropped in some measure to their top-leftmost corner. Zooming out does not extend the rendered region.
MuPDF renders the file correctly. See the two comparison screenshots. Note that MuPDF shows the picture at native resolution but llpp is actually zoomed in.

![llpp](https://user-images.githubusercontent.com/18417628/40414469-90a5d880-5e78-11e8-97c8-70af8adfd144.png)
![mupdf](https://user-images.githubusercontent.com/18417628/40414470-90c647fa-5e78-11e8-818e-6450ab82fed4.png)

**Comment by moosotc** [comment]
Aanok <notifications@github.com> writes:

> I have a specific .cbz file such that the first page is in 1345x1864
> resolution, the second is 2726x1864, all others are 1280x1864.
> Only the first page is rendered correctly. All other are cropped in
> some measure to their top-leftmost corner. Zooming out does not extend
> the rendered region.
> MuPDF renders the file correctly. See the two comparison
> screenshots. Note that MuPDF shows the picture at native resolution
> but llpp is actually zoomed in.
>
> ![llpp](https://user-images.githubusercontent.com/18417628/40414469-90a5d880-5e78-11e8-97c8-70af8adfd144.png)
> ![mupdf](https://user-images.githubusercontent.com/18417628/40414470-90c647fa-5e78-11e8-818e-6450ab82fed4.png)

Have you tried -T? (i.e. open the problematic cbz with llpp and in
llpp's window press '-' followed by 'T')

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Aanok <notifications@github.com> writes:

> I had not. That fixed the issue!

Cool. It would be nice if you could save me the trouble of closing this
issue ;)

-- 
mailto:moosotc@gmail.com

**Comment by Aanok** [comment]
Welp, beat me to it. Thanks for the help in any case :)
