### ISSUE TITLE
vim-searchindex

### ISSUE THREAD

**Issue by acgtyrant** [moosotc/llpp#87]
Hi, I request a feature again. Look at https://github.com/google/vim-searchindex please, the vim-searchindex plugin will show the index of a current match and the total number of matches when you repleat last search (forward/backward). I hope llpp support this feature too. Thank you!

**Comment by moosotc** [comment]
Isaac Ge <notifications@github.com> writes:

> Hi, I request a feature again. Look at
> https://github.com/google/vim-searchindex please, the vim-searchindex
> plugin will show the index of a current match and the total number of
> matches when you repleat last search (forward/backward). I hope llpp
> support this feature too. Thank you!

Searching in pdf is, for the lack of better term, hard. I suppose some
kind of integration with pdfgrep (https://pdfgrep.org/) is doable, but
will require some thinking (i'm happy with what's in llpp, external
tools as is.. so no promises)

-- 
mailto:moosotc@gmail.com

**Comment by acgtyrant** [comment]
If you decide not to support the feature, just close this issue.
