### ISSUE TITLE
Collapse outline

### ISSUE THREAD

**Issue by Docbroke** [moosotc/llpp#89]
Some of my books have long outlines with multiple levels, which makes very difficult to find a next chapter. If all outlines can be collapsed so that only top level outline are visible, it will be very comfortable.

**Comment by moosotc** [comment]
Docbroke <notifications@github.com> writes:

> Some of my books have long outlines with multiple levels, which makes
> very difficult to find a next chapter. If all outlines can be
> collapsed so that only top level outline are visible, it will be very
> comfortable.

Have you tried left and right arrows in the outline view? (Those
navigate level wise).

-- 
mailto:moosotc@gmail.com

**Comment by Docbroke** [comment]
Yes, I have I have tried left and right arrows. Trouble is they navigate from level 1 > level 2 > level 3 > next level 1. While it skips multiple outlines of same level, it still doesn't take me directly to next top level outline.
```
*level 1
      -level 2
      -level 2
      -level 2
           +level3
                .level4
*level 1
```

**Comment by Docbroke** [comment]
Here is an pdf file for example. It has multilevel outline.
[https://transfer.sh/tKpwD/example.pdf](url)

This book has outline like
```
chapter 1
     1.1
     1.2
          1.2.1
chapter 2
      2.1
```
What I want is outline to look like
```
+chapter 1
+chapter 2
+chapter 3
...
```
Where clicking on + (or right arrow) will show subchapters,
```
-chapter 1
     1.1
     +1.2
+chapter 2
+chapter 3
```
and clicking on "-" or left arrow will collapse this outline again.

**Comment by moosotc** [comment]
Docbroke <notifications@github.com> writes:

> Here is an pdf file for example. It has multilevel outline.
> [https://transfer.sh/tKpwD/example.pdf](url)

Thank you.

>
> This book has outline like
> ```
> chapter 1
>      1.1
>      1.2
>           1.2.1
> chapter 2
>       2.1
> ```
> What I want is outline to look like
> ```
> +chapter 1
> +chapter 2
> +chapter 3
> ...
> ```
> Where clicking on + (or right arrow) will show subchapters,
> ```
> -chapter 1
>      1.1
>      +1.2
> +chapter 2
> +chapter 3
> ```
> and clicking on "-" or left arrow will collapse this outline again.

I'm not going to be implementing colapsing, it has way too non obvious
consequences (filtering for one). And from where i stand
up/down/left/right arrows provide good enough way to jump around in this
scenario. Sorry.

-- 
mailto:moosotc@gmail.com

**Comment by Docbroke** [comment]
Alright.
I don't know much about coding but if you like to see an example, zathura has collapsing outlines.

**Comment by moosotc** [comment]
Docbroke <notifications@github.com> writes:

> Alright.
> I don't know much about coding but if you like to see an example,
> zathura has collapsing outlines.

Installed zathura(poppler version) - what it does with outlines feels
nice indeed will keep (nice parts) in mind, thank you.

-- 
mailto:moosotc@gmail.com
