### ISSUE TITLE
Copy the selection with ctrl+c

### ISSUE THREAD

**Issue by acgtyrant** [moosotc/llpp#91]
I would like to have this feature. Thank you!

**Comment by moosotc** [comment]
Isaac Ge <notifications@github.com> writes:

> I would like to have this feature.

Copy where? When you select something it's automatically piped to
selection-command no need to press any keys.

-- 
mailto:moosotc@gmail.com

**Comment by acgtyrant** [comment]
I do not like to use primary selection which use middle-mouse-click to paste. I would like to use clipboard which use ctrl+v to paste.

**Comment by moosotc** [comment]
Isaac Ge <notifications@github.com> writes:

> I do not like to use primary selection which use middle-mouse-click to
> paste. I would like to use clipboard which use ctrl+v to paste.

Then change the aforementioned selection command to:

`xclip -i -selection clipboard' [1] or whatever selection CUA keys in
"normal" applications use

-- 
mailto:moosotc@gmail.com

**Comment by fu123456** [comment]
I also meet this problem. I like vim-style keybinding. 'y' is for copy and 'p' is for paste. How do it?

**Comment by moosotc** [comment]
FuGang <notifications@github.com> writes:

> I also meet this problem. I like vim-style keybinding. 'y' is for copy
> and 'p' is for paste. How do it?

How to do what? I honestly do not know what to add to the discussion in
this issue. If you have specific question not address by comments in the
issue try to describe what it is that you want.

-- 
mailto:moosotc@gmail.com

**Comment by fu123456** [comment]
When I have selected a region including text, and then press 'y' (meaning copy these text), finally I can press the particular keybinding I have defined, e.g, 'p' in my Emacs buffer. Therefore, how I can copy the text selected by mouse? Ctrl-insert does not work, and I map ctrl-c to ctrl-insert which also does not work.

**Comment by moosotc** [comment]
FuGang <notifications@github.com> writes:

> When I have selected a region including text, and then press 'y'
> (meaning copy these text), finally I can press the particular
> keybinding I have defined, e.g, 'p' in my Emacs buffer. Therefore, how
> I can copy the text selected by mouse? Ctrl-insert does not work, and
> I map ctrl-c to ctrl-insert which also does not work.

When you select text in llpp it will be piped through xclip (by default)
xclip (it it is installed at all) will put the make the text the primary
selection, this can be put into emacs by doing something like:

(insert (gui-get-selection 'PRIMARY 'UTF8_STRING)) [1]

You can change the selection command to put it into clipboard, this is
explained in the earlier comments.

You can also have your own seletion-command and go wild with things (the
command will be called and the text will be piped through it)

[1] https://github.com/moosotc/snippets/blob/master/.emacs maps
    alt-insert to paste primary selection
    (note it's real alt that is mapped not meta)

-- 
mailto:moosotc@gmail.com

**Comment by fu123456** [comment]
thanks, it does work for my Emacs.
