### ISSUE TITLE
Can't paste any buffer into llpp

### ISSUE THREAD

**Issue by freed00m** [moosotc/llpp#92]
Hi,

I am not using this often, however sometimes I would like to copy word from other apps and then paste them in the search. However I can't paste with Ctrl-v neither Ctrl-shift-v nor the middle mouse button. 

I might have a messed up config but I can't think of anything

```
<llppconfig>
<ui-font size='20'><![CDATA[/usr/share/fonts/noto/NotoSansMono-Medium.ttf]]></ui-font>
<defaults
    width='1200'
    height='1000'
    scroll-bar-width='4'
    scroll-handle-height='12'
    horizontal-scrollbar-visible='false'
    vertical-scrollbar-visible='true'
    case-insensitive-search='true'
    preload='true'
    page-bias='0'
    scroll-step='24'
    auto-scroll-step='2'
    max-height-fit='true'
    highlight-links='false'
    under-cursor-info='false'
    vertical-margin='2'
    zoom='100'
    presentation='false'
    rotation-angle='0'
    fit-model='width'
    pixmap-cache-size='32M'
    tex-count='256'
    slice-height='24'
    thumbnail-width='76'
    background-color='127/127/127'
    scrollbar-color='163/163/163/178'
    scrollbar-handle-color='0/0/0/178'
    tile-width='2048'
    tile-height='2048'
    mupdf-store-size='256M'
    checkers='true'
    aalevel='8'
    trim-margins='true'
    trim-fuzz='0/0/0/0'
    uri-launcher='xdg-open &quot;%s&quot;'
    path-launcher='lp &quot;%s&quot;'
    color-space='rgb'
    invert-colors='false'
    brightness='1.000000'
    selection-command='xclip -i -selection clipboard'
    synctex-command='echo SyncTex'
    pax-command='cat'
    askpass-command=''
    savepath-command=''
    update-cursor='true'
    hint-font-size='12'
    horizontal-scroll-step='24'
    page-scroll-scale='1.000000'
    use-pbo='false'
    wheel-scrolls-pages='false'
    remote-in-a-new-instance='false'
    point-and-x='false'
    point-and-x-mark='word'
    scroll-bar-on-the-left='false'
    last-visit='-9223372036854775808'
    edit-annotations-inline='true'
    coarse-presentation-positioning='false'
    use-document-css='true'>
<keymap mode='view'>
<map in='q' out=''/>
<map in='k' out='ctrl-k'/>
<map in='ctrl-j' out='j'/>
<map in='+' out='ctrl-+'/>
<map in='shift-F' out=''/>
<map in='=' out='ctrl-shift-0'/>
<map in='m' out=''/>
<map in='shift-P' out=''/>
<map in='j' out='ctrl-j'/>
<map in='ctrl-k' out='k'/>
<map in='i' out=''/>
<map in='shift-M' out=''/>
<map in='shift-B' out=''/>
<map in='shift-S' out='i'/>
<map in='f' out=''/>
<map in='e' out=''/>
<map in='a' out=''/>
<map in='-' out='ctrl--'/>
<map in='b' out=''/>
<map in='shift-Q' out=''/>
<map in='shift-H' out=''/>
</keymap>
</defaults>
</llppconfig>
```

**Comment by moosotc** [comment]
Antonín Dach <notifications@github.com> writes:

> Hi,
>
> I am not using this often, however sometimes I would like to copy word
> from other apps and then paste them in the search. However I can't
> paste with Ctrl-v neither Ctrl-shift-v nor the middle mouse button.
>
> I might have a messed up config but I can't think of anything
>

Pasting simply was never implemented, here's a quick hack:

diff --git a/listview.ml b/listview.ml
index 51ee16a..cf531d5 100644
--- a/listview.ml
+++ b/listview.ml
@@ -120,7 +120,7 @@ let enttext () =
 ;;
 
 let textentrykeyboard
-      key _mask ((c, text, opthist, onkey, ondone, cancelonempty), onleave) =
+      key mask ((c, text, opthist, onkey, ondone, cancelonempty), onleave) =
   state.text <- E.s;
   let enttext te =
     state.mode <- Textentry (te, onleave);
@@ -175,6 +175,11 @@ let textentrykeyboard
 
   | Delete -> ()
 
+  | Insert when Wsi.withshift mask ->
+     let s = getcmdoutput (fun s ->
+                 prerr_endline ("error pasting: " ^ s)) "xclip -o" in
+     enttext (c, s, opthist, onkey, ondone, cancelonempty)
+
   | Code _ | Ascii _ ->
      begin match onkey text kt with
      | TEdone text ->

[..snip..]

-- 
mailto:moosotc@gmail.com

**Comment by buglong** [comment]
> Hi,
> 
> I am not using this often, however sometimes I would like to copy word from other apps and then paste them in the search. However I can't paste with Ctrl-v neither Ctrl-shift-v nor the middle mouse button.
> 
> I might have a messed up config but I can't think of anything
> 
> ```
> <llppconfig>
> <ui-font size='20'><![CDATA[/usr/share/fonts/noto/NotoSansMono-Medium.ttf]]></ui-font>
> <defaults
>     width='1200'
>     height='1000'
>     scroll-bar-width='4'
>     scroll-handle-height='12'
>     horizontal-scrollbar-visible='false'
>     vertical-scrollbar-visible='true'
>     case-insensitive-search='true'
>     preload='true'
>     page-bias='0'
>     scroll-step='24'
>     auto-scroll-step='2'
>     max-height-fit='true'
>     highlight-links='false'
>     under-cursor-info='false'
>     vertical-margin='2'
>     zoom='100'
>     presentation='false'
>     rotation-angle='0'
>     fit-model='width'
>     pixmap-cache-size='32M'
>     tex-count='256'
>     slice-height='24'
>     thumbnail-width='76'
>     background-color='127/127/127'
>     scrollbar-color='163/163/163/178'
>     scrollbar-handle-color='0/0/0/178'
>     tile-width='2048'
>     tile-height='2048'
>     mupdf-store-size='256M'
>     checkers='true'
>     aalevel='8'
>     trim-margins='true'
>     trim-fuzz='0/0/0/0'
>     uri-launcher='xdg-open &quot;%s&quot;'
>     path-launcher='lp &quot;%s&quot;'
>     color-space='rgb'
>     invert-colors='false'
>     brightness='1.000000'
>     selection-command='xclip -i -selection clipboard'
>     synctex-command='echo SyncTex'
>     pax-command='cat'
>     askpass-command=''
>     savepath-command=''
>     update-cursor='true'
>     hint-font-size='12'
>     horizontal-scroll-step='24'
>     page-scroll-scale='1.000000'
>     use-pbo='false'
>     wheel-scrolls-pages='false'
>     remote-in-a-new-instance='false'
>     point-and-x='false'
>     point-and-x-mark='word'
>     scroll-bar-on-the-left='false'
>     last-visit='-9223372036854775808'
>     edit-annotations-inline='true'
>     coarse-presentation-positioning='false'
>     use-document-css='true'>
> <keymap mode='view'>
> <map in='q' out=''/>
> <map in='k' out='ctrl-k'/>
> <map in='ctrl-j' out='j'/>
> <map in='+' out='ctrl-+'/>
> <map in='shift-F' out=''/>
> <map in='=' out='ctrl-shift-0'/>
> <map in='m' out=''/>
> <map in='shift-P' out=''/>
> <map in='j' out='ctrl-j'/>
> <map in='ctrl-k' out='k'/>
> <map in='i' out=''/>
> <map in='shift-M' out=''/>
> <map in='shift-B' out=''/>
> <map in='shift-S' out='i'/>
> <map in='f' out=''/>
> <map in='e' out=''/>
> <map in='a' out=''/>
> <map in='-' out='ctrl--'/>
> <map in='b' out=''/>
> <map in='shift-Q' out=''/>
> <map in='shift-H' out=''/>
> </keymap>
> </defaults>
> </llppconfig>
> ```

The `paste-command` is missing in your conf, set paste-command='LC_CTYPE=UTF-8 xclip -o -selection clipboard', and press shift-insert to paste clipboard text. Also, you can map ctrl-v to shift-ins in the global keymap if you want to use ctrl-v instead.
