### ISSUE TITLE
Ask for password if password protected PDF is opened

### ISSUE THREAD

**Issue by mwalle** [moosotc/llpp#93]
I know there is a commandline option, but it doesn't work well with the history option. Is there any reason why the program can't ask for a password in its status line?

**Comment by moosotc** [comment]
Michael Walle <notifications@github.com> writes:

> I know there is a commandline option, but it doesn't work well with
> the history option. Is there any reason why the program can't ask for
> a password in its status line?

If LLPP_ASKPASS environment variable is set its contents will be used as
a path to the program to inquire the user for the password (ssh-askpass,
rofi, dmenu, anything to get the password and print it to stdout thing
will do i suppose)

And yes there's a reason - i don't feel competent enough to deal with
"security"...

-- 
mailto:moosotc@gmail.com

**Comment by mwalle** [comment]
Ahh, thanks. I missed that. That is even better than the status line ;)
