### ISSUE TITLE
Issue with comicbook

### ISSUE THREAD

**Issue by mac1202** [moosotc/llpp#96]
Hi using llpp to read comicbook, I got issue when image aren't all the same size or aspect ratio, it completely fail. llpp crop image and only display a tiny part of it. It would be awesome if it can handle image the same way as qcomicbook, everything fit to width without cropping or adding border.

Here a screenshot of the problem [Screenshot](https://i.imgur.com/87dPV2e.png)

**Comment by moosotc** [comment]
mac1202 <notifications@github.com> writes:

> Hi using llpp to read comicbook, I got issue when image aren't all the
> same size or aspect ratio, it completely fail. llpp crop image and
> only display a tiny part of it. It would be awesome if it can handle
> image the same way as qcomicbook, everything fit to width without
> cropping or adding border.
>
> Here a screenshot of the problem [Imgur](https://i.imgur.com/87dPV2e.png)

It'd be nice if you have the "bad" comicbook so i can check things out.

-- 
mailto:moosotc@gmail.com

**Comment by mac1202** [comment]
Here a little sample.
[test.zip](https://github.com/moosotc/llpp/files/2405396/test.zip)
and side by side comparison between llpp and qcomicbook
[Screenshot](https://i.imgur.com/UlFoPvo.png)

**Comment by mac1202** [comment]
Another sample where a lot of crop occurs. First image blurred because of NSFW content. I think the issue happen when one image aspect ratio is a lot different from the other. For example a banner that is very width and not too height.
[test2.zip](https://github.com/moosotc/llpp/files/2405449/test2.zip)

**Comment by moosotc** [comment]
mac1202 <notifications@github.com> writes:

> Another sample where a lot of crop occurs. First image blurred because
> of NSFW content. I think the issue happen when one image aspect ratio
> is a lot different from the other. For example a banner that is very
> width and not too height.
> [test2.zip](https://github.com/moosotc/llpp/files/2405449/test2.zip)

The screenshot of llpp window tells me nothing about what the problem
is, what i nees is a comic book itself.

-- 
mailto:moosotc@gmail.com

**Comment by mac1202** [comment]
I have attach two sample zip.

**Comment by moosotc** [comment]
mac1202 <notifications@github.com> writes:

> I have attach two sample zip.

Oh, i just thought you made two archives with screenshots. I those are
fed to llpp then, i guess, i can see your predicament. I can only
suggest "trimming the margines"

$ llpp test2.zip
P
-T
(Followed by Ctrl-3 if you prefer the images to fit the same area)

-- 
mailto:moosotc@gmail.com

**Comment by mac1202** [comment]
Thank you -T did the trick.
