### ISSUE TITLE
zooming steps are too coarse

### ISSUE THREAD

**Issue by quesada** [moosotc/llpp#99]
In my use case, I just need two page view, then Presentation mode. It's damn hard to make the zoom level fit a page height correctly, and I have to tweak it after scrolling a couple of times with arrow keys. It's maddening.

A param for zoom step size would be lovely, the same way we have scroll step size.

**Comment by moosotc** [comment]
Jose Quesada <notifications@github.com> writes:

> In my use case, I just need two page view, then Presentation
> mode. It's damn hard to make the zoom level fit a page height
> correctly, and I have to tweak it after scrolling a couple of times
> with arrow keys. It's maddening.
>
> A param for zoom step size would be lovely, the same way we have
> scroll step size.

Setting fit model[1] to page doesn't do it for you?

[1] Either in the 'i' screen or cycling via Ctrl-3

-- 
mailto:moosotc@gmail.com

**Comment by prosoitos** [comment]
I also would like to have a smaller zoom step (or a way to set it in the settings).

I know of Ctrl-3, so this is not to fit the page height. It's just that I often find that one zoom step is too big and the next is too small.

Thanks!!!

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> I also would like to have a smaller zoom step (or a way to set it in
> the settings).
>
> I know of Ctrl-3, so this is not to fit the page height. It's just
> that I often find that one zoom step is too big and the next is too
> small.
>
> Thanks!!!

Here’s the code that increases zoom level

| Ascii '+' | Ascii '=' when ctrl ->
  let incr = if conf.zoom +. 0.01 > 0.1 then 0.1 else 0.01 in
  pivotzoom (conf.zoom +. incr)

Do i understand you correctly that you want to have 0.1 (large) and 0.01
values be user settable?

**Comment by prosoitos** [comment]
Yes, I think that it would be nice to be able to set the zoom steps, if this is not too much hassle to implement.

Side note: many thanks for llpp. I started using it a week or so ago and I love it more and more. It does all that I wanted of a pdf reader and could never find :slightly_smiling_face:

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> Yes, I think that it would be nice to be able to set the zoom steps,
> if this is not too much hassle to implement.

Okay, will try to address it after some sleep.

>
> Side note: many thanks for llpp. I started using it a week or so ago
> and I love it more and more. It does all that I wanted of a pdf reader
> and could never find :slightly_smiling_face:

Heh, glad to be of service.

**Comment by prosoitos** [comment]
Great! Thanks :slightly_smiling_face:

**Comment by moosotc** [comment]
Marie-Helene Burle <notifications@github.com> writes:

> Great! Thanks :slightly_smiling_face: 

diff --git a/genconfstruct.sh b/genconfstruct.sh
index 05d94db..1abbcfa 100644
--- a/genconfstruct.sh
+++ b/genconfstruct.sh
@@ -76,6 +76,7 @@ b hlinks false
 b underinfo false
 i interpagespace 2
 f zoom 1.0
+f zoominc 0.01
 b presentation false
 i angle 0
 i cwinw 1800
diff --git a/main.ml b/main.ml
index 5e5c062..f4804c7 100644
--- a/main.ml
+++ b/main.ml
@@ -1407,6 +1407,11 @@ let settrim trimmargins trimfuzz =
                  (btod conf.trimmargins) x0 y0 x1 y1);
   flushpages ()
 
+let calczoominc inc =
+  let zi = if inc = `dec then -. conf.zoominc else conf.zoominc in
+  let ziB = zi *. 10. in
+  if conf.zoom +. zi > ziB then ziB else zi
+
 let setzoom zoom =
   let zoom = max 0.0001 zoom in
   if zoom <> conf.zoom
@@ -2183,6 +2188,10 @@ let enterinfomode =
       (fun () -> truncate (conf.zoom *. 100.))
       (fun v -> pivotzoom ((float v) /. 100.));
 
+    src#string "zoom increment"
+      (fun () -> string_of_float conf.zoominc)
+      (fun v -> conf.zoominc <- float_of_string v);
+
     src#int "rotation"
       (fun () -> conf.angle)
       (fun v -> reqlayout v conf.fitmodel);
@@ -3187,9 +3196,7 @@ let viewkeyboard key mask =
      in
      enttext (String.make 1 c, E.s, Some (onhist !S.hists.pat),
               textentry, ondone (c = '/'), true)
-  | Ascii '+' | Ascii '=' when ctrl ->
-     let incr = if conf.zoom +. 0.01 > 0.1 then 0.1 else 0.01 in
-     pivotzoom (conf.zoom +. incr)
+  | Ascii '+' | Ascii '=' when ctrl -> pivotzoom (conf.zoom +. calczoominc `inc)
   | Ascii '+' ->
      let ondone s =
        let n =
@@ -3204,9 +3211,7 @@ let viewkeyboard key mask =
        )
      in
      enttext ("page bias: ", E.s, None, intentry, ondone, true)
-  | Ascii '-' when ctrl ->
-     let decr = if conf.zoom -. 0.1 < 0.1 then 0.01 else 0.1 in
-     pivotzoom (max 0.01 (conf.zoom -. decr))
+  | Ascii '-' when ctrl -> pivotzoom (max 0.01 (conf.zoom -. calczoominc `dec))
   | Ascii '-' ->
      let ondone msg = S.text := msg in
      enttext ("option: ", E.s, None,
